:hardbreaks:

....
옛날 옛적 어느 마을에
신데렐라 라는 아름다운 소녀가 살고 있었어요.

나쁜 계모와 언니의 괴롭힘을 받는
신데렐라였지만 어느 날 성에서
무도회가 열리게 되었습니다.

계모와 언니는 치장을 하고 무도회에 나갔지만
신데렐라는 무도회에 입고 나갈
드레스가 없었어요.

그때 마법사 페어리 갓 마더가 나타나
신데렐라에게 마법을 걸었습니다.

아름다운 드레스와 유리 구두를 신은
신데렐라가 호박 마차에 올라
무도회장으로 향합니다.

이윽고 신데렐라는 성의 무도회에서
왕자님과의 운명적인 만남을 갖게 됩니다.
....

== 서쪽 고갯길

엑스
...그 다음 신데렐라는 왕자님의 사랑을 받고,
뭐~ 이런저런 일 끝에 결혼한다는 거지.
잘됐구만 잘됐어, 라는 해피엔딩.

엑스
이전 왕비님은 물론 또 그 이전의 왕비님도
모두 이런 식으로 왕자님과 만났지.
이젠 일종의 전통행사처럼 됐어.

레이나
상구의 역사는 같은 줄거리로 반복된다고 알려져 있어.
아무도 그것을 이상하다고 생각하지 않지.
즉, 일종의 [암묵적인 룰] 같은 거야.

엑스
암묵적인 룰이라...
그런데 그보다 말야...

엑스
왜 주위에 빌런밖에 없는걸까!
가장 많이 보여야 할 사람들은 전혀 보이지 않는데...!

레이나
진정해.
여기는 이미 카오스 텔러의 영역이야.
적지 한가운데 있다고 생각해야해.

셰인
셰인의 조언입니다.
빌런에게는 속성이 있으니 약점속성으로 공략하여
빠르게 해치워 버립시다.

셰인
그럼, [먼저 때리는 사람이 이긴다] 작전으로 갑니다.
신참 씨.

***
*전투*

셰인
...이해가 빠르네요, 신참 씨.
역시 언니가 눈여겨 본 유망주 다워요.

엑스
고마워.
그런데, 카오스 텔러를 쓰러뜨리지 않는 이상
전투는 계속 되는 거지?

타오
무~슨 걱정이 그렇게 많으신가,
우리 넷이 함께라면 저 정도의 빌런은 깜찍한 수준이지!

레이나
그건 그래. 타오말이 맞아.
이 상태라면 그렇게까지 걱정할 필요는 없어보여.
자,  계속 가보자.

엑스
...이 사람들, 상당히 터프하구나...

== 강 건너편 고갯길

엑스
...기분 탓인가?
마을 가까이 갈수록 빌런이 점점 더 많이
나타나는 것 같은 기분이 드는데...!

레이나
기분 탓이 아니야.
아마 그건...

타오
엇, 아가씨. 입을 움직이기보다는
먼저 손을 움직이는 편이 좋을 것 같아...!

셰인
설명은 전투가 끝난 다음에 합니다!

레이나
어쩔 수 없네.
우선 이 전투를 끝낸 후에 얘기하자!
엑스!

엑스
나 참, 빌런이란 성가신 존재구나!

***
*전투*

엑스
...뭐라고?
빌런은 원래 이 상구의 주민이었다고?

레이나
응, 카오스 텔러의 손에 의해 『운명의 서』가
다시 쓰여진 상구의 주민이야.
카오스 텔러는 그렇게 해서 빌런을 만들어내는 거지.

레이나
얘기하지 않았었나?

엑스
아니아니아니, 처음 들어!
빌런들이 상구의 주민이었다니...
우리 지금까지 아무렇지도 않게 마구 해치우면서 왔잖아!

타오
나 원 참!
나쁜 녀석들을 싹 다 날려버리고 온게 뭐 어때서 그래!
뭘 일일이 그런걸 신경 쓰고 있어?

엑스
타오 씨,
그렇게 쉽게 생각할만한 일이 아니잖아요 지금!

레이나
안심해, 엑스.
우리는 그 누구도 죽이지 않았어.
말했잖아? 모든 것을 제자리로 돌려놓는다고.

레이나
카오스 텔러를 쓰러뜨린 다음 내 힘으로
카오스 텔러를 원래의 스토리 텔러로 [조율] 할 거야.
그러면 큰 문제 없이 모든 게 잘 될 거야.

엑스
카오스 텔러를 원래의 스토리 텔러로 [조율]...?
그런 게 가능해?

타오
아가씨를 단순한 방향치 공주라고
생각하지 않는 편이 좋을걸?
[조율의 무녀]는 두려움의 존재니까 말야.

레이나
누가 방향치 공주라고요?

엑스
무슨 소리인지는 모르겠지만...
아무튼 카오스 텔러를 어떻게든 하면 괜찮아지는 거지?
그렇다면 정말 다행이다...

셰인
바꿔 말하면 카오스 텔러를 어떻게든 하지 못하면
그대로 세인 일행은 대량 학살범 확정이라는 거죠...

엑스
반드시 카오스 텔러를 쓰러뜨리자!
사랑하는 고향을 지키기 위해서라도!

레이나
엑스, 너 리액션이 꽤 좋구나...

== 회상

신데렐라
있잖아, 봐봐, 엑스!
내 드레스 어때? 잘 어울리는거 같아?

엑스
...그래, 정말 아름다워.
정말로 페어리 갓 마더가 와 주신거구나.

신데렐라
응,[운명의 서]에 기록된 대로야.
12시가 되면 마법이 풀리겠지만...
결국 오늘밤 내 운명은 새롭게 바뀌겠지.

엑스
그래. 오늘을 기다리며 네가 악랄한 계모 밑에서
견뎌올 수 있었던 거잖아.
엉뚱한 데서 실수하면 안 된다?

신데렐라
아이 참, 내가 무슨 실수를 한다고 그래.
이제서야 말하지만, 너에겐 항상 고마운 마음뿐이야.
내가 힘을 낼 수 있었던 건 너의 응원 덕분이니깐.

신데렐라
나한테 너는 소중한, 정말 소중한 친구야.
앞으로도, 계속...

엑스
하하,
미래의 왕비님께 그런 말을 들은 것만으로도 영광입니다요.
자자,빨리 가야지. 호박 마차가 기다리고 있잖아?

신데렐라
맞아! 다녀올게!
나, 꼭 운명을 바꿔 보겠어!

엑스
그래,잘 다녀와.
조심하고,신데렐라...

== 혼돈의 성 밑 마을

타오
쳇, 빌런 놈들… 많기는 엄청 많구만!
거리가 아주 우글우글 난장판이네!

엑스
잠깐! 저 빌런들 중에
성의 병사처럼 보이는 사람도 있는데?!

레이나
아무래도 카오스 텔러에게 조종당하고 있는 것 같아.
그냥 빌런이랑 똑같다고 생각하는게 좋을거야.
애초에 우리 말을 들으려 조차 안할 테니까.

레이나
엑스, 이대로 저 사람들과 싸워야 하는데
괜찮겠어? 상대가 사람의 모습을 하고 있어서
아무래도 부담스럽지 않을까 싶은데.

엑스
상관없어.
저 앞에 신데렐라가 기다리고 있으니까...
상대가 누구든간에 난 여기를 지나가야만 해!

타오
말 한 번 잘했다! 상남자구만!

셰인
하나씩 정리하면서 나갑시다.
진짜 목표물은 저 너머에 있을 겁니다.

***
*전투*

엑스
...음? 뭐지?
빌런들 중에 유독 커다란 녀석이 눈에 띄는데...?

타오
저건 메가 빌런이라는 놈이야.
굳이 따지자면 대장급 빌런이라고나 할까?

셰인
카오스 텔러 정도까지는 아니지만
강적임에는 틀림없죠.

레이나
자, 상황은 이정도로 정리하고.
어때? 엑스, 싸울 각오가 좀 된 것 같아?

엑스
이제 와서 무슨말이야,
각오같은 건 이미 예전에 했어.

***
*전투*

엑스
이 검은...

레이나
얼음으로 만들어진 검인가 보네.
아까 그 메가 빌런이 떨어뜨린 건가?

엑스
이건, 왕국에서 대대로 전해 내려오는
감춰진 보물의 검이야.
날이 마법의 얼음으로 되어 있다고 들은 적 있어...

셰인
그런데 메가빌런이 왜 그 검을...?

타오
그 검을 떨어뜨린 메가 빌런은 원래 성의 관계자가
아니었을까? 그렇다면 카오스 텔러도...
성 안에 숨어있을 확률이 굉장히 높아보이는군.

레이나
그 검, 소중히 잘 가지고 있도록 해.
카오스 텔러는 [주연]과 관련 있는 물건이
약점일 경우가 많아.

레이나
그 검이야말로 신데렐라를 구할 수 있는
비장의 카드가 될지도 몰라.
어떻게 사용할지는 네게 맡길게.

엑스
그래, 알겠어.

***

레이나
엑스, 어때?
성까지 갈 수 있는 길은?

엑스
안 되겠어.
빌런들이 결집해서 다 막아버렸어.
이쪽으로 가는 건 불가능해 보여.

레이나
그렇구나, 곤란하게 됐네...
따로 빠져나갈 길이 있으면 좋겠는데.

셰인
아, 잠깐만요.
북쪽 길 방향으로는 비교적 한산해 보이네요.
어디로 이어지는 길인지는 확실치 않지만...

엑스
저 길은 그냥 산길로 알고있는데.
가 봤자 딱히 산 밖에 보이지 않을지도...아, 잠깐?

엑스
생각해보니 저 산 위쪽으로 좀 더 들어가면
성과 연결되는 작은 길이 있다고 들었던 것 같아.
멀리 돌아가는 곳이라 인적은 드물지만.

타오
호오~ 좋은걸.
[급할수록 돌아가라]라는 말도 있잖아?
빌런 놈들의 허를 찌를 수 있겠군.

레이나
그럼, 정해졌네.
확률은 반반이겠지만 딱히 다른 대안이 없으니
일단은 북쪽 산으로 가보자.

== 북쪽의 산

셰인
다들 빨리 안오고 뭐하시나요.
딱히 제가 빠르다는 생각은 들지 않으니
어서들 올라오세요.

엑스
셰인은 산길인데도 잘도 걸어가네...

타오
나도 셰인도 시골 산속에서 자랐으니까
이 정도쯤은 뭐 일상이었지. 너도 꽤 잘 걷는데?

엑스
...나약한 소리 하고 있을 순 없죠.
서둘러야 하니까.

타오
그렇게 너무 긴장하면 지치기만 한다고.
...어라? 아가씨, 왜 그래?

레이나
엑스, 말이 맞아...
이런 데서... 약한 소리하고 있을 수는... 없어...
후아... 후아...

타오
아하, 그러고 보니 아가씨는 성 안에 주로 있었을테니
이거 산길은 좀 힘들겠구만.

엑스
성에서 살았다고?

타오
못 들었어?
이봐 아가씨는 말야, 원래...

레이나
거기! 쓸데없는 얘기는 하지 마!
이 정도는 끄덕 없으니 신경 안써도 돼.
후아 후아...

엑스
아무래도… 좀 쉬었다 가야할 것 같은데요.

타오
음… 그게 좋겠어.

***
*전투*

엑스
?
바닥에 뭔가 있는데? 이건 뭐지?

셰인
아앗, 그건!
스킬 코어잖아요!

엑스
스킬 코어?

셰인
아, 모르시는군요?
그럼 일단 이 셰인이 설명을 해야겠군요.

엑스
의욕이 완전 넘치는데...

타오
셰인은 무기 마니아거든.

레이나
각오하도록 해. 네가 상상하는 것보다 길어질 거야.

셰인
신참 씨, 당신의 무기를 잘 들여다보세요.
뭔가 이상한 [구멍]같은게 보이지 않습니까?

엑스
우왓, 진짜다!
전혀 모르고 있었네!

셰인
이건 스킬코어를 끼워 넣을 수 있는 연결부에요.
아까 주운 스킬 코어를 끼워 넣으면
무기에 여러 특성을 부여할 수 있죠.

셰인
즉, 무기와 스킬 코어를 조합하면
당신이 원하는 무기로 커스터마이징할 수 있는 것입니다.

셰인
참고로 [미니어처 왕국]에 무기 연구소를 세우면
무기를 제작할 수도 있어요.
※모형정원의 왕국

엑스
무기 제작?
그런 것까지 할 수 있다고?

셰인
예스.
대신 무기 제작에는 레시피와 재료가 필요합니다.

셰인
초보자용 모든 종류의 무기 레시피는 기본으로 있으니,
그걸 갖고 이것저것 만들어 보는 것도 괜찮겠네요...

엑스
셰인, 숨이 너무 거칠어.

셰인
앗, 실례.
너무 흥분했나 보네요.

셰인
이상으로, 세인 선생님의 무기 강좌,
커스터마이징 편 마칩니다.
들어주셔서 감사합니다.

***

레이나
다행이야. 성 쪽으로 뻗은 길이 보여.
성으로 갈 수 있을 것 같아.
게다가 빌런도 없어. 모든것이 순조로워 보이네.

셰인
스킬 코어도 있으니 아까 그 길로 돌아간다 해도
빌런들을 해치우면서 충분히 갈 수 있을 것 같네요.

타오
드디어 카오스 텔러가 있는 곳으로 쳐들어가는군!
그런데, 싸울 준비는 되어 있나?

타오
필요하다면 왔던 길을 되돌아가서
잠시 탐색이나 수집을 하는 것도 괜찮을 듯 한데.
새로운 재료를 얻을 수도 있으니.

타오
그러고 보니,
아까 싸웠던 호위병들이 금이나 은을 떨어뜨렸었지.

타오
탐색 시작 전, 상세사항을 확인해 보면
무엇을 얻을 수 있는지 알 수 있으니까 참고하도록.

레이나
그래. 준비되는 대로 빠르게 가보자!

== 신데렐라의 성

셰인
자, 방이 여러 개 있는데
무도회장은 어느 쪽으로 가야 하는 걸까요.

엑스
나도 이곳은 처음이지만
예전에 신데렐라에게 들은 기억으로는
이 통로 안쪽에 무도회장이 있다고 했었어.

타오
그러고 보니 너는 이 성에 온 목적이
왕자의 얼굴을 보고 싶어서라고 했었지?

타오
그런데 만약 왕자를 만난다고 해도...
만나서 뭘 어떻게 할 생각이었어?

엑스
확인해 보고 싶었어요.
신데렐라의 운명을 바꿔 줄 왕자가 어떤 사람일지......

엑스
그리고 만약...
왕자가 신데렐라에게 어울리지 않는 사람이라면
그녀에게 마음을 전해도 괜찮지 않을까 싶어서...

엑스
아하하, 나도 참 바보같죠?
[운명의 서]의 기록은 바꿀 수 없을텐데.

레이나
바꿀 수 있어.
[공백의 서]의 소유자라면.

레이나
우리는 자신의 운명을 선택할 수 있을 뿐 아니라
타인의 운명까지 바꿔놓을 수 있어.

엑스
정말!? 그렇다면...

레이나
다만 그렇게 할 경우,
네 소꿉친구인 신데렐라는 [주연]에서 물러나게 돼.
다른 누군가에게 그 배역이 주어질거야.

엑스
아......

레이나
타인의 운명을 바꾼다는 건 그런 거야.
저질러 버린 행동의 결과에는 반드시 책임이 따른다.
그걸 잊지 마.

엑스
알겠어.
명심할게.

***

엑스
이 앞이 무도회장이야.

레이나
카오스 텔러에게 잔는 통하지 않아.
단숨에 처들어가자, 알겠지?
그럼,3,2, 1......

*

타오
잠깐, 무도회는 커녕 이건 완전 빌런들의 파티잖아!
카오스 텔러는 어디에 있는 거야?

엑스
신데렐라!
다행이다, 아직 빌런으로 바뀌지 않았어!
지금 구하러 갈게!

엑스
잠깐, 엑스!
옆에 누군가가 있어!

????
이런이런, 새로운 손님의 행차신가?

엑스
뭐지, 저건...
저것도 빌런...?

????
자~ 자~ 나는 소원을 이뤄주는 마법사~
아름다운 드레스도 유리 구두도 모두 바라는 대로.

엑스
소원을 이뤄주는 마법사...?
설마, 당신은...
페어리 갓 마더...!

레이나
아니야! 저건 페어리 갓 마더에 빙의한 혼돈의 원흉...
카오스 텔러야!

????
이루어져라, 이루어져라.
추악한 것은 아름답게, 깨끗한 것은 역겹게,
따분한 질서는, 자극적인 혼돈으로...

엑스
멈춰!
신데렐라에게 다가가지 마!

레이나
카오스 텔러에게 말은 통하지 않아!
직접 공격해서 멈추게 하는 수밖에 없어!
모두, 준비됐어!?

타오
언제든지 갈 수 있어!

셰인
준비 완료예요.

엑스
기다려 신데렐라.
지금 바로 이 악몽을 끝낼 테니까!

***
*전투*

신데렐라
...엑스?
...거기 있는 거야? 엑스?

엑스
신데렐라!
정신이 들어? 다친 데는 없어?

신데렐라
...방금 아주 무서운 꿈을 꿨어.
페어리 갓 마더가 갑자기 변해서 모두를...
괴물로 변하게...

엑스
괜찮아… 괜찮아… 신데렐라...
이제 악몽은 끝났어...

신데렐라
있잖아, 엑스.
왕자님은, 왕자님은 무사하셔?

엑스
무사해. 그래, 무사하고 말고.
이제 곧 전부 원래대로 되돌아갈 거야.
네 운명도 이제 곧 바뀔 거고.

신데렐라
그렇구나... 다행이다...

*

레이나
운명을 바꿀 기회는...
이제 필요 없어?

엑스
이제부터 최고의 해피엔딩을 맞이해야 하는
주연들을 방해하면 안 되지.
나머지는 부탁할게. [조율의 무녀] 님.

레이나
\.....
그래, 알았어.

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라
여기 조율을 시작하오니......』

*조율 컷씬*

엑스
레이나의 몸에서 하얀 빛이 흘러 넘쳤다.
그것은 혼돈을 질서로 되돌리는 조율의 빛.

엑스
그렇게 상구는 원래의 모습으로 돌아가고
내게는 또다시, [공백의 운명]이 돌아왔다.

*

셰인
신데렐라도 왕자님과 결혼해서 완벽한 해피엔딩이 됐네요.
그런데, 이제부터는 어떻게 할 거예요?

레이나
늘 그랬듯 [원흉]의 뒤를 쫓아야지.
카오스 텔러의 위협에 노출된 상구는
아직도 많이 있으니까...

타오
그녀석한테 이야기 안 해도 괜찮겠어?

레이나
그가 싸웠던 건 자신의 고향을 지키기 위해서였으니까.
우리 여행에 따라올 이유가 없잖아.

타오
그렇지, 딱히 따라올 이유는 없겠지.
그런데 말이야, 저기 뛰어오는 녀석은 누굴까나?

셰인
꽤나 엄청난 기세로 달려오네요.
어라, 저건 배웅하는 분위기는 절대 아닌 것 같은데.
어떻게 할 거예요,레이나 언니.

레이나
무슨 생각인지 지켜봐야겠지만
동료는 한 명이라도 더 많을수록 좋잖아, 안 그래?

*

엑스
어~~이! 레이나, 타오, 셰인, 기다려 줘!

엑스
나도 너희와 같이 갈게!

엑스
나는 태어날 때부터
어떤 운명도 주어지지 않았다.
그게 당연하다고 생각했다.

엑스
하지만 레이나 일행을 만나고,
[인도의 책갈피]를 알게 되고,
겨우 깨닫게 되었다.

엑스
나는 어떤 형태로도,
내 운명의 모습을 선택하지 않았다는 걸.

엑스
[공백의 서]의 소유자는
자신이 무엇이 될지 스스로 선택할 수 있다.
그래서 나는 그들과 함께 여행에 나섰다.

엑스
공백이었던 내 운명의 이야기는
이렇게 시작되었다...
