= このリポジトリについて

== 他の言語
link:README.adoc[한국어]

== 概要
日本のモバイルゲーム『グリムノーツ』のシナリオテキストをすべて保存するために作成したリポジトリです。

なぜ保存するのかって？ 「こんな内容がこの辺にあった気がするんだけど……」と探し回るのが本当に大変だったからです。一度苦労して（厳密には一度ではありませんが）後で楽に検索して見つけられるようにしました。

基本的には韓国語ユーザー向けのリポジトリですが、オタクの方ならお分かりでしょう。日本のサブカルチャーを楽しむ上で、日本語テキストがどれほど重要かということを。キャラクターの一人称や二人称の違いから生じるニュアンスの差は、決して見逃せません。これが何を意味するのでしょうか？

韓訳文を中心に保存していきますが、追々原文も保存する予定ですので、最終的には日本語ユーザーの方々も活用できるリポジトリになるのではないか……と考えています。

READMEは不要だと思っていましたが、ないとアクセスするたびに見栄えが悪かったので作成しました。

== 構成
フォルダ::
* 무인（無印）
* 리페이지（リ・ページ）
* 학원（学園）
* 히어로 에피소드（ヒーローエピソード）

ナンバリング::
リリース時期に合わせた ※日本サーバー基準
* 自然数（メインストーリー）
* 小数（イベントストーリー）
* ID（ヒーローエピソード） +
ヒーローのファイルIDは、リリース順とは大きく異なります。

テキスト::
* Flero公式韓訳 (-Flero)
* 非公式ユーザー韓訳 (-Username) +
この場合、該当ドキュメントの最上部に翻訳元の出処を記入します。
* 日本語原文

脚注::
「※」を付け、名前の横や台詞の下に短い脚注が付いている場合があります。このリポジトリの目的自体が検索の利便性にあるため、翻訳の語彙の違いによる検索の不便さを減らすためのものです。翻訳文による語彙の差異があっても、判断により脚注の有無が決定されます。

AsciiDoc::
Markdownでまとめようとすると、強制改行を入れるために一つひとつ打つのが非常に面倒で、かといってtxtで上げるとレンダリングされず可読性が低いため、採用したマークアップ言語です。 +
AsciiDocの特徴なのか、ピリオドが3つ連続していると(\...)、三点リーダ(…)に変換してレンダリングされるようです。私は原文が三点リーダでない限り、三点リーダに置き換えていません……。rawテキストを見ればどちらか判別可能です。 +
また、ピリオドのみの（＝三点リーダ）台詞をそのまま移すと、文法上ブロック扱いになってしまいます。そのため、rawテキストを見ると前にエスケープ文字(\)が入っていますが、ないものとして考えていただければ幸いです。
