= 이 레포지토리에 대해

== 다른 언어
link:README-Ja.adoc[日本語]

== 개요
일본 모바일 게임 그림노츠(グリムノーツ)의 시나리오 텍스트를 전부 저장하기 위해 만든 레포지토리입니다.

그걸 왜 저장하냐고요? "이런 내용이 이쯤에 있던 거 같은데……." 하면서 뒤적뒤적하기 너무 힘들었습니다 진짜. 그냥 이렇게 한 번 고생해서 -- 사실 엄밀히 한 번은 아니지만 -- 나중에 편하게 검색해서 찾으려고요.

기본적으로 한국어 사용자를 위한 레포지토리지만, 오타쿠라면 다들 아실 겁니다. 일본 서브컬쳐를 향유하려거든, 일본어 텍스트가 얼마나 중요한지. 캐릭터의 1인칭, 2인칭 차이에서 발생하는 뉘앙스 차이를 놓칠 수 없다는 걸. 이게 무슨 의미일까요?

한역문 위주로 저장하겠지만, 차차 원문도 저장할 생각이므로, 최종적으로는 일본어 사용자 분들도 사용할 수 있는 레포지토리가 되지 않을까…… 라고 생각을 합니다.

README는 필요없다고 생각하는데, 없으니 들어올 때마다 너무 못생겨서 만들어 주었습니다.

== 구성
폴더::
* 무인
* 리페이지
* 학원
* 히어로 에피소드

넘버링::
출시 시기에 맞춘 ※일본 서버 기준
* 자연수(메인스토리)
* 소수(이벤트스토리)
* ID(히어로 에피소드) +
히어로의 파일ID는 출시순서랑 많이 다릅니다.

텍스트::
* 플레로 공식 번역(-Flero)
* 비공식 유저 번역(-Username) +
이 경우, 해당 문서의 최상단에 번역문 출처를 기입합니다.
* 일본어 원문(-Ja)

각주::
'※'를 달고 이름 옆 또는 대사 아래에 짧은 각주가 달려있을 수도 있습니다. 이 레포지토리의 용도 자체가 검색의 편의를 위해서인만큼, 번역의 어휘차이로 인한 검색의 불편함을 줄이기 위한 용도입니다. 번역문에 따른 어휘차이가 있어도, 판단에 따라 각주 여부가 결정됩니다.

AsciiDoc::
마크다운으로 정리하자니 강제 줄바꿈을 하려면 매우매우 귀찮게 하나하나 쳐 줘야 하고, 그냥 txt로 올리자니 렌더링이 안 되어 가독성이 별로라 찾아낸 마크업 언어입니다. +
AsciiDoc의 특징인지, 마침표 세 개가 연달아 있으면(\...) 말줄임표(…)로 바꿔서 렌더링 하더군요. 저는 원문에서 말줄임표가 아니면 말줄임표로 옮기지 않았습니다……. raw 텍스트를 보면 어느쪽인지 알 수 있습니다. +
또한 마침표만 있는(=말줄임표) 대사를 그대로 옮기면 문법상 블록이 되더라고요. 그래서 raw 텍스트를 보면 앞에 이스케이프 문자(\)가 있을 텐데, 없다고 생각해주시면 되겠습니다.
