:hardbreaks:

https://youtu.be/lUs1FHgSls8
....
우리들은 태어나면서부터,
한 권의 책을 받게 된다.

우리들이 사는 세상, 삶의 의미, 운명,
그 모든 것이 기록돼 있는 희곡,
「운명의 서」

전지전능한 존재, 스토리텔러가
기술한 「운명의 서」에 따라,

우리들은 태어나서 죽음을 맞을 때까지,
「운명의 서」에 쓰인 역할을 줄곧 연기한다.
그게 이 세계의 사람들의 삶의 방식.

그러니, 제발 누가 좀 가르쳐 줘.

공백의 페이지만 가득한 「운명의 서」를
받은 이는,

대체 어떤 운명을 연기하며
살아가야 하는 건지.
....

== 시작의 숲

????
아하하... 안녕하세요~ 여러분.
이런 험한 숲 속에 참 많이들 계시네요
근데 여기엔 어떤일로...? 관광이라도 오신건가요?

수수께끼의 괴물
\......

????
어이쿠, 그렇게까지 쳐다볼 필요는 없잖아요.
전 그냥 지나가는...
조연A일 뿐이니까요.

????
...우선 말이죠, 그 애부터 풀어주면 어떨까요?
쓰러진 나무 밑에 깔린 여자아이를 여럿이서 둘러싸고
대체 뭐하는 겁니까.

소녀
으... 음... 빌런!?

소녀
거기 당신! 뭐 하는 거야!
빨리 도망쳐!!

수수께끼의 괴물
크르! 크르!
크르르르아아아아아!!

????
으앗! 위험해! 겨우 피했네!
이봐 괜찮아? 혼자서 빠져나올 수 있겠어?

소녀
아... 발이...
발이 끼어서 움직일 수가...

소녀
어쨌든 나 혼자서 어떻게든 해볼테니,
당신은 어서 도망쳐!

????
하아... 안돼, 그럴 수는 없어.
적힌 것 없이 아무 역할조차 주어지지 않은 조연이라도
의지란게 있으니까...!

소녀
잠깐... 적힌게 없다니?
아무런 역할도 주어지지 않았다고?
당신, 설마......

수수께끼의 괴물
크르! 크르!
크르르르아아아아아!!

????
역시 말이 통하는 상대는 아닌 것 같네...

????
어쩔 수 없지.
혼자 목검으로 연습해 온 검술이지만...
모두 한꺼번에 상대해주겠...!

소녀
잠깐! 부탁이야, 이걸...
[인도의 책갈피]를 받아!

소녀
그 [인도의 책갈피]를 네 [공백의 서]에 끼워넣어!
저 괴물들, 빌런들과 싸울 힘이 생겨날 거야!

????
뭐...뭐라고? [공백의 서]?
아무것도 쓰이지 않은 채 새하얗게 비어있는
내 [운명의 서]를 말하는 거야?

소녀
믿기지 않겠지만 일단 내 말대로 해줘!
그 [공백의 서]를 가진 너라면
히어로의 영혼과 반드시 연결될테니!

????
히어로? 영혼?
잘 모르겠지만...상황이 상황인만큼...
알겠어! 한번 해볼게!

***
*엑스가 잭으로 커넥트하는 컷씬*
*전투*

????
내가 정말 이겼다니......
뭐였지, 방금 그 힘은? 대체...

소녀
그건 [인도의 책갈피]에 간직된 히어로의 힘.
오래된 전설로부터 전해져 온 히어로의 영혼이
네 [공백의 서]와 연결되어 힘을 내려 준 거야.

소녀
지금 너와 연결되어 있는 건 하늘까지 닿는
커다란 콩나무를 타고 올라가 하늘에 사는 거인들과
싸운 용기 있는 소년, 잭의 영혼이야.

????
아하하… 미안. 아직 잘 모르겠어...
하지만 덕분에 괴물들을 물리쳤으니 다행이야.
자 그럼 바로 이 나무를 치워줄게. 하나,둘!!

소녀
고마워, 덕분에 살았어.
그러고 보니 네 이름도 아직 듣지 못했네.

엑스
나는 엑스.
이 숲을 빠져나가면 있는 작은 마을에서 사는
별 볼일 없는 조연이야.

소녀
그렇구나, 엑스, 기억할게.
나는 레이나, 상구의 바깥에서 왔어.

엑스
[상구]? 바깥에서 왔다니......
저 괴물에 대해서도 알고 있는 것 같은데......
이 책갈피도 그렇고, 대체 정체가 뭐야?

레이나
미안하지만 그 질문에는 대답할 수 없어.
그 [인도의 책갈피]는 네가 가지고 있어.
몸을 지키는 데 조금은 도움이 될 거야.

엑스
앗,레이나.
어디로 가는 거야?

레이나
성에서 동료들과 만나기로 했거든. 빨리 가봐야 할 것 같아.
안녕, 먼저 갈게 엑스.
어쩌면 언젠가 다시 만날 수도 있을거야.

엑스
... 잠깐, 기다려 봐 레이나!
잠깐!

엑스
그쪽 길은 성과 반대 방향이야!

레이나
\........................

엑스
우연치 않게 사실 나도 성에 볼일이 있거든.
길을 안내할 테니 일단 같이 가지 않을래?

레이나
...그래, 부탁할게.

***

엑스
그런데 아까 하던 이야기 말인데...
바깥에서 왔다니, 대체 어떻게 된 거야?
[상구]라는 건 또 뭐고?

레이나
꽤 끈질기게 물어보는구나 그거.
음... 나 때문에 너도 휘말린 거니까
좋아. 좀 더 알려주는 게 좋을지도 모르겠네.

레이나
스토리 텔러에 대해서는 알고 있지?
[상구]란 이 스토리 텔러가 만들어낸 공간
그 자체를 말해.

레이나
상구는 옛 전설을 바탕으로 만들어졌고,
그곳에 사는 사람들은 그 전설 속에 존재하는
인물들의 역할을 부여받아 일생을 살아가...

레이나
어떤 사람은 맑고 아름다운 공주의 역할을,
어떤 사람은 고상하고 늠름한 영웅의 역할을,
어떤 사람은 무섭고도 소름끼치는 악인의 역할을...

레이나
이렇게 기본 토대가 된 전설의 줄거리를
옮겨 쓰는 과정에서, 상구에 사는 사람들은
스토리 텔러가 기록한 대로 운명을 살아가는 거야.

레이나
이 세계에는 여러 명의 스토리 텔러가 존재하고
각자 자신만의 상구를 만들어내고 있어.
다시 말해 세계에는 많은 상구가 존재하고 있다는 거야.

레이나
우리는 그 상구를 돌아다니는 여행을 하고 있어.
바깥에서 왔다는 건 말 그대로 이 상구의 바깥에 있는
다른 상구에서 왔다는 의미야.

엑스
바깥 세계... 그런 곳이 있다는걸 쉽게 믿기는 어렵네...
그럼, 아까 그 괴물들은 뭐야?

레이나
그건 카오스 텔러가 만들어낸 괴물, 빌런이라고 해.

엑스
...카오스 텔러?

레이나
그래, 카오스 텔러.
이상하게 변해 버린 스토리 텔러를 그렇게 부르고 있어.

레이나
카오스 텔러는 상구를 혼란에 빠뜨리고
결국 사라지게 만드는 존재야.
우리는 그렇게 되는 걸 막기 위해 이 상구로 온 거고.

엑스
... 잠깐만.
그럼 혹시, 지금 네가 성으로 가려는 이유는 설마......

레이나
... 미안, 엑스! 이야기는 나중에!

엑스
또 빌런들이!?

레이나
카오스 텔러를 막지 않는 한 빌런도 계속 나타날 거야!
이번에는 나도 싸울게!

엑스
그 책갈피, 또 갖고 있었어!?
잠깐 너도 싸운다는 건...

레이나
나도 [공백의 서]를 갖고 있어.
자, 가자 엑스!

***
*레이나가 셰리로 커넥트하는 컷씬*
*전투*

레이나
상구에는 반드시 상징과도 같은 [주연]이 있는데,
카오스 텔러는 그 [주연] 또는 주변인물 누군가에게 빙의해서
상구를 혼란에 빠뜨리게 하지.

레이나
오늘 밤 성에서 무도회가 열리지?
어쩌면 이 상구의 [주연]이 그 무도회에
참석할거란 생각이 들었어.

레이나
엑스,
너 [주연]에 대해 뭔가 짚이는 게 있지?
네가 성으로 가려는 것도 그 사람과 관련된 거 아냐?

엑스
......신데렐라.
이 세계의 [주연]이라면 그녀밖에 없어.

엑스
신데렐라는 지금 성의 무도회에 있을 거야.
거기서 왕자님과 만나 사랑을 맺게 되어 있거든.
이정도면 어엿한 [주연]아니겠어?

레이나
자세히 알고 있네. 그렇게나 유명해?

엑스
본인한테 들었으니까.
집이 가까워 어릴 때부터 소꿉친구로 지냈어.

엑스
서로 어릴 때부터 알던 지긋지긋한 사이지만
결혼할 왕자님이 어떤 사람일지 신경 쓰여서 말야.
그래서 성으로 가고 있었던 거야.

레이나
흐음...
혹시 그 신데렐라를 좋아해?

엑스
그, 그럴 리가!
그냥 상황이나 좀 지켜보려고...

엑스
...정말 그것뿐이야.
설마, 카오스 텔러라는 존재가 나타날 줄은
생각도 못했어...

엑스
성에 있는 사람들...그리고 신데렐라...
모두 괜찮을까...

레이나
아무 일 일어나지 않도록 우리가 가는 거야.
소중한 것을 지키기 위해서라도
우선은 빨리 이 숲을 빠져나가자.

엑스
...응.

***

엑스
그런데 바깥 세계에는 이상한 게 다 있네.
이 [인도의 책갈피]만 해도... 히어로가 어쩌고했지만...

레이나
[인도의 책갈피]에 담겨 있는 건 옛 전설이나 전승 등으로
전해져 내려오는 히어로의 영혼이야.
책갈피의 앞뒤에 히어로의 영혼을 담을 수 있어.

레이나
이 세팅을 유니온이라고 하는데,
어떤 직업의 히어로와 유니온을 결성할 수 있는지는
책갈피에 나타난 문장에 따라 달라져.

레이나
책갈피로 연결할 수 있는 히어로의 영혼이 더 있다면
좀 더 다양한 방법으로 전투를 할 수 있겠지만...

엑스
잠깐. 발소리가 들려...
분명 새로운 빌런일 거야...
좋아, 다시 히어로와 연결해서...

빌런
크르르! 크르크르르르!!

엑스
으아, 너무 많아!
아무리 히어로의 힘을 빌린다 해도
이 상황을 돌파하기는 힘들 것 같은데...!?

레이나
침착해, 엑스.
확실히 [지금의 우리]만으로는 버거워.
둘이서 싸우는 거… 힘들긴 하겠지만....

???? ※타오
넷이서 싸우면 한 개도 안 힘들지롱!

레이나
타오!
셰인!
너희들, 먼저 성으로 가 있었던 거 아니었어?

타오
거참, 어쩔 수 없잖아 아가씨.
지금 사방에 빌런이 넘쳐나 정신이 없단 말이야.
이 녀석들이 길이라도 비켜주면 모를까.

셰인
레이나 언니야말로 늦었네요.
또 길을 잃으신 건가요? 그리고 그 남자 분은?

엑스
아, 음, 처음 뵙겠습니다!
엑스라고 합니다!
성까지 레이나 씨의 길 안내를 하고 있던...

레이나
그렇게 격식 차릴 필요 없어.
타오,이 사람도 [공백의 서]의 소유자야.
책갈피도 이미 건네줬어.

타오
오호라 그렇군! 그럼 얘기가 빠르겠네!
자 그렇다면 너도 좀 도와주셔야겠어!

타오
아,소개가 늦었군!
나는 타오! 이쪽은 여동생 셰인이야.

셰인
넵,셰인입니다.
잘 부탁해요,신참 씨.

엑스
자, 잘 부탁드려요!

타오
좋았~어! 아가씨와 합류했으니,
팀 편성을 하러 가볼까!

*파티 설정*

타오
그럼~ 타오 패밀리 제군들! 가볼까?!
전투 축제 시작이다!

레이나
잠깐!
나를 거기에 넣지 말라고 전부터 말했었지?!

***
*전투*

레이나
시정석을 입수했네...
좋아, 이 정도로 모였으면
[그것]을 할 수 있어!

엑스
[그것]이라니?
...그보다 레이나.
왜 등에 있던 책을 땅바닥에 내려놓은 거야?

레이나
쉿. 잠깐만. 나도 오랜만에 하는 거라...... 으음......
찾았다. 이 페이지네. 에헴.

레이나
나와라 [마법의 거울]!

엑스
......!?
책 속에서 거울이 나왔어...!?

레이나
이건 [마법의 거울].
거울에 비친 사람의 마음에서
새로운 히어로의 영혼을 불러내는 소환 도구야.

레이나
백문이 불여일견이지. 자, 잘 보고 있어.
지금부터 이 시정석과 거울을 사용해서
새로운 히어로의 영혼을 불러내는 거야!

*가챠*

레이나
...놀랐는걸. 설마 엑스의 책갈피에
와일드의 문장이 나타날 줄이야...

엑스
와일드라니?
그게 뭐길래 그렇게 놀라는거야?

레이나
보통은 책갈피에 한 두 가지의 직업과 연결할 수 있는데,
와일드는 모든 히어로의 영혼과 연결할 수 있는 문장이거든.

레이나
와일드의 문장은 정말 드물어.
나도 소문으로밖에 듣지 못했는데
정말 이 문장을 가진 사람이 있을 줄이야.

셰인
음,반대로 너무 많은 걸 할 수 있어서
특출난 게 없다고도 할 수 있지만요.
아니면 개성이 없다던가.

타오
허나 대단한 건 맞지.
히어로의 힘을 충분히 끌어내서 싸우기도 했고 말이야.
꽤 열심히 단련한 것 같아. 제법인데 너!

엑스
단련했다고 할 정도는 아니에요.
그저 소중한 것을 지킬정도의 힘은 있어야 할 것 같아서...

엑스
...저기 레이나, 타오, 셰인.
부탁이 있어요.

엑스
카오스 텔러를 쓰러뜨리는 거,나도 돕게 해 줘요.
여기는 내 고향이잖아요.
자신이 사는 곳은 자신이 책임져야죠.

타오
호오~ 책임을 진다라... 멋진데?
오케이 좋았어!
너를 우리 패밀리의 객원 멤버로 인정해 주지.

셰인
방해가 되지 않는다면 상관없습니다.
딱히 사정 봐 주지는 않을 겁니다.
잘 부탁해요.

레이나
사실 끌어들이고 싶지는 않았지만
네 힘이 필요할지도 모르겠어.
잘 부탁할게. 엑스.

엑스
응,나야말로.

***

레이나
......라는 사실이 이 상구의 [주연]에 대해서
알게 된 정보야.

타오
그렇구만.
그러니까 그 긴데렐라와 관련된 녀석이
바로 카오스 텔러라는 거네!

셰인
타오 오빠, 긴데렐라가 아니에요.
신데렐라입니다.

타오
걱정마라. 엑스!
너의 곁에는 무적의 타오 패밀리가 함께 있다!
네 여자친구,반드시 구해보이겠어!

엑스
저기,여자친구가 아니라니까요.

레이나
소용없어. 이 남자는 다른 사람 얘기를 잘 안 듣거든.
그리고 그 패밀리 어쩌구에 나는 좀 넣지 말아 주시지?
왠지 열 받거든?!

타오
슬슬 마을에 도착하겠군.
좋아, 이 몸이 직접 널 단련시켜 주겠어!

엑스
단...련을 시킨다니...
지금 그러고 있을 때가 아닌 듯한데...

타오
자~알 알고 있어.
다시 말하자면 실전 연습이라는 거지.
내 예감이 맞다면 이제 곧......

셰인
타오 오빠,왔어요.

셰인
전방에 새로운 빌런이 출현했습니다.

엑스
실전 연습이란게... 이런 거예요?!

레이나
그러니까 아까 말했었잖아.
타오는 이런 남자라니까.

타오
목숨 걸고 익힌 경험은 쉽게 잊혀지지 않는다는 말씀!
자, 간다! 타오의 실전 배틀 강좌 시작이다!

***
*전투*

타오
꽤 그럴싸해졌군. 좋아 이걸로 준비 완료!
이제 위풍당당하게 킨데렐라를 구하러 갈 수 있을거야!

셰인
신.데.렐라입니다. 킨데렐라 아닙니다.

엑스
조금은… 강해졌을까?
내가 얼마나 강해진 건지 전혀 실감이 나진 않는데.

레이나
현재의 자신의 상태를 되돌아볼 수 있다면
실감이 나겠지?

레이나
마침 잘 됐어.
널 [그 장소]로 한 번 데려가봐야 할 것 같아.

엑스
그 장소?
그런데… 왜 또 그 이상한 책을 내려놓는 거야?

레이나
이 책의 이름은 [미니어처 왕국].
거울을 꺼낼 때만 쓰는 이상한 책이 아니야.
진짜 모습을 지금부터 보여줄게.
※모형정원의 왕국

레이나
[...지금 이곳에서 나의 왕국의 문을 열어
초대받은 공백의 영혼을 가진 자
나의 권한으로 그것을 허가하노라...]

엑스
책 속의 마을에서 빛이...!

레이나
잘 왔어. 엑스.
여기가 [미니어처 왕국]의 안이야.

*미니어처 왕국*
