= 2. 빨간 망토의 상구 - Flero
:hardbreaks:

....
옛날 옛적 어느 마을에
빨간 망토라고 불리는 여자아이가
살고 있었습니다.

어느 날, 심부름 부탁을 받은 빨간 망토는
숲속에 있는 집에 살고 있는 할머니에게로
향했습니다.

그러자 빨간 망토 곁에 늑대가 나타나,
이렇게 말했습니다.

「빨간 망토야, 할머니에게
꽃을 따다 가져다드리면 어떨까?
이 길 끝에 예쁜 꽃이 피어 있거든.」

빨간 망토는 흔쾌히 길을 돌아갑니다.
그러나 늑대는 할머니를 잡아먹으려고
몰래 계획하고 있었습니다.

먼저 집으로 온 늑대는 할머니를
잡아먹고 그대로 할머니인 척하며
빨간 망토를 기다리고 있었습니다.

아무것도 모르는 빨간 망토는
할머니 집을 찾아옵니다. 그리고...
....

== 숲의 고갯길

엑스
... 겨우 빠져 나왔네!
설마 상구 바깥이 저런 안개로 뒤덮여 있을 줄은...

레이나
저건 [침묵의 안개]야.
모든 언어와 개념을 집어삼켜버리는 공간이지.
혼자 헤매고 있으면 존재까지 전부 사라져 버린다고 해.

레이나
우선 카오스 텔러의 존재를 감지해서 다음 상구로
온 것까진 좋은데... 여기는 대체 어떤 상구인 거지?

셰인
역시나 이 상구에 대한 상황 파악부터 필요하겠네요.
우선은 어디든 마을이 나오면 좋겠습니다만...

늑대
우오오오오오오오오오오오!!

엑스
으앗! 뭐야!
방금 들린 울음소리는... 늑대인가?

타오
아니,
아무래도 늑대보다 더 사나운 놈들인 것 같은데...

엑스
설마, 빌런!?

레이나
지금 놀라고 있을 때가 아니야!
모두 당장 책갈피를 준비해!

셰인
12시 방향에서 다수의 빌런들을 확인했습니다.
남김없이 다 섬멸해 버립시다!

***
*전투*

엑스
다행히 해치우긴 했지만...
갑작스럽고 난폭한 환영식이었네.

레이나
어느 상구에 들어가든 대부분 늘 이런 식이야.
그건 그렇고, 대체 어느 쪽으로 걸어가야 하는걸까...

????
너희들, 잠깐 실례해도 될까?

셰인
어라? 그 총은...... 혹시 사냥꾼이신가요?

사냥꾼
아, 나는 숲 근처에 있는 마을에 살고 있어.
잠깐 묻고 싶은 게 있는데, 이 주변에 여자아이 못 봤어?

사냥꾼
빨간 망토를 두르고
빵과 포도주가 담긴 바구니를 든
귀여운 여자아이인데...

타오
글쎄, 안타깝게도 못 봤는데.
그 귀여운 아가씨에게 무슨 일이라도 생긴 건가?

사냥꾼
며칠 전에 숲에 살고 있는 할머니 집으로 심부름 간 후로
아직까지 돌아오지 않고 있어.
나는 그 아이 엄마에게 부탁받아 찾고 있는 중이었어.

사냥꾼
게다가 최근 이상한 늑대들도 많이 보여서...
[운명의 서]에 이런 일은 안 적혀 있었는데...

엑스
레이나, 혹시 저 사람이 말하는 아이가
이 상구의 [주연]이 아닐까?

레이나
...그럴 수도 있을 것 같아.

레이나
여행자들이라 이 주변은 잘 모르지만......
혹시 괜찮으시면 저희도 그 여자아이 찾는 걸 도와드릴까요?

사냥꾼
오! 그래준다면 나야 고맙지!
저 늑대들과 싸워봤던 너희가 도와준다면
정말 든든할 것 같다!

셰인
그런데 사냥꾼 아저씨, 그 여자아이는 이름이 뭐예요?

사냥꾼
이 곳에선 그 여자아이의 이름은 아무런 의미가 없어.
그 아이는 빨간 망토를 두르는 운명을 가지고 태어났거든.
그래서 다들 그 아이를 이렇게 부르지.

사냥꾼
[빨간 망토],이게 그 아이의 이름이야.

== 숲의 남부

엑스
빨간 망토가 사라진지 얼마나 된건가요?

사냥꾼
아마도 대략 일주일 쯤.
마지막으로 목격된 건 숲으로 들어가는 모습이라더군.
그러니 분명 단서도 숲에 있을 텐데...

타오
빨간 망토 아가씨가 가려했던 할머니 집은 가 봤어?
숲 속에 있다고 했지?

사냥꾼
도중에 늑대들이 나타나는 바람에 아직 가 보지도 못했어.
수색대도 행방불명됐고......

사냥꾼
빨간 망토는 옛날부터 알고 있던 아이야.
영리한 아이니까 분명 어디 꼭꼭 잘 숨어 있긴 할텐데.......

셰인
한마디로 이 주변은 아주 위험한 곳이라는 거네요.

레이나
우선 이 주변에 단서가 있는지 찾아보자.
다들 신중해야 해.

***
*전투*

엑스
어? 이건 새로운 무기 레시피인가?
잘됐다. 그럼 무기 연구소에서 새로운 무기를 제작해서......

셰인
우왓, 그건!
진화 무기 레시피잖아요!

엑스
진화 무기 레시피?
셰인의 저 반응...왠지 이 상황,전에도 분명 본 적이 있......

레이나
잠깐만. 셰인!
지금은 우선 빨간 망토의 단서를 찾아야 할 때......

타오
늦었어 아가씨. 벌써 셰인의 스위치에 불이 들어왔어.

셰인
후후, 여러분 오래 기다리셨습니다.
셰인 선생님의 무기 강좌 시간이 돌아왔습니다.
이번에는 무기의 진화에 대해 알아보도록 하죠.

셰인
히어로들이 사용하는 무기는 진화 무기 레시피와
재료를 이용해서 더 강력한 무기로 진화시킬 수 있습니다.

셰인
물론 진화시키려면 일단 무기가 있어야 해요.
없을 경우엔 레시피를 얻어 무기를 만들어야 합니다.

셰인
의외로 이 상구에서는 여기저기에서
진화 레시피를 많이 발견할 수 있을지도 몰라요.
생각만 해도 벌써부터 가슴이 뛰기 시작하네요......

레이나
셰~이~인?
상황은 알고 있는 거지?

셰인
흠흠. 그냥 한번 말해 본 것 뿐이에요.
언니의 상냥함도 조금 더 진화하면 좋을텐데 말이죠.
뭐,이번에는 이 정도만 할까요.

셰인
 그럼 이상으로,
셰인 선생님의 무기 강좌 〈진화 편〉을 마치겠습니다.
들어주셔서 감사합니다~.

***

늑대
우오오오오오오오오오오오오오!

엑스
늑대 울음소리가 끊이지 않네요...

사냥꾼
이 지긋지긋한 늑대 놈들.
원래의 운명대로라면 내가 놈들의 배를 찢고
빨간 망토를 구해야 하는 건데......

레이나
빨간 망토를 구한다고?
그게 당신의 [운명의 서]에 적힌 역할이예요?

사냥꾼
그래, 맞아. [빨간 망토]를 두른 여자아이가
할머니로 변한 늑대에게 잡아 먹히고
그 아이를 사냥꾼인 내가 구하는 것이 나의 역할이야.

사냥꾼
이 세계는 그렇게 흘러가도록 되어 있었어.
모두 스토리 텔러님이 정한 운명이었지.
그런데, 대체 왜......

타오
살다보면 예정대로 되지 않는 일이 더 많지 않아?
그래서 인생이 더 재미있는 거고.

사냥꾼
뭐, 어쨌든.
예정대로든 아니든 그 아이는 내가 반드시 구해야 해.
무슨 일이 있어도 기필코.

엑스
반드시 빨간 망토를 찾도록 해요!
이런 숲에 여자아이를 혼자 있게 해선 안 되니까요.

사냥꾼
응, 고마워...

????
꺄아아아아아아아아아아아아아!!

셰인
지금 비명 소리...... 북서쪽 방향에서 들렸어요.
여자아이 목소리 같았는데,혹시......

사냥꾼
그 아이야... 그 아이의 목소리야!!

엑스
잠깐만요! 혼자 가는 건 위험해요!

레이나
늦었어, 이미 가버렸어!
어쩔 수 없네. 우리도 빨리 뒤쫓아가자!

== 깊은 숲의 동굴

엑스
이런 숲 속에 동굴이 있네?

레이나
발자국이 이쪽으로 이어지고 있어.
빨리 사냥꾼을 찾아야 해! 너무 늦기 전에......

????
크르, 크르르르아아아아아!!

엑스
방금 그 소리, 뭐지?

타오
정신 바짝 차려. 아무래도 성가신 녀석들이 있는 것 같아...!

***
*전투*

엑스
설마 메가 빌런까지 나타날 줄이야......
그나저나 그 사냥꾼 아저씨는 무사한가?
서둘러 찾아야 할텐데......

셰인
아니, 찾지 않아도 될 것 같아요.
이건 방금 그 메가 빌런이 떨어뜨린 건데요...

레이나
그건, 그 사냥꾼의 사냥총!?
그렇다면 설마, 지금 그 메가 빌런이......

엑스
자, 잠깐만.
조금 전까지도 같이 있었잖아.
아까까지만 해도 같이 이야기 나눴잖아......

타오
카오스 텔러에게 당한 거야.
녀석은 틀림없이 이 숲 어딘가에 숨어 있어.
젠장, 내가 같이 있었어야 했는데...!

엑스
... 레이나.
네 힘으로 카오스 텔러가 있는 곳을 찾을 수는 없는 거야...?
이 근방에 있는 거잖아...?

레이나
내가 찾을 수 있는 건,
카오스 텔러가 있는 상구까지야.
그 상구 안에서 카오스 텔러가 어디 있는지는 알 수 없어.

레이나
이 상구는 이미 카오스 텔러의 영역이 되어 버렸어.
저쪽에서 먼저 정체를 드러내지 않는다면......
앗!?

엑스
왜 그래, 레이나!?

레이나
거기 누구지? 이쪽으로 나와 주겠어?

????
미, 미안해요! 노, 놀라게 할 생각은 없었어요!

엑스
빨간 망토를 두른 여자아이... 설마, 너는...

늑대
우오오오오오오오오오오오!!

레이나
이런 동굴에까지 늑대가!? 일단 여기를 빠져나가자!

레이나
너도 이쪽으로 와! ... 빨간 망토라고 불러도 되지?

빨간 망토
네, 넷! 잘 부탁드려요...!

== 숲의 깊은 곳

빨간 망토
나, 엄마 심부름으로 할머니 댁에 가고 있었어.
그러다 늑대를 만났는데, 늑대가 지름길을 알려줘서...

빨간 망토
지름길로 가는 중에 할머니 드리려고 꽃을 꺾고 있었는데...
갑자기 많은 늑대들이 쫓아와서 계속 숲 속에서 도망쳤어...

엑스
그랬구나. 무서웠을텐데 혼자서 잘 견네.
이제 우리가 있으니까 안심해.

빨간 망토
엑스 오빠... 고마워...

타오
우선 이 아이를 안전한 마을에 데려다 줘야겠군.
이런 위험한 숲에서 계속 데리고 다닐 수는 없으니까.

레이나
무슨 소리야. 카오스 텔러의 공격이 계속되고 있는 이상,
이대로 탐색을 계속 해야 해.
마을이 안전하다고 보장할 수 없어.

타오
아이를 지켜가며 어떻게 탐색을 하라는 거야.
아가씨, 미안하지만 여기에서는 패밀리 대장인
내 지시에 따라 줘야겠어.

레이나
나는 당신 패밀리에 동참한 기억도 없을 뿐더러
널 대장으로 인정하지도 않아.
일단, 리더는 나잖아?

타오
어이 잠깐만, 그거야 말로 말이 안 되잖아.
아가씨가 리더였다면 우리는 이미 길을 잃었을걸?

레이나
상구에서만 길을 잃는 거라고!
전략적인 면에서는 아무 문제 없어!

엑스
두 사람 지금 싸우고 있을 때가 아니잖아!
셰인, 말리지 않아도 돼!?

셰인
걱정하지 마세요. 늘 있는 일이니까.
이 쓸모 없는 싸움을 반복하는
언니와 타오 오빠의 머리가 가끔 걱정은 되지만요......

셰인
우선 가만히 있는 것도 위험하니까 쉴 곳을 찾아볼까요?
두 사람은 어차피 알아서 따라올 테니.

엑스
좋아. 가자, 빨간 망토.

빨간 망토
응.

*

타오
...잠시 휴전하지. 아가씨.

레이나
...좋아. 나도 말을 너무 많이 했더니 피곤해졌어.

빨간 망토
엑스 오빠, 배 안 고파? 나, 빵 가지고 있는데!

엑스
고마워. 하지만 괜찮아.
할머니께 드리려는 빵을 먹을 수는 없는걸.

빨간 망토
응... 알았어...

레이나
엑스,아이 달래는 솜씨가 좋은데?

타오
순수하고 상냥한 성격이니까 아이도 잘 돌보는 거겠지.
그런데 앞으로 어떻게 하면 되려나......

엑스
빨간 망토야. 너는 어떻게 하고 싶어?
마을로 돌아가고 싶어?

빨간 망토
난 할머니가 계신 곳에 가고 싶어.
아직 제대로 심부름도 마치지 못했고......

빨간 망토
엑스 오빠랑 다른 분들한테
많이 미안하지만... 할머니댁에 가면 안 될까?

엑스
빨간 망토가 이렇게 말하는데 다들 어떻게 할래?

타오
...이거, 어쩔 수 없잖아.

레이나
...할 수 없네. 여기는 [주연]의 말에 따르자.

엑스
다들, 고마워!

셰인
\...............

레이나
왜 그래, 셰인?

셰인
아니, 아무것도 아니에요. 서둘러 갈까요...

== 할머니의 집

빨간 망토
할머니, 나야! 어? 집에 안 계신 걸까?

엑스
아무도 없어...
싸운 흔적은 없으니 어디론가 외출하신 걸까?

레이나
할머니로 변장한 늑대도 보이지 않아.
아직 운명의 서에 적힌 일이 벌어지기 전인건가?

타오
그나저나 꽤나 마음 느긋한 할머니시네.
테이블 위에 물건들도 잔뜩 어질러져 있고......
이 잔에 남아있는 건...... 포도주인가?

엑스
그러네. 그럼 일단 집 밖으로 나가서 찾아 보는 게...

셰인
잠시만요. 그 전에 확인하고 싶은 게 있어요.

셰인
빨간 망토 씨, 빨간 망토 씨.
일주일씩이나 숲 속에 있었는데
어째서 바구니 안의 빵에 곰팡이가 생기지 않은거죠?

빨간 망토
음, 왜일까? 곰팡이가 잘 생기지 않는 빵이라서?

셰인
빨간 망토 씨, 빨간 망토 씨.
왜 그 바구니 안의 포도주 병은 그렇게 양이 줄어 있는거죠?

빨간 망토
어랏, 그러게? 누가 마신 건가? 에헤헤.

엑스
셰인, 갑자기 무슨 말을 하는거야?

셰인
빨간 망토 씨, 빨간 망토 씨.
당신은 왜 우리를 여기로 데리고 온 거죠?

빨간 망토
아하하, 그거야 뻔하잖아.
늑대 먹이로 삼으려고?

늑대
우오오오오오오오오오오오오오오!!

엑스
빌런에게 포위당했어.
설마, 네가...... 카오스 텔러였던거야?!

레이나
아무래도 우리,완전히 당한 것 같네.

타오
흥, 이 꼬맹이가 우릴 우습게 보고 있군.
셰인, 용케도 알아차렸구나!

셰인
일주일이나 숲에 있었다는데 너무 말끔하잖아요.
아마도 이 집을 중심으로 먹이로 삼을 표적을
확보해 왔나 봅니다. 아마 할머니께서도, 벌써......

빨간 망토
후후, 그렇게 무서운 표정 짓지 마.
이 아이들도 굶주렸는걸.
오늘은 오빠가 최고의 저녁식사가 되어주지 않을래?

***
*전투*

빨간 망토
...역시 다르네, 오빠들.
마을 사람들처럼 운명의 서를 고쳐 쓸 수가 없어...
대체 어떻게 된 거야?

엑스
... 어째서, 어째서야?
사냥꾼 아저씨는 너를 도우려고 했는데 대체 어째서, 이런...!

빨간 망토
무슨 소리를 하는 거야?
남자는 모두 치사~한 늑대인걸?
상냥한 얼굴로 다가와서 속이는 늑대잖아?

빨간 망토
그 사람은 나를 속였어. 나를 이용해서 엄마한테 접근했지.

빨간 망토
그러니까 다들 늑대한테 잡아 먹혀도 되는 거야!

레이나
이제야 정체를 드러냈군, 빨간 망토... 아니, 카오스 텔러!

타오
어이, 포기하는게 좋을걸.
카오스 텔러에게 홀린 녀석에게 설득 따위 안 통해.
쓰러뜨려서 원래대로 돌려놓는 수밖에 없어.

셰인
그게 이 아이를 구할 유일한 방법이예요.
각오 단단히 해요. 신참 씨.

빨간 망토
후후, 친절한 오빠.
당신은 과연 어떤 맛이 날지 너무너무 기대되는걸?

엑스
빨리 그 아이에게서 나가, 카오스 텔러.
이 이상 빨간 망토한테 그런 짓 시키지 마!!

***
*전투*

빨간 망토
그 사람...... 처음부터 날 속였단 말야......
분명 엄마에게 접근하려고 나를 이용했던 거야......
아무도 나한테는 관심도 없어......!

엑스
그렇지 않아... 너를 제대로 바라보고 있는 사람도 있어.
너는 영리한 아이잖아?
그러니까 내 말이 거짓말이 아니라는 것도 알 거야.

빨간 망토
\......

레이나
엑스, 이제 괜찮아. 나머지는 나한테 맡겨.

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라
여기 조율을 시작하오니......』

*조율 컷씬*

엑스
레이나에 의해 빨간 망토의 상구가 조율되고
카오스 텔러의 존재는 모두에게 잊혀졌다.
빨간 망토에 관한 모든 이야기는 제자리를 찾았다.

엑스
이건 나중에 들은 새로운 이야기......

*

셰인
사냥꾼 아저씨, 빨간 망토 어머니와 결혼한다더군요.
빨간 망토도 마음이 복잡했을 겁니다.

타오
부모의 재혼은 아이에게는 예민한 문제니까.
그 약해진 틈을 카오스 텔러가 비집고 들어갔던 건가.

엑스
결국, 나는 아무것도 하지 못했어.
그 아이를 슬픔 속에서 구하지도......

레이나
그런 건 아무도 못해.
그리고 네가 한 일, 완전히 부질없던 건 아니었나 본데?

엑스
응?
저기 있는 사람, 빨간 망토랑 사냥꾼 아저씨 아냐?

*

사냥꾼
빨간 망토야. 당장 나를 아빠로 인정해 주지 않아도 괜찮아.
하지만 내 마음이 진심이라는 것만 믿어줬으면 좋겠어.

사냥꾼
나는 네 엄마도 너도 사랑한단다.
그건 예전부터 변함없어... 그러니까...

빨간 망토
당장은 믿을 수 없어. 그러니까 천천히 생각해 볼래.

빨간 망토
이래도 나, 무지 영리한 아이라고.
그러니까 지금은 그렇게 하는 걸로, 괜찮지?

사냥꾼
...아아, 물론이지!

엑스
빨간 망토가 내가 한 말을 기억해 줬구나......

레이나
네 말이 효과가 있었는지는 모르겠지만
용기를 내는 데 조금은 도움이 되었나 보네.

레이나
... 슬슬 출발하자.
우리의 도움이 필요한 상구는 아직도 많이 있을테니까.
