= 5. 눈의 여왕의 상구 - Flero
:hardbreaks:

....
어떤 곳에 겔다와 카이라는
여자아이와 남자아이가 사이좋게 살고 있었습니다.

마음씨 착한 두 사람은 기쁠 때나 슬플 때
언제나 함께 하며 친남매보다 더 깊은 인연으로
이어져 있었습니다.

하지만 어느 날 카이는
저주받은 거울의 파편에 심장과 눈을 찔려,
눈처럼 차가운 성격으로 변해버렸습니다.

이윽고 카이는 무서운 눈의 여왕의 환심을 얻어
얼음과 눈에 갇힌 나라의 궁전으로
끌려가게 되었습니다.

남겨진 겔다는 카이를 찾으러
혼자서 멀고 먼 여행을 떠났습니다.
그리고.......
....
※게르다

== 눈보라의 설원

엑스
에...에...엣취!!
엄청나군, 온통 눈밭이야...
레이나, 산길이 험한데 괜찮겠어?

레이나
응. 괜찮아. 나도 운동 좀 하는 편이거든!
이런 산 정도는 금방 올...
오...올...올라챠아아앗!!

엑스
혹시 지금 그거 재채기야?

타오
큰일났네, 얼른 따뜻한 곳을 찾아야겠어.
이러다간 카오스 텔러고 뭐고 우리가 죽게 생겼어.

셰인
맞아요. 얼른...엇?!

셰인
저기 누가 있어요!
누구지? 여자애같은데.

엑스
진짜다!
저기요, 여기 좀 봐요!

*

????
하아, 하아...카이...

타오
우리를 못 본 것 같군...
이런, 괜찮은 건가?
다리가 완전 풀린 것 같은데...

셰인
그냥 가 버렸어요...
언니, 어떻게 할까요?

레이나
모, 모른 척 할 순, 없잖아.
빠알리, 쫓아가자...
샨낄, 힘들...

레이나
들, 드, 들...들깨챠아아앗!

***

엑스
이놈의 눈보라는 멈출 생각을 않네...

셰인
이거 장난이 아닌데요. 마치 태풍같아...
그 아이, 괜찮을까요...

레이나
...으...으윽.

타오
이거이거...
아가씨도 완전히 추위에 당해버렸군.
아까 그 꼬맹이도 무사하면 좋을텐데...

셰인
...!

셰인
앗, 아까 그 꼬마 아가씨 아닌가요?

*

????
으...으으...

엑스
눈밭에 쓰러져 있어!
큰일이야! 빨리 구해야 해!

레이나
참 내, 눈치들도 없이 이 타이밍에...

셰인
얼른 처리하겠습니다.
빌런 따위에게 방해 받을 순 없죠.

***
*전투*

셰인
정신차리세요. 제 목소리 들립니까?

????
으...으으... 거기에 있는 사람은... 카이...?
카이야?

엑스
헛소리까지 하네.
앗 뜨거! 열 좀 봐.

레이나
회복마법을 쓰면 열은 내리겠지만...
일단 따뜻한 곳으로 데리고 가야할 것 같아.

타오
내가 업을게.
그나저나, 대체 왜 이런 꼬마가 혼자 산에...

레이나
사정은 나중에 들으면 돼. 일단 서두르자.
눈 내리는 모양새가 심상치 않아.

셰인
동굴이라도 찾아야 할 것 같아요.
산 어딘가에 있을 거예요. 서두르죠!

== 설산의 동굴

????
으...음... 으...여긴?
히앗! 산적이닷! 산적인가요?!

셰인
아니요, 산적 아닙니다.
갑자기 움직이면 안 돼요. 동상 위험도 있으니까.

????
휴~ 고, 고맙습니다...
죄송해요, 살려주셨는데 산적이라고 해서...

레이나
괜찮아, 우린 그냥 여행자일 뿐이야.
넌 이름이 뭐니?

????
전 겔다예요. 저주받은 거울의 파편에 찔린 후
[눈의 여왕]에게 납치당한 소꿉친구 카이를 구하러
남쪽 나라에서 여기 얼음의 나라까지 왔어요.

엑스
눈의 여왕? 뭐야 그건?

겔다
이 설산 깊은 곳에 궁전이 있는데
거기에 마법의 힘을 가진 여왕이 살아요.

겔다
파편에 찔린 후, 카이는 감정을 모르는 상태가 됐어요.
그리고 나서 [눈의 여왕]에게 납치되었고...
그래서 저는 카이를 구하러 여기까지 온 거예요.

겔다
이러고 있을 시간 없어요. 빨리 가야 하는데...
어...어라?

엑스
아직 열이 안 내렸어. 지금은 안정이 먼저야.
푹 쉬어야해... 알았지?

겔다
...으...알겠습니다.

엑스
...레이나.
눈의 여왕과 카오스 텔러...
뭔가 관계가 있을 것 같지 않아?

레이나
그렇지도 몰라.
어쨌든 겔다를 혼자 놔 둘 순 없으니까
그 궁전으로 같이 가보는 게 좋을 것 같아.

타오
난 찬성.
그 외에는 딱히 단서도 없고.
그런데, 그 전에...

엑스
뭐야... 이런 동굴까지 빌런들이!

레이나
정말, 이런 곳에서까지 싸워야 해?
어쩔 수 없지, 다들 여기서 버텨야 해!

***
*전투*

레이나
빌런이 또 올까?
그건 그렇고 겔다. 이렇게 위험한 곳까지
어떻게 혼자 올 생각을 했어?

엑스
엄청 구하고 싶은가 보구나.
그 카이라는 남자애 말야.

겔다
네... 구하고 싶어요...
저에게 카이는 친오빠나 다름없으니까요.

겔다
엄청 다정하고 멋지고 완전 훈남이라구요!
그래서... 그러니까 제가 구해야 해요.

겔다
겔다는 카이를 꼭 구해야 해요.

셰인
...[친오빠나 다름없다], 군요.

셰인
알겠습니다. 그렇다면 구해야겠네요.
저희들이 도와줄게요.

셰인
...슬슬 제2라운드 시작하나 봐요.

*

타오
또 왔어?!
이거 완전 근성 싸움이잖아!

레이나
이게 마지막이길 빌 수 밖에 없어!

***
*전투*

레이나
휴, 겨우 해치웠네.

엑스
눈 그쳤나본데? 이제 밖에 나갈 수 있겠다.
눈의 여왕 궁전이 어딘지 알아?

겔다
...아니요.
이 눈을 내리게 하는 것이 눈의 여왕이라는 건 알고 있지만...

셰인
그럼 금방 찾을 수 있겠군요.

엑스
응? 정말?

셰인
지금 산에서 불고 있는 바람은
태풍처럼 소용돌이 모양으로 불고 있잖아요.

셰인
그러니까 바람 방향을 반대로 거슬러 가면 태풍의 눈...
그곳에 눈의 여왕 궁전이 있을 겁니다.

타오
역시 내 동생!
머리가 잘 돌아 가네! 그럼 이제 가 보자.

셰인
겔다. 목적지가 우리들이랑 같으니 함께 가요.
혼자서 가는 것보다 훨씬 안전할 거예요.

겔다
셰인, 고마워요.
우리 좋은 친구가 될 것 같아요! 헤헤헤.

셰인
흠흠... 이제 출발해볼까요?
갈 길이 멀어요.

엑스
...셰인이 저렇게 모르는 애한테
적극적으로 말 거는 스타일이었던가?

레이나
나도 이상하다고 생각했어.
저러는 건 처음 보는 것 같아.

타오
글쎄, 뭔가 공감하는 부분이 있는 거 아닐까?

타오
[오빠와 여동생]이라... 그런 이야기야 흔해빠진 거잖아.

== 흰 눈의 계곡

겔다
셰인! 빨리, 빨리이~!

셰인
알겠으니 좀 천천히 가요.
겔다, 몸도 성하지 않은데 그렇게 뛰다간 큰일 나요.

엑스
저 둘 꽤 친해졌네. 죽이 잘 맞는 건지 아닌 건지...
그런데 타오, 왜그래?

타오
기분 탓일지도 모르지만... 저 꼬맹이 왠지 찜찜하군.

레이나
겔다가 카오스 텔러일지도 모른다는 거야?

타오
카오스 텔러라기보다... 뭔가 위화감이 좀...

엑스
위화감이라니? ...그건 무슨...?

*

????
..겔다, 내가 오지말라고 했지!

겔다
...카이?

*

셰인
저 사람이... 카이?! 도대체 어떻게 된 거죠?
저 사람 빌런이랑 같이 있잖아요.

레이나
질문하고 있을 시간 없어.

카이
눈의 여왕님의 명령이다.
침입자를 즉각 처단해.

타오
온다!
다들 전투 준비!

***
*전투*

타오
야, 카이라고 했지? 꽤나 난폭하게 구네.
너 혹시 카오스 텔러냐?

카이
카오스 텔러라니, 그게 뭔데? 난 그런 거 몰라!
네 놈들이야말로 왜 겔다와 같이 있는거야!

셰인
당신이 카오스 텔러가 아니라니까 물어 보죠.
당신은 왜 빌런을 이끌고 있는겁니까?
왜 겔다의 곁을 떠난 거죠?

카이
...나는 [운명의 서]에 따르고 있을 뿐이야.
겔다를 두고 떠난 것도, 눈의 여왕님께 온 것도
전부 [운명의 서]로 정해져 있지.

카이
나는 눈의 여왕님과 계약을 맺었어.
그 분의 눈의 왕국 건설을 도와야 해.

카이
그러니 겔다... 방해하지 마.
또 여기 왔을 때 아무리 너라고 해도 안 봐줄 거야!

레이나
세상에... 메가 빌런까지 소환한 거야?
진짜 싸울 기세잖아.

엑스
겔다, 네 마음을 확실하게 전해.
카이가 돌아왔으면 하잖아.
그것 때문에 이런 눈 투성이 나라까지 온 거잖아!

겔다
...맞아... 데리고 돌아가야 해.
겔다는 꼭 카이를 구해야 해. 그게 겔다의 운명이니까.

셰인
겔다?

카이
이제 끝이다. 겔다... 너는 여기로 오면 안 돼!

***
*전투*

엑스
카이, 이제 그만해. 우리들이 싸울 이유는 없잖아.
이제 그만 겔다랑 함께 돌아가!

카이
시끄러!
아무 것도 모르는 주제에 잘난 척 지껄이지 마!
겔다는... 겔다는 말야...!

겔다
저기, 카이.
그 계약만 지키면 돌아올 수 있는 거야?
대신할 수 있는 사람만 데리고 오면 되겠네?

겔다
그럼 얘는 어때?

셰인
겔다?! 왜 지팡이로 셰인을 가리키는 겁니까?

겔다
셰인... 움직이지 마. 이래도 나 마법은 좀 쓸 줄 알아.
저항하면 바로 마법 쓸 거야.

타오
이건 또 무슨 상황이야?
내 소중한 여동생에게 도대체 무슨 짓을 하는 거야!

레이나
그랬던 거구나. 저주받은 거울의 파편...
그 파편에 찔린 건 카이가 아니라 겔다였던거야!

엑스
그런 말도 안 되는!
그렇다면 겔다는 도대체 왜 여기까지 카이를 찾으러...

레이나
그저 [운명의 서]에 따랐을 뿐일거야.
아마 저 아이는 자기가 왜 카이를 구하고 싶은지
모르는 거 아닐까?

타오
그거였군... 내가 느낀 위화감이...

겔다
나 확실하게 알고 있어요.
겔다라는 여자아이는 카이를 구한다.
그것이 이 세계에서 겔다의 역할...

겔다
내 마음이 텅 비어버려도 그 역할만은 완수해야 해.
그러니까 셰인... 부탁이야. 카이 대신이 되어 줘. 제발...

카이
그게 아냐, 겔다...
그만해... 그만두라고...

엑스
뭐야...이 흔들림은?

타오
모두 엎드려!
눈사태다! 눈덩이가 몰려온다!

셰인
겔다!

*

엑스
몇 분 후
나, 타오, 레이나는 눈사태를 피했지만
셰인과 겔다는 보이지 않았다.

타오
셰인... 이 바보 녀석!

레이나
화풀이는 나중에 해. 눈사태가 저쪽으로 내려갔어.
셰인이 기다리고 있을거야... 서둘러!

== 설산의 기슭

엑스
...저기... 겔다 아냐?
그 옆에 쓰러져 있는 건...

타오
셰인!

*

레이나
겔다... 무슨 일이 있었는 지 말해!
셰인은 무사해?

겔다
눈사태에 파묻이기 직전에 셰인이 날 구해줬어.
방금 셰인을 눈에서 파냈어. 아직 숨은 쉬고 있는데...

타오
...야...정신 차려!
너 이자식! 내 소중한 동생을 이 지경으로 만들다니...
도대체 무슨 생각이야!?

셰인
타오 오빠...
그...그만하세요.

레이나
셰인! 괜찮아? 움직여도 되는 거야?!
기다려. 지금 회복 마법 걸테니까!

셰인
걱정하지 않아도 괜찮습니다. 언니...
셰인 보기보다 꽤 터프하거든요.
그것보다도 타오 오빠, 무섭게 그러지 말아요.

셰인
겔다는 셰인이 지켜준 겁니다.
그러니까 겔다한테 너무 그러지 마세요.

타오
진짜 돌아버리겠군.
진짜 요만큼도 귀여운 구석이 없는 동생이라니까.

겔다
왜 구한 거야? 그게 셰인의 운명이야?
널 이해할 수 없어... 진짜 모르겠어...
무슨 생각인지.. .난 모르겠다구...

셰인
그냥 보고만 있을 순 없었어요...
[오빠와 여동생]이라는 말까지 들었으니 더욱,
모른척할 수 없었어요.

겔다
\...............

타오
무슨 말인지 모르겠다는 표정이네.
머리에 쥐날 때까지 고민해 봐.
너한테 사람의 마음이 조금이라도 남아 있다면 알겠지.

*

타오
그러고보니, 카이란 놈은 없나 보군...

셰인
눈사태를 그냥 당하고 있을 위인이 아닐겁니다.
아마 눈의 여왕 궁전으로 돌아갔을 거예요.
일단 빨리 가죠. 이제 괜찮으니까.

레이나
아우...아무리 마법을 걸었다고 해도
너무 빨리 회복하는 거 아냐?
그래도 다행이야. 무사해서...

엑스
그래... 셰인, 다행이야. 돌아와 줘서 기뻐.

셰인
닭살 돋아요, 그만 그만. 쑥스럽잖아요.
하지만... 걱정 끼쳐 드려서 죄송해요.

셰인
저 무사히 살아 돌아왔습니다.

*

셰인
꽤 깊은 곳까지 왔네요.
눈의 여왕 궁전도 곧 나오겠죠.

겔다
...응.

셰인
겔다는 왜 카이를 데리고 돌아 가려고 했던 거죠?
[운명의 서]에 그렇게 따르고 싶었나요?

겔다
...역시 모르겠어... 머리 아파...
기분이라든지 뭘 원하는지 그런 거 하나도 모르겠어.

겔다
지금까지 겔다가 카이와 어떻게 지냈는지 기억은 있어.
하지만 기억과 마음이 따로따로...
마치 내가 아닌 것 같아.

겔다
지금의 나는 [기쁘다]든지 [슬프다]든지...
그런 거 전혀 못 느끼거든.

셰인
옛날엔 셰인도 혼자였어요.
[기쁘다] [즐겁다]... 그런 거 잘 몰랐어요.

셰인
언젠가부터 엄청 부산스러운 [오빠]가 생기고,
그러면서 셰인의 마음 속에 다양한 감정이
생겨나기 시작했어요.

셰인
겔다에게 없는 마음을 카이 씨가 가지고 있을 거예요.
그러니까 겔다는 카이 씨를 꼭 찾아와야 해요.

겔다
휴... 셰인이 무슨 말 하는지 이해가 안 돼.

셰인
몰라도 상관없어요. 셰인이 도와줄 거니까.
그것만 알고 있으면 돼요.

*

타오
...나 참. 우리 동생님께서는 너~무 사람이 좋은 거 아냐?
어이... 너네들도 그렇게 생각하...?!

엑스
흑...흑... 셰인...

레이나
...훌쩍... 셰인... 너... 흐흑...
이런 타오를 그렇게 생각할... 흑...

타오
...이...이봐... 그만 해...
둘이 동시에 왜 울고 난리야...

엑스
타오도 목소리가 벌써 우는데 뭐.

타오
무! 무슨 말 같잖은 소리야!
이건 그거라고, 그거! 저기 뭐냐, 코...코가 막힌 거라고!

타오
다들 사람은 좋아가지고... 에이... 팔자야, 팔자.
귀여운 여동생이 분투하겠다니, 협력해줘야지.

타오
좋았어! 그럼 가볼까.

== 얼음 궁전

엑스
벽 전체가 얼음이야...
도대체 이 궁전 뭐야...?!

셰인
어디부터 찾아야 할까요?
인기척이 전혀 없어요.

레이나
찾을 필요 없을 것 같아.

타오
일부러 우릴 맞이하러 나오셨네.
같이 돌아갈 마음이 생겼나?

카이
아니. 안 돌아가.
돌아갈 생각도 없어.
그러니 겔다, 빨리 돌아가!

겔다
카이... 왜 그러는 거야? 내겐... 겔다에겐, 당신이 필요해.
카이... 제발...

겔다
그런 소리 그만 해!
넌 네 [운명의 서]에 따르고 있을 뿐이잖아.
그런 거... 이젠 아무 의미 없어...!

타오
[운명의 서]에 속박되어 있는 건 너도 마찬가지잖아!
아니면 여동생을 돕기 위해서냐?

카이
...?!

타오
역시... 같은 오빠 입장이라 알 것 같군.
원래 네게 걸려야 하는 저주가
소중한 여동생에게 걸려 버린 거겠지.

타오
다정다감하다는 네가 신경 안 쓰일 리가 있나.
안 그래?

겔다
카이... 진짜야?

카이
너랑 상관없는 얘기야!
그만하고 꺼져... 사라져... 사라지라고!

엑스
우린 사라질 생각 없어!
그치, 셰인?

셰인
무슨 당연한 말을 하는 겁니까... 신참 씨.
우리들은 오지랖이 엄청 넓어서 참견하는 게... 맞습니다.

***
*전투*

카이
하아... 하아... 하아...

엑스
카이... 이제 진실을 말하지 그래.
우리들은 너와 겔다를 도와주고 싶어.
사실은 너도 가지고 있는거 아니야?

엑스
그 뭐랄까...
자신의 진짜 바람 같은 거 말야.
그래서 우리가 여기까지 온 거라고.

카이
어떻게 해야 할 지 나도 몰라!
원래 저주 받아야 할 운명인건 나인데...
지금은 이 방법 밖에 없어...

카이
계약대로 하면 겔다를 원래대로 돌려주겠다고 했어!
눈의 여왕이 그랬어... 그러니까...!

겔다
카이... 그랬구나...
내가 카이를 고통스럽게 하고 있었던 거네...

카이
겔다...?
너 울고 있는 거야?

겔다
...어, 어라?
내, 내가... 어째서? 난 마음이란 게 사라진 지 오래인데...

레이나
눈의 여왕은 저주를 못 풀어.
겔다의 저주를 풀 수 있는 건 카이 너밖에 없어.

타오
알아 들었냐? 이제 도망치는 건 그만 해.
얘랑 얼굴 마주보고 얘기해서 풀어!

카이
\......

카이
기억하고 있어? 둘이서 같이 키운 장미말야.
잊을 리가 없지.
겔다가 찬송가를 부르며 열심히 물을 줬었잖아...

카이
겔다... 네가 필요해. 네게서 도망치지 않을게.
네가 잃어버린 마음을 다시 찾을 때까지
네 옆에 영원히 있을 거야!

겔다
카이...
난... 나는...!

????
카이를 넘 보지 마라...
이 아이는 내 것이다.

*

엑스
눈의 여왕?!
저 모습은... 역시...

레이나
...그래, 정답이야.
눈의 여왕, 당신이 이 상구의 카오스 텔러구나.

눈의 여왕
카이는 이 세계에서 가장 맑은 마음을 가진 자다.
그렇기 때문에 그 마음을 영원히 가둬 두고 싶은 거지.

눈의 여왕
사랑하는 사람을 위해 필사적으로 발버둥치는 모습...
슬픔, 탄식, 분노... 얼마나 아름답느냐?

셰인
그러니까 당신은 고통스러워 하는 카이를
곁에 두고 싶어서 다를 이렇게 만들었단 건가요?
이런 나쁜...!

셰인
당신만은 절대 용서 못합니다!

***
*전투*

타오
이제 널 속박하고 있는 건 없어.
빨리 겔다한테 가 봐.

카이
겔다... 겔다!
절대 헤어지지 말자! 영원히 같이 있을 거야!

겔다
카이...울고 있어...?
눈의 여왕한테서 해방도 됐는데 뭐가 그렇게 슬퍼?
왜...나도 울고 있는 거지?

카이
그건 기뻐서야.
나도, 겔다도, 겨우 함께 있을 수 있게 돼서,
그게 기뻐서 우는 거야...

겔다
기...뻐...? 이게...?
나... 나는...!

카이
겔다에게 들어간 거울의 파편이... 산산히 흩어지고 있어...!
혹시 저주가...!

겔다
카이! 카이... 나 여기에 있어!
기뻐! 내 마음 속에 기쁨이 넘쳐 흐르고 있어!

셰인
...그렇군요. 겔다는 그렇게 웃는 군요.

겔다
셰인... 미안... 널 너무 아프게 했어...
그런데도 넌 날 몇 번이고 구해주고...

셰인
그럼 사과 대신에 아주 끝내주는 미소로 인사 해 주세요.
셰인은 겔다의 미소가 보고 싶어요.

겔다
...응, 그렇게.
셰인... 고마워요. 진짜 고마워.

타오
아하하... 웃는 건지 우는 건지 나도 모르겠다.
우리 여동생은 하나도 안 변했지만.

셰인
시끄러워요! 훌쩍...
언니... 뒷일을 부탁드려요.

레이나
그래. 알았어.

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라
여기 조율을 시작하오니......​』

*조율 컷씬*

== 눈이 녹은 초원

카이
겔다... 이제 곧 집에 도착할 거야.
집에 가서 장미 키우자.
아름답고 예쁜 장미로...

겔다
응... 카이!

엑스
눈이 녹아 내리고 세계에 봄이 찾아온다.
따뜻한 햇살 아래 둘의 웃음 소리가
마을을 조용히 울린다.

엑스
그런 둘의 모습을 지켜보며
우리들은 다시 다음 상구로 여행을 떠난다.
이야기를 본래의 모습으로 되돌리기 위해...
