= 6.1. 프린세스·이펙트!! ※프린스 키스 이펙트 - Flero
:hardbreaks:

엑스
――카오스텔러를 [조율]하기 위한 여행을 하는 우리는
여행 도중 어느 상구에 들어가게 된다.

엑스
레이나의 말에 따르면 카오스텔러와는 아무 상관 없는
평화로운 상구로, 우리도 느긋하게 전진하면서
이 상구를 벗어나려고 했었다.

엑스
한 여자아이가 쓰러져 있는 것을
발견하기 전에는――

== 난쟁이의 숲

엑스
...어쩌지, 이 아이 숨이 멎은 것 같아!

레이나
지, 진정해 엑스.
이럴 때에는 의사, 의사를 불러야 해...
지금 내가 마을에 가서 누군가 데려 올게!

타오
진정하라고 아가씨. 그러는 게 훨씬 더
위험하다고(길을 잃어버릴 수 있으니까).
빨리 손을 쓰면 다시 숨을 쉴지도 모르겠는데...

엑스
음, 그래, 알았어.
...그럼 이렇게...!

레이나
어? 엑스 어째서 얼굴을 가까이 대고...
엇, 입맞춤!?
잠들어 있는 여자아이에게 무슨 짓이야!

셰인
아니에요 언니. 저건 인공호흡입니다.
솜씨가 좋네요, 신참 씨.
초보의 솜씨라고 볼 수 없을 정도예요.

엑스
옛날엣, 근처엣, 살던읍, 할아버지갓,
가르쳣, 주셔서읍,

엑스
이렇겟, 가슴을 압박하면섯, 숨을읍, 불어 넣으면읍,
눈을 뜰 거얏,

????
......음, 으응?

엑스
아, 정신이 든 거야?
다행이다, 괜찮아――

????
왕자님...
기다리고 있었습니다, 왕자님~~~~!!

전원
엇?

????
처음 뵙겠습니다, 저는 백설공주라고 합니다!
드디어 만나러 와 주셨군요, 왕자님.
아아, 세상에나 이토록 상냥한 얼굴!

백설공주
결혼식 준비는 어떻게 할까요?
일정은? 초대 손님은? 요리는? 연회장은?
이 날을 위해서 이것저것 계획을 짜다 보니――

엑스
자, 잠깐만! 백설공주라 했지?
나는 왕자님이 아니야!
다들 보고만 있지 말고 좀 말려봐!

타오
꼬마. 말리고 싶은 마음은 간절하지만
어쩐지 그럴 상황이 아닌 것 같군.

*

셰인
...무슨 뜻이에요, 언니.
이 상구에는 카오스텔러가 없는 것
아니었나요?

레이나
...어쩐지 곤란한 일에 말려든 것 같아.
우선 이 자리를 떠납시다!
자, 백설공주도 같이!

***
*전투*

엑스
―― 백설공주와 함께 빌런을 물리친
우리는 우선 안전한 곳까지 도망갔다.

엑스
우리는 그곳에서 백설공주에게 자세한 사정을
들을 수 있었다. 백설공주가 맞이하게 될 운명의
결말에 대해서도――

*

레이나
즉, 당신은 독사과를 먹고 잠이 들었다.
하지만 왕자님이 키스를 해서 당신은 눈을 뜨고
마침내 결혼을 한다...그것이 당신의 운명이란 말이지?

백설공주
그렇다니까!
나의 [운명의 서]에는
그렇게 적혀 있었어.

엑스
그래서, 백설공주를 깨울 왕자님의 키스
대신 내가 인공호흡을 해버려서
운명의 줄거리가 바뀐 거구나...

셰인
그 얘기예요. 그리고 뒤엉킨 줄거리를 수정하기
위해서 스토리텔러가 무리한 방법을 펼친 것이
현재의 이 상황인 것 같아요.

레이나
말하자면 그 빌런들은 카오스텔러가 아니라
일반적인 스토리텔러가 만들어낸 병사들이란 거지.
그러니까 [조율]로 막을 수 없어.

레이나
애초에 카오스텔러와 스토리텔러는 같은
존재이니까 빌런을 만들어 내는 것도 이상할 게
없긴 하지. 설마 이런 일이 벌어질 줄이야.

타오
이번에는 꼬마의 선량함이 문제가 되었군.
이렇게 된 이상 빨리 이 상구를 빠져나가는 게 최선일
것 같은데...

백설공주
싫어.엑스 님과 떨어지는 건
절대 안돼!! 키스도 했는걸!

백설공주
내 첫키스를 줬으니까
책임져!!

셰인
굉장해. 대사만 들으면 신참 씨
완전히 몹쓸 왕자네요.
어이, 몹쓸 왕자님.

엑스
그만두지 못해!
이상한 별명 붙이려고 하지 마!

타오
뭐, 어쨌든 구해줬으니까
마지막까지 책임을 져야겠지.
어떻게 할 거야, 아가씨?

레이나
...이 아이의 운명이 어떻게 바뀐 건지 알 수 없지만
이런 곳에 이 작은 아이를 두고 가는 것도
못할 짓이야.

레이나
진짜 왕자를 찾는 게
가장 좋겠지만...적어도 가까운 마을까지
이 아이를 데리고 가자.

백설공주
와아~!
여러분 그리고, 엑스 님.
부족하겠지만 잘 부탁드립니다!

엑스
하하하…

== 왕비의 성

독사과의 왕비
백설공주는 예정대로 독사과를 먹고는
영원히 잠들어 버렸어. 비로소 거울이 말한
세상에서 가장 아름다운 여성 [한 명]이 사라졌어.

독사과의 왕비
그리고 또 한 사람...라 벨을 없애면
내가 세상에서 가장 아름다운 여성...
그렇지 거울아...후후후...

== 짐승의 숲

엑스
백설공주, 괜찮아?
엄청 졸려 보여.

백설공주
괜찮아요, 엑스 님...
이 정도는...정말, 끄떡 없어요...

셰인
이제 착한 아이는 잠들 시간이에요.
슬슬 쉴 수 있는 장소를 찾아보는 게
좋겠어요...

셰인
그런데 타오 오빠. 눈치 채셨나요?

타오
아아.
아까부터 누군가 따라오고 있어.

엑스
...설마 빌런?

엑스
아닌 것 같아.
빌런이라면 미행을 하지 않고
금방 습격했을 거야...

타오
어~이, 우리한테 볼일이 있지?
숨어있지 말고 어서 나오는 게
어때?

????
흥. 꽤 큰소리 치는군, 인간.

백설공주
엄청 큰 사람이네요...
늑대는 아니겠지요...

엑스
그런 것 같아...
빌런도 아닌 것 같은데...

야수 라 베트
늑대도 빌런도 아니다.
나에게는 라 베트라는 이름이 있다.
그보다 [야수]라 흔히들 부르고 있지만.

야수 라 베트
내 모습을 보고 겁내지 않다니 보기 드문 여행자구나.
그래서? 내 영토에 찾아 와서
무슨 볼일이 있는 거지?

레이나
우리는 쉴 곳을 찾고 있어.
적어도 하룻밤만 묵을 곳을 빌려줄 수
없을까.

야수 라 베트
...예전에도 그렇게 말하는 여행자를 재워 주었더니
엄청난 배신을 당했다. 인간은 신뢰할 수 없어.
어서 사라져.

셰인
그럼, 이 근처에 마을이 있는지 알려주실 수 있나요?
왕자님이 있을 법한 궁전도 함께 있으면
가장 좋겠지만...

야수 라 베트
...궁전?...왕자?
너희들, 궁전으로 가고 싶은 거냐...

야수 라 베트
잘 들어라, 여행자들이여.
내 부탁들 들어준다면
저택을 안내해 주겠다.

엑스
정말입니까!?
감사합니다, 베트 님!
이봐, 백설공주. 이제 금방이니까 조금만 힘내.

백설공주
으...
알겠습니다...후아암...

야수 라 베트
이쪽이다, 따라와.
도중에 무엇이 나올지 모르니까
조심해라.

== 장미의 저택

엑스
―― 우리는 라 베트 저택으로 들어갔다.
그곳은 아름다운 장미가 피어있는 저택이었다.

엑스
우리를 저택에 초대한 라 베트의 부탁.

엑스
그것은 이웃 나라 궁전으로 간 채
저택에 돌아오지 않는 한 여성을
확인해달라는 것이었다――

*

레이나
라 벨...음 그러니까, 벨이라고 불러도 될까?
당신은 그 사람을 찾고 있단 거지?

야수 라 베트
찾고 있는 게 아니야. 단지, 궁전에서 온 편지를
읽고 이 저택을 떠난 뒤 돌아오지 않고 있다.
어떻게 지내는지 조금 궁금할 뿐.

야수 라 베트
아마도 야수와 함께 사는 나날이
견딜 수 없을 만큼 싫었을 거야. 떠난다고 한다면
내가 잡을 수는 없겠지만 뭐, 혹시나 하고 말이야.

타오
...어쩐지 이 상구에는
귀찮은 녀석들만 나오는 것 같아.
대체 어떤 이야기가 원본이야?

레이나
그보다 세계관이 맞지 않는 것 같은데?
어쩌면 이곳은 스토리텔러가
여러 이야기를 합쳐서 만들어낸 상구일지도 몰라...

백설공주
벨 님...벨 님...

엑스
백설공주, 억지로 일어나지 않아도 돼.

백설공주
아니에요, 걱정하지 않으셔도 됩니다.
그보다 벨 님이라면 혹시.

백설공주
이번에 이웃나라 첫번째 왕자님과 결혼한다는
벨 님이 아닐까――

야수 라 베트
겨, 겨겨겨겨겨, 결호오오오오오온!?

백설공주
꺄아악!!
저, 저 혹시, 이상한 말을 했나요!?

셰인
잘은 모르겠지만 야수님의 멘탈에
크리티컬 히트가 발생한 건 틀림 없는 것 같아요.

야수 라 베트
벨...오오, 왜지 벨이여...
내 청혼은 그렇게나 계속 거절했으면서...!

야수 라 베트
...두고 볼 수만은 없어.
나도 간다, 여행자들이여!

레이나
어. 당신도 가는 거야?

야수 라 베트
당연하다! 벨을 누구에게도 줄 수 없다!!
마음대로 떠나다니 용서할 수 없어, 용서치 않아!!
그럼, 날이 밝으면 출발이다!!

엑스
...혹시 우리가
이 상구의 줄거리를 점점
이상한 방향으로 바꾸고 있는 건가?

레이나
곤란한걸.
이 상황, 엄청 곤란해졌어.

== 이웃 나라의 성 밑 마을

엑스
―― 다음날 아침, 우리는 베트와 함께
이웃나라 궁전에 도착했다.

엑스
시가지는 왕자와 벨의 결혼 소식으로 떠들썩했다.
우리는 어떻게든 벨을 만날 수 없을지 탐색을
시작했다――

셰인
어쩐지 벨 님은 신부수업 때문에
초원에 있는 오두막에 격리되어 있는 것 같아요.
경비가 매우 삼엄하다 해요...

야수 라 베트
흥!
그런 것쯤은 내 힘으로 제압해 버리겠어...!

레이나
부탁이니까 여기에서 소란 피우지 말아줘.
 +
그럼 어떻게 접근할까.

백설공주
어라, 저기에 있는 건...

엑스
응? 백설공주, 무슨 일이야?

백설공주
...역시 틀림없어!

엑스
아, 잠깐만. 백설공주!

*

독사과의 왕비
(후후훗, 라 벨, 네 손에
독사과를 건넸어...
모든 것은 내 [운명의 서]에 적힌 대로야...)

독사과의 왕비
(자, 라 벨. 어서 독사과를 먹고
영원히 잠들어 버려....그러면
나는 또 다시 세상에서 가장 아름다운 여자가――)

백설공주
새어머니, 오랜만이에요!
건강하셨어요?

독사과의 왕비
으음, 백설공주.
꽤 건강해 보이는 구나――

독사과의 왕비
배, 배배배 백설공주!?
어째서 여기에!?

백설공주
저는, 벨 님에게 인사를 드리러 왔는데...
어머니께서는 어째서 여기에?

독사과의 왕비
아, 아니, 나는...

독사과의 왕비
(어째서 백설공주가 라 벨을 만나러...?
이대로라면 라 벨에게 준 사과의 정체를
백설공주가 눈치챌지도 몰라...이대론 안 돼...)

독사과의 왕비
...실은 나도 벨 님에게 인사를 드리러 왔단다.
잘됐구나 백설공주. 너도 나라를 대표하는 사람으로서
나와 함께 가는 게 좋겠어.

백설공주
감사합니다. 새어머니!
맞아요, 나라의 대표이니까요.
그럼 이분들도 함께 잘 부탁 드려요!

독사과의 왕비
...이분들?

백설공주
네, 저를 많이 도와주신 분들이에요!
엑스 님! 여기에요!
새어머니가 벨 님을 만나게 해주신대요!

독사과의 왕비
(히익!? 엄청 많은데!?
인간이 아닌 것도 있어!?
에잇, 할 수 없군!!)

독사과의 왕비
좋습니다 여러분.
라 벨 님과 만날 수 있도록 계획을 짜 보겠습니다.
저를 따라 오시지요.

== 성 근처의 초원

라 벨
벌써 그 장미 저택을 떠나온 지 한달.
분명 그 사람도 걱정하고 있을 거야...
결국 아버지를 설득하지 못하고 여기까지 와버렸어...

라 벨
아까 노파에게 받은 이 사과.
그 사람이라면 한입에 몽땅 털어 넣었을 거야...

라 벨
...나 좀 봐, 무슨 소리를 하는 거야.
지금 나는 베트와 만날 염치가
없어...

야수 라 베트
벨!

라 벨
거짓말...어째서...
베트, 어째서 당신이 여기에...!

야수 라 베트
...벨, 어째서지.
너는 내가 아니라 왕자를 택하는 거야?

라 벨
...아버지의 부탁이에요. 왕자가 나를 무척
마음에 들어 하니 결혼 하라고.
그러는 게 내가 행복해질 수 있는 길이라고.

야수 라 베트
그 남자는 얼마나 더 제 멋대로 할 셈이야...!
내 장미뿐만 아니라 벨까지 빼앗으려는 건가!

라 벨
그건 당신도 마찬가지에요...
장미의 보상으로 나를 억지로 저택에 데려다 놓고는
부인으로 삼으려고 몇 번이나 몇 번이나 청혼을 하고...

야수 라 베트
그래도 나는 너를 사랑해!
너도 같은 마음이잖아!

야수 라 베트
[운명의 서]에도 그렇게 적혀 있다고!

라 벨
...!

라 벨
...돌아가.

야수 라 베트
벨?

라 벨
돌아가요! 당신은 나를 사랑하지 않아.
단지 [운명의 서]에 적혀 있으니까
그에 따라 행동하는 것 뿐이에요!

야수 라 베트
아, 아냐!
나는…!

라 벨
...이 사과, 먹고 싶으면 먹어도 좋아요.
이제 입맛도 없어져 버렸어.

라 벨
그럼 잘 가요.
이제 두 번 다시 당신과 만날 일은 없을 거에요.

야수 라 베트
기다려, 벨!
벨...벨...

야수 라 베트
사과 따위 다 뭐야...
이런 것...!!

***

레이나
어머나? 백설공주와 함께 있는 게 아니었어?
[왕자님].

엑스
더 이상 놀리지 말아줘...
백설공주라면 지금 왕비와 함께 있어.

엑스
...저기 말야, 여기에는 카오스텔러가 없는데
어째서 모두 미래의 운명에서
벗어난 행동을 하는 걸까?

레이나
좋던 나쁘던 [공백의 서] 주인은 그 존재 자체만으로도
상구에 강한 영향을 미치지. 그 주인이
외부에서 온 사람이라면 더욱.

레이나
상구의 주민이 [운명의 서]를 무시하고 행동하는 건
일반적으로는 절대 있을 수 없어. 그 불가능한 일이
너의 키스를 계기로 일어나고 있어.

레이나
빨리 이 상구를 벗어나지 않으면
앞으로 어떤 일이 일어날지 예측조차 되지 않아――

라 벨
아무도 없어요?
누가 좀 와주세요!!

엑스
당신은 혹시 벨?
왜 그러십니까?
어라, 베트와 함께 있는 게...

라 벨
당신들 베트와 아는 사이야!?
베트가...그 사람...
갑자기 야수처럼 난폭해졌어...!

레이나
뭐라고요!?
베트는 지금 어디에!?

라 벨
마을로 갔어...
내 말은 전혀 들리지 않는 것 같았어...
이대로라면 그 사람은 진짜 괴물이 되어버릴 거야...!

엑스
괜찮아요, 우리가 있으니까!
모두들, 가자!

라 벨
나도 함께 가겠어!
그 사람을 말려야 해...!

***
*전투*

== 이웃 나라의 성 밑 마을

야수 라 베트
...으, 으윽.
내가, 무슨 짓을...

라 벨
벳! 아아, 베트...
나를 알겠어요...?

야수 라 베트
벨...어떻게 된 거야...
이제 두 번 다시 만나지 않겠다 했잖아...
너는 분명 나를 경멸했었어...

라 벨
내가 경멸해서 그게 뭐가 어떻다는 거에요!
나를 정말로 사랑한다면
그런 걸로 나를 떠나지 말아요...!

야수 라 베트
…미안하군. 나는 단지 함께
있고 싶었을 뿐이야...장미를 돌보는
너의 모습을 계속 곁에서 지켜보고 싶었어...

라 벨
...미안해요. 사과해야 할 사람은 나에요.
언제나 주위 사람 말만 듣다가...
당신을 이렇게 상처 주고 말았네요...

라 벨
우선 몸을 치료하고...
그 뒤에 함께 돌아가요...
장미가 피어나는 당신의 멋진 저택으로.

야수 라 베트
어, 돌아가자...
나의 저택으로...

*

셰인
우선 야수는 벨의 사정을 듣고
의원에서 치료를 받기로 한 것 같아요.
다행히도 부상자는 없었어요...

타오
야수 아저씨가 난폭해진 것은 그 아가씨에게
받은 사과를 먹었기 때문이었어요...
그 사과는 공주님이 먹은 독사과와...
※플레로의 실수

레이나
아마 같은 거겠지. 게다가 벨은 그 사과를
모르는 노파에게 받았다고 했어.

엑스
그 말은 원래 독사과는 벨이 먹었어야
했던 걸까? 하지만 우리가 베트를 데리고
왔기 때문에 운명이 크게 바뀌고 말았어...

레이나
그런 상황이지. 이제 이 상구의 운명은 확실히
뒤틀린 것 같아.

레이나
...어쩌면 우리가 사라진다고 해서
해결될 상황이 아닐지도 몰라.

***

백설공주
베트 님도 벨 님도 무사해서 다행이에요...
빨리 베트 님이 쾌차하면 좋겠네요.

라 벨
고맙습니다, 백설공주 전하...
왕비 전하도 친히 문병을 와 주시다니...
정말 황송합니다....

독사과의 왕비
신경 쓰지 마세요, 라 벨 님.
라 베트 경에게는 공주가 신세를 많이 졌다 들었습니다.
어서 쾌차하시길 바랍니다...

독사과의 왕비
(...어째서 어째서 어째서 어째서 어째서 어째서어!!
어째서 라 벨이 아닌 저 야수가 사과를
먹은 거야!!)

독사과의 왕비
(아까부터 [운명의 서]에 쓰여있지 않은 일만 일어나고...
이대로 나는 야망을 이루지 못한 채
치욕스러운 결말을 맞이하게 되는 건가!?)

독사과의 왕비
(싫어...이대로 백설공주 앞에서
쇠구두를 신고 춤추게 되다니
그런 거 절대로 싫어!!)

독사과의 왕비
(...이렇게 된 이상 지금 당장 백설공주와
라 벨에게 독사과를 먹이고
내 운명을 맞추면 돼...!)

백설공주
――!?
새어머니! 저길 봐요!?

*

빌런
크르! 크르!
크르르르아아아아아!!

*

독사과의 왕비
뭐야...괴물이 저렇게 많이...!
대체 어디서 나타난 거지...!

엑스
백설공주! 벨! 왕비님!
다들 무사한가!?

백설공주
엑스 님!
무, 무슨 일이 일어나고 있는 거죠!?

레이나
슬픈 예감이 적중했어...!
스토리텔러는 우리뿐만 아니라 운명에서
벗어난 등장인물들까지 없애버릴 생각인 것 같아!

엑스
미안해, 백설공주. 내가 쓸데없는 짓을 해서
이런 일에 말려들게 해버렸어. 책임은 확실히 지겠어.
너희는 내가 반드시 지켜줄게!

백설공주
엑스 님...!
그럼 저도 싸우겠어요!
도움 받기만 하는 공주님이 아니라고요!

라 벨
그건 나도 마찬가지...
그 사람과 장미 저택에 돌아가기 위해서라도
이런 곳에 쓰러져 있을 수 없어!

독사과의 왕비
(...대체, 무슨 일이 벌어지고 있는 건지
전혀 알 수 없지만
다들 의욕이 넘치고 있는 듯하니 우선은 나도...!!)

독사과의 왕비
왕가의 사람으로서 괴물에게 지고 있을 수는
없습니다. 나도 돕겠어요!

셰인
드디어 하이라이트가 온 것 같군요.

타오
좋았어!!
덤벼라, 빌런 녀석들!
우리가 다 함께 너희를 날려 주마!

***
*전투*

백설공주
새어머니 궁술은 뛰어나십니다!
엄청 강하시네요!

독사과의 왕비
이 정도는 별 것 아니란다.
백설공주 네가 가진 빛에 비하면...

독사과의 왕비
(맞아, 마법 거울이 말했었어.
백설공주는 마침내 세상에서 가장 맑고 아름다운 여성이
된다고...그래서 평범한 내가 질투를 했어)

독사과의 왕비
(백설공주와 라 벨, 운명적으로 사랑 받던 그녀들의 빛을
더럽히고 나락으로 떨어뜨리고 싶었어. 그 때문에 어떤 벌을
받게 되는지 따위는 아무 상관 없었어...)

독사과의 왕비
(나는 운명적으로 사랑 받지 못한 어둠.
그것이 스토리텔러가 만들어낸
내 역할이며 살아가는 방식이니까...)

백설공주
그렇지 않아요!
새어머니는 매우 강하고, 아름답고 그리고,
엄청 상냥한 분이에요!

독사과의 왕비
엣…?

백설공주
새어머니는 저의 동경이에요.
저는, 피를 나누지 않은 저를 사랑해준
새어머니 같은 분이 되고 싶어요.

백설공주
그러니까 저는 새어머니가
아주, 아주 많~이 좋아요!

독사과의 왕비
...바보 같은 소리 하지 말고
지금은 싸움에 집중해.
아직 괴물의 습격은 끝나지 않았다구요.

백설공주
그렇군요! 미안합니다!
아, 저는 엑스 님을 살펴보고
올게요!

독사과의 왕비
...정말 바보 같구나.
너 같은 빛이 나 같은 어둠을
동경해서 어떡해.

독사과의 왕비
...좋아. 어차피 나는 쇠구두를 신고 춤추며
지옥으로 떨어질 운명.

독사과의 왕비
적어도 지금만큼은 사랑하는 딸과 함께
운명에 맞서 보겠어!

== 이웃 나라의 성

레이나
거리에 있는 녀석들은 대부분 처리한 것 같은데
설마 궁전까지 침입하다니...
정말 사리 분별을 못하는 구나!

셰인
어쩌면 우리가 모르는 곳에서
운명을 벗어난 행동을 하던 사람이 여기에
있을지도 모르겠어요.

타오
정말, 나도 고향에서는 꽤나 설쳤지만
이런 건 처음이야! 이곳의 스토리텔러는
어지간히도 다른 사람이 싫은가 보군!!

엑스
이대로라면 끝이 없어...!
망할, 대체 어떻게 하면...!

????
포기하지 마!

엑스
벳! 그리고 모두들!
벌써 움직여도 되는 거야!?

야수 라 베트
너희들에겐 걱정을 끼쳤구나.
이건 너희들뿐만 아니라 나에게도 지워진
운명의 시련이다. 함께 싸우자!

야수 라 베트
벨, 함께 가줄 거지?

라 벨
물론.
당신과 모두 함께 있다면
어떤 시련도 극복할 수 있어!

독사과의 왕비
[운명의 서]에는 적혀있지 않은
이런 흐름도 나쁘지 않네.
아직 괴물의 습격은 끝나지 않았다구요.

백설공주
엑스 님.
나도 함께 있어요.
마지막까지 싸울게요!

엑스
다들､고마워...
그럼 가보자!
이 시련을 다 함께 넘어 보는 거야!

***
*전투*

== 성 근처의 초원

엑스
백설공주, 베트, 벨, 그리고 왕비.
우리는 이제 가볼게.

레이나
미안합니다. 저희 때문에
이 상구에도 폐를 끼치고 말았네요...

야수 라 베트
신경 쓰지마. 무슨 일이 있었던 건지, 사실은
잘 이해할 수 없지만...우선은 수습해야 할 방향으로
수습된 것 같군.

라 벨
또, 언제든지 놀러 오세요.
장미 저택에서 베트와 기다리고 있을게요.

백설공주
엑스 님…

엑스
미안, 백설공주.
이번에야말로 이별이군.
마지막까지 책임지지 못해서 미안해.

백설공주
...저, 사실은 알고 있었어요.
엑스 님이 운명의 왕자님이
아니라는 걸.

백설공주
하지만 엑스 님이 그러니까, 엄청
멋진 분이었기 때문에, 그만
기분이 들떠서...정말로 죄송합니다!

엑스
백설공주. 분명 너에게는 나보다
멋진 왕자님이 나타날 거야. 너에게 주어진
운명을 믿고 기다리고 있어, 알겠지?

백설공주
네...알겠습니다...

독사과의 왕비
그래요. 백설공주. 너에게는 빛나는 미래가
기다리고 있어. 나도 너를 위해서 지원을
아끼지 않을 생각이야――

백설공주
그렇네요. 결혼하게 되면 새어머니가
쇠구두를 신고 춤을 춰야 하니까요.

독사과의 왕비
어?

백설공주
나쁜 일에 대한 벌은 필요하지요.
독사과를 준 사람, 새어머니였지요?
 [운명의 서]에 그렇게 적혀 있었어요?

독사과의 왕비
......백설공주.
너, 나를 좋아하는 것 아니었니?

백설공주
새어머니.
그건 그거고, 이건 이거에요.

셰인
신참 씨.
또 복잡한 일이 생기기 전에 빨리.

타오
그렇지. 또 스토리텔러의 기분을
건드리면 곤란해지니까 말이야.

엑스
...그럼.
여러분, 건강하세요.

백설공주
안녕, 엑스 님.
잘 가요, 나의 왕자님...
