= 7. 모모타로의 상구 - Flero
:hardbreaks:

....
옛날 옛날, 어떤 곳에
할아버지와 할머니가 살고 있었지.

매일 할아버지는 산으로 나무하러,
할머니는 강으로 빨래를 하러 갔어.


어느 날, 할머니가 강에서 빨래를 하고 있는데
위에서 아주 큰 복숭아가 둥둥 떠내려온 거야.

놀란 할머니가 복숭아를 집으로 가져가서
할아버지와 함께 복숭아를 가르자, 세상에!
안에서 건강한 남자아기가 태어났지 뭐야.


할아버지와 할머니는 복숭아에서 태어난 아이를
『모모타로』라고 이름 짓고 소중하게 키웠어.
그리고.......
....

== 키비노 초원 ※수수

엑스
어째 평화로워 보이는데
여기도 카오스텔러가 있을까?

레이나
상황을 좀 지켜보자.
때가 되면 뭔가 알 수 있을거야.

레이나
어머? 둘다 왜 그래?
말도 없이 둘러보기만 하고...

셰인
아, 아뇨...

타오
하하, 아무것도 아니야.
그냥 좀 고향 풍경이랑 닮은 것 같아서...

????
히이이익!
제발! 제발 살려주시오~~!!

엑스
방금 그 비명은!?

레이나
저 쪽에서 났어!

*

모모타로
누가!
누가 좀 살려주시오!!

셰인
타오 오빠...! 저 사람은...

타오
쳇! 역시 그랬군!

타오
모모타로!
싸우지 않을거면 거기 얌전히 있어!

엑스
모모타로?
타오가 어떻게 저 사람의 이름을 알고 있는 거야?

셰인
알고 있을 수 밖에요.
저 사람, 모모타로는 이 상구의 [주연]...
저희 고향의 [주연]이니까요.

엑스
고향? 여기가 타오와 셰인의 고향이야!?

셰인
얘기는 나중에 하죠.
우선 저 겁쟁이 [주연]부터 구해야 합니다!

***
*전투*

모모타로
무서웠소... 정말 무서웠다오...
역시 나같은 게 도깨비를 퇴치하는 건 말도 안 되오...
※오니

레이나
자,다시 한번 얘기를 정리해보자면
빌런들이 도깨비들과 손을 잡고 당신을
습격했다는 거지?

모모타로
그, 그렇소... 오니가시마의 생존자가
최근에 세력을 키우고 있소.
그 때문에 할아버지와 할머니도 다시 한번 싸우라고 하셨소만...

모모타로
개와 꿩과 원숭이는 계속 무공을 세워서 출세했고
지금은 소자의 험담을 하는 판국이오...
이제 소자 혼자서는 아무것도...

엑스
타오, 셰인. 정말 이 사람이
이 상구의 [주연]이야?

셰인
모모타로를 자처했으니 아마 그렇겠지.
솔직히 셰인이 봐도 이 겁먹은 모습은 너무
[주연] 같지가 않네요.

엑스
그건 그렇고, 여기가 타오와 셰인의 고향이라면
지인들한테 정보를 들을 수 있지 않을까?

셰인
안 되요. 상구와 바깥 세계는 시간의 흐름이 다르거든요.
이 곳을 떠난 지 한참 지났으니
이제 지인들도 이 세상 사람이 아닐 거예요...
※플레로의 실수

타오
상구를 떠난 자가 있을 곳은 없는 건가...
그런데도 여기는 아무것도 안 변했네.
카오스텔러까지 나타난 마당에...

타오
엉? 넌 뭐야? 왜 내 앞에...

모모타로
부탁드립니다! 타오 나리. 그리고 여러분!
당신들의 실력을 믿고 부탁드리건대
부디 저를 부하로 받아 주시옵소서!

모모타로
여기 수수경단도 드리겠사옵니다!
부디! 제발!

타오
왜 부하가 되는데 수수경단을 바치는 거야.
애초에 내 패밀리는
이런거에 넘어 갈 정도로 만만하지 않...

레이나
맞아! 우물우물...우리를...오물오물....
만만하게 생각하면...우걱우걱...곤란...꿀꺽...
큰일이야. 얘들아, 이 경단 완전 맛있어!

셰인
안 되겠어요, 타오 오빠.
아주 쉽게 넘어갔네요.
자존심이라는 것이 손톱만큼도 없어요. 이 사람.

엑스
부하가 되는 건 제쳐 두고 일단 우리랑 함께 가자.
카오스텔러는 [주연] 주변에 존재하니까.

타오
아아~ 원 참. 알았어...

***

모모타로
우하하! 타오 나리 일행과 함께라면
도깨비에게 쇠몽둥이를 준 것이나 마찬가지요!
무서울 게 아무것도 없사옵니다!

셰인
갑자기 세게 나오네요. 이 겁쟁이가.

엑스
[도깨비에게 쇠몽둥이]라니...
도깨비랑 싸우려는 사람이 이 비유를
써도 될까요...?

레이나
무서운 게 없는 건 좋은데
모모타로, 이제부터 어쩔 셈이야?
그 도깨비는 어디에 있는데?

모모타로
이 근처에서 잠복하고 있다고 들었소만
어디로 도망쳤는지는... 도깨비의 우두머리인
[오니히메]를 찾으면 큰 공을 세우게 될 것이오만...

모모타로
역대 최고로 칭송받는 선대 모모타로를 넘어서는 것,
그것이 바로 나의 염원이오! 그러기 위해서
어떻게든 오니히메를 잡아야 하오!

타오
어이, 모모.
쓸데없는 소리 하지 말고 빨리 따라와.
급하다며?

모모타로
예입! 지금 즉시 가겠사옵니다!

엑스
타오와 셰인은 오랜만에 고향으로 돌아왔는데
별로 기쁘지 않은가봐...?

레이나
좋은 추억이 없는 거 아닐까...
아마 저 두 사람도 이 곳에서는 주눅 든 모습으로
살았을 테니까...

엑스
그런데 두 사람은 무슨 역할이었을까?
나 같은 조연이었을까? 별로 상상이 안 되...
※플레로의 실수

엑스
어?

레이나
왜 그래?

엑스
지금 저기 뿔이 달린 여자아이가 있었던 것 같은데...

모모타로
정말이오? 엑스 나리!

모모타로
오니히메일지도 모르오!
어서 쫓아갑시다!

엑스
어엇?! 앗, 잠깐만!

셰인
...타오 오빠.

타오
...지금은 참아, 셰인.
무슨 일이 일어나고 있는지 이 두 눈으로 확인할 때까지.

== 도깨비가 숨어있는 초원

모모타로
발자국은 여기까지 이어져 있소...
가까운 곳에 있을 것이오!

엑스
하지만 그럴듯한 모습은 어디에도...
셰인, 뭔가 찾았어?

셰인
왜 셰인한테 물으시죠? 신참 씨.
몰라요. 알 리가 없잖아요?

엑스
...왜 화내는 거야?

셰인
화 안 났어요. 화난 것처럼 보여요?
신참 씨 눈은 폼으로 달고 다녀요?

타오
그쯤에서 그만 뒤, 셰인.
괜히 화풀이 하지 말고.

레이나
어쨌든 신중해야 돼. 도깨비가 있다는 건
아마 빌런도...

*

????
......!?

레이나
찾았다! 저 애 아니야!?

모모타로
틀림없소! 오니히메요!
어서 쫓아갑시다!

타오
기다려. 모모!
움직이지 마!

빌런
크르르...

모모타로
끼아아아아악!!
꼬마 도깨비! 꼬마 도깨비가 잔뜩 몰려오고 있소!!
타오 나리이~~!

타오
꺅꺅 거리지 마!
당장 해치워 주마...
각오해라. 빌런들아!!

***
*전투*

????
......하아, 하아.

모모타로
우하하. 막다른 골목이다!
오니히메, 단념해라!

오니히메
모모타로!
니아토스테사우유테...!
※이 얼마나 끈질긴 녀석…!

엑스
저 애가 뭐라고 한 거야...?

모모타로
저들이 쓰는 말은 도깨비 말이오.
우리가 쓰는 말은 통하지 않소.
이해할 필요도 없소만...

모모타로
자, 자, 얌전히 이쪽으로 오시게!
더이상은 도망 갈 수 없소!

레이나
잠깐, 모모타로...
너무 난폭하게 몰아세우는 건...

레이나
...어, 셰인?

셰인
사아누쯔히 오니히메.
셰인 치쯔누테우토쿠토.
이니친테키미오시소히즈니우.
※안녕하세요, 오니히메.
※셰인 일행을 따라와.
※당신을 잡히게 하지는 않아.

오니히메
이니치. 카누자기히니소레하...?
카노기우, 치세코토! 누아고아치쯔누
니키미기사와시로토우레하!
※당신, 오니어를 말할 수 있어…?
※부탁해, 도와줘! 인간들에게
※동료가 살해당하고 있어!

모모타로
셰인 나리!
도깨비 말을 아시옵니까?

타오
그야 당연하지.
셰인은 원래 도깨비니까.

모모타로
도깨비...셰인 나리가!?
대체 어찌 된 일이옵니까!

셰인
어떻게 된 건지는 제가 묻고 싶군요.

셰인
오니히메님은 반란을 꾀한 적이 없다는데요.
당신네 인간들이 일방적으로 동료를 잡아 들였다고요.

모모타로
허, 헛소리 하지 마시오!
도깨비는 사람이 베어야 할 적이오!
에이...이렇게 된 이상!

모모타로
타, 타오 나리...!
어...찌하여...

타오
미안하군. 모모. 잠깐만 자고 있어.
너를 부하로 써주는 것도 여기까지다.
우선 여길 빠져 나가자.

레이나
가다니 대체 어디로...?

타오
눈에 안 띄는 곳이지.
안정되면 전부 설명할게...

== 은둔자의 숲

레이나
그러니까 오니히메 님은 빌런에 대해서
아무것도 모른다는 거야?

셰인
네. 아무래도 빌런이 도깨비도 습격하고 있나 봐요.
오니히메님은 모모타로가 빌런을
조종한다고 생각했던 것 같아요.

타오
가능성이 없다고는 못 하겠지만...희박하지.
모모는 진심으로 빌런을 두려워하고 있었어.
도깨비가 조종하는 거라고 완전히 믿는 눈치였잖아.

엑스
오니히메는 앞으로 어떻게 하고 싶어?
역시 인간이... 원망스러워?

오니히메
오치스. 즈베아하에쯔호키오르치우도세...
모모타로 치쯔누에비오로치 오니가시마호
키오르치우도세...
※나, 자신의 집으로 돌아가고 싶어요…
※모모타로 일행에게 빼앗긴 오니가시마로
※돌아가고 싶습니다…

셰인
오니가시마로 돌아가고 싶대요.
모모타로들이 빼앗은 오니가시마로...
공주님의 소원은 그것뿐이에요.

엑스
그렇구나. 그럼 오니가시마로 가자.

레이나
엑스. 진심이야?
아직 모모타로랑 오니히메 중에 누구 말이 맞는지
모르잖아?

엑스
누가 옳은지는 모르지만
나는 오니히메님이 바라는 게 그거라면 도와주고 싶어.
그 마음은 잘못된 게 아니잖아.

타오
잘못된 게 아니다...라...

타오
오니가시마에 갈 거면 동쪽 해안으로 가자.
거기서 작은 배를 타고 나갈 수 있을 거야.

레이나
너 오니가시마에 가본 적 있어?

타오
...응. 예전에 잠깐.

셰인
아. 셰인이 길을 알아요.
언니들도 따라와 주세요. 이쪽이에요.

타오
나 참... 다 두고 왔다고 생각했는데...
나도 너무 감상에 빠졌네.

***

엑스
타오. 왜 그래?
곧 숲을 빠져나갈 거야.

타오
엑스... 미안.
아니 좀... 하여튼 고향에 오니 영 상태가 안 좋아.

엑스
타오와 셰인은 고향을 별로 그리워하지 않는 것 같아...
돌아오고 싶다는 생각은 안 해?

타오
없어.

타오
나도 셰인도 여기서 살면서 숨이 막힐 것 같았어.
이제와서 바깥 세계로 떠난 걸 후회할 리가 없지.

타오
너도 봤잖아? 모모타로와 도깨비의 싸움을.
이 상구에서는 말야, 그런 싸움을 끝없이
반복하고 있어.

타오
설령 카오스텔러를 [조율]한다고 해도
그런 싸움이 반복될 뿐이라고 생각하면...

엑스
타오...

타오
...미안. 쓸데없는 소리를 너무 많이 했군.
가자. 얼른 오니가시마에 가야지.

*

모모타로
차, 참말이옵니까!
타오 나리가 도깨비 녀석들과 내통하고 있다니...!
그런... 설마...

????
설마 우리 말을 의심하는 게냐?
우리보다 도깨비 녀석들과 내통한 배신자들을
믿는 게냐.

모모타로
그, 그런 일은 없사옵니다!
허, 허나... 제 힘으로는 도저히 그들을...

????
알고 있다. 그러니 네게 새 [부하]를 붙여주지.

모모타로
소자에게 새로운 [부하]를...?!
개이옵니까? 원숭이이옵니까? 아니면 꿩이옵니까?

????
훨씬 더 좋은 거다.
녀석들을 데려가서 배신자를 처벌하거라.
알겠느냐? 모모타로,

모모타로
네, 분부 받들겠나이다!

== 결투의 해안

모모타로
역시 오니가시마로 떠날 셈이었구려.
새로운 부하들과 함께 기다리고 있었소.
오니히메를 소자에게 넘기고 얌전히 잡혀 주시오!

엑스
모모타로!
말도 안 돼, 같이 있는 건...
메가 빌런!? 그것도 세 마리나!

타오
그 녀석이 지금 너의 개와 원숭이와 꿩인가.
아무래도 빌런이 모모타로 편인 건
틀림없는 것 같군.

레이나
메가 빌런을 세 마리나 상대하게 될 줄이야...
하지만 상관 없어. 우리 4명이 힘을 합치면
녀석들을 돌파하는 것 쯤이야!

셰인
잠깐만요. 좋은 생각이 있어요.
그쪽 진영과 셰인네 진영에서
한 명씩 일대일로 겨루는 건 어떨까요?

레이나
메가 빌런을 혼자서!?
셰인, 무슨 소리를 하는 거야!

셰인
죄송해요, 언니. 그래도 필요한 일이에요.
저 겁쟁이 무사를 정신 차리게 하기 위해서도
타오 오빠를 위해서도...

모모타로
소자는 그리해도 상관 없소!
오히려 바라는 바요!

셰인
타오 오빠. 말끔하게 떨쳐 버려야 되요.
안 그러면 오빠와 셰인은 앞으로 나아갈 수 없어요.
※플레로의 실수

타오
무슨 소리를 하는 거야, 너는.
이런 일에 아가씨들을 끌어들일 수는...

엑스
좋아, 그렇게 하자.
나는 하겠어.

레이나
일대 일 자체는 마음에 안 들지만
여기 오고나서 타오의 억눌린 얼굴 보는 것도
이제 질렸어. 하기로 한 이상 제대로 한방 먹일 거야.

타오
...흥, 알았어.
이 승부는 타오 패밀리가 모두 함께 받아주지!

*

셰인
우선 첫 번째 승부.
첫 타자는 신참 씨가 맡아 주세요.

엑스
아, 응. 첫 타자를 맡는 건 좋은데...

엑스
왜 평범한 빌런까지 있는 거야?
일대 일... 아니 그냥 솔로 배틀 아니었어!?
모모타로, 이 빌런은 무시해도 되는 거야!?

모모타로
[비일러언]이라는 게 그 꼬마 도깨비를 말하는 것이오?
그게 대체 어디 있다는 말이오?

레이나
...아무래도 카오스텔러의 힘으로 환각을 보고
있는 것 같아. 엑스. 이제 단념하고 싸워!
나중에 회복시켜줄게!

엑스
하여튼 레이나는 말도 안 되는 소리를 잘도 해!
아, 정말...뭐 어쩔 수 없지!

엑스
그럼 1번 타자 엑스!!
잘 부탁드립니다아아아아!!

***
*전투*

셰인
두 번째 승부.
다음 타자는 언니가 나가 주세요.

레이나
...저기 셰인.
지금 여기서 내가 다음 타자를 맡으면
누가 대장으로 나오는데?

셰인
?
당연히 타오 오빠죠.

레이나
뭐? 그건 싫어.
내가 대장 할래.

셰인
아니 언니. 진짜 분위기 파악 좀 해 주세요.
대장은 타오 오빠로 정해졌어요.
아까 언니도 수긍하셨잖아요.

레이나
그치마~안! 여기서 타오를 대장이라고 인정하면
내가 타오 패밀리를 인정한 것 같잖아!
싫어! 그것만은 싫어!

셰인
...신참 씨, 데려가 주세요.

엑스
...알았어.
레이나, 이제 포기하자~.

레이나
잠깐 엑스. 뭐하는 거야?
아니, 쫌! 이거 놔!

레이나
그만둬어어~~!
대장은 나라고~~~!!

모모타로
...적군인 소자가 말하는 것도 이상하지만
레이나 나리는 괜찮은 것이오?

타오
아가씨를 보지 마.
가끔 허당일 때도 있지만...
저래 보여도 우리의 믿음직한 공주님이거든.

*

레이나
아, 정말 어쩔 수 없네...
잘 들어. 타오한테 영광을 돌리는 건
이번만이야!

레이나
각오해라. 메가 빌런.
빌런들과 함께 네 혼돈을 여기서 끝내주마!

***
*전투*

셰인
세 번째 승부.
부대장 셰인 입니다.

오니히메
셰인
쿤테코토...
※셰인
※조심해…

셰인
걱정 마세요.
모모타로의 부하 따위한테 질 셰인이 아니니까요.

모모타로
셰인 나리. 꼭 확인하고 싶은 게 있소.
그대는 정녕 도깨비 출신이오?

셰인
그렇다고 할 수 있죠. 뿔은 안 달려 있지만요.
덕분에 오니가시마에 있었을 땐
전혀 도깨비 대우를 못 받았어요.

셰인
[모모타로] 씨. 한 가지만 말씀해 주세요.
당신은 대체 무엇을 위해서 싸우는 거죠?

모모타로
물론! 역대 [모모타로]에게 부끄럽지 않은
영웅이 되기 위함이오.

모모타로
도깨비 퇴치는 내게 주어진 사명이오!
그렇다면 그 사명을 다하는 것은 당연하지 않소!

셰인
알겠네요.
당신과 얘기해봤자 헛수고라는 걸.

레이나
셰인. 걱정 말고 들이받아버려!
그런 빌런 따위는 네 적수가 못 돼!

셰인
...고마워요. 언니.
신참 씨와 아가씨가 이어준 승부를
꼭 타오 오빠한테 넘겨 줄게요.

셰인
목표물은 정했어요.
자, 들이받아 볼까요?

***
*전투*

셰인
마지막 승부.
대장... 타오 오빠. 부탁드려요.

타오
...어떻게 된 거야? 모모타로. 부하가 전부 당했는데도
의욕이 넘치는군.

모모타로
소자 역시 [모모타로]의 이름을 이어받은 자...
여, 여기서 무너질 수는 없소!
타오 나리. 그대는 모를 것이오...

모모타로
[모모타로]로 살아가는 중압감이 어느 정도인지...
선대가 너무 위대했던 탓에 늘 비교 당하며 살아온
내 마음을...그대는 모를 것이오!

타오
옛~날 옛날 어떤 곳에
스토리텔러가 아무 역할도 안 준 꼬마가 있었다지.

타오
꼬마는 매일 주변 사람들의 괴롭힘을 당하면서 언젠가
출세할 날만 꿈꾸고 있었어. 훈련을 거듭하면서
자신이 [주연]이 될 날을 꿈꿨다나?

모모타로
...?
타오 나리, 대체 무슨 얘기를 하는 거요?

타오
어느 날 성장한 꼬마가 늘 그랬듯이 훈련을
하고 있는데 길 건너편에서 모모타로 일행이
걸어왔어.

타오
놀란 꼬마는 모모타로에게 뛰어가서 머리를
숙이고는 이렇게 말했지.
[모모타로! 나를 당신의 동료로 받아 줘!]

타오
모모타로는 꼬마를 마음에 들어해서 [타오]라는
이름을 새로 지어주고 자신의 동료로 맞아줬대.

모모타로
타오 나리, 어찌된 일이오...
그대는 선대 모모타로를 알고 있었소?

타오
이 뒷얘기가 궁금하면 나를 쓰러뜨려 봐.
우리는 너를 이기고 갈 거다.

모모타로
그렇게는 못 하오!
우...우...우아아아아아아아아아아아아악!

***
*전투*

모모타로
내가...졌소.
선대의 부하...아니 동료였던 사람을 상대로...

타오
...모모. 이거 하나는 알려주지.
내가 아는 [모모타로]는 결코 자신의 무공을
위해서 싸운 적이 없어.

타오
너도 사실을 알고 있잖아?
이 세계가 이상하다는 걸.
네가 데려온 부하의 정체도 알고 있을 테지...

모모타로
소자와 싸웠던 도깨비는 모두 도망치기만 할 뿐
전혀 공격해오지 않았소.
도깨비는 사람들에게 위협이 되는 존재일텐데...

모모타로
허나 소자의 아버지와 어머니가... 할아버지와 할머니가
도깨비는 나쁜 존재라고... 그래서 기대에 부응하려고
소자는... 소자는...

레이나
할아버지와 할머니는 오니가시마에 계신 거지?
너한테 아까 그 부하들을 붙여준 것도 그 두 사람이야?

모모타로
할아버지와 할머니는 변해 버렸소.
소자가 오니가시마의 보물상자를 가지고 돌아갔을 때부터
마치 다른 사람처럼 변해서...

모모타로
...부탁이오. 타오 나리. 소자는 이제 정말
무엇을 심판해야 하는지 모르겠소...
부디 소자 대신 이 세계를 구해주시오...

타오
카오스텔러를 [조율] 한다 해도
모모타로와 도깨비의 싸움은 멈추지 않아.
그래도 지금 상태보다는 낫겠지...

타오
나머지는 우리한테 맡겨.
반드시 이 곳을 원래 세계로 되돌려 놓을게...
되돌려 놓을 테니까...

엑스
몰랐어...
설마 타오가 모모타로의 동료였다니...

레이나
그런데 뒷얘기가 더 있을 것 같았는데...
셰인은 뭐 아는 거 없어?

셰인
...글쎄요. 셰인도 자세한 건 모르겠네요.

== 오니가시마

오니히메
윳나키옷토사로치...
오치스하사쿄에...
※드디어 돌아았어…
※나의 고향…

셰인
드디어 돌아온 내 고향... 이라는군요.
셰인이 있었을 때와는 상당히 달라진 것 같지만요...

레이나
셰인 덕분에 아무도 없는 해안에 도착했어.
할아버지와 할머니는 어디 계신 걸까?

셰인
모모타로 씨가 한 말을 듣고 생각해 보면
아마 도깨비 보물창고 근처에 있을 거예요.
정확히 섬의 중심에 있습니다.

엑스
타오. 안색이 안 좋은데 괜찮아?

타오
어. 미안. 괜찮아....

타오
얼른 끝내버리자고...
이런 기분 나쁜 악몽은...

***

셰인
여기가 보물창고예요.
어딘가에 할아버지와 할머니가 계실 텐데...

타오
...!?
위험해! 셰인!

셰인
말도 안 돼... 타오 오빠 괜찮아요!?

타오
걱정 마... 이 정도 쯤은 끄덕 없어...
그건 그렇고 방금 그거 마법이야?
마법을 쓰는 도깨비가 있다는 소리는 못 들어봤는데...

????
하하핫. 할아범.
실패 하셨구려.

???
히히힛. 할멈.
마법은 약하고 시시해.
역시 이 몽둥이로 한 방에 끝내버려야지...

엑스
저건... 도깨비!?
머리가 두 개야...!

타오
모모타로네 할아버지와 할머니군...
모모타로는 눈을 폼으로 달고 다니냐?
오니히메보다 훨씬 도깨비 같잖아...

쌍두의 도깨비 ※쌍두 오니
말이 심하구나 꼬마들.
...어라? 이것 봐라? 타오라고 했던가?
타오... 타오... 타오...

쌍두의 도깨비
옳거니! 생각 났다! 소문으로 들었지!
네가 선대 모모타로를 배신하고 죽이기까지 한
그 타오냐!!

타오
......윽!!

쌍두의 도깨비
모모타로의 동료였던 남자... 허나 도깨비와 싸우면서
혼란에 빠져 모모타로를 배신하고 모모타로로 둔갑한
남자로구나!

쌍두의 도깨비
끔찍한 소행이지... 피도 눈물도 없는 짐승이여.
그런 녀석이 우리를 도깨비라고 부르다니 참 가소롭군!

셰인
아니야! 타오 오빠가 죽인 게 아니에요!
아무것도... 아무것도 모르면서...

엑스
...알고 있어 셰인, 타오.

엑스
저 녀석들 절대로 용서 안 할 거야.
우리 동료를 모욕하다니...!

레이나
...그래. 엑스.
그런데 [우리를 도깨비라고 부르는] 게 아니라
도깨비 맞잖아? 아무리 봐도.

셰인
아가씨... 신참 씨...

타오
...그래 맞아. 그랬지.
해치워버리자. 셰인. 아가씨.
―그리고 엑스.

타오
타오 패밀리의 도깨비 퇴치를
잘 지켜보라고!!

***
*전투*

== 회상

타오
...왔나? 도깨비 아가씨.
나를 죽이러 온 건가...?
죽일 테면 죽여... 난 이제 지쳤어...

셰인
...잘도 셰인의 동료를 죽였군요.
모모타로 씨.

타오
아니... 모모타로는... 이 전투에서 죽었거든...
[공백의 서]를 가진 자와 연관되는 바람에
녀석의 운명이 틀어지고 말았어... 나 때문이야...

셰인
[공백의 서]...? 당신도 가지고 있나요...?

셰인
...셰인도 죽이기 싫어요.
더이상 도깨비로 살고 싶지 않아요.
이런 싸움은 이제 싫다고요...

타오
...그렇군. 너도 [공백의 서]의 소유자였구나.
너. 바깥 세계에 대한 얘기 들어본 적 있어?
우리 같은 존재가 갈 수 있는... 바깥 세계...

셰인
아. 들어본 적은 있어요...
하지만 바깥은 깊은 안개에 둘러싸여 있어서...
혼자 나갔다가는 길을 헤맬 거라고...

타오
그럼 같이 가자.
혼자 가면 헤매겠지만 둘이 손잡고 가면
적어도 흩어질 일은 없겠지...

셰인
그럼 그 허리에 찬 수수경단 하나를 셰인한테 주세요.
그러면 어디든지 함께 할게요.

타오
하하. 얼마든지.
그렇지, 부하는 내 취향이 아니니까...
의남매를 맺자. 내 이름은 타오. 네 오빠뻘이지. 어때?

셰인
좋아요. 잘 부탁합니다. 타오 오빠...

== 회상 끝

엑스
원래 모습으로 돌아온 [모모타로]의 상구에서는
타오가 말한 대로 모모타로와 도깨비의
격렬한 전투가 막을 열었다.

엑스
아무도 그 운명에 대해 의문을 갖지 않은 채.
모모타로와 오니히메는 오니가시마에서 계속 싸우고 있다.
그리고 우리는 그들의 운명에 간섭할 수 없다.

엑스
이게 최선이었을까...
우리가 할 수 있는 일이 없었을까...?

레이나
그 이상 생각해봤자 어쩔 수 없어. 우리는 여행자야.
카오스텔러 때문에 뒤틀린 부분을 돌려놓으면 떠나야 해.
타오가 거기까지 딱 잘라 생각할 수 있을지는 모르겠지만...

타오
내가 어쨌다고? 아가씨!
왜 울상이야? 둘 다!
자. 얼른 출발하자고! 대장은 나잖아!

레이나
뭐라고...!
이봐. 그건 어쩔 수 없이 양보했던 거거든!
리더는 나야!

엑스
다행이야. 타오 씩씩해보이네...
응? 셰인, 왜 그래?

셰인
...고맙습니다. 그 때 타오 오빠를 위해서 화를 내 줘서.
이러니저러니 해도 신참씨도 열정적인 데가 있네요.

엑스
...?
당연하잖아? 동료인데.
자, 가자. 저사람들 우리를 두고 가겠어.

셰인
혼자일 땐 헤매도 둘이면 서로를 놓치지 않죠.
...넷이면 어디든지 갈 수 있겠죠.

셰인
앞으로도 따라 갈게요. 타오 오빠. 아가씨.
그리고 엑스......아니, 역시
[신참 씨]가 좋겠어요.
