= 8.4. 메이드 캣 리포트!! - Flero
:hardbreaks:

== 소크라홀테의 저택

나레이션
옛날 옛적, 숲 속에 있는 마법사 소크라홀테의 저택에
4명의 메이드 캣이 살고 있었습니다.

나레이션
소크라홀테는 마법 수행을 하느라 늘 외출중이었죠.
그래서 메이드들은 언제든 주인님이 돌아오실 수 있도록
집안 일과 식사 준비로 늘 바빴습니다.

나레이션
그런 그녀들의 [운명의 서]에는 이렇게 쓰여져 있습니다.
언젠가 저택에 그녀들의 [진정한 주인님]이 맞이하러
올 거라고.

나레이션
오늘도 4명의 메이드 캣은 언젠가 찾아올
[진정한 주인님]을 기다리며 부지런히 일을 했습니다.

화이티
하아~ 창문으로 들어오는 햇빛이 기분 좋아...
청소도 끝났고 빨래도 다 했으니까,
오늘은 메이드 일도 끝났...

캐롤
아, 안 돼, 화이티!
아직 청소도 안 끝났고 빨래는 지금부터
시작이란 말이야!

블루
나 참, 항상 시끄러운 녀석들이야.
저 녀석들은 신경쓰지 말고 얼른 일을 끝내야...

뭔가가 깨지는 소리
와장창!!

캐롤
히익!? 뭐, 뭐야. 방금 그 소리는...!?

블루
복도 안쪽이네... 미아가 또 무슨 짓을 저질렀군...
상황을 보고 와야겠어.
화이티도 당장 일어나.

화이티
흐에?

*

빌런
크르르... 크르르...!

캐롤
으... 으와아아, 저, 저게 뭐야!?
유령 같은 게 잔뜩...!
미아! 또 네가 한 짓이야!?

미아
아, 다들! 있잖아, 들어봐!
내가 방금, 복도에서 혼자, 걸레질 경주를
하다가, 최고 기록을 경신했거든!

미아
그런데 속도를 너무 내다가, 항아리를 깨버렸지 뭐야.
그런데, 항아리 안에서, 저 유령이 푸화학~ 하고,
나오기 시작했어!

캐롤
그, 그그그그거 혹시 소크라홀테 님이
연구를 위해서 괴물을 가둬놨다는... 봉인의 항아리야!?
어떡하지! 어떡해! 큰일났네!

화이티
정말 큰일이네.
이렇게 더러워졌으니 청소를 다시 해야 되겠는데.

블루
그 전에 이 괴물들을 청소해야지.
일손이 좀 더 많았으면 좋겠어...

???? ※엑스
너희들 괜찮니!?

캐롤
히익!!?
이, 이번엔 또 뭐야!?

레이나
이 저택 주인한테 부탁 받아서 왔어!
너희를 구하러 온 거야!

레이나
지금은 설명할 시간이 없어!
이 녀석들을 퇴치하는 걸 도와주겠니?

블루
...알았어.
빨리 끝내 버리자.

미아
다같이 노는 거야!?
신난다! 그럼, 나도 힘 좀 써야지!

***
*전투*

나레이션
저택에 나타난 괴물 소동은 여행자들의
협력으로 일단락 되었습니다.

나레이션
하지만 아직도 모든 괴물을 다 쓰러뜨린 건 아닙니다.
저택이 안전해질 때까지 여행자들은
저택에 머물기로 했습니다.

나레이션
하지만 4명의 메이드는 갑자기 나타난 여행자들이
저택에 머물게 되자 안절부절하기 시작했습니다.

나레이션
저 여행자들이야말로 그들을 마중 온
[진정한 주인님]이 아닐까? 곧바로 메이드들은
여행자들 모르게 작전회의를 시작했습니다.

캐롤
정말 저 사람들이 우리를 마중 나온
[진정한 주인님]일까...?
소크라홀테 님의 지인이라고 했는데.

화이티
음, 글쎄. 유령들이 또 어디서 나타날 지 모르니까
당분간 머물러 주는 건 고맙지만.

미아
그래도 그래도, 북적거리니까 즐겁잖아!
다같이 뭐 하고 놀까?
블루는 하고 싶은 놀이 있어?

블루
일단 저 사람들부터 살펴 봐야지.
정말로 주인님의 친구인지.
우선 그것부터 확인하지 않으면 다 소용 없잖아.

미아
오오! 말하자면 스파이 놀이구나!
나 그런 거 잘 해!

캐롤
그, 그래. [진정한 주인님]인지 아닌지는 모르겠지만
우리도 선택할 권리가 있는 걸.
저 사람들을 제대로 지켜봐야지...

셰인
고양이 여러분, 이런 데서 뭐하고 계세요?

캐롤
으아아악!?
아, 아무것도 아니에요...
몰래 소근소근 말한 적 없어요, 없다고요...!

미아
사실은요! 우리 지금부터 다같이
여행자 여러분을 상대로 스파이...

블루
손님. 오늘은 위험한 상황에서 구해주셔서 감사합니다.
피로회복을 위해서 [새콤한] 음식은 어떠신가요?

셰인
오~ 달콤한 음식이 아니라 새콤한 음식인가요?
좋네요. 이왕이면 셰인은 흰쌀과 매실 장아찌를
부탁할게요. 그 조합은 정말 최고거든요.

블루
흰쌀과 매실 장아찌...?
잘 모르겠지만 알겠습니다.
자, 우선 방부터 안내하지요.

캐롤
저 사람들을 정말 제대로 파헤칠 수 있을까?
미아. 우리가 하려는 일을 여행자들한테
절대로 말하면 안 돼. 알겠어?

미아
라~져!
맡겨 줘~!

캐롤
정말 괜찮을까...
어? 그러고 보니 화이티가 아까부터 계속 조용한데
대체 뭘 하고 있...

화이티
Zzz...

캐롤
그러니까 자면 안 된다고!!

***

캐롤
저기... 정말로 미아 혼자 보내길 잘 한 걸까?
역시 다같이 가는 게 좋지 않았을까...

캐롤
생각해 봐. 저번에도 미아 혼자 저택을 빠져 나가서
안 돌아온 적이 있잖아...

화이티
문제 없어. 미아는 아주 착한 아이니까.
분명히 잘 해줄 거야.
블루도 그렇게 생각하지?

블루
글쎄.
그 녀석들에 대해서 뭔가 알 수 있다면 상관 없어.
그건 내버려 두고 이제 치우자.

캐럴
블루 혹시 화났어?
항상 우리를 노려보잖아.

화이티
아니. 아마 미아를 걱정하느라 그런 걸 거야.
사실 블루는 정말 상냥하거든. 그러니까 괜찮아.

== 저택 주변의 숲

미아
저기 저기!
여행자 여러분은 뭐하고 놀아요?
제가 이 숲에서 놀만한 곳은 잘 알거든요!

엑스
저기... 미안. 미아.
우리는 노는 게 아니라 그 유령들이
이 주변에 있는지 조사하고 있는 것 뿐이라...

미아
우우~, 재미없어.
그럼 그럼... 여행 얘기는 어때요?
재미있는 얘기 많이 들려줘요!

레이나
후후, 귀여운 아이구나. 일부러 숲을 안내해
주겠다니 친절하기도 하지.

타오
그래?
왠지 고양이는 제멋대로 구는 이미지라 거북하단 말이야.
고를 수 있다면 개가 더 좋은데.

셰인
셰인은 무조건 고양이 파예요.
특히 얼룩무늬 고양이를 정말 좋아해요.
개는 개인적으로 여러가지 사연도 있구요.

셰인
그보다 언니. 주변 상태는 어때요?
뭔가 팟 하고 느껴지는게 있나요?

레이나
모르겠어. 하지만 그 마법사가 한 말이
진짜라면 이 저택에 분명히...

미아
저기 저기. 뭐가요? 무슨 얘기 해요?
나도 같이 할래 공겨~억!!

레이나
으헉!?

레이나
으윽, 기다려. 바보 고양이!!

미아
우와 우와~ 술래잡기다!

엑스
...조사할 상황이 아니네.

타오
일단 계속 가자.
마법사 아저씨한테도 부탁 받았으니까...

== 소크라홀테의 저택

나레이션
숲의 조사를 마친 엑스들은 저택으로 돌아왔습니다.

나레이션
메이드들은 다시 작전회의를 열었고 여행자들과
동행한 미아로부터 일행에 대한 보고를 들었습니다.

미아
엑스는 엄청 상냥했어.
내가 하는 말을 잘 들어줬거든.
하지만 놀이 상대로는 좀 별로였어.

미아
셰인은 정말 재미있어!
그런데 나랑 좋아하는 게 다른 느낌이랄까?

미아
타오 오빠는
음... 뭐랄까. 무진장 땀 냄새가 나!

미아
그리고 레이나 언니는 장난감으로서 최고야!
이상 미아의 보고야!

캐롤
...미아. 이건 놀이 상대에 대한 평가잖아.
그 여행자들이 정말 [진정한 주인님] 인지 모르겠어...

화이티
하지만 좋은 사람들인 건 틀림없어 보여.
좋아, 이번에는 내가 가볼까!

블루
괜찮겠어?

화이티
하여튼, 내가 잠만 잔다고 생각하면 큰 착각이야!
이래 보여도 이 중에서는 맏언니니까!
나한테 맡겨!

미아
오오! 화이티 힘내!

캐롤
...왠지 좀 불안한데.

블루
하여튼, 무리는 하지 마.

== 저택 주변의 초원

화이티
그리하여 이번에는 저 화이티가
여러분의 안내를 하겠습니다.
잘 부탁드려요.

레이나
어떻게 된 건지는 잘 모르겠지만 일단 잘 부탁해.
이렇게 여러 모로 신경 써줘서 고마워.

화이티
아니에요~. 소크라홀테 님의 소중한 친구분이시니
이 정도는 당연하죠.

화이티
이 주변에 있는 초원은 햇살이 따뜻하거든요.
산책하는 데는 최고죠.
뭐든 필요하신 게 있으면 사양 말고 말씀해 주세요.

타오
그래그래, 좋아.
고양이 파는 아니지만 이런 건 참 좋군. 으음.

셰인
타오 오빠. 개나 고양이가 아니라
그냥 귀여운 메이드가 좋은 거잖아요?
너무 쉬운 남자라 좀 별로네요.

엑스
워워. 모처럼 재워 주시는데
화이티 씨 일행과는 사이좋게 지내자.

엑스
빌런이 걱정되긴 하지만...
화이티. 이 주변에 수상한 소문이 난 장소는 없어?

화이티
쌔근...zzz

엑스
어!? 방금 전까지 평범하게 깨어 있었는데!?
화이티, 괜찮아?
이런 곳에서 자면 감기 걸...

화이티
캬햐야야야양!!
자고 있을 때 건드리지 말라냐아아아아아아!!

엑스
아... 아야... 아파! 아파다구!
손톱으로 할퀴지 말아 줘!

셰인
타오 오빠, 저래도 좋아요?

타오
미안.
저건 역시 안 되겠어.

레이나
어휴. 아무튼 계속 가 보자.
정말 이상한 메이드 투성이네. 이 저택은.

== 소크라홀테의 저택

나레이션
초원 조사를 마친 엑스들은
저택으로 돌아왔습니다.

나레이션
메이드들은 다시 작전회의를 열었고
여행자들과 동행한 화이티로부터
이하 생략...

화이티
엑스 씨는 내 낮잠을 방해했으니까 나쁜 사람이야.
다른 사람들은 좋은 사람.
[진정한 주인님]이 누구인지는 모르겠어. 이상.

캐롤
역시 화이티도 문제가 있었어...

미아
어쩔 수 없지. 화이티는 우리 말고
다른 사람이 자는 데 깨우면 어어어어엄청
기분 나빠하잖아.

화이티
미안... 솔직히 반성하고 있어.

미아
그래서 다음엔 누가 갈 거야?
블루가 가 볼래?

블루
아니. 나는 좀...
캐롤이 가는 게 어때?

캐롤
어... 그, 그걸 나 혼자 하는 거야?
안 돼, 안 돼. 못해... 못 한다고!

미아
캐롤.
가끔은 응석 부리지 말고 네 힘으로 해내야지.

캐롤
미... 미아가 타일렀어!?
우... 우우... 아, 알았어.
내가 어떻게든 해 볼게...

화이티
저기... 캐롤.
못 하겠으면 못 하겠다고 말해도 돼.

캐롤
하, 할 수 있어. 지금까지 공부한
마법 중에서도 가장 대단한 걸 써서 그 사람들이
[진정한 주인님]인지 아닌지 맞힐 거야!

== 저택 주변의 동굴

캐롤
응. 이 근처에 있으면 그 사람들도 눈치 못 채겠지?
지금은 저택에서 자고 있는 것 같던데.

캐롤
[진정한 주인님]이 마중 오는 걸 계속 기다렸는 걸.
선생님이 가르쳐 주신 대로 마법으로
점치면 잘 될 거야... 하나 둘... 이얍!!

캐롤
...어? 아무 일도 안 일어나잖아?
실패했나? 이상하네.
할 수 없지. 다시 한번 해 보고...

빌런
크르르... 크르르...!

캐롤
꺄아아아아아아아아아아!
어째서!? 왜 유령들이 오는 거야!!

캐롤
싫어. 오지마!
바보 바보 바보 바보!!
우에에엥~ 누가 좀 살려줘요!!

엑스
캐롤, 괜찮아!?
다친 곳은 없어!?

캐롤
어... 엑스 씨 일행이잖아!?
왜 이런 곳에...

레이나
아아... 좀 사정이 있어서
이 주변을 조사하고 있었거든...

레이나
그것보다... 큰일이네.
빌런의 움직임이 점점 활발해지고 있어.

셰인
검은 고양이가 불러들인 것 아닐까요?
왜 검은 고양이를 불길한 징조라고 하잖아요.

캐롤
아, 아니야! 나는 안 불길해!
그런 말... 하지마아~~

타오
아, 울지 마. 울지 마.
이대로 동굴을 빠져 나갈 거야. 할 수 있겠어?

캐롤
응...

== 소크라홀테의 저택

캐롤
우우... 무서웠어...
엄청 둘러싸여서 이제 끝난 줄 알았어.

미아
잘 참았구나. 캐롤.
자, 이제 괜찮아. 안 무서워.

캐롤
고마워... 하아, 쓰다듬어 주니까 기분 좋다...
미안해. 결국 나도 못 알아냈어.
나쁜 사람들은 아닌 것 같은데...

화이티
음. 어째 [진정한 주인님]을 따질 상황이 아닌 것 같네.
유령들이 점점 많아지는 것 같아.

화이티
하다못해 소크라홀테 님께서 돌아오신다면 소동도
가라앉을 텐데.
언제쯤이나 저택으로 돌아와 주실까?

블루
너희는 저택에 남아 있어.
내가 직접 확인하고 올게.

캐롤
확인하다니... 어, 블루가 가는 거야?

화이티
오오!
역시 블루도 해볼 마음이 든 거야?

블루
그런 거 아니야. 내가 걱정하는 건...!
아니, 아무것도 아니다.
잘 들어. 너희는 절대로 쓸데없는 짓 하지 마.

캐롤
왠지 방금 블루 엄청 무서웠어...

화이티
괜찮을 거야. 분명히...

미아
블루...

== 저택 주변의 숲

블루
―고양이는 절대로 떼지어 다니지 않는다.
오는 사람 안 막고 가는 사람 안 잡는다.
우정이나 동료 같은 말은 고양이에게 어울리지 않는다.

블루
그러니까 나는 저 녀석들과 친하게 지내지 않을 거야.
우연히 같은 저택에서 일하게 되었을 뿐인
시끄러운 녀석들. 그게 내가 생각하는 녀석들이다.

블루
[진정한 주인님]이 어떤 녀석인지도 관심 없어.
그게 내 운명이라면 거부할 생각이 없으니까.
정해진 날까지 고용된 메이드로서 맡은 일을 다할 뿐.

블루
그러니까 이건 그 녀석들을 위해서 하는 게 아니야.
맡은 일을 다하는 고양이로서 이 저택을 지키려는 것.
그것 뿐이야―

*

셰인
저기, 여러분도 슬슬 눈치 채셨겠지만
아무래도 고양이 메이드들이 세인들을 몰래
염탐하고 다니는 것 같네요.

레이나
우리의 목적이 들킨걸까?
골치 아프네. 아직 아무 단서도 못 잡았는데.

엑스
이렇게 된 이상 저 애들한테도 사정을 설명하자.
그러면 협력해 줄 지도 모르잖아.

타오
그만둬. 잘못 하다가는 더 귀찮은 사태가
벌어질 수도 있다고. 마법사 아저씨 일을 알게 되면
고양이 아가씨들도 당황해서...

블루
흐음. 그게 무슨 뜻이지?

레이나
블루...!
어디서부터 들었어?

블루
어디서부터 들었던 상관 없잖아.

블루
이상하다고 생각했어... 괴물이 나타난 것과 동시에
네 녀석들이 왔지.
[진정한 주인님]은 커녕 [진정한 원흉]이었군.

블루
각오해라.
저택을 위협하는 자는 이 창으로 찔러 죽이겠다!

레이나
아니야! 부탁이야. 얘기를 들어줘!
우리는 소크라홀테가 이 저택을...
너희를 지켜 달라고 부탁해서 온 거야!

레이나
진짜 적은 너희들 가운데...

빌런
크르르... 크르르...!

블루
뭐... 이 녀석들...!
방금 전까지 기척도 없었는데!

타오
쳇. 아무래도 저 쪽에서 눈치를 챈 것 같군!

엑스
블루, 얘기는 나중에 하자!
지금은 함께 여기서 벗어나야 돼!

블루
네 녀석들, 나중에 전부 실토해야 할 거야!

***
*전투*

레이나
우리는 카오스텔러... 그러니까
이 세계를 위협하는 적을 쫓아 왔어.

블루
카오스텔러...
이 세계를 위협하는... 적?

엑스
응. 여행을 하던 도중에 소크라홀테를 만나서
함께 카오스텔러의 행방을 찾고 있었는데.

엑스
그 카오스텔러가 아마 이 저택에 있을
거라는 것까지 알아냈어...

블루
기다려 봐. 우리 중에 적이 있다고?
바보 같은 소리를 하는군.
우리는 평범한 메이드일 뿐이야.

셰인
안타깝지만 사실이에요.
지금 저택 주변에서 나타나는 빌런도
그 카오스텔러가 만들어낸 거죠.

타오
당신들 주인도 카오스텔러한테 당했지.
범인은 댁의 동료들 중에 있어.

블루
소크라홀테 님이 우리 중 누군가에게 당했다니...
그런 말도 안 되는 일이 있을 리가 없어.
왜냐하면 우리는 계속 저택에...

== 회상

캐롤
봐봐. 요전에도 미아, 혼자서 방을 빠져나가서
돌아오지 않은 적도 있고...

== 저택 주변의 숲

블루
미아... 거짓말이지...?

== 소크라홀테의 저택

캐롤
블루가 안 돌아오네.
무슨 일이 생긴 걸까...?

화이티
그러게... 서두르지 않으면 저녁 식사가 식어버릴 텐데.

미아
저기, 캐롤, 화이티.
너희 둘은 [진정한 주인님]이 나타났으면 좋겠어?

캐롤
어? 그, 그야 그렇지...
[진정한 주인님]이 많이 쓰다듬어 주면 좋겠어.

화이티
나도 그래.
[진정한 주인님]과 함께 많이 많이 낮잠 자고 싶어!

미아
그렇구나.
그러면 내가 너희의 [진정한 주인님]이 되어 줄게.

화이티
미아?

미아
내가 너희가 하고 싶어 하는 걸 많이 해 줄게.
그러니까 계속 이 저택에서 다같이 놀자.

캐롤
미아. 무슨 소릴 하는 거야...

미아
좀 더 다양한 놀이를 하자.
친구는 얼마든지 있으니까 전혀 안 지루할 거야.

미아
다음에는 다같이 뭐 하고 놀까?

***

빌런
크르르르... 크르르르으...

*

블루
쳇. 저택에 괴물들이...!
얘들아! 캐롤! 화이티! 미아!

엑스
잠깐! 혼자 튀어나가면 안 돼!
이미 이 곳은 카오스텔러가 지배하는 영역이 되어
버렸어, 위험한 장소라고!!

블루
하지만 서두르지 않으면 저 녀석들이...
그리고 얼른 미아를 정신 차리게 해줘야 돼!

레이나
진정해. 괜찮아. 미아도 다른 아이들도
꼭 원래 모습으로 돌아올 수 있어.
그러니까 서두르지 말고 확실한 방법을 찾아야 해.

레이나
아마 미아는 아직 카오스텔러로써 완전히
힘을 각성한 게 아닐 거야.
이 틈에 쓰러뜨려서 [조율]을 하고 싶은데...

화이티
블루!

블루
화이티! 캐롤!
다행이다. 무사했구나...

캐롤
우리는 간신히 도망쳐왔어...
미아가 갑자기 저 유령들을 불러들여서...

캐롤
왜 미아가 이런 짓을...?
미아는 우리가 싫어진 거야?

엑스
그런 게 아니야.
지금 미아는 나쁜 녀석한테 홀려 있는 것 뿐이야.
그 녀석을 몰아내고 [조율]을 하면 미아도 예전처럼...

미아
아~ 다들 이런 곳에 있었구나~

*

블루
미아. 전부 네 짓이었나...
소크라홀테 님도 네가!

미아
후후, 그게~ 나도, 어쩔 수가 없었어.
소크라홀테 님은 말야, [진정한 주인님]을
저택으로 데려오는 역할이었단 말이야.

미아
그런 짓을 하면~ 우리가, 뿔뿔이 흩어지잖아?
그래서 말야 소크라홀테 님을 유령들 친구로 만들어줬지!

캐롤
미아... 부탁이야.
무서운 말은 그만하고... 예전의 미아로 돌아와 줘...

셰인
유감이지만 저렇게 되면 설득은 안 통해요.
카오스텔러를 쓰러뜨리고 [조율] 하지 않으면
예전의 모습으로 돌아올 수 없어요.

타오
너희는 위험하니까 물러나 있어.
여기는 우리가 어떻게든 해볼 테니까.

화이티
나도... 싸울 거야!
씩씩한 미아가 없으면 안심하고 잘 수가 없는 걸!

블루
그래.
미아, 너한테 충분한 벌을 주겠어.

캐롤
나, 나도!
너무 무섭지만... 미아가 이대로 안 돌아오는 게
더 싫어!

미아
다같이 놀아주는 거지?
후후후, 좋아~ 많이, 많이 놀자!

***
*전투*

미아
어째서... 다들 어째서...
[진정한 주인님] 같은 건 없어도 돼...
다같이 여기서 메이드 일을 하면 되잖아...

미아
뿔뿔이 흩어지는 건... 싫어...

화이티
정말 바보 바보 바보야!! 그것 때문에 고민한 거야?
그럼 곧바로 언니한테 상담 했어야지!
이렇게 될 때까지 끌어안고 있지 말고!

캐롤
미안해, 미아... 알아차리지 못 해서...
우리는 항상 함께였는데...

블루
모르는 게 당연하지.
고양이는 떼지어 다니지 않으니까.
자기 말고는 관심 없는 게 고양이잖아.

캐롤
블루. 지금 그런 얘기는 안 해도 되잖아...!

블루
하지만 우리는 메이드 캣이지. 메이드 캣은
어떤 고양이보다도 단단한 인연으로 이어져 있어.
그러니까 어디를 가든 뿔뿔이 흩어질 일은 없어.

미아
블루... 다들 고마워...
하지만 내가 모두에게 너무 심한 짓을...

엑스
괜찮아. 이건 다 나쁜 꿈이거든.
눈을 뜨면 모든 게 원래대로 돌아가 있을 거야.
그 때 씩씩한 네 모습으로 돌아가면 돼.

미아
그럼 다들...
내가 씩씩해지면... 또 놀아줄 거야?

레이나
물론이고말고, 태클 말고 다른 놀이라면 좋아.
그러니까 안심하고 지금은 잠들렴.
그럼 간다...

*조율 컷씬*

*

????
미아.
이봐, 일어나. 미아!

== 소크라홀테의 저택

미아
어... 다들.
뭐 하는 거야?

캐롤
뭐하냐니...
곧 소크라홀테 님이 돌아올 시간인데
미아가 이런 곳에서 자고 있잖아.

화이티
마음은 이해가 돼.
날씨가 이렇게 좋은 걸. 나도 좀 졸려...

블루
너까지 잠들면 어떡해.
이제 얼른 준비하자.

캐롤
...?
왠지 블루가 상냥해진 것 같지?

화이티
그러게.
후후. 드디어 우리한테도 마음을 열어준 건가?

블루
뭐...!
바보! 그, 그런 거 아니거든!

미아
후... 후후... 후후후!

블루
왜 그래. 미아.
갑자기 웃어 대니까 기분 나빠.

미아
아니!
다같이 있으니까 즐거워서!

????
얘들아, 다녀왔어.
잘 지냈니?

미아
이 목소리는... 주인님!

화이티
어머 큰일났네!
자, 다들 서둘러!

블루
나 참, 어쩔 수 없군.

캐롤
아... 잠깐만~!

나레이션
옛날 옛적, 숲 속에 있는 마법사 소크라홀테의 저택에
4명의 메이드 캣이 살고 있었습니다.

나레이션
그들은 성격도 좋아하는 것도 제각각이었죠.
하지만 서로를 배려하며 도왔고
몹시 단단하고 끈끈한 인연으로 이어져 있었어요.

나레이션
언젠가 저택으로 그들을 마중 나온다는 [진정한 주인님].
그게 어떤 사람인지 그들은 아직 모릅니다.

나레이션
그래도 그들은 자신의 운명을 두려워하지 않아요.
희망을 가지고 오늘도 웃는 얼굴로 즐겁게
열심히 메이드 일을 합니다.

미아
그럼~ 하나 둘...

메이드 캣 전원
다녀오셨어요, 주인님!!
