= 10. 거울 나라의 상구 - Flero
:hardbreaks:

....
어떤 곳에 앨리스라는 소녀가 살았습니다.
공상을 좋아하는 앨리스는 가이 포크스의 날 전날,
난로 앞에서 새끼 고양이에게 말을 건넵니다.

「키티, 이제 장난은 그만.
착하게 굴지 않으면
거울 저편의 집으로 보내버릴 거야!」

앨리스는 새끼 고양이를 혼내면서 거울 세계에 대한
공상을 펼쳤는데, 바로 그때 난로 앞에서
거울의 어떤 변화를 느꼈습니다.

안개 같은 것으로 변해가는 거울.
무서워하며 거울에 다가간 앨리스는 다음 순간
거울 안을 빠져나갔습니다.


그리하여 앨리스는 붉은 여왕과 하얀 여왕이
모든 세상에서 체스 게임을 펼치는
기묘한 『거울 나라』에서 헤매게 되었습니다.
....

== 하얀 초원

엑스
으... 응... 헉?
다들 어디...

셰인
넵, 셰인... 여기 있습니다...

타오
나도 있어...
어라? 아가씨는...

레이나
여기 있어... 다행히 모두 다 모인 듯 하네...

레이나
잠깐만. 앨리스는 어디에 있는 거야?

????
크흣... 흐흐흐...
그러고 보니 [공주님]은 앨리스 이야기를
무척이나 좋아하셨지요.

로키
잘 지내셨나요!
[조율의 무녀] 일행 여러분!
[거울 나라]에 어서 오십시오!

엑스
로키!? 왜 네가 여기에...!
앨리스는 어디에 있어!

로키
그렇게 소리치지 마세요. 앨리스가 어떻게 되든
상관 없잖아요? 스토리 텔러에게 중요한 건
[역할]일 뿐 [배우]가 아니거든요.

로키
아무리 [주연] 이라고 해도
앨리스를 대신할 만한 사람은 얼마든지 있으니까요.
전에 알라딘의 상구에서 여러분도 다 지켜보셨잖아요?

== 회상

알라딘
이제 됐어요. 충분해요... 이게 내가 선택한 운명...

== 하얀 초원

엑스
너... 너 이자식!!!!

레이나
잠깐, 엑스! 뭔가 있어!!

*

엑스
저 녀석은... 모자장수로 변신한 괴물...!

타오
도망쳐, 엑스!
잘 모르겠지만... 저 녀석은 위험해!!

로키
크흐흐... 자, 게임이 시작되었습니다.
여러분과 우리[들] 중 과연 승자는 누구일지.
크흣 크흣 크흐흐...

***

엑스
왜 로키가 여기에...
저 괴물도... 어쩌면 모두 로키가 꾸민 일인 거야...?

레이나
일단 상황을 정리해 보자.
우리가 모르는 일이 너무 많아.

레이나
우선 확실한 건 여기가 아까 있었던
[이상한 나라]와는 다른 상구라는 사실이야.

셰인
아~ 그러고 보니 로키가 말했죠.
[『거울 나라』에 어서 오십시오!] 라고.

타오
그렇다면 우리도 모르는 사이에
다른 상구로 옮겨진 건가...

타오
그러면 모자장수로 둔갑한 저 괴물도
상구를 이동할 수 있는 [공백의 서]의 소유자...?

레이나
아니, 그 괴물로부터 카오스 텔러의 기운이 느껴졌어.
틀림없을거야.

엑스
잠깐만.
카오스 텔러는 서로 다른 상구를 이동할 수 있어?

레이나
아니, 원칙적으로 카오스 텔러는 자기 상구와 연결된 존재.
상구를 떠나 이동한다니 가능할 리가 없어...

셰인
흐~음. 이해할 수 없는 것이 너무 많네요.
애당초 여기는 어떤 상구인 걸까요?
앨리스 님과의 연결고리도 알 수 없구요...

레이나
거울 나라... 거울 나라...
흐음, 앨리스 이야기에 이런 게 있었던가...
정말 앨리스와 관련이 있을지도 모르겠...

3월 토끼 ※삼월토끼
마~치♪ 마~치♪ 토끼의 마~치♪
MARCH는 3월~♪ MARCH는 행진곡~♪
토끼의 3월~♪ 토끼의 행진곡~♪

타오
저기, 지금 어디선가 많이 봤던
녀석이 지나간 것 같은 기분이 드는데.

셰인
아니, 틀림없어요.
3월이라는 단어를 또박또박 말했는 걸요.
틀림없이 지금 지나간 건 3월 토끼 씨예요.

엑스
하지만 아까 그 3월 토끼는
우리를 못 본 것 같았는데...

레이나
하지만 이제 확실해졌어.
역시 여기는 앨리스와 관련이 있는 상구라는 것!

레이나
당장 3월 토끼를 뒤따라가자!

== 하얀 진영의 마을

엑스
어~이, 3월 토끼!

3월 토끼
응? 누구신지?
내 이름을 어떻게 알고 있는 거야?

엑스
무슨 말을 하는 거야.
앨리스와 같이 티 파티도 했었잖아?
모자장수는? 같이 있는 거 아니야?

3월 토끼
해터에 대해서도 알아?
으음, 뭔가 수상한 걸...
혹시 너희들 [붉은 여왕]의 스파이냐!?

타오
어이, 토끼 선생. 이제 그만 좀 하시지.
그 [붉은 여왕]이 누군지 모르겠지만
도와 준 은혜까지 잊어버리다니...

레이나
기다려, 타오.
어쩌면 이 3월 토끼는
진짜 우리를 모르는 걸지도 몰라...

엑스
무슨 말이야?
같은 이름의 똑같이 생긴 존재라는 말이야?

셰인
똑같이 생겼다기보다는 이 상구의 [3월 토끼] 라고 할까요.
셰인 일행이 [이상한 나라]에서 만난 분과는 다른 존재일지도...

3월 토끼
으~~~ 수상해 수상해~~~
스파이냐~~? 스파이지~~?

엑스
안 되겠어.
완전히 수상한 사람으로 의심 받고 있어.

엑스
저기, 3월 토끼.
우리는 단지 이야기를 듣고 싶을 뿐...

엑스
이런 곳까지 빌런이!?

3월 토끼
으악, 으아악!
[붉은 여왕]의 군대다! 포위당했어!

레이나
3월 토끼, 이 빌런... 이 아니고,
[붉은 여왕]의 군대를 몰아내면 우리를 믿어줄 거야?

3월 토끼
정말?
정말 이 녀석들을 쫓아버릴 수 있어!?

셰인
네, 맡겨 주세요.
붉은 여왕인지 파란 여왕인지
하여간 빌런을 상대로 질 수는 없죠.

***
*전투*

3월 토끼
정말로 당신들은 [붉은 여왕]과 아무 관계 없는 거구나~

엑스
응. 애당초 [붉은 여왕]이 누구인지도 잘 모르는걸...

3월 토끼
진짜!? 모른다구!?
우리 [하얀 여왕] 세력과 [붉은 여왕] 세력의
치열한 전투를!?

3월 토끼
[붉은 여왕] 측에 최근 무서운 괴물이
가세했다거나 내가 [하얀 여왕]의 사신으로 얼마나
고생을 했는지 등등 아무것도 모른단 말이야!?

셰인
아, 지금 대략적인 상황은 알게 됐으니 괜찮습니다.
근데 괴물이라니 혹시...

레이나
로키와 같이 있던 카오스텔러를 말하는 건가?
그러고 보니 도망치려고 할 때 로키가 말했지...

== 회상

로키
크흐흐... 자, 게임이 시작되었습니다.
여러분과 우리[들] 중 과연 승자는 누구일지.
크흣 크흣 크흐흐...

== 하얀 진영의 마을

타오
정신 나간 놈이군...
전쟁을 게임처럼 생각하다니...

3월 토끼
설마 당신들은 [붉은 여왕] 반대파?
그렇다면 우리 [하얀 여왕] 세력에 협력하지 않을래?

3월 토끼
[붉은 여왕]의 군대를 쓰러뜨려 준다면
우리한테도 큰 도움이 될 거야!
협력해주면 내가 알고 있는 정보도 알려줄게!

셰인
이야~ 여기 3월 토끼는 말이 잘 통하네요.
왠지 마음이 높이는 듯하면서도 뭔가 부족한 듯한...

3월 토끼
게~다~가~♪

3월 토끼
당신처럼 귀여운 사람이라면 [하얀 여왕] 세력...
이라는 전제하에 우리는 언제든 웰컴이라구~~

레이나
히익!

엑스
이런 흐름, 전에도 본 적 있어...

셰인
정말 역사는 반복되는 군요...

타오
아가씨는 진짜 이상한 녀석들에게 인기가 많네...

레이나
자, 잠깐. 들러붙지 마...
너희도 좀 도와 줘! 도와 달라구~!
헬~~프~~미~~~!

3월 토끼
그럼 모두 [하얀 여왕]님이 계시는 곳으로 안내할게~!
잠시 도중에 있는 숲에서 동료를 만나서 갈 거야~!
자, 렛츠고♪

== 시인의 숲

엑스
―3월 토끼의 안내를 받아 우리는 숲에 도착했다.
그곳에서 3월 토끼는 동료를 만나기로 했는데...―

3월 토끼
아~! 있다 있어♪
여기야~ 해터~♪

모자장수 해터
이제야 왔군. 3월 토끼.
응? 뭐야, 동행이 있었어?

엑스
엇, 모자장수...

레이나
반응하지 마. 엑스...
저 사람은 우리가 아는 모자장수가 아니니까...

타오
알고는 있지만...
깔끔하게 정리가 안 되네...

3월 토끼
이 사람들은 우리에게 협력해 줄
[붉은 여왕] 반대파 사람들이야.
마침 [하얀 여왕]님이 계신 곳으로 안내하려던 참이야.

모자장수 해터
음, 그렇군. 잘 부탁해.

엑스
어라? 여기 모자장수는 꽤 괜찮은...

레이나
그 이상은 말하지 마.
쓸데없는 이야기가 될 것 같으니까.

3월 토끼
이제 이 숲을 빠져나가면
[하얀 여왕]의 성에 도착해.
서둘러 가자~

타오
읏샤. 당장 가 볼까~

레이나
3월 토끼도 모자장수도
[이상한 나라]에서 만났던 자들과는 달라...

레이나
우리가 만났던 그 앨리스는...
정말로 이 상구에 있는 걸까?

엑스
우선 믿고 가 보자, 레이나.
나아가지 않으면 아무것도 알 수 없으니까.

엑스
분명 앨리스는 기다리고 있을 거야.
또 앨리스를 만나게 되면
이 거울 나라의 모험담을 실컷 들려주자.

레이나
응, 그래.

***

셰인
아, 그렇군요. 여기 모자장수 님은
[붉은 여왕] 측 괴물에 대해 조사하고 있던 건가요?

모자장수 해터
그래... 아직 자세한 건 베일에 감춰져 있어.
[붉은 여왕] 세력은 그 괴물을 자바워크라고 부르는 듯한데...
※재버워크

레이나
자바워크... 그 괴물의 이름...

모자장수 해터
맞아. 자바워크를 조심해야 해.
물어뜯는 입과 움켜쥐는 발톱!
접접새도 조심하길...

3월 토끼
...해터?

모자장수 해터
이글이글 불타는 눈동자로... 나타나는 자바워크...
울창하고 오싹한 나무 숲에서 나와
쫑알짹짹거리며 다가온다...!

*

자바워크
찾았다...
나의 앨리스를 노리는 놈들...!

3월 토끼
왜, 왜왜왜!? [붉은 여왕]의 괴물이...
자바워크가 왜 여기 있는 거야...!
어떻게 된 일이야, 해터!

자바워크
소용없다.
그 자의 [운명의 서]는 내가 바꿔 썼지.
그 녀석은 이제 내가 조종하는 인형이다.

레이나
드디어 나타났구나, 카오스텔러...
하지만 이제 와서 후회해 봤자 늦었어!
지금 당장 [조율]을 해 주겠...

모자장수 해터
해 질 녘 나긋하고 끈적한 토브들...
풀밭에서 빙글빙글 돌며 구멍을 팠네...
가녀린 보로고브!

레이나
꺅!?

엑스
레이나!

엑스
뭐, 뭐야. 이거... 꼬리에 포위 당한거야...?
뭐가 이렇게 큰 거야...!

자바워크
로키에게 이야기는 들었다...
[조율의 무녀]만 떼어 놓으면 무서울 것은 없지...
너희들만으로는 나를 막지 못해.

타오
하아아아아아아아아아아앗!!

타오
엑스! 여기는 우리가 맡을 테니!
넌 아가씨를 되찾아!! 숲을 빠져나간 후에 만나자!
절대로 돌아오지 마!

셰인
꼬리 끝 쪽의 틈을 통과하면 빠져나올 수 있어요!
무슨 일이 있어도 언니를 지켜 주세요!
나중에 우리도 쫓아갈 테니까! 서둘러요!!

엑스
타오... 셰인...!

엑스
나중에 만나자! 꼭이야!!

***

레이나
모자장수... 당신, 나를 어디로 데려갈 셈이야?

모자장수 해터
찔러라, 계속해서 찔러라, 보팔 검!
끝을 내라, 자바워크.
발소리를 내며 승리하라!

레이아
부탁이야... 이제 그 시를 멈춰...!
머리가 아파서 미칠 것 같아!

모자장수 해터
들브토 한적끈 고하긋나 녘 질 해
네팠 을멍구 며돌 글빙글빙 서에밭풀
브고로보 린녀가

레이나
누가... 좀 도와 줘...
엑스...!!

엑스
레이나한테서 떨어져~~~~~!!

모자장수 해터
크헉!?
털썩, 크억~~~~~~~

레이나
엑스! 아아, 다행이다...!
자바워크한테서 도망쳤구나!

레이나
어라? 근데 타오와 셰인은?
같이 있던 거 아니었어?

엑스
두 사람은... 자바워크를 막고 있어.
내가 그곳에서 빠져나갈 수 있도록...

레이나
안 돼... 카오스텔러를 두 사람이
상대하는 건 너무 무모하다구!! 빨리 돌아가야...!

엑스
안 돼. 먼저 숲을 빠져나가라고 말했어.
절대로 돌아오지 말라고...

레이나
무슨 소리 하는 거야...
타오와 셰인을 그냥 내버려두자는 말이야?
말도 안 돼! 빨리 돌아가야...!

엑스
레이나를 지키는 것, 그게 타오와 셰인의 선택이야!
두 사람이 만들어 준 길을 절대로 헛되이 할 수 없어!!

레이나
그래. 결국 또 나는...
누군가의 선택에 의해 살아가는 거네...

빌런
크르르 크르르...

엑스
레이나만 그런 게 아니야.
나도 이렇게 도망쳤잖아.
너를 지키는 사명을 받고 도망쳤다고...!

엑스
그 둘은 반드시 이곳을 벗어날 수 있어.
동료를 믿는다면... 같이 가자. 레이나!

레이나
엑스...!

***
*전투*

레이나
\......

엑스
조금만 더 기다리자. 레이나.
분명 돌아올 거야...
그 둘이 그렇게 쉽게 당했을 리가 없어.

레이나
아니, 누가 죽는 건 순식간이야.
모두 그랬어... 국왕이었던 아버지도 어머니도...
신하들... 친구들... 알라딘도...

레이나
모두... 순식간에... 사라졌어.
나만...혼자 두고...

레이나
그래도... 나는, 도망갈 수 없어.
그 모두의 마음이 나에게 맡겨졌으니까.
그래서 카오스 텔러를 [조율]하는 사명을 완수해야돼.

엑스
그랬군. 그게 레이나가 싸우는 이유구나.

엑스
그렇다면 나도 그 마음을 함께 짊어지겠어.
나는 순식간에 사라지거나 하지 않을 거야.
절대로 레이나를 혼자 놔두지 않아.

레이나
엑스... 고마워...
네가 있어 줘서...

????
에... 에... 에...

셰인
에~~~~~~~~~~취!!

셰인
......헉... 이런.

레이나
타오... 셰인... 3월 토끼...!

타오
아니야, 아가씨.
우리는 3월 토끼 덕분에 잘 빠져나올 수 있었어...
아냐, 지금 막 여기 도착한 거야. 그렇지, 3월 토끼?

3월 토끼
응응! 몰래 엿듣거나 하지 않았어!
둘이 좋은 분위기길래 어디까지 가나
몰래 엿듣거나 하는 짓은 절대 하지 않았다구!

셰인
3월 토끼 씨.
[얼버무리다]라는 말의 뜻은 알고 있나요?

셰인
아... 음 그게... 두 사람도 말이죠...

레이나
우와아아아아아아아아아아아아아!!
다행이다... 훌쩍, 다행이야...
모두... 무사해서... 정말 다행이야!

타오
아 뭔가 이런 거 좀 오글거리긴 하지만...
뭐 나쁘지는 않네.

셰인
걱정을 끼쳐서 미안해요 언니.
신참 씨도 고생 많았어요.

레이나
아니야, 다들.
돌아와 줘서 고마워...!

엑스
―이렇게 해서 우리는 다시 모여
[하얀 여왕]의 성으로 향했다.

엑스
카오스텔러에게 가는 길은 멀다.
하지만 우리는 걸음을 멈추지 않는다.
같은 생각을 마음에 품고 걸음을 계속한다―

== 하얀 진영의 시가지

엑스
―[하얀 여왕]의 성에 도착한 우리는
[하얀 여왕]의 환대를 받았다.

엑스
3월 토끼의 소개로 곧바로
[하얀 여왕] 세력에 협력하기로 했는데...―

타오
성 아랫마을이 [붉은 여왕] 군대에 공격을
받았다니 큰일이잖아!!

3월 토끼
그런 거지! 게다가 우리는 늘
사람이 모자라서 전투력도 부족하니까!
그냥 웃을 수밖에 없지 뭐! 아하하하하하하하하...

셰인
3월 토끼. 눈에 생기가 없어요...
그래서 이 부족한 전투력으로 어떻게 싸우면 될까요?

레이나
[붉은 여왕] 군대는 동쪽에서 쳐들어 와.
그러니까 거기에 병력을 집중시켜 당당히 맞서야지.

타오
그 밖에 뾰족한 수는 없는건가?

레이나
[붉은 여왕]의 배후에는 틀림없이 로키가 있어.
지금쯤 우리가 여기 있는 것도
로키는 다 알고 있을 거야.

레이나
그 녀석은 기묘한 꾀를 쓰고 우리의 반응을 즐기지.
어딘가에 덫을 놓았을지도 모르고,
자칫 무모해 보이는 정면 승부야말로 최선의 방책이야.

타오
차가운 표정으로 무모하다고 말하다니...
뭐 그런 것도 싫진 않지만!

엑스
체력 승부라는 거네...
좋아. 해 보자고 모두!

== 붉은 진영의 거점

나레이션
[붉은 여왕] 군대와 엑스 일행이 전투를 펼칠 무렵.
[붉은 여왕] 군대의 거점에서는...

로키
좀 더 지혜로운 방법을 생각한답시고
발버둥 칠거라 생각했습니다만...
우리의 덫에 걸려들어 주면 좋겠는데 말이죠...

????
당신의 나쁜 버릇이에요. 로키.
그런 식으로 쉽게 상대를 우롱하는 것.
아무리 적이라고 해도 존중해줘야지요.

로키
칼리 님...
자바워크 쪽은 괜찮은가요?

칼리
네. 아직까진 괜찮습니다...
당신이 무리하게 자바워크를 끌어내지 않았다면
조금 더 빨리 완성시킬 수 있었을 것을...

로키
죄송합니다. 칼리 님.
불안 요소를 빨리 제거하고 싶었을 뿐입니다...

칼리
알고 있어요. [조율의 무녀]를 없애고 싶었겠죠?
하지만 힘으로 눌러봤자 레이나 님은 절대
꺾이지 않을 거예요.

칼리
이제 곧 레이나님 일행이 저 빌런들도 무찌르겠죠.
그러면 그들이 있는 곳에 인사를 하러 갈까 해요.

로키
칼리 님! 진심이십니까!?
설마 자신의 정체를 말씀 하실 생각이십니까!?

칼리
다시 그들과 대화를 해야 합니다.
몇 번이고 몇 번이고...
우리의 정의를 그들에게 알려야 해요.

칼리
그것 또한 [혼돈의 무녀]인 제 사명이니까요.

로키
알겠습니다. 칼리 님.
그렇다면 저도 함께 동행하겠습니다.
부디 무모한 일은 하지 않으시도록...

== 하얀 진영의 시가지

타오
뭐야?
벌써 끝이야? 의외로 별 것 아니군.

셰인
잠깐만요. 저쪽에서 누가 와요.
앗... 저건...!?

로키
여어~ 여러분!
꽤나 건투를 하고 계신 모양이군요!

엑스
로키...!?
게다가 같이 있는 건... 칼리잖아!
왜 칼리와 로키가 같이...!?

레이나
다시 만날 줄 알았어.
하지만 설마 이런 식일 줄은 몰랐네.
대체 당신의 정체는 뭐야? 칼리.

칼리
그렇게 무서운 얼굴은 하지 말아 주세요.
제 이름은 칼리.
로키와 함께 여행을 하고 있는 [혼돈의 무녀]입니다.

타오
혼돈의 무녀...라고...?
그게 무슨 말이야!

로키
말 그대로입니다. 질서가 있는 곳에 혼돈이 있죠.
그녀는 카오스 텔러를 만들어내는 무녀입니다.

엑스
카오스 텔러를 만들어낸다고...!?
그게 네 짓이었어, 칼리!?

칼리
네, 그게 제 사명이니까요.

레이나
...!!

레이나
아무래도 천천히 이야기를 나눌 필요가 있겠어...!

칼리
오늘은 인사를 드리러 왔을 뿐입니다.
뒷이야기는 저희 거점으로 오셨을 때
마저 말씀드리도록 하지요.

로키
[붉은 여왕]의 진영에서 기다리고 있겠습니다.
서로에 대해 더 잘 알기 위해...

엑스
레이나, 네 기분은 알아.
그러니까 지금은 냉정해져야 해.
잊지 마. 레이나한테는 우리가 함께 있다는 것을...

레이나
그래, 엑스.
괜찮아. 이제 냉정을 되찾았어.
차분히 이야기 나눌게.

레이나
다 같이 그 녀석들이 있는 곳으로 가자.
꼭 들어야 할 이야기가 있으니까...

== 붉은 진영의 거점

칼리
어서 오세요. 잘 오셨습니다.
[조율의 무녀] 일행 여러분.
자, 어디서부터 이야기를 할까요.

레이나
우선... 당신들의 목적이 무엇인지 가르쳐 주겠어?
왜 카오스 텔러를 세계에 퍼뜨린 건지?

칼리
우리의 목적은 하나.
이 세상을 스토리 텔러의 지배에서 해방시키는 것입니다.

엑스
스토리 텔러로부터... 해방?

칼리
여러분도 여러 상구를 여행하며 보셨을 거예요....
스토리 텔러가 만들어내는 상구가 얼마나
부조리한지를...

칼리
상구는 눈에 보이지 않는 새장...
사람들은 끝나지 않는 이야기를 끊임없이 연기하죠.
그들은 자신이 이상하다는 사실조차 모릅니다...

엑스
그래서 그런 이유로 카오스 텔러를...?
이곳에 사는 사람들의 생각을 모두 짓밟아가며...?

칼리
짓밟는다? 아니요, 그렇지 않습니다.
상구의 주민, [운명의 서]를 가진 인간에게
[자신의 생각]이라는 개념은 존재하지 않습니다.

칼리
애당초 갖고 있지도 않은 생각을
어떻게 짓밟고 지킨다는 건가요?

엑스
칼리... 아니야... 그렇지 않아. 그렇다면 당신들은
무엇을 지킨다는 거야? 레이나의 소중한 것을
빼앗았으면서까지 무엇을 위해 싸우는 거지!

로키
당연히 이 감옥에 갇힌 [공백의 서]의 주인을 위해,
운명에 매인 그들의 영혼을 위해 싸우고 있는 겁니다.

로키
안정은 정체를 낳고 정체는 파멸을 초래하죠.
그래서 이 세계에는 정체를 막을 혼돈이 필요합니다.
혼돈이야말로 살아갈 의미를 만드니까요.

로키
It takes all the running you can do,
to keep in the same place.

로키
그곳에 도달하려면 전력을 다해 달려야만 합니다.
그것이 생명의 진리니까요.

타오
아무래도 우리와 너희는 신념이 다른 것 같군.

셰인
그렇네요. 어떻게 할 거예요, 언니.
조금 더 이야기 나눌 거예요?

레이나
이제 확인할 건 하나 뿐이야.
앨리스는 어디에 있어?
이 상구와 앨리스는 어떤 관련이 있는 거야?

로키
우리가 순순히 이야기할 거라고 생각하나요?

레이나
그렇다면 억지로라도 말하게 하는 수밖에!

***
*전투*

칼리
절대로 우리 생각에는 찬성할 수 없다는 거군요?

레이나
당신들의 시시한 이야기에 맞장구 쳐 줄 마음은 없어.
우리의 목적은 단 하나.
자바워크를 [조율]해서 앨리스를 되찾는 것뿐이야.

칼리
그렇군요... 그렇다면 서두르는 편이 좋을 거예요.

칼리
이제 곧 자바워크가 앨리스를 집어삼켜
완전한 힘을 손에 넣게 될 테니까요...

엑스
앨리스를 집어삼킨다고...? 무슨 말이야...!
이 상구는 대체 뭐야!

칼리
[이상한 나라]와 [거울 나라],
앨리스라는 같은 [주연]을 공유하고 있는,
다르면서도 이어져 있는 상구...

칼리
수학자이자 시인이기도 한 남자가 만들어낸
동화의 세계. 그것이 이 두 상구의 본질이지요.

레이나
같은 [주연]을 공유?
대체 무슨 말을 하는 거야?

칼리
그건...

로키
칼리 님!
더 이상 상대할 필요 없습니다!

로키
[조율의 무녀] 일행 여러분.
이제부터 이 자가 여러분을 상대해 드릴 겁니다!

타오
나타났군. 메가 빌런!

셰인
가끔은 당신이 직접 나서지 그래요?
우리를 상대하는 게 그렇게 무섭나요?

로키
그렇게 도발해도 소용 없습니다.
절대로 이 분에게는 손끝 하나 댈 수 없습니다!

***
*전투*

레이나
자, 다음은 또 누구를 내보내려고?
자바워크를 불러 준다면
당장이라도 [조율]해 줄 수 있는데...?

로키
동료들이 모이면 기세 등등해지는 건 여전하군요.
좋습니다. 당신이 의지를 굽힐 때까지
몇 번이고 상대해 드리지요...

칼리
자바워크는 여기보다 남쪽 결계에 있습니다.
레이나 님이 찾고 있는 앨리스도 같은 곳에 있고요.

로키
칼리님! 어째서?

칼리
말했을 텐데요. 적이라고 해도 존중해야 한다고.
우리는 이 분들을 설득하는 데 실패했습니다...
여기는 우리의 패배예요.

레이나
꽤나 분별력이 있군. 칼리.
우리를 막지 않아도 괜찮겠어?

칼리
자유란 내면의 목소리에 부끄럽지 않은 방식으로
살아가는 것입니다. 지금 내 마음이 패배를
인정한 이상 그것은 결코 부정할 수 없습니다.

칼리
다시 만납시다. 여러분.
언젠가 이 세상이 스토리 텔러에게서
해방되는 그 날까지.

로키
크흣... 크후후...
앞으로 여러분의 여행에 행운이 있기를.
이 로키가 진심으로 바라고 있겠습니다.

셰인
하고 싶은 말만 하고 가 버렸네요.

타오
자바워크는 남쪽에 있다고 했는데
어떻게 된 일이지...
완전한 힘이 어쩌고 저쩌고 말했잖아...

엑스
하지만... 지금 확실히 말했어...
우리가 아는 앨리스는 이 상구에 있다고...
그렇다면 우리가 해야 할 일은 정해져 있어...!

레이나
이대로 계속 가자. 자바워크가 있는 남쪽 땅으로.
앨리스를 구하기 위해!!

== 결말의 체스판

타오
어떻게 된 거야. 여기는...?
기묘한 지형... 마치 장기판 같은...

셰인
아니. 여기는 오히려 체스판이라고 하는게 맞나요?
이게 칼리가 말한 체스판의 정체...

엑스
그런데 앨리스는 대체 어디에...

????
살려 줘... 누가... 제발...!
어둡고... 추워... 누가 여기서 날 좀 꺼내 줘...!

레이나
앨리스? 앨리스야!?
제발! 있다면 대답해!

*

앨리스의 목소리
혹시 레이나...!? 와 준 거야...!?
맞아! 나 앨리스야! 나 여기 있어...!

앨리스의 목소리
제발! 빨리 와 줘!
이대로라면 이 괴물이 나를 집어삼켜...

앨리스의 목소리
아아, 제발... 그만해...
그 시 좀 읊지 마...! 머리가 깨질 것 같아...!

????
이야기 꾼이여. 자바워크를 조심하라...
물어뜯는 입과 움켜쥐는 발톱...!
접접새도 조심하길.

빌런
흉측한 밴더스내치!
어디서든 물고 늘어지는 입에 움켜쥐는 발톱!

엑스
이건 모자장수가 읊었던 시...
자바워크가 읊고 있는 건가.

타오
뭐든 상관없어!
바로 입 다물게 해 주지!

***
*전투*

자바워크
누구냐... 내 시를 방해하는 자는...

엑스
자바워크. 드디어 나타났군...!
응? 잠깐, 자바워크 옆에 누가 있어.

앨리스
레이나! 모두들!

레이나
앨리스!?
자바워크, 당장 앨리스를 돌려 줘!

자바워크
그럴 수는 없지... 이 아이는 내가 세계를 지배하기
위한 열쇠니까. [이상한 나라]와 [거울 나라]
모두를 지배하기 위함이지.

타오
무슨 소리를 하고 있는 거야...
그런 게 가능할 리가 없잖아...!

레이나
아니. 어쩌면 가능할 수도 있어.

레이나
칼리가 말했어.
[이상한 나라]와 [거울 나라]는 같은 [주연]을
공유하고 있는, 이어져 있는 상구라고...

레이나
두 상구가 앨리스라는 [주연]으로 묶여 있다면...
자바워크가 [이상한 나라]에 나타나는 것도 말이 돼.

셰인
그럼 자바워크는 두 상구를 지배하려고 하는 건가요.
앨리스 씨를 집어삼킨다는 것도... 대체 어떻게...

자바워크
그건... 나라는 존재를 안정시키기 위함이다.

자바워크
나는 [거울 나라]의 상구에 있는 시 속에서만
이야기할 수 있는 존재. 내가 존재하기 위해서는
많은 스토리 텔러와 듣는 이가 필요하지.

자바워크
그러기 위해서는 [거울 나라]만으로는 부족해...
[이상한 나라]도 지배해야만 해.

자바워크
그래서 앨리스가 필요했다.
그래서 로키와 협력해서 [이상한 나라]의
카오스 텔러를 제거한 거다...!

엑스
그렇군... 하트의 여왕이 있는 곳으로
우리를 유도한 것도 [이상한 나라]의 카오스 텔러를
제거하기 위함이었던 거군...

자바워크
너희는 모른다... 육체를 가진 너희들은...
이야기 속에서만 존재하는 자의 분노 따위...
어차피 이해할 수 없겠지...!

엑스
그래, 네 분노는 이해할 수 없어.
하지만 외롭다는 건 잘 알아.
누구에게도 의지할 수 없는 슬픔은 느껴봤으니까...

엑스
하지만 그런 내게도 동료가 생겼어.
함께 마음을 나눌 수 있는 동료가...
그래서 이 마음을 지키기 위해 우리는 싸우는거야!

엑스
레이나, 타오, 셰인...
가자... 여기서 결판을 짓자!

레이나
그래, 아무리 주어진 [운명] 이라 해도
그 마음만은 아무도 부정할 수 없어!

***
*전투*

앨리스
다들 고마워. 몇 번이고 나를 도와줘서...
하지만 이걸로 정말 이별이네.

레이나
응. 나도 들려주고 싶은 이야기가 많아.
그러니까 다시 이 상구로 오게 되면 꼭 이야기하자.
네가 나를 기억해 준다면 말이야.

앨리스
물론이지! 너를 절대로 잊지 않을 거야!
꼭 다시 만나자! 약속이야!

레이나
응. 꼭이야.

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라,
여기 조율을 시작하오니....』

*조율 컷씬*

셰인
드디어 앨리스의 상구와도 작별이군요.

타오
아가씨, 사실은 섭섭한 거 아냐?

레이나
바보 같은 소리. 칼리와 로키를 막지 않는 한
카오스 텔러는 계속 태어날 거야.
여행은 앞으로도 계속되겠지. 그러니까...있잖아...

레이나
앞으로도 함께 해 줄 거라고 생각하면 되는 거지?

레이나 이외 전원
\......

레이나 이외 전원
 +
...풉 ...푸하하하하하하하하하!!

엑스
뭐... 뭐야... 이제 와서 새삼스럽게!
말했잖아. 절대로 레이나를 혼자 두지 않겠다고.
네가 싫다고 해도 우리는 함께 할 거야.

레이나
~~~~~칫!
알겠다고! 바보 같은 소리 해서 미안하다고!
그럼 다시 출발하자!

레이나
[인도의 책갈피]와 히어로들의 영혼과 함께!

*

칼리
안타깝군요... 분하네요...
저들의 마음을 바른 길로 인도하지 못한 것이...
교단의 무녀, 실격이네요...

로키
칼리 님. 너무 실망하지 마십시오.
아무 문제 없습니다.
이번에는 꽤 의미 있는 성과를 얻었으니까요.

로키
상구를 이동할 수 있는 카오스 텔러의 검증 성공,
우리라는 존재를 [조율의 무녀] 일행에게 각인시킨 것.
그 밖에도 여러 가지로 포석을 깔아두었습니다...

칼리
...당신 몸은 괜찮은 건가요?

로키
이 정도는 아무 것도 아닙니다.
지금은 우리도 다음을 위해 나아가도록 해야 합니다.

로키
다가올 [해방의 그 날]을 위해
저는 계속 칼리 님 곁에 있을 테니까요.