:hardbreaks:

....
옛날에 플린트라는
무서운 해적이 있었다.

그는 많은 수하를 거느리고
바다를 휩쓸고 다니며 온갖 금은보화를
손에 넣었다고 한다.

선원들의 『공포』의 대명사가 된 플린트는
막대한 보화를 어느 섬에 숨기고
마침내 세상을 떠났다.
\

플린트가 죽은 뒤 그의 부하였던 해적들은
그 행방을 쫓으려 혈안이 되었으나,
아직도 보물을 찾지 못했다고 전해진다...
....

== 서쪽 해안

엑스
우와... 우와아아아아아아...!!
뭐야, 이렇게 커다란 호수는 처음 봐!!

레이나
아, 엑스 너는 본 적 없구나?
이건 [바다]라는 거야.

레이나
바다는 호수보다 훨씬 더 넓고 깊어.
스토리 텔러들이 나타나기 전에는
세계의 70%가 바다였다고 해.

타오
얏호! 바다다 바다 바다다아아아!!
엑스!!
나랑 건너편 바위까지 누가 더 빨리 가는지 내기하자!!

엑스
잠깐... 기, 기다려, 타오!!
으앗! 뭐야 이 물, 엄청 짜잖아! 근데 시원해서 기분 좋아!!

레이나
...저 녀석들, 애도 아니고!!
할 수 없지. 셰인, 우리끼리라도 이 주변을 조사하러...

셰인
언니, 비키니와 원피스 중 어떤 수영복이 좋으세요?
언니 정도의 몸매라면 의외로 대담하게 입는 것도...

레이나
어디서 가져 온 거야!
안 입어, 입을 리가 없잖아!

레이나
아, 정말!!
어디서 카오스 텔러가 날뛰고 있을지 모르는데,
얘네들은 왜 이렇게 태평한 거야!!

셰인
어라? 저기 오빠가 돌아오고 있어요.

레이나
나 참, 이번에는 또 무슨 장난을 치려고...
잠깐? 누군가를 업고 있네?

*

????
크으... 빌어먹을...

타오
아저씨, 정신 차려! 이제 곧 해안이야!

엑스
레이나! 셰인! 빨리 [책갈피]를 준비해!

*

셰인
또... 바다에서 빌런이 잔뜩...

레이나
감탄하고 있을 때가 아니잖아!
어서 히어로와 연결하자!

***
*전투*

????
휴우~, 덕분에 살았어, 형씨들.
나는 존 실버라고 해. 위험할 뻔했는데 구해줘서 고마워.

타오
당연한 건데 뭘.
실버, 당신은 이 섬에 사는 사람이야?

실버
아니, 이 섬에 사는 건 아냐.
나는 작고 허름한 배에서 일하던 요리사야.

실버
같은 배의 동료들과 함께 있었는데,
갑자기 몇 명이 괴물로 변해서 다들 도망쳤어.
나는 너희 덕분에 살았지만 동료들은 어떻게 됐을지...

레이나
괴물... 그렇구나, 카오스 텔러에게 당한거야.
이미 이 섬은 카오스 텔러의 영역이 되어버렸어.
빨리 그 놈을 찾아서 [조율]해야 할텐데...

엑스
그런데 실버 씨는 왜 이 섬에 온 거야?

실버
꿈을 찾아 온 거지.
해적 플린트가 이 섬에 숨겼다는 엄청난 보물을 말이야.

타오
...보...물?

레이나
잠깐, 타오. 왜 설레는 표정을 짓고 있는 거야.
지금 우리가 뭘 해야 하는지 제대로 알고 있는 거지?

타오
뭘 해야 하는지? 물론 알고 있지.
그야 당연히 보물찾기잖아?

레이나
당연히 카오스 텔러의 조율이잖아!
바보! 너는 왜 이렇게 바보인 거야!?

타오
거 참, 뭘 모르는구만?
언제든 로망을 잃지 않는 게 남자의 미학이라는 거야!

레이나
알고 싶지도 않아! 네 바보 같은 미학 따위!

엑스
...나, 이제 이 광경에 익숙해졌어.

셰인
잘됐네요. 무슨 일이든 적응하는 건 중요하니까요.

실버
크하하! 재미있는 친구들이구만!

실버
보물 위치는 모르고 카오스 텔러가 뭔지도 모르겠지만,
섬 안내 정도는 해 주지.
이 섬에서 무슨 일이 벌어지는 건지 나도 알고 싶으니까.

== 용암의 터

타오
...그래서 작은 배밖에 주지를 않으니 무지하게 힘들었어.
그걸로 바다 건너 섬까지 가라니 말이 돼?

실버
하하, 그렇지만 꽤 하는걸? 제대로 섬까지 건너왔잖아.
보통 남자가 할 수 있는 일이 아니야.

엑스
아직도 믿기지가 않아.
이런 넓은 바다를 사람 손으로 건널 수 있다니...

실버
되고 말고. 인간에게 불가능 따윈 없으니까.
꿈과 의지만 있다면 어떤 바다라도 건널 수 있지.

엑스
와... 잘은 모르겠지만, 엄청 멋진 말이네요.

*

레이나
...그새 완전히 친해졌네.
언제 또 빌런이 습격해올지 모르니까 빨리 가자.

빌런
크르르! 크르크르르!!

레이나
... 늦었네.

타오
쳇, 나타났냐 빌런 놈들! 이 타오님이 상대해주마!
...셰인? 왜 전투 준비도 하지 않고 멍하니 있어?

셰인
지금, 저기... 누군가, 사람 모습이...

레이나
뭐라고!?

셰인
아, 안돼... 저쪽으로 가버렸어요. 어떻게 할까요?

타오
...그럼 셰인, 넌 먼저 저 녀석을 쫓아가.
우리도 여길 정리하고 곧 합류할게.

셰인
...라져.

엑스
앗, 셰인 없이 싸우는 거야!?

타오
이 정도는 셋만으로도 충분해!
자, 빌런 놈들을 날려버리고 따라가자!

***
*전투*

엑스
하아... 하아...
셰인이 사람 모습을 봤다고 했는데 진짜야?

타오
그 녀석은 시력과 육감이 뛰어나.
셰인이 [봤다]고 하면 난 그게 유령이라고 해도 믿을 거야.
...엇, 돌아왔다.

셰인
미안, 놓쳐버렸어요.
의외로 재빠른 게... 아무래도 아이 같았는데...

실버
아이?
...그렇군, 짐 녀석이구만!

레이나
아는 사람이야?

실버
아마도 내가 있던 배의 견습생 꼬맹이일 거야.
다른 동료들처럼 괴물로 변했거나 습격당한 줄 알았는데,
무사했던 건가...

엑스
실버 씨의 동료?
...그럼, 그 아이는 왜 우리한테서 도망친 걸까.

실버
겁이 많은 녀석이거든.
잔뜩 겁먹어서 우리까지 경계하는 걸지도 몰라.

레이나
그렇다면 바로 뒤쫓아가자. 뭔가를 알고 있을지도 몰라.
셰인, 어느 쪽으로 갔는지 알아?

셰인
북쪽에 있는 동굴로 가는 것 같았습니다만...

실버
북쪽이라... 알겠어. 그쪽으로는 내가 안내하지.
짐을 내버려둘 수는 없으니까.

== 어두컴컴한 동굴

짐
...여기까지는 못 쫓아오겠지.

셰인
이거 미안해서 어쩌죠.

짐
우왓! 왜, 왜왜왜왜 여기에!

타오
이 동굴 안에 꼬맹이가 숨어 있을 만한 곳은 뻔하던데.

엑스
괜찮아. 무서워하지 않아도 돼.
실버 씨도 우리와 같이 있어. 우리는 네 편이야.

짐
...실버? 그 인간도 여기 있어?

레이나
응, 여기까지 안내도 해 줬어.
어라, 어디로 갔지? 방금 전까지 같이 있었는데...

짐
안 돼! 빨리 도망가야 돼!

짐
그 인간은 동료가 아니야! 아주 악랄한 해적이라고!

타오
!? ...이봐, 그게 무슨 말...

엑스
뭐야! 지진!?

레이나
아니야! 이건... 동굴이 무너지고 있어!
이대로라면 갇혀버릴 거야!!

타오
...일단 안쪽이야. 모두, 안쪽으로 도망쳐!

*

실버
...안타깝군, 정말 안타까워.
동료로 삼아볼까 하고 기회를 엿봤었는데
잘 안 풀리는구만~

실버
보물이 있는 곳으로 안내하진 못했지만
적어도 이 어둠 속에서 보물 꿈이라도 실컷 꾸라고.
크하하,하하하하!

***
*전투*

짐
존 실버... 저 인간은 해적 플린트의 부하였던 놈이야.
플린트의 배에서 키잡이로 일했던 무서운 남자였어.

짐
트렐로니 씨가 선원을 구할 때, 요리사로 들어왔는데
함께 도와주겠다며 자기 동료들까지 불러서 배에 태웠어.

짐
섬에 도착해 보물의 위치를 알게 되자마자
존 실버와 해적들이 반란을 일으켰어.
그리고 어느새 모두 괴물로 변해 있었고...

셰인
그럼, 카오스 텔러가 실버 아저씨에게 빙의해서
반란을 일으킨 걸까요?

레이나
글쎄... 어디까지가 그 사람의 본성인지 모르겠어.
뭐랄까, 종잡을 수 없는 사람이었으니까.

타오
\..............................

레이나
타오...

셰인
지금은 그냥 가만히 내버려 두세요.
...타오 오빠 나름대로 실버의 배신을 참는 중이에요.

엑스
실버의 목적이 뭔지
직접 만나서 확인할 수밖에 없는 걸까...

엑스
...음, 그 전에 여기서 나가는 게 먼저겠지만.

????
그르르르오오오오오오오오오!!!

짐
핫!? 저건 뭐지!?

엑스
메가 빌런... 이런 동굴에까지 나타나다니...!

타오
하, 마침 잘 걸렸다.
지금 머리 끝까지 화가 나서 아주 미치겠거든....

타오
일단은 너덜너덜하게 때려눕혀주마, 덩치 큰 괴물아!

***
*전투*

레이나
저기 봐! 메가 빌런이 나타났던 곳! 빛이 들어오고 있어...!

엑스
어쩌면 저쪽으로 빠져나갈 수 있을지도...!
모두 서두르자!

== 동굴에서 빠져나간 해안

셰인
무사히 탈출에 성공했네요.
문제는 실버 아저씨가 어디로 갔느냐인데...

타오
... 아마 보물이 있는 곳일 거야.

타오
분명 녀석은 거기에 있어. 녀석의 본질은 해적이야.
그렇다면 분명 이 섬의 보물도 열심히 찾고 있겠지.

레이나
그런데 보물이 있는 곳은 어떻게 찾아야 하지?

짐
...내가 알고 있어. 플린트의 보물이 어디에 있는지...

짐
트렐로니 씨한테 받은 보물 지도를 갖고 있어.
내가 앞장서서 안내할게.

엑스
...짐, 괜찮은 거야?
보물이 있는 곳으로 가면 더 위험해질지도 몰라.

짐
나는 제대로 된 선원이 되고 싶어.
그래서 이 모험에 참여했던 거야.

짐
부탁이야. 같이 가게 해줘.
나도 그 실버에게 한 방 먹여 주고 싶단 말이야!

타오
... 후, 후후. 말 한 번 잘했네, 꼬맹이!
그게 바로 사나이라는 거다!

타오
좋아, 우리가 그 얼간이 실버를 쳐부수러 가자고!
타오님의 실력, 해적 놈들에게 보여주겠어!

레이나
...참, 정말 시끄러운 남자야.
그래도 겨우 원래 상태로 돌아왔다고 해야 하나?

셰인
...응. 역시 타오 오빠는 이렇게 나와야죠.

== 입구에 있는 해안

짐
지도를 봐선 이 주변...
이 해안 어딘가 보물이 잠들어 있는 동굴이 있을 텐데...

셰인
...파도에 지워졌지만, 사람이 지나간 듯한 흔적이 있어요.
주의깊게 살펴보면 입구를 찾을 수 있을지도 몰라요.

타오
...아니. 아무래도 주의깊게 찾을 필요가 없어 보이는군.

*

엑스
빌런이...! 이렇게나 많이...!

레이나
역시... 이 주변에 숨겨진 무언가가 있다는 거네.

레이나
미안하지만, 그 길을 터 줘야겠어!

***
*전투*

엑스
봐봐! 저기!
빌런들의 발자국이 건너편의 후미진 동굴로 이어져 있어...

짐
아, 저기다!
저기가 지도에 그려져 있는,보물이 숨겨진 동굴이야!

레이나
바보 같은 빌런들이네. 일부러 단서를 남겨 주다니...

타오
글쎄. 어쩌면 우리를 불러들이는 걸지도 몰라.
실버 자식, 아직도 뭔가 계획하고 있는 거냐...!

셰인
트랩따위 상관 없습니다. 앞으로 나아가보죠.
노려야 할 표적은 저 안에 있으니까요.

짐
저기, 동굴 안은 미로처럼 되어 있어서 아주 위험해.
여기서부터는 내가 안내할게!

엑스
응. 부탁할게, 짐.

== 플린트의 동굴

짐
...응? 지금 안쪽에서 뭔가 빛 같은 게...
...설마!

짐
모두, 이쪽으로 와줘!

*

타오
이런 이런... 이거 기절초풍하겠구만...
보물이 산더미처럼 쌓여있네.

셰인
저쪽에 보이는 건 배의 잔해인 것 같아요.

짐
역시... 보물은 진짜 있었구나!
굉장해, 굉장해! 이거 봐! 이 금화, 반짝반짝 빛나고...

엑스
짐? 왜 그래, 짐.

짐
...우, 윽, 으아아아아아아아아아아아!

엑스
짐! 대체... 왜...!

실버
크크크... 그건 꿈으로부터 저주받았기 때문이지.

타오
실버...!

실버
후, 다시 만나서 기쁘구나. 죽다 만 놈들.

레이나
인사는 그만둬. 당신, 짐한테 무슨 짓을 한 거야...!

실버
나는 아무 짓도 안 했어.
단지, 이 보물에 약간의 저주를 걸었을 뿐이지.

실버
보물을 만진 자는 나와 같은 꿈에 홀려
실버 해적단의 명예로운 선원이 되도록 하는 저주를 말이야.
재미있잖아?

엑스
용서 못해... 네 놈만은 절대 용서 못해...!

실버
이봐, 그렇게 흥분하지 말라구.
세상 물정 모르는 너희에게 가르쳐 주지.
진짜 해적의 무서움을 말이다!

타오
진짜 해적?
빌런들을 모아서 대장 놀이하는 것 뿐이잖아, 실버.

타오
무적의 타오 패밀리를 얕보지 말란 말이다!

***
*전투*

실버
...크, 크크크...
역시 너희는 평범한 녀석들이 아니었군.

레이나
남은 건 당신 혼자야, 실버 선장. 아니, 카오스 텔러.
바로 당신을 [조율]해서 모두를 원래대로 되돌려놓겠어...

실버
원래대로 되돌려...? 잠깐, 농담하지 말라고.
힘들게 손에 넣은 보물이다. 놓칠 수 있을까보냐!

엑스
저게 카오스 텔러가 빙의한 실버의 모습인가...!

타오
...이봐, 너는 바라는 게 뭐야.
그런 모습이 되면서까지 대체 어떤 꿈을 이루고 싶은 거냐.

실버
당연한 거 아냐?
나는 이 보물을 모은 대해적, 플린트를 넘어서는
위대한 바다의 남자가 될 거다!

실버
보물이라는 이름의 저주받은 꿈에 매혹된 자들을 끌어들여
일곱 개의 바다를 지배하는 거다!
그것이야말로 나의 목표!

실버
너희도 이쪽으로 와라.
나와 같이 꿈을 펼쳐보자고!

레이나
그런 짓을 좋다고 할 리가 없잖아.

엑스
네 꿈에 함께 어울리는 짓따위 절대로 사양하겠어.

셰인
셰인은 타오 오빠를 따르겠어요.
뭐, 오빠의 대답은 듣지 않아도 알 것 같지만.

타오
...남자라면 말야, 항상 로망을 잃어서는 안 되지.
실버, 네놈의 꿈엔 그런 로망이 눈꼽만큼도 보이지 않아.

타오
네놈의 꿈, 여기서 끝을 내 주지.

실버
...그렇군, 그렇다면 어쩔 수 없지.

레이나
뭐, 포탄!? 설마 저 배에서!

엑스
아직도 저쪽에 동료가 남아 있었던 건가!

실버
해적은 말야, 최후의 순간까지 비장의 카드를 숨겨놓거든...

실버
자, 마지막 연회를 시작해 볼까.
이대로 내 꿈의 양식이 되어라!! 빌어먹을 애송이들아!!

***
*전투*

실버
어째서... 어째서냐, 플린트 선장...
왜 나는... 당신처럼 위대한 해적이 되지 못하는 거야...

타오
...아가씨, 부탁해.

레이나
네가 부탁을 하다니 흔치 않은 일이네.
...알았어. 나머지는 나한테 맡겨둬.

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라
여기 조율을 시작하오니......​』

*조율 컷씬*

엑스
세계가 조율되고 빌런이 된 짐과 사람들은
모두 원래대로 돌아왔다.

엑스
아무래도 이 상구에서 실버의 반란 자체는
처음부터 예정된 운명이었던 듯하다.
그리고 실버와 그 무리들이 마지막에 붙잡히는 것 또한.

엑스
섬의 소동은 끝이 났고 결국 남은 것은 꿈의 흔적뿐.
우리는 짐 일행이 탄 배를 보내면서 이 상구를 떠났다.

== 입구에 있는 해안

엑스
이 [바다]와도 이별인가. 뭔가 시원섭섭하구만...

엑스
...그런데, 타오는 어딜 간 거야?

셰인
잃어버린 게 있어서 잠시 다녀온다고 했어요.
곧 돌아올 거예요.

레이나
어휴, 정말 자기 마음대로라니까!
대체 뭘 잃어버렸다는 거야?

셰인
글쎄요... 분명 남자의 결판, 꿈, 로망...
뭐 그런 거 아닐까요?

== 서쪽 해안

승무원
자자, 빨리 올라타, 해적들!

실버
\.........

타오
[인간에게 불가능 따윈 없다고.
꿈과 의지만 있다면 어떤 바다라도 건널 수 있지]였었나?

실버
......?

타오
당신의 꿈에 동참할 수는 없지만
당신의 이 말만은 가슴에 새겨두도록 하지.
잘 가라, 실버. 건강하고.

실버
......흥. 그쪽이야말로 항상 로망을 소중히 하라고.

타오
어?

타오
...쳇, 미워할 수 없는 해적이군, 당신은.

타오
자, 다들 기다리고 있으니 슬슬 가 봐야겠군.
혼돈을 끝낼 다음 여행지로!