= 4. 돈키호테의 상구 - Flero
:hardbreaks:

....
라 만차 지방의 어느 마을에
한 명의 몰락한 시골 귀족 노인이 살고 있었다.

노인은 평화로운 마을에서
너무나 한가한 나머지,날이면 날마다
기사도 책을 열심히 읽었다.

이윽고 노인은 책 이야기에 완전히 심취해
머릿속이 온통 책에서 읽은
많은 공상으로 가득해졌다.

현실과 공상의 경계를 잃어버린 노인은 결심한다.
자신도 이야기 속 기사와 마찬가지로
세상의 부정을 제거하는 모험을 떠나기로.

이렇게 해서 노인은 갑옷과 투구를 몸에 걸치고
삐쩍 마른 말 로시난테에 올라타
하인 산초를 데리고 여행을 떠난다.

노인의 이름은 알론소 키하노.
기사로서의 이름은
『라 만차의 기사 돈키호테』...
....

== 바람 부는 초원

​ +
크르르...크르르...
크르르 우루롸아아!

엑스
...어떻게 할까? 들어오자마자 포위 당했는데.

타오
새삼스럽긴. 이번만 그런 것도 아니잖아 .
해지기 전에 마을까지 돌파하자!
피라미들을 모두 상대할 필요는 없잖아?

셰인
맞습니다. 다 처리할 순 없으니까요.
일단 포위망을 흐트려서 다른 곳으로 빠져나가는 게...

????
이보시오~! 기다리게나, 제군들! 기다리시오!

레이나
응? 누구야?

????
괘씸한 악마의 똘마니들아!
전도유망한 젊은이들에게 무슨 짓이냐!
이 방랑 기사가 혼내 주마!

셰인
저기... 할아버지, 괜찮습니다.
저희들은 괜찮으니까 물러서 계세요.

타오
셰인, 잠깐만. 사람을 겉모습만 보고 판단하면 안돼.
혹시 모르잖아, 이 할아버지 엄청 강할지도...

????
자, 받아라! 내 정의의 칼날에 목숨을 부지한 악은 없다!!
이야아아아아아아!

레이나
응? 갑자기 멈추셨는데 괜찮은 걸까?

????
으...으아악!!! 허..허리에 보이지 않는 악마의 일격이...!

레이나
그것 참 웃기네.
악마의 일격은 무슨, 허리 삐끗한 거잖아?

엑스
저기...괜찮으십니까? 제 어깨 잡으세요.

????
으...으...허...허리에 보이지 않는 악마의 일격이...!

셰인
일단 싸우기나 하죠.
자세만 잡고 있었더니 피곤해지네요.

***
*전투*

레이나
자, 회복 주문을 걸어 뒀어요. 이제 움직일 수 있죠?

????
으으... 허리에서 악마가 사라졌다...
이 무슨 신비한 능력인가... 혹시 자네 성녀인가!

레이나
그건 너무 오버하는 거 같아요.

????
감사하오. 그건 그렇고 제군들도 대단하구만.
그 악마 녀석들 우리 실력에 겁을 먹고 도망가 버렸어!

셰인
할아버지는 뭘 하셨더라?

엑스
할아버지, 저희는 그 악마들을 쫓고 있어요.
혹시 뭔가 알고 있으...

????
...산초? 산초 아니냐!
너 이녀석, 이런 곳에서 뭘 하고 있는 거냐!

엑스
어? 저기, 할아버지? 사람 잘못 보셨어요!
전 엑스라구요. 할아버지랑 초면인걸요.

????
할아버지라니!
나는 자랑스런 라 만차의 기사이며,
슬픈 표정의 기사...그리고 사자의 기사...

????
잃어버린 기사도를 실천하며 전도하는 돈키호테다!
주인님의 얼굴을 잊어버리다니 한심한 놈!
자, 가자!

엑스
간다니 어딜?

돈키호테
당연한 걸 왜 묻느냐! 정의를 위해 악마를 토벌하러 가야지!

돈키호테
마법사가 보낸 악마녀석들이 곧 마을에 나타날 것이다!
우리들이 어서 가서 무고한 백성들을 구해야 한다!

셰인
어떻게 하죠? 왠지 망언같은 느낌이 마구 듭니다만...

타오
뭐 어때, 일단 따라가자! 그게 재미있을 것 같아!

레이나
지금 어떻게 해 볼 단서도 없으니까 말이지.
그럼 가볼까? 뒷처리를 부탁할게, 산초.

엑스
...엥? 혹시 귀찮은 건 다 나한테 시키는 거야!?

== 해안가의 마을

떠드는 아이
앗, 거짓말쟁이 돈키호테 할아버지다!
있잖아, 악마 물리쳤어?

기막혀하는 부인
또 저 할아버지야? 이번엔 무슨 난리를 피울 작정인 거지...

엑스
돈키호테씨... 인기 많네요?
왠지 수근거리고 있...는 것 같은데
다들 빌런... 악마에 대해 모르는건가요?

돈키호테
흠. 왠지 악마는 내 눈에만 보이는 것 같다.
그래서 백성들은 아직 악마의 존재를 인식하지 못하고 있지.

돈키호테
그렇지만 다들 내 말을 믿고,
마을을 위험에서 지켜야 한다며 악마 토벌에 협력하고 있다.
보거라!

돈키호테
어~이! 곧 악마가 이 땅에 나타날 것이다!
다들 빨리 피해라!

도망가는 마을 사람
저 할아버지 또 시작이다... 빨리 도망가자!

셰인
이건 다들 할아버지한테서 도망치는 거 아닌가요?
도대체 무엇을 어떻게 하면 저런 반응을 보이는 겁니까?

돈키호테
흠, 악마와의 격렬한 전투 덕분일지도.
종종 주변을 쑥대밭으로 만들기도 하니... 앗?

타오
우왓!? 진짜 나타났어?!

돈키호테
악마놈들... 드디어 모습을 드러냈군!
이 돈키호테님이 있는 이상 악마 녀석들이
맘대로 하도록 내버려 두지 않겠다! 산초, 따라 와라!

엑스
돈키호테씨, 먼저 가지 마요!

레이나
이 할아버지, 설마...

엑스
레이나, 왜 그래?

레이나
아무 것도 아냐, 나중에 얘기할게. 우선은 같이 가자!

***
*전투*

엑스
돈키호테씨가 카오스 텔러일지도 모른다고?

레이나
확실한 건 아니지만...
저 사람 주변에서만 빌런이 나타나고 있어...
가능성은 있다고 생각해...

레이나
목적이 뭔지는 모르겠지만 우리들에게 접근한 것도
빌런과 싸우는 틈을 노리려는 게 아닐까?

엑스
말도 안돼...

타오
어이, 거기 둘! 수다 그만 떨고 서둘러!
할아버지가 또 어디론가 갈 생각인가 봐.

엑스
이번엔 어디로 가시는데요?

돈키호테
당연한 걸 왜 묻느냐!
마법사를 해치우기 위해 동쪽 황야로 간다!

레이나
마법사?

돈키호테
그렇다! 이 마을에 악마를 계속 보내고 있는 나쁜 마법사다!

돈키호테
녀석은 마법으로 사람들을 속이고 있지.
풍차로 가장한 거인을 몇 번이나 보내고 악마를 조종하는,
그야말로 혼돈을 부르는 자다!

셰인
그래서 원흉을 없애버리기 위해
동쪽 황야로 간다고 할아버지가 말하셨어요.

레이나
그건 알겠는데... 왜 하필 동쪽이지?

돈키호테
물론 바람이 동쪽에서 불기 때문이다!
기사의 신이 날 이끌고 있다! 우물쭈물할 시간 없다!

레이나
진짜 어디까지가 진짜인 거지?

엑스
아마도 다 진짜일거야.
지금도 그때도 우리들을 도우려고 했었잖아.

엑스
레이나가 무슨 말 하는지는 알겠는데...
저 사람은 카오스 텔러는 아닌 것 같아.
그러니까 좀 믿어 보고 싶은데...

레이나
너 의외로 고집 세구나?
알았어, 당분간은 상황를 지켜보자.
그러다보면 알 수 있겠지.
※오타 아님

== 마녀의 황야

엑스
이 황야에도 빌런들이! 정말 마법사가 있는 걸까?!

타오
와우, 제법인데! 할아버지, 감이 꽤 좋은데!

돈키호테
이 정도 쯤이야 정의의 기사라면 당연한 거다!
덤벼라! 마법사의 똘마니들아!
이 방랑 기사님이 상대해 주마!

셰인
...솔직히 별로 상관은 없는 일인데요 할아버지,
별명 너무 많은 거 아닌가요.

레이나
투덜 거리고 있을 때가 아니야! 놈들이 온다!

***
*전투*

돈키호테
하앗... 하아앗!!

빌런
크르... 크르르르...

타오
어라? 할아버지, 꽤 하는데? 의외로 실력 좋잖아!

셰인
무모함이 무적의 공격이 되기도 하니까요.
어쩌면 이대로 돌파할 수 있을지도 모르겠습니다.

돈키호테
이대로 마법사 있는 곳까지 돌파한다! 터업...윽!

엑스
돈키호테씨?! 왜 그래요?

돈키호테
허, 허리에 악마의 일격이...

엑스
또 허리 삔 거예요?!

셰인
빌런들이 후퇴하고 있어요.
어쩌죠? 할아버지에게 회복 마법 쓰고 뒤쫓아갈까요?

레이나
지금 마법을 걸어도 어차피 또 재발할거야.
일단 물러나서 마을로 돌아가자.

돈키호테
으으... 이 돈키호테님이... 말도 안 되는 실패를...

엑스
얼른 제 어깨 잡으세요. 마을로 돌아갑니다. 알겠죠?

레이나
너... 정말로 수발 하나는 잘 드는 구나.

== 해안가의 마을

돈키호테
큭... 기사인 내가... 하인의 어깨를 빌리다니...
에잇, 산초! 날 늙은이 취급하지 마라...!

엑스
네네, 알겠습니다. 산초든 손초든 뭐든 좋습니다.
자자, 마을에 도착했습니다.

????
어머, 돈키호테님. 몸이... 무슨 일이 있으셨나요?

돈키호테
이게, 누구야, 내 사랑하는 공주!
성녀 둘시네아님, 평안하...

돈키호테
에고, 악마 녀석들이 좀 애를 먹여서...
뭐, 생채기 정도이옵니다.

둘시네아
너무 무리하지 말아 주세요.
저는 늘 돈키호테님이 무사하게 돌아오시길
기도드리고 있답니다. 이쪽은 친구분들이신가요?

돈키호테
아닙니다. 기사란 고독한 몸이옵니다.
평생의 친구는 그리 쉽게 만드는 게 아니옵니다.
이들은 모두 제 하인들이옵니다.

둘시네아
그렇군요... 여러분, 돈키호테님을 잘 부탁드립니다.

둘시네아
돈키호테님의 활약 덕분에 마을 분들 모두가
안심하고 지내고 있답니다.

둘시네아
그럼, 전 이만...

셰인
와~ 아름다운 분이시네요.
할아버지를 신뢰하고 있는 것 같더군요.

돈키호테
이렇게 여유부리고 있을 순 없지. 빨리 출발해야 해.

레이나
잠깐만요! 아직 허리가 안 나았...!

돈키호테
무슨 말을 하느냐! 공주님의 기대를 저버릴 순 없다.
무엇보다 백성들을 불안에 떨게 할 순 없지.
마법사를 없애야 한다! 그것이 기사의 도리다!

엑스
...알겠습니다. 우리들도 같이 가겠습니다.

타오
거짓말도 우기면 진실이 된다는 거군.
아가씨도 그만 포기해. 이 할아버지는 똥고집이야.

레이나
...할 수 없네. 일단 지금은 빌런들 정찰 정도만 해요.
무턱대고 덤비지 않는 걸로, 알겠죠?

***
*전투*

돈키호테
아직도 마법사의 단서를 못 찾은 건가...

엑스
지금 셰인이랑 친구들이 먼 곳으로 정찰 갔어요.
이제 돌아올 시간인데...

???? ※로키
어라? 혹시 거기에 계신 분은
그 유명한 돈키호테님 아니십니까?

돈키호테
그렇다! 내가 라 만차의 기사 돈키호테다!
처음 보는 얼굴인데. 당신은 이 마을 사람인가?

????
아닙니다. 저는 여기저기를 떠돌아다니는
하찮은 음유시인이옵니다.
옆에 계신 분은 소문의 산초님이십니까?

엑스
...무슨 소문을 들었는지 모르지만
저는 산초가 아니라 엑스입니다.
돈키호테씨의 들러리라고나 할까...

돈키호테
그건 또 무슨 망발이냐!
음유시인, 미안하네. 이 산초는 착한데 머리가 좀...

엑스
아하하...

????
역시, 소문대로 유쾌한 분들이시군요.
요즘 악마들이 날뛰어서 마을이 불안에 떨고 있습니다.
여러분들의 활약을 기대하고 있습니다.

????
언젠가 여러분들의 모험담을 꼭 들려주십시오.
그럼 전 이만.

엑스
정말 유명한가 보네요. 돈키호테씨도 산초 씨도...
그런데 왜 그러시죠?

돈키호테
마을 분위기가 심상치 않다...

레이나
엑스! 돈키호테!

엑스
다들... 안색이 왜 그래?

셰인
큰일났습니다!
지금 이 마을로... 빌런의 군대가 쳐들어 오고 있습니다!

***

엑스
[그걸] 발견한 건 정찰 나간 마을의 경비병들이었다.

엑스
마을을 침공하는 빌런들은 약 500마리.
그 중에는 메가 빌런도 있었다고 한다.

엑스
빌런의 침공 소식이 이미 마을 전체에 퍼졌다.
지금까지 악마의 존재를 믿고 있지 않던 마을 사람들도
소식을 전해들은 순간 공포의 도가니에 빠졌다.

슬퍼하는 부인
악마가 진짜 있다니... 이제 우리 어떻게 하지...

비관하는 남자
싸워야지... 하지만 500마리나...
마을에 있는 남자는 경비병까지 300명도 안 되는데...

*

레이나
다들 불안해하고 있네...

타오
어쩔 수 없어. 이건 이미 전쟁통 수준이야.
빌런보다도 지금은 마을 사람들의 패닉 상태가 더 위험해.

셰인
어떻게 해야할까요?
뛰어난 사령관이 있으면 좀더 진정이 될텐데...

엑스
마을의 높은 사람에게 얘기를 해 보자.
모두의 안전을 확보하고 나서 우리들끼리 빌런 토벌을...

돈키호테
그럴 필요 없다.

돈키호테
후~~~~~~읍

돈키호테
진정해라아아아아아아!
모두우우우우우우우우우!

놀라는 아이
엉? 거짓말쟁이 할아버지?

돈키호테
나는 자랑스런 라 만차의 기사, 사자의 기사 돈키호테다!
다들 두려워 하지 마라!

돈키호테
이 마을에는 나처럼 눈부신 기사가 있다!
나야말로 그대들의 희망이다! 나야말로 그대들의 빛이다!
악마를 두려워 하지 마라!

돈키호테
돈키호테를 잊지 마라!
그대들에게 승리와 평화를 가져다 주겠다고 약속하겠다!

마을 사람들
...오, 오옷! 우오오오오오오오오오!!

엑스
대단하다... 마을 사람들이 불안을 떨쳐냈어!

레이나
...과연 고결한 기사님이셔.
자, 갑시다, 저 사람의 거짓말을 진실로 바꾸기 위해서!!

***
*전투*

엑스
메가 빌런은 격퇴되었으며
빌런들도 개미처럼 뿔뿔이 흩어지더니 사라져 버렸다.

엑스
싸움에서 이기고 돌아온 돈키호테씨와 우리들을
마을 사람들은 열광적으로 환영해 주었다.
그리고 그날 밤 축하연회가 벌어졌다

*

엑스
모두들 신나게 즐기고 있구나.
으~음, 난 열 좀 식히고 나서 돌아갈까...

????
안녕하세요.
이런 곳에 혼자 계셨군요, 산초 씨.

엑스
당신은 전에 만났던 음유시인님...?
아, 저는 밤바람을 좀 쐬고 있었어요.
음유시인님이야말로 왜 여기에?

????
당신과 이야기를 하고 싶었습니다.
엄청난 활약이었다고 들었습니다.

엑스
아니에요, 제가 무슨...
다 돈키호테씨의 덕분이죠.

????
무슨 말씀을.
저 불쌍한 노인은 자신의 역할을 충실히 연기했을 뿐입니다.
자신의 [운명의 서]에 얽매여 있을 뿐인거죠.

엑스
...무슨 얘기를 하고 싶은 거죠?

????
딱히 없어요. 단지 하나 물어보고 싶었을 뿐입니다.
당신들의 싸움엔, 무슨 의미가 있습니까?
이 세상에 지킬만한 가치가 있습니까?

????
스토리 텔러가 만들어내는 운명과
카오스 텔러가 만들어내는 악몽.
이 두 가지에 대체 어떤 차이가 있습니까?

엑스
의미가 없다? 그럴 리가 없잖아요!
아니, 잠시만요, 당신이 어떻게 카오스 텔러를...

레이나
엑스! 여기 있었네?

엑스
레이나, 마침 잘 왔어! 지금 이 사람이 카오스 텔러에 대해...!

엑스
응? 어디 갔지?

레이나
엑스, 정신 놓고 있을 때가 아냐.
잘 들어. 돈키호테가 사라졌어.

엑스
뭐? 왜?

레이나
나도 몰라. 지금 난리도 아냐. 갑자기 남쪽으로 급하게 갔대.
우리들도 빨리 뒤쫓아가자.

엑스
알았어!

== 산기슭의 숲

돈키호테
......여기까지 쫓아올 줄이야. 과연 내 부하들이군.

레이나
마을을 구한 기사님이 이런 숲에서 뭘 하고 있는 거죠?
우리들을 내 팽개치고.

돈키호테
둘시네아님이 사라지셔서 찾으러 온 것이다.
혹시 그 분에게 무슨 일이 일어났을지도 몰라.

셰인
그 아름다운 사람이?
그러고 보니까 축하연에서도 안 보였어요.
하지만 왜 이 숲에?

돈키호테
기사의 촉이 여기라고 말하고 있어.
그 분은 여기에 계실거다. 틀림없어.

타오
엄청난 자신감이군. 그저 그런 거짓말쟁이는 아닌 것 같지만.
아니, 그런데 없어진 거 정도로 너무 호들갑 떠는 거 아냐?

돈키호테
기사는 거짓말 안 한다! 내 명예를 걸고 절대로 안 한다!

돈키호테
그 분이 내 앞에서 갑자기 사라지시다니 말도 안 된다...
있을 수 없는 일이다... 뭔가 안 좋은 일이! 쿨럭 쿨럭...!

엑스
갑자기 소리 지르면 몸에 안 좋아요!
마을 방위전이 끝나자마자 바로 온 거잖아요.
좀 적당히 하세요...!

돈키호테
무슨 말을 하느냐! 하인이 주인인 내게 대들다니!

엑스
당신을 생각해서 말하는 겁니다.
당신은 마을에 필요한 분입니다.
여기서 무슨 일이라도 생기면 어떻게 할 겁니까?

엑스
둘시네아님은 저희가 찾겠습니다.
그러니까 돈키호테씨는 여기서 쉬고 계세요.

돈키호테
...거 참, 어리석군.
멍청하고 착하고 약간 용감한 하인이다.

돈키호테
둘시네아님을... 부탁한다.

엑스
네! 믿어 주세요!

***
*전투*

엑스
찾았다! 둘시네아님!

둘시네아
당신은 돈키호테님과 함께 있던...?

레이나
이런 곳에서 뭘 하고 계세요?
돈키호테도 걱정하고 있어요.

둘시네아
확인할 게 있었습니다. 돈키호테님, 그리고 절 위해서...
당신들에게는 얘기해 두는 편이 좋겠죠?

둘시네아
저, 둘시네아는 실존하는 인물이 아닙니다.
돈키호테님의 망상이 만들어낸...공상일 뿐이죠.

엑스
잠깐만요. 지금 그게 무슨 말입니까?
아니, 마법사는 그렇다 쳐도
당신은 지금 여기에 존재하잖아요...?

둘시네아
그 분의 풍부한 상상력은 현실의 모습까지도
왜곡시키는 힘을 가지고 있습니다.
그 결과로 제가 생겨난 거예요.

둘시네아
그래서 저는 두렵습니다.
어쩌면 지금 이 세계에 나타난 악마도 모두
그 분의 망상에서 태어난 것이 아닐까 하고...

엑스
...둘시네아님, 말씀해 주십시오.
다른 뭔가도 알고 계시는 군요. 그래서 여기로 온 거죠?

둘시네아
예전에 돈키호테님은 이곳 앞의 언덕에 있는
풍차를 거인이라 부르며 싸움을 건 적이 있습니다.

둘시네아
그 때부터였어요. 그 전에는 존재하지 않았던 악마들이
점점 늘어나 마을을 공격하기 시작했습니다.
틀림없이 그 언덕에 비밀이 있을 거예요.

둘시네아
하지만 그 사실을 밝히면...
돈키호테님이 해 오신 일을 부정하는 게 되지 않을까...

돈키호테
그럴 리 없습니다!

둘시네아
돈키호테님!
설마... 어디서부터 들으신 건가요?

돈키호테
내 사랑하는 공주님, 걱정마시옵소서.
무슨 일이 있어도 제 신념을 배신하는 일은 없사옵니다.
그렇습니다, 무슨 일이 있어도.

둘시네아
돈키호테님...

돈키호테
산초, 따라와라! 풍차가 있는 언덕으로 가자!
이제야 말로 이 세계의 악을 박멸할 때가 왔다!

엑스
...네!

== 풍차 언덕

셰인
...바람이 정말 센대요. 평상시보다 더 심합니다.
※오타 아님

타오
저게 그 풍차인가? 크게 이상해 보이지는 않는데...

엑스
\............

== 회상

????
당신들의 싸움, 무슨 의미가 있습니까?
이 세상을 지킬 의미가 있습니까?

????
스토리 텔러가 만들어내는 운명과
카오스 텔러가 만들어내는 악몽.
이 두 가지에 대체 어떤 차이가 있습니까?

== 풍차 언덕

레이나
엑스! 왜 그래? 표정이 무서워.

엑스
...아냐, 신경쓰지 마.
그것보다도 카오스 텔러의 낌새가 느껴져?

레이나
모르겠어... 기척을 숨기고 있는 건지.
아니면 여기에 없는 건지...

돈키호테
윽, 기다리거라!

타오
...핫, 빌런이 줄줄이 기어나오잖아.
왠지 여기가 본거지 같은 예감이 마구 드는데.

셰인
신참 씨, 멍하게 있지마요.
고민하는 건 여길 빠져나가고 나서 하세요.

엑스
그래. 잘 알고 있어!

***
*전투*

돈키호테
산초, 저길 봐라! 언덕 위에 서 있는 공포의 거인을!
이번에야말로 내 창으로 끝장을 내주마!

엑스
저건... 풍차인데요. 자, 잠깐만요, 돈키호테씨!
도대체 무슨 짓 할 생각이에요!

돈키호테
각오해라! 마법으로 몸을 숨긴 거인 놈아! 하이야앗!

셰인
우와...저 할아버지... 풍차로 막 달려드네...
제정신이 아니예요...

레이나
앗, 잠깐! 저건... 저 모습은...!

*

풍차 거인
그르르... 구오오오오오옷!!

타오
서..서...설마... 말도 안돼... 풍차가 거인이 되다니...
이건 꿈이야...

돈키호테
회오리 바람을 일으키다니...!
그 날과 똑같군! 오늘은 꼭 쓰러뜨린다!

레이나
그래... 그런 거였어!
저 풍차가 변한 거인도 둘시네아님처럼
돈키호테가 만들어낸 망상인 거야!

레이나
너무 강하게 구현된 망상에 들러붙은 카오스 텔러.
그 것이 저 풍차 거인의 정체야!

셰인
...세상에...
무슨 일이든 일어날 수 있는 거군요.

*

돈키호테
크어어어어어어억!!

엑스
돈키호테씨?! 정신차리세요!

돈키호테
크으... 내가... 기사인 내가... 이렇게 무너지다니...

돈키호테
엑스... 부탁한다... 저 괴물을 막아라...
기사로서 부디 이 세계를... 지켜라...

엑스
마지막에 이름을 부르다니... 치사해요.
안심하세요. 부탁 하지 않으셔도 그럴 생각이었으니까요.

레이나
어떻게 할거야?

엑스
나도 잘 모르겠어.
하지만 돈키호테 씨의 마음을 부정하고 싶지는 않으니까,
저 풍차의 거인과 싸울 거야!

***
*전투*

둘시네아
돈키호테님... 그리고 여러분...
드디어 악몽에서 깨어나게 해 주셨군요...

돈키호테
둘시네아님, 어떻게 여기에...

둘시네아
돈키호테님도 이미 눈치 채셨을 거예요.
저 역시 망상으로 만들어진 이 세계의 왜곡 중 하나입니다.
있어서는 안되는 존재예요.

레이나
둘시네아님...
지금부터 우리들은 이 세계를 원래대로 되돌릴 겁니다.
그러면 아마 당신도...

둘시네아
...괜찮습니다. 그것이 이 세계의 진정한 모습이라면.
그리고 저는 돈키호테님의 마음 속에
계속 살아 있으니까요. 그렇죠?

돈키호테
...네, 물론입니다. 물론이고말고요.
내 기사도에 맹세하고서라도 반드시 약속은 지키겠습니다.

레이나
자, 그럼. 이제 슬슬...

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라
여기 조율을 시작하오니......​』

*조율 컷씬*

== 바람 부는 초원

돈키호테
음... 나는 지금까지 무엇을...
헉! 그러고보니 거인은?! 마법사는 어떻게 됐지?!

산초
주인님... 또 잠꼬대 같은 망상이십니까? 적당히 좀 하십시오.
주인님한테 휘둘리는 제 입장이 좀 되어 보시라구요.

돈키호테
응? 산초? 너 산초냐?
이상하군, 얼굴이 다른데...
헉! 설마 마법사가 한 짓이냐?!

산초
내 참, 태어났을 때부터 이 얼굴입니다요.
이상한 말 그만하십시오. 출발합니다!

레이나
저 사람이 진짜 산초...
착각한 것 치고는 너무 안 닮았는데...

셰인
하지만 분위기는 비슷한 구석이 있었나 보네요.

타오
의외로 너라면 자기를 상대해 줄 거라고
눈치챈 걸 지도 모르지.
눈치 하난 빨랐어 그 할아버지.

엑스
그거, 전혀 위로나 칭찬처럼 안 들려...
하지만 다행이야. 진짜 산초 씨와 무사히 만난 모양이니.

셰인
혹시 좀 부럽고 그렇습니까?

엑스
...설마. 우리들에게는 우리들의 여행이 있는걸,
그렇지? 레이나.

레이나
물론. 이제 슬슬 떠나볼까.
새로운 카오스 텔러를 [조율]하기 위해서...

*

???? ※로키
또 [조율의 무녀]가 방해했는가.
그러나 그들조차도 진짜 [마법사]가 있다는 사실을
알아차리지는 못한 듯하군...

????
크크크... 나도 서둘러 볼까.
모든 거짓을 혼돈으로 바꾸어,
새로운 카오스 텔러의 싹을 틔우기 위해...
