= 6.2.허무한 수호자가 찾는것 - NAES with Gemini
:hardbreaks:

== 초급 수호자와의 해후 개막 엑스 편

엑스
──『허무의 상구』라고 알아?
스토리텔러가 사라져서,
멸망을 맞이하려 하는 상구를 그렇게 부른대.

엑스
질서나 운명을 이야기하는 자도 없는 세계는
황폐해져 버리고, 사람들은 빌런에 가까운 존재인
할로우 빌런으로 변하고 말아.

엑스
상구에서 상구로 떠도는 여행자들은 때때로,
그런 『허무의 상구』에 길을 잃고 들어가는 일이 있는 모양이야.

엑스
만약 발을 들이면 끝장, 할로우 빌런을 쓰러뜨리고,
스코어를 획득하지 않는 한 상구를 빠져나가는 것은
불가능해. 마치 지금의 우리처럼───

=== 허무의 숲

엑스
이상하네… 다들 어디로 간 거지…
어느샌가 이상한 숲에 들어와 버렸고…

????
환영한다, 운명에 얽매이지 않는 여행자여.
나의 결투 무대에 온 것을…

엑스
……누구냐, 넌!?

????
나는 할로우 가디언…
멸망해 가는 고향에 초대받은, 탐욕스러운 여행자들이여.
나는 너희에게 결투를 신청한다.

할로우 가디언
너희가 자신의 강함을 자부한다면, 나와
싸워 그 모습을 증명하라. 진정 강한 자에게만,
스코어의 칭호가 주어지리라.

할로우 가디언
이곳을 나갈 수 있는 것은 스코어를 높인 강자뿐.
약자는 영원히 허무한 몸이 되어 방황하거라…

엑스
방금 그건 대체 뭐였지…
게다가 스코어의 칭호라니…

레이나
엑스! 여기 있었구나!

엑스
다들!
혹시 다들도
할로우 가디언을 만난 거야?

레이나
그래, 아무래도 귀찮은 일에
말려든 모양이네.

타오
우리뿐만이 아니라, 다른 말려든
녀석들도 있는 모양이더군.

셰인
일단 저 붉은 유령 씨를 쫓아가죠.
이야기는 그다음인 것 같아요.

엑스
알았어, 서두르자!

== 초급 수호자와의 해후 개막 레이나 편

레이나
──『허무의 상구』를 알고 있니?
스토리텔러가 사라져서,
멸망을 맞이하려 하는 상구를 그렇게 불러.

레이나
질서나 운명을 이야기하는 자도 없어진 세계는
황폐해지고, 그곳에 사는 사람들은 빌런에 가까운 존재인
할로우 빌런으로 변하고 말지.

레이나
상구에서 상구로 떠도는 여행자들은 때때로,
그런 『허무의 상구』에 길을 잃고 들어가는 일이 있는 모양이야.

레이나
만약 발을 들이면 끝장, 할로우 빌런을 쓰러뜨리고,
스코어를 획득하지 않는 한 상구를 빠져나가는 것은
불가능해. 정말이지, 웃기지도 않는 이야기지───

=== 허무의 숲

레이나
…리더인 나를 두고 다들 어디로 간
걸까. 정말 협조성이 없다니까.
빨리 찾아내서 합류해야겠어…

????
환영한다, 운명에 얽매이지 않는 여행자여.
나의 결투 무대에 온 것을…

레이나
누구야!?
…카오스 텔러는 아닌 것 같네.

????
나는 할로우 가디언…
멸망해 가는 고향에 초대받은, 탐욕스러운 여행자들이여.
나는 너희에게 결투를 신청한다.

할로우 가디언
너희가 자신의 강함을 자부한다면, 나와
싸워 그 모습을 증명하라. 진정 강한 자에게만,
스코어의 칭호가 주어지리라.

할로우 가디언
이곳을 나갈 수 있는 것은 스코어를 높인 강자뿐.
약자는 영원히 허무한 몸이 되어 방황하거라…

레이나
기다려, 이봐! …가 버렸네.
멸망해 가는 고향… 할로우… 설마 여기,
그 『허무의 상구』인 걸까?

레이나
아무래도 우리 말고도 말려든
여행자가 있는 모양이네… 좋아, 우선 다들과
합류하기 위해서라도 빨리 이동해서───

타오
자─ 스톱, 스톱, 아가씨!

레이나
타오, 셰인!
다행이다, 무사했구나.
…그런데 스톱이라니 뭐야?

타오
아, 아아, 아가씨도 그 유령 녀석을 봤지?
함부로 움직이는 건 위험하다고 생각해서 말이야.
(특히 아가씨가 또 미아가 될까 봐)

셰인
신참 씨의 목소리도 저쪽에서 들렸어요. 다 같이
모이고 나서 저 붉은 유령 씨를 쫓아가죠.
(언니를 혼자 두면, 안 돼. 절대로.)

레이나
알았어.
할로우 가디언이라고 했었나…
우리를 붙잡아 둔 대가는 톡톡히 치르게 될 거야…!

== 초급 수호자와의 해후 개막 타오 편

타오
──『허무의 상구』라고 알고 있나?
스토리텔러가 사라져 버린,
멸망을 맞이하려 하는 상구를 그렇게 부른다더군.

타오
질서나 운명을 이야기하는 자가 사라지면 말이지,
그곳에 사는 녀석들은 빌런에 가까운 존재인
할로우 빌런으로 변해 버린다는 모양이야.

타오
상구에서 상구로 여행하는 자들은 때때로,
이 『허무의 상구』에 길을 잃고 들어가는 일이 있다.
그런 소문이지.

타오
만약 발을 들이면 끝장, 할로우 빌런을 쓰러뜨리고,
스코어를 획득하지 않는 한 상구를 빠져나가는 것은
불가능하다더군. 남자라면 할 수밖에 없겠지?───

=== 허무의 숲

타오
아가씨───!
셰인───!
꼬맹아───! 있으면 대답해라───!

타오
안 되겠군, 대답이 없어.
어쩔 수 없지. 여기서는 목소리를 더 높여서…
하나 둘, 흐으으으으읍……… 엇

????
환영한다, 운명에 얽매이지 않는 여행자여.
나의 결투 무대에 온 것을…

타오
우오오옷!?
갑자기 뭐야! 깜짝 놀라게 하지 마!!
응? 누구냐, 네놈은?

????
나는 할로우 가디언…
멸망해 가는 고향에 초대받은, 탐욕스러운 여행자들이여.
나는 너희에게 결투를 신청한다.

할로우 가디언
너희가 자신의 강함을 자부한다면, 나와
싸워 그 모습을 증명하라. 진정 강한 자에게만,
스코어의 칭호가 주어지리라.

할로우 가디언
이곳을 나갈 수 있는 것은 스코어를 높인 강자뿐.
약자는 영원히 허무한 몸이 되어 방황하거라…

타오
할로우 가디언? 스코어의 칭호?
무슨 소릴 하는 거야, 저 녀석.
…그나저나 의외로 몸매가 끝내주는데.

타오
결투인가. 싸움도 물론 나쁘지 않지만,
혹시 모르지, 밤의 결투를 신청해 보는 것도…

셰인
지이이이이익

타오
………셰인, 너 언제부터 거기 있었냐?

셰인
「우오오오오오오오! 할로우 쨩!
할로우 쨩, 낼름낼름낼름낼름!!」
하던 부분부터였을까요, 이 변태동자.

타오
그런 적 없어! 변태동자라고 하지 마!
…아─ 뭐냐.
일단 너도 상황은 파악하고 있는 모양이군?

셰인
물론이죠. 셰인 일행 말고도
말려든 여행자분이 있는 모양이에요.
언니랑 신참 씨하고도 빨리 합류하죠.

타오
좋아, 전원 모인 김에 가 볼까.
타오 패밀리의 싸움 축제, 특별편이다!

== 초급 수호자와의 해후 개막 셰인 편

셰인
──『허무의 상구』를 알고 계시나요?
스토리텔러가 사라진,
멸망을 맞이하려 하는 상구를 그렇게 부른다고 해요.

셰인
질서나 운명을 이야기하는 자도 없어지면,
그곳에 사는 녀석들은 빌런에 가까운 존재인
할로우 빌런으로 변해 버린다고 하더라고요.

셰인
상구에서 상구로 여행하는 자들은 때때로,
이 『허무의 상구』에 길을 잃고 들어가는 일이 있다.
그런 소문이 있는 모양이에요. 오오, 무서워라.

셰인
만약 발을 들이면 끝장, 할로우 빌런을 쓰러뜨리고,
스코어를 획득하지 않는 한 상구를 빠져나가는 것은
불가능하다던가. 정말 민폐라니까요───

=== 허무의 숲

셰인
…자, 시작하자마자 외톨이가 되어 버렸습니다만,
이건 대체 어떤 상황인 걸까요.

셰인
언니는 평소처럼 미아가 된 거라 쳐도,
타오 오빠랑 신참 씨까지 없는 건,
아무래도 비상사태 같네요…

셰인
아, 실례합니다, 거기 계신 분.
이 근처에서 엑스트라 같은 소년이랑 시끄러운 동자랑
허당 공주님 못 보셨나요?

????
나는 할로우 가디언…
멸망해 가는 고향에 초대받은, 탐욕스러운 여행자들이여.
나는 너희에게 결투를 신청한다.

셰인
오호라, 남의 말은 안 듣는 스타일인가요.
그렇군요.

할로우 가디언
너희가 자신의 강함을 자부한다면, 나와
싸워 그 모습을 증명하라. 진정 강한 자에게만,
스코어의 칭호가 주어지리라.

할로우 가디언
이곳을 나갈 수 있는 것은 스코어를 높인 강자뿐.
약자는 영원히 허무한 몸이 되어 방황하거라…

셰인
하아, 이거 생각보다 귀찮은 상황인 것 같네요.
…아무래도 셰인 일행 말고도 말려든
사람이 있는 모양인데. 자자, 어쩌면 좋을지.

타오의 목소리
아가씨───!
셰인───!
꼬맹아───! 있으면 대답해라───!

셰인
일단 시끄러운 동자는 발견했네요.
신참 씨랑 언니도 근처에 있을 것 같고요.
우선은 다들과 합류부터 할까요.

***

셰인
여러분, 다 모였네요. 스코어의 칭호인지
뭔지는 모르겠지만, 일단 지금은
저 붉은 유령 씨를 쫓아가기로 해요.

== 초급 수호자와의 해후 종막 엑스 편
=== 허무의 숲

할로우 가디언
더 보여라, 강한 자여.
더욱 너희의 힘을 내게 증명하라…

엑스
───할로우 가디언을 놓쳐 버린
우리는 두 팀으로 나뉘어 추적을 계속하게 된다.

엑스
나는 우선 레이나와 콤비를 이뤄,
할로우 가디언의 뒤를
쫓기 시작했는데…───

***

엑스
저 할로우 가디언을 『조율』할 수는
없는 거야?

레이나
카오스 텔러가 아니니까 무리야.
이제 이 상구에 스토리텔러는 없어.
누구도 원래대로 되돌릴 수 없는 거야…

엑스
이 상구의 스토리텔러는
어디로 가 버린 걸까?

레이나
모르겠어. 수명이 다해 소멸한 건지,
아니면 어딘가로 떠나 버린 건지.

레이나
생각해 봤자 소용없어. 지금은 어쨌든
저 할로우 가디언을 찾는 게 우선이야.
가자, 엑스.

엑스
아, 기다려, 레이나!
──응?

엑스
뭔가 발밑에 떨어져 있어… 이건 메달인가?
누구 건지는 모르겠지만,
일단 주워 둘까.

== 초급 수호자와의 해후 종막 레이나 편
=== 허무의 숲

할로우 가디언
더 보여라, 강한 자여.
더욱 너희의 힘을 내게 증명하라…

레이나
───신출귀몰한 할로우 가디언을 쫓기 위해
우리는 두 팀으로 나뉘어 행동하게 되었다.

레이나
우선 엑스와 팀을 이뤄, 어딘가로 사라진
할로우 가디언의 뒤를 쫓는 우리.
자, 대체 어디부터 찾아야 할까───

***

레이나
으음, 으음으음…

엑스
레이나, 끙끙 앓으면서 괜찮아?
혹시 어디 아픈 거야?

레이나
아니야, 지금 할로우 가디언의 행방을
추리하고 있는 거야. 정말로 강한 사람은 말이지,
완력이 아니라 머리를 쓰는 법이니까.

엑스
머리를 쓴다고?

레이나
할로우 가디언의 목적은 강한 인간과 싸우는 것.
적은 쌍검을 써서 공격해… 분명 더 싸우기 편한
장소로 이동하고 싶을 거야…

레이나
싸우기 편한 곳을 고른다면 주위에 차폐물이 없는 장소…

레이나
그렇다면 이동한다면 이런 숲이 아니라…
그래! 초원이야! 분명 초원으로 이동해서───

엑스
레이나! 저기 있던 여행자분한테 물어보고 왔어!
할로우 가디언, 황야 쪽으로 향했대!
레이나 말대로 머리를 써 볼 일이네!

레이나
내 활약을 가로채지 마!

== 초급 수호자와의 해후 종막 타오 편
=== 허무의 숲

할로우 가디언
더 보여라, 강한 자여.
더욱 너희의 힘을 내게 증명하라…

타오
───나타났다 사라지기를 반복하는 유령 녀석을
쫓기 위해, 우리는 두 팀으로 나뉘게 되었다.

타오
우선 나는 셰인과 팀을 이뤄 녀석의 뒤를
쫓았지만, 그나저나 어디로 가 버린 건지 원.
그 유령 녀석은…───

***

타오
나 원 참, 도망치는 발 하나는 빠르구먼.
대체 어디로 사라진 거야…

셰인
그리 멀리는 가지 않았을 거예요.
도망치는 게 목적도 아닌 것 같고,
금방 찾을 수 있을 겁니다.

셰인
오히려 걱정되는 건 언니 쪽인데…

타오
그쪽이야말로 괜찮겠지.
꼬맹이가 붙어 있으니까.

셰인
…타오 오빠는 꽤나 신참 씨를
아끼시는 모양이네요.

타오
처음으로 생긴 동생뻘이니까 말이야. 그야 귀여울 수밖에
없지. 우리 멤버 치고는 제대로 됐고,
저래 봬도 의외로 근성도 있거든.

타오
너도 이제 슬슬 신참 취급은 그만둬라.
그 녀석, 은근히 신경 쓰는 모양이라고.

셰인
…신참 씨는 신참 씨예요.
신참 씨가 아니게 됐을 때 생각해 보죠.
자, 서둘러요, 타오 오빠.

타오
…뭐, 동생 아끼는 방법은 제각각인가.
내가 참견할 일도 아니지.
──응? 뭘 밟았나?

타오
이건 메달인가? 왜 이런 곳에…
뭐, 됐어. 감사히 주워 가도록 할까.

== 초급 수호자와의 해후 종막 셰인 편
=== 허무의 숲

할로우 가디언
더 보여라, 강한 자여.
더욱 너희의 힘을 내게 증명하라…

셰인
───그렇게 해서 시작된, 붉은 유령 씨와
셰인 일행의 술래잡기.

셰인
일단 도망친 붉은 유령 씨를 쫓기 위해,
셰인 일행은 두 팀으로 나뉩니다.
우선 타오 오빠와 팀을 이뤄 근처를 탐색합니다만…───

***

타오
그 유령 녀석, 어디로 간 거야.
아직 승부는 나지 않았는데.

셰인
여전하시네요, 타오 오빠는 이런 싸움질
정말 좋아하신다니까요. 저기요, 셰인은 이런
분위기 서툴거든요…

타오
아, 그러고 보니 셰인. 너 이거 줄게.
방금 주운 건데 말이야─.

셰인
…이거, 금메달인가요?

타오
오우, 내 생각에 이건 그 유령 녀석이
흘린 게 아닌가 싶은 기분이 들어서 말이지.

셰인
그 붉은 유령 씨가요.

타오
옛날에 들은 소문인데, 할로우 빌런이라는 건
자신이 인정한 녀석에게 보물을 건네주는 일이
종종 있다더군.

셰인
합시다, 찾읍시다, 싸웁시다.
메달을 팍팍 벌어 보자고요.
목표는 일확천금입니다.

타오
…넌 알기 어려운 것 같으면서도,
참 알기 쉬운 성격이란 말이지.

== 중급 수호자의 추적 개막 엑스 편
=== 허무의 황야

엑스
다른 여행자들 말로는 이 근처에
할로우 가디언이 나타난 모양이야.
타오랑 셰인 일행도 왔을 텐데, 어디 있지?

레이나
우선 저 할로우 가디언에 대해서
정보를 정리해 보자.

레이나
방금 전 전투에서 눈치챘는데, 아무래도
할로우 가디언은 마법 공격과 빛 속성 공격에
약한 모양이야.

엑스
그런 것 같네. 약점을 찌르면 얻는 스코어도
높아지는 것 같고, 그 밖에도 여러 가지 싸우는 법을
시험해 보는 게 좋을지도 몰라.

레이나
그렇긴 한데, 정작 중요한 할로우 가디언을
찾을 수가 없으니 원…

타오의 목소리
아, 네놈, 이봐!
유령 녀석, 거기 서라!

레이나
방금 건 타오의 목소리!?

엑스
할로우 가디언이 나타난 거야!
서두르자, 레이나!

== 중급 수호자의 추적 개막 레이나 편
=== 허무의 황야

레이나
다들 모였네. 그럼 다시 한번,
할로우 가디언에 대해 확인을 하겠어.

레이나
할로우 가디언의 약점은 마법 공격과
빛 속성 공격. 이 약점을 찌름으로써 얻을 수 있는
스코어도 높아진다… 이 견해에 틀림없겠지.

타오
그래, 그 밖에도 여러 가지 싸우는 법을 시험하면,
얻는 스코어가 높아지는 모양이야.
조심해, 유령 녀석은 이제 바로 근처에 있어.

레이나
간다, 다들.
『조율의 무녀』 일행으로서,
지고 있을 수만은 없으니까!

== 중급 수호자의 추적 개막 타오 편
=== 허무의 황야

셰인
이 황야에 저 유령 씨가 있는 모양이네요.
신참 씨랑 언니도 벌써 도착했을 즈음이라고
생각합니다만.

타오
…그나저나 셰인, 눈치챘냐?
그 유령 녀석의 약점.

셰인
물론이죠. 빛 속성 공격이랑 마법 공격이
약점인 것 같아요. 약점을 찌르면 더
많은 스코어를 얻을 수 있는 모양이고요.

셰인
그 밖에도 싸우는 방식의 조건에 따라 받는 스코어는
달라지는 것 같지만요. 이건 여러 가지 시도해 볼
수밖에 없겠네요.

타오
그렇지. 그 정도만 알고 있으면 충분해…

타오
아, 네놈, 이봐!
유령 녀석, 거기 서라!

​ +
타오 오빠, 저쪽에서 언니랑 신참 씨가
달려오고 있어요. 일단 합류하고 나서,
다시 쫓아가기로 해요.
※아마 이름 누락은 공식의 실수

타오
…어쩔 수 없군.
방금 이야기를 아가씨들한테도 전하고,
녀석을 전력으로 때려눕히자고!

== 중급 수호자의 추적 개막 셰인 편
=== 허무의 황야

엑스
할로우 가디언의 약점은
빛 속성 공격이랑 마법 공격이었지.
그 밖에는 어떤 싸우는 법이 유효할까.

레이나
그건 여러 가지 시도해 보는 수밖에 없겠네.
빈틈을 노리는 듯한 공격을 하면 스코어가 높아지는
모양이지만…

타오
뭐, 요컨대 날려 버리면 되는 거야.
날려 버리면.

셰인
어쨌든 몇 번이고 도전해 보는 수밖에 없겠네요.
시행착오의 정신으로 가자고요.

== 중급 수호자의 추적 종막 엑스 편
=== 허무의 황야

엑스
이번엔 타오랑 수색인가.
그러고 보니 지금까지 둘만 있게 된 적은
별로 없었네.

타오
그러고 보니 그렇군.
야, 꼬맹아. 좋은 기회다. 이참에
물어보고 싶은 게 있는데 말이야.

엑스
뭔데?

타오
저 할로우 가디언이라는 녀석,
그 차림새로 봐서 생전에는 상당한
미인 누님이었을 거라 생각하는데, 어때?

엑스
에, 신경 쓰이는 게 고작 그거야?

타오
바보 자식! 남자한테는 중요한 문제라고!
솔직히 「어, 의외로 스타일 좋은데」라고,
조금은 생각했지, 너도!

엑스
적당히 좀 해, 타오!
지금 우리는 위험에 처해 있단 말이야.
그러니까 여기서 확실히 말해 두겠는데!

엑스
할로우 가디언이랑 싸우는 동안,
사실 조금 두근거렸습니다.

타오
좋아, 좀 더 자세히 이야기해 볼까, 동지여.

== 중급 수호자의 추적 종막 레이나 편
=== 허무의 황야

레이나
또 할로우 가디언을 놓쳐 버렸네…
이 술래잡기는 언제까지 계속되는 걸까…
너도 그렇게 생각하지, 셰인?

셰인
완전요. 이제 귀찮기도 하고요, 언니.
평소의 그거 있잖아요, 슥삭 하고 해서
팍 하고 끝내 버려 주세요.

레이나
내 『조율』의 힘을 그런 잡스러운 표현으로 말하지 마!
저 녀석은 카오스 텔러가 아니라 할로우 빌런,
내 힘은 통하지 않는단 말이야.

레이나
정말이지, 폼이 안 나네. 『조율의 무녀』도
 여기서는 아무런 도움도 안 되고…

셰인
무슨 소릴 하시는 거예요, 언니.
언니는 대단한 사람이에요. 퍼펙트하다고요.
좀 더 자신을 가지세요.

레이나
셰인… 너…

셰인
이렇게 놀려 먹는 맛이 있는 일품 소재가
그리 쉽게 있을 리 없잖아요.

레이나
좋─아, 알았어.
아무래도 너에겐 설교가 필요할 것 같네.

== 중급 수호자의 추적 종막 타오 편
=== 허무의 황야

타오
하지만 그 유령 녀석이 쓰고 있는
쌍검이라는 것도 꽤 나쁘지 않단 말이지.
난 기본적으로 방패를 들 때가 많지만 말이야.

엑스
아아, 쌍검인가…
나도 옛날에 동경해서 연습했던 적이 있었지…

타오
헤에─ 괜찮네.
왜 그만둔 거야?

엑스
응, 목도를 두 자루 쥐고 휘두르면서, 바위를 상대로
칼을 내리치는 수행을 하고 있었는데 말이야.
그랬더니 이웃집 할아버지가 지나가다가,

엑스
「타악기 연습하니?」라고 하셨어.

타오
타악기.

엑스
목도가 타악기 스틱으로 보였나 봐.

타오
스틱.

엑스
그 한마디에 난 단번에 꿈에서 깼지.
그 이후로 쌍검을 볼 때마다
그때의 애절한 기분이 되살아나서…

타오
이제 됐어, 말하지 마.
넌 충분히 노력했다.
어쨌든 저 유령 녀석이나 찾자, 어?

엑스
응…

== 중급 수호자의 추적 종막 셰인 편
=== 허무의 황야

셰인
그러고 보니 언니.
저 붉은 유령 씨 말이에요,
역시 원래는 여성이었을까요?

레이나
반대로 저 모습에 남자라면 기겁하겠지만.
갑자기 왜 그래?

셰인
아니, 뭐랄까, 저 붉은 유령 씨,
차림새가 너무 섹시한 거 아닌가 싶어서요.
언니는 어떻게 생각해요?

레이나
어, 그런가…?
저 정도는 별거 아니라고 생각하는데…

셰인
무르시네요. 언니는 위기감이 부족해요.
남자는 대개 멍청해서 저런 섹시한 거에
홀랑 속아 넘어간단 말이에요.

셰인
방심하고 있다간 타오 패밀리에
부족한 섹시 담당 요원으로서
저 붉은 유령 씨가 합류할 위험성이───

레이나
그럴 리가 없잖아, 뭔 걱정이야!

레이나
…그나저나 섹시 담당 요원이 부족하다면
우리는 무슨 담당 요원인데?
뭐, 나는 리더 담당으로서───

셰인
셰인은 참모 담당,
언니는 마스코트 담당이에요.

레이나
누가 마스코트야, 이 보케 담당아.

== 상급 수호자의 의지 개막 엑스 편
=== 허무의 거리

엑스
『허무의 상구』에도 이런 거리가 있구나.
할로우 가디언도 그렇게 되기 전에는 이 거리에
살고 있었을까…

타오
글쎄다.
그보다 감상에 젖는 것도 좋지만,
지금 그럴 때가 아닌 것 같은데?

엑스
…이런 곳에도 빌런이 나타나다니.
이것도 할로우 가디언이?

타오
뭐든 상관없어.
덤벼온다면 날려 버릴 뿐이지.
…오호라, 마침 타이밍 좋게 가세도 온 모양이군.

레이나
타오! 엑스!
괜찮아!?

엑스
다들 모였네.
가자, 할로우 가디언은
이 안쪽에 있을 거야!

== 상급 수호자의 의지 개막 레이나 편
=== 허무의 거리

레이나
의외로 이런 거리 풍경도 남아 있네.
이런 상황만 아니었으면 천천히
둘러보고 싶었지만…

셰인
기분은 알겠지만요,
완전히 그럴 때가 아니네요.
언니, 저길 보세요.

***

엑스
…이런 곳에도 빌런이 나타나다니.
이것도 할로우 가디언이?

***

셰인
타오 오빠랑 신참 씨네요.
저 붉은 유령 씨, 아무래도 이 근처에
있는 건 틀림없는 것 같아요.

레이나
정말이지, 쉴 새 없이 몰아치네.
서두르자, 셰인!

== 상급 수호자의 의지 개막 타오 편
=== 허무의 거리

타오
젠장, 그 유령 녀석은 어디 있는 거야.
빌런들뿐이라 정말 끝이 없구먼.

레이나
합류하자마자 이런 꼴을 당하다니 말이야.
어쨌든 이 빌런들을 쓰러뜨리자.
할로우 가디언은 이 근처에 있을 거야!

셰인
투덜거려 봤자 소용없어요, 타오 오빠.
이런 건 셰인 일행에게 일상다반사잖아요.

엑스
어쨌든 이 빌런 군단을 돌파하는 거야!
그러면 분명 활로도 열릴 거야!

타오
알고 있다고, 빌어먹을.
귀찮게 한 만큼 확실하게 저 유령 녀석한테
돌려주겠어. 기다려라!

== 상급 수호자의 의지 개막 셰인 편
=== 허무의 거리

셰인
꽤나 훌륭한 건물들이 이어져 있네요.
보물이 잔뜩 잠들어 있을 예감이 팍팍
드는데요.

레이나
그런 말 할 때가 아니잖아.
빌런이 이렇게나 많이…!
빨리 두 사람 곁으로 서둘러야 해!

***

타오
기다리다 지쳤다고, 아가씨, 셰인!
이걸로 타오 패밀리 전원 집합이군!

셰인
자, 업무 시간입니다.
이제부터 스코어랑 메달을 잔뜩
벌어 보자고요.

== 상급 수호자의 의지 종막 엑스 편
=== 허무의 거리

셰인
흠흠, 취락의 규모로 보아 옛날에는 아주
큰 거리였던 모양이네요. 이른바 성곽 도시 중
하나였을지도 모르겠어요.

엑스
그렇네. 여기 살던 사람들도
전부 빌런이 되어 버린 걸까…

셰인
스토리텔러가 사라진 상구의
숙명이에요, 신참 씨.
잃어버린 것은 두 번 다시 돌아오지 않죠.

셰인
그래도 분명 지켜야만 하는 것이
있을 거예요. 여기 있던 사람들의 마음이나 의지 같은
것을요. 그렇게 생각하지 않나요, 신참 씨.

엑스
아아, 그래. 네 말이 맞다고 생각해.
그러니까, 셰인. 이것만은 말하게 해 줘.

엑스
거리에서 챙겨 온 보물,
주머니 밖으로 삐져나왔어.

셰인
…신참 씨, 잃어버린 것은 돌아오지 않는 법이에요.
그러니 그렇게 되기 전에 여기 있던 분들을 대신해서
보물을 보호해야 할 의무가 저희에게───

엑스
제자리에 둬.

셰인
넵…

== 상급 수호자의 의지 종막 레이나 편
=== 허무의 거리

타오
이런 걸 고스트 타운이라고 하나.
왠지 기분 나쁘다기보다는
쓸쓸한 기분이 드는 풍경이군.

레이나
어머, 왠지 타오답지 않은 말이네.

타오
나를 그냥 싸움밖에 모르는 바보로 생각하면
곤란하다고, 아가씨. 그 유령 녀석이 어떤 기분
이었을지 잠깐 생각해 본 것뿐이야.

타오
그 녀석도 원래는 인간이었을 거 아냐?
어쩌면 이 상구의 『주역』이었을지도
모르지.

타오
어떤 운명을 가졌는지는 모르겠지만,
어쩌면 아직까지도 자신의 운명에 그 녀석은
얽매여 있는 걸지도 몰라.

레이나
그럴지도 모르겠네. 이제 그걸 알 방법은 남아 있지
않지만. 그래서? 넌 할로우 가디언의
마음인지 뭔지에 어떻게 응해 줄 생각인데?

타오
정해져 있지.
전력 전개로 날려 버린다.

레이나
역시 싸움 바보잖아.

타오
그런 아가씨는?

레이나
정해져 있잖아.
───전력 전개로 날려 버릴 뿐이야.

== 상급 수호자의 의지 종막 타오 편
=== 허무의 거리

타오
일단 이 근처 빌런들은
어느 정도 물리친 모양이군.

레이나
그러게. 하지만 이런 아무도 없는 거리라는 것도
재미있네. …흐음.

타오
…아가씨, 설마 하는 말인데,
이 근처를 탐색해 보자느니 하는 건
생각 안 하고 있겠지?

레이나
응? 아니 아니, 설마.
그냥, 에이, 탐색이라기보다 산책?
잠깐 이 근처를 느긋하게 돌아보는 것도 괜찮겠다 싶어서…

타오
무슨 소리야, 아가씨.
지금이 어떤 상황인지 알고 있는 거야.
그럴 틈은 없다고.

레이나
윽… 그러네, 미안해…
지금은 저 할로우 가디언을 쫓아야만
하니까. 잠깐 들떠서───

타오
아가씨는 길 잃기의 천재니까 말이야.
혼자 산책이라니 너무 위험하다고!
좀 더 자각을 가져 주지 않으면 곤란해, 정말이지.

레이나
타오, 한 대 때려도 될까?

== 상급 수호자의 의지 종막 타오 편
=== 허무의 거리

셰인
오호, 또 메달을 획득했네요.
스코어도 꽤 벌었고, 붉은 유령 씨가 말하는
『강한 자』에 가까워진 게 아닐까요.

엑스
…으음, 근데 『강한 자』라는 건 구체적으로
어떤 사람을 가리키는 걸까. 스코어를 높인 강자만이
이 상구를 탈출할 수 있다고 말하고 있지만.

셰인
그건 다른 사람보다 스코어를 많이 모은 사람, 아니겠
어요. 다른 여행자분들도 말려든
모양이고요.

엑스
그럼 다른 사람보다 스코어를 많이 모으면
상구를 빠져나갈 수 있는 거라면 말이야…

엑스
처음부터 다 같이 협력해서 똑같은 스코어가
되도록 조정해서 싸우면, 전원 1위니까
빨리 이 상구를 나갈 수 있는 거 아냐?

셰인
또 이 승부를 근본부터 뒤엎는
발상을 하시네요, 신참 씨.

엑스
하지만 불가능하진 않잖아?
다른 사람들과 좀 더 서로 협력하면
이 상구를 빠져나가는 것쯤은 간단히───

셰인
결론부터 말하죠.
그 제안은 쓰레기 같다고 생각합니다.

엑스
쓰레기.

셰인
그렇죠. 어차피 그런 짓을 해 봤자
배신하는 사람이 나오게 마련이에요. 게다가
다른 사람한테 뒤처지는 건 절대 사절이고요.

셰인
어차피 이길 거라면 온리 원이 아니라
넘버원입니다. 다 같이 손잡고
사이좋게 골인이라니 넌센스예요.

엑스
…혹시 셰인은 지기 싫어하는 성격이야?

셰인
지는 걸 좋아하는 사람은
세상에 없답니다.

== 최상급 수호자의 소원 개막 엑스 편
=== 허무의 결투장

엑스
할로우 가디언은 이 안쪽에 있어…
분명 이게 마지막 싸움이 되겠지.
다들, 가자…!

***

할로우 가디언
잘 왔다, 강한 자여.
자, 너희의 최고의 검을 보여라.
영웅의 자격을 내게 증명하라.

엑스
할로우 가디언, 이제 이런 일은
끝내는 거야. 우리에겐 완수해야 할
사명이 있으니까.

할로우 가디언
운명을 가지지 못한 여행자에게 어떤 운명이 있다는 것인가.
운명을 말하고 싶다면 자신의 검으로 말하라.
내가 흥미 있는 것은 그것뿐이다.

엑스
그렇다면 여기서 결판을 내겠어!

== 최상급 수호자의 소원 개막 레이나 편
=== 허무의 결투장

레이나
할로우 가디언은 이 안쪽에 있는 모양이네…
분명 이게 마지막 싸움이 될 거야.
다들, 가자!

***

할로우 가디언
잘 왔다, 강한 자여.
자, 너희의 최고의 검을 보여라.
영웅의 자격을 내게 증명하라.

레이나
미안하지만 할로우 가디언, 네
시련에 더 이상 어울려 줄 생각은 없어.
술래잡기도 이걸로 마지막이야.

할로우 가디언
운명을 가지지 못한 여행자에게 어떤 운명이 있다는 것인가.
운명을 말하고 싶다면 자신의 검으로 말하라.
내가 흥미 있는 것은 그것뿐이다.

레이나
말은 잘하네.
그렇다면 마음껏 보여 주겠어.
『조율의 무녀』 일행의 저력을 말이야!

== 최상급 수호자의 소원 개막 타오 편
=== 허무의 결투장

타오
유령 녀석은 이 안쪽에 있는 모양이군…
후딱 결판을 내 주도록 하지 않겠어.
가자, 얘들아!

***

할로우 가디언
잘 왔다, 강한 자여.
자, 너희의 최고의 검을 보여라.
영웅의 자격을 내게 증명하라.

타오
이러쿵저러쿵 귀찮구먼, 당신도.
운명 같은 거에 얽매이지 말고,
솔직하게 싸움을 즐기면 좋을 텐데 말이야.

할로우 가디언
운명을 가지지 못한 여행자에게 어떤 운명이 있다는 것인가.
운명을 말하고 싶다면 자신의 검으로 말하라.
내가 흥미 있는 것은 그것뿐이다.

타오
아─ 알았어, 알았다고. 요컨대 누가 더
강하냐는 이야기지? 좋아, 끝까지 해 보자고.
기분 좋게 성불시켜 주마, 유령 녀석!

== 최상급 수호자의 소원 개막 셰인 편
=== 허무의 결투장

셰인
자자, 저 붉은 유령 씨는 이 안쪽인 것 같네요.
슬슬 스코어 벌이도 질려 가던 참이었어요.
다들, 가는 거예요.

***

할로우 가디언
잘 왔다, 강한 자여.
자, 너희의 최고의 검을 보여라.
영웅의 자격을 내게 증명하라.

셰인
공교롭게도 검보다는 원거리 무기가 취향이라서요.
영웅의 자격이라. 『인도의 책갈피』를 보여 드리는 건
안 될까요?

할로우 가디언
운명을 가지지 못한 여행자에게 어떤 운명이 있다는 것인가.
운명을 말하고 싶다면 자신의 검으로 말하라.
내가 흥미 있는 것은 그것뿐이다.

셰인
붉은 유령 씨, 역시 남의 말은 안 듣는 분 같네요.
뭐, 됐어요. 어차피 여기서 결판을
내는 건 변함없으니까요. 각오하세요.

== 최상급 수호자의 소원 종막 엑스 편
=== 허무의 결투장

할로우 가디언
과거에 나는 이 나라를 지키는 한 명의 여검사였고,
그리고 영웅이었다. 여왕 폐하께 하사받았던
금메달이 그 증표.

할로우 가디언
영웅으로 인정받은 여검사는 이윽고 여왕이 되고,
다음 여검사에게 영웅의 증표인 메달을 수여한다.
그런 운명의 윤회가 이 세계에는 있었다.

할로우 가디언
그 운명의 윤회도 지금은 끊어져 버렸지만…
아직 세계에는 영웅에 걸맞은 강함을 가진 자가
있다는 것을 확인할 수 있었다.

할로우 가디언
그러니 나도 끝을 맺으마.
자신의 운명을 여기서 끝내도록 하겠어…

***

엑스
결국 저 할로우 가디언도,
『허무의 상구』도 사라져 버렸네…
강한 자라고 인정받았다는 뜻일까?

레이나
글쎄. 어쩌면 의외로 그런 건 아무래도 좋고,
운명에 얽매이지 않는 『공백의 서』 소유자들에게
심술을 부리고 싶었을 뿐일지도 모르지.

레이나
…어쩌면 또 그런 상구에 길을 잃고 들어갈
날이 올지도 몰라.

엑스
…응. 분명 그럴지도 모르겠네.

엑스
───앞으로 이야기될 이야기가 있다면,
더 이상 누구에게도 이야기되지 않는 이야기 또한 존재한다.

엑스
이 안개 너머에는 아직 그런 상구가 잔뜩
남겨져 있고, 분명 지금도 다음 여행자가
지나가기를 기다리고 있을지도 몰라.

엑스
우리는 다시 『허무의 상구』에 이끌린다.
이 안개 속을 여행하는 한…───

== 최상급 수호자의 소원 종막 레이나 편
=== 허무의 결투장

할로우 가디언
과거에 나는 이 나라를 지키는 한 명의 여검사였고,
그리고 영웅이었다. 여왕 폐하께 하사받았던
금메달이 그 증표.

할로우 가디언
영웅으로 인정받은 여검사는 이윽고 여왕이 되고,
다음 여검사에게 영웅의 증표인 메달을 수여한다.
그런 운명의 윤회가 이 세계에는 있었다.

할로우 가디언
그 운명의 윤회도 지금은 끊어져 버렸지만…
아직 세계에는 영웅에 걸맞은 강함을 가진 자가
있다는 것을 확인할 수 있었다.

할로우 가디언
그러니 나도 끝을 맺으마.
자신의 운명을 여기서 끝내도록 하겠어…

***

레이나
드디어 끝났네.
정말이지 엄청난 일에 말려들었어.

셰인
의외로 셰인은 즐거웠어요.
보세요, 금메달도 이렇게나 많이 받았잖아요.
이렇게 벌 기회, 분명 또 안 올 거예요.

레이나
…그렇지도 않을 것 같아.

셰인
네?

레이나
확실하게는 말 못 해. 하지만 그런 예감이 들어.
앞으로 우리는 몇 번이고 그런 상구에
발을 들이게 될 거라는 걸 말이야…

레이나
───이야기를 마친 이야기도 있으면, 또 새롭게 이야기되는
이야기도 태어난다. 그런 세계에서 우리는
살아가고 있어.

레이나
그러니 끝났을 터인 이야기가 다시금 우리를
손짓하는 날이 찾아올지도 몰라.
안개 너머에서, 분명히…───

== 최상급 수호자의 소원 종막 타오 편
=== 허무의 결투장

할로우 가디언
과거에 나는 이 나라를 지키는 한 명의 여검사였고,
그리고 영웅이었다. 여왕 폐하께 하사받았던
금메달이 그 증표.

할로우 가디언
영웅으로 인정받은 여검사는 이윽고 여왕이 되고,
다음 여검사에게 영웅의 증표인 메달을 수여한다.
그런 운명의 윤회가 이 세계에는 있었다.

할로우 가디언
그 운명의 윤회도 지금은 끊어져 버렸지만…
아직 세계에는 영웅에 걸맞은 강함을 가진 자가
있다는 것을 확인할 수 있었다.

할로우 가디언
그러니 나도 끝을 맺으마.
자신의 운명을 여기서 끝내도록 하겠어…

***

타오
쳇, 자기 용건만 끝나니까 휑하니 사라지긴.
정말이지 유령이라는 것도 제멋대로구먼.

셰인
그래도 이러니저러니 해도 타오 오빠랑은 뜻이 맞지 않았
나요. 그런 강함을 추구하는 사람, 싫어하지
않잖아요?

타오
좋고 싫고의 문제가 아냐. 미인 누님
이었으면 사이좋게 지내고 싶었겠지만 말이지.
그리고───

셰인
그리고요?

타오
…아니, 아무것도 아냐.

타오
───유령 녀석은 말했다.
이걸로 드디어 자신의 운명을 끝낼 수 있다고.

타오
하지만 정말 그럴까? 자신보다 강한 녀석을
발견하면 뒤를 잇게 하는 게 아니라, 그 녀석보다
강해지고 싶어지는 게 정상이잖아?

타오
아마 또 우리는 유령에게 이끌릴 거다.
이 『허무의 상구』에 발을 들이는 날이
분명 올 거야…───

== 최상급 수호자의 소원 종막 타오 편
=== 허무의 결투장

할로우 가디언
과거에 나는 이 나라를 지키는 한 명의 여검사였고,
그리고 영웅이었다. 여왕 폐하께 하사받았던
금메달이 그 증표.

할로우 가디언
영웅으로 인정받은 여검사는 이윽고 여왕이 되고,
다음 여검사에게 영웅의 증표인 메달을 수여한다.
그런 운명의 윤회가 이 세계에는 있었다.

할로우 가디언
그 운명의 윤회도 지금은 끊어져 버렸지만…
아직 세계에는 영웅에 걸맞은 강함을 가진 자가
있다는 것을 확인할 수 있었다.

할로우 가디언
그러니 나도 끝을 맺으마.
자신의 운명을 여기서 끝내도록 하겠어…

***

셰인
결국 다 같이 손잡고 골인인가요.
왠지 개운치 않은 결말이네요….
붉은 유령 씨는 이걸로 정말 만족했을까요.

엑스
역시 셰인도 할로우 가디언이
신경 쓰였던 거야?

셰인
…딱히 그런 건 아니에요. 이번에는
메달을 잔뜩 받을 수 있었지만,
이런 귀찮은 일은 두 번 다시 사절이에요.

셰인
이제 두 번 다시 망령 씨 따위와는 엮이고 싶지
않네요.

셰인
───그 말에 거짓은 없어요.
귀찮은 일을 싫어하는 건 사실이니까요.
하지만 뭐, 그럴 수도 없는 노릇이죠.

셰인
그야 셰인 일행은 운명에 얽매이지 않는
『공백의 서』 소유자니까.

셰인
바꿔 말하면 앞으로 그런 귀찮은 일에
말려들 기회는 얼마든지 있다는 소리죠.
그러니 분명 또 저 상구에 올 날도…───
