= 6. 알라딘의 상구 - Flero.adoc
:hardbreaks:

....
어느 나라에 알라딘이라는 소년이 있었습니다.
알라딘은 매우 게을러서 일을 하지 않아
항상 엄마를 곤혹스럽게 했습니다.

그러던 어느 날 알라딘은 나쁜 마법사에게 속아
어느 동굴에 갇혔습니다.

좌절하던 알라딘은 동굴 속에서
마법의 램프를 발견했습니다.
알라딘이 우연히 램프를 문지르자
안에서 누군가가 나타났습니다.

그는 알라딘에게 이렇게 말합니다.
「나는 램프의 요정입니다.
당신의 소원을 무엇이든 들어드리지요.」


이렇게 해서 알라딘은 램프의 요정의 마법으로
동굴을 빠져나왔습니다.
그 후 마을로 돌아와 요정의 힘으로
하나 둘 소원을 이뤘습니다. 하지만.......
....
※램프의 요정 지니

== 뜨거운 사막

엑스
지난번에는 설산이더니 이번엔 사막이야?!
너무 극과 극 아냐?

타오
그런 말 하면서 쓸데없이 체력 낭비하지 마.
일단 오아시스나 찾자고.

셰인
언니. 좀만 더 힘내도록 합시다.
화이팅하겠습니다, 화이팅.

레이나
누...누가... 무...무울...
마을 방향이라도 알면...

알라딘
오호라. 물을 원하심까, 아가씨?
그럼 이 물 한 잔 어떠신가요?
천국의 맛을 경험하실 수 있슴다!

엑스
어라, 누구시죠?

알라딘
안녕하심까!
사막 여행 중인 한 마리의 외로운 늑대, 알라딘임다!
반갑습다!

셰인
이상한 녀석이 또 등장했군요.
언니 모른척해요. 척봐도 수상한...?!

레이나
벌컥... 벌컥... 벌컥... 후아!!!
살았다~! 이제야 좀 살 것 같아!

레이나
\......

레이나
고마워. 감사의 인사는 해야지.
그런데 우리들한테 무슨 볼 일이라도 있어?

셰인
한 발 늦었네요.
손도 못 써볼 것 같은데... 어쩌죠?

알라딘
헤헤헤, 고맙긴요!
...컥, 녀석들이 쫓아왔네?!
그럼 뒷처리 좀 부탁합죠!

엑스
뭐가 쫓아 왔다는 거야?
야, 알라딘, 어디 갔...

엑스
빌런!
혹시 우리들 저 알라딘이란 녀석한테 당한 거야?

타오
아무래도 그런 거 같네.
그 애송이... 잽싸게 도망갔어...
어떻게 할까, 아가씨?

레이나
선택지가 없잖아.
빌런을 빨리 해치우고 쫓아가자!
저녀석 가만 안 두겠어!

***
*전투*

알라딘
헤헤, 착해 빠진 녀석들이군.
그보다 아까 그 아가씨 엄청 미인이던데,
혹시 다시 만나면 작업 좀 걸어 봐야 겠...

레이나
호오~ 그럼 이런 건 어떠신지?

알라딘
엣?

타오
와우... 끝내주는데, 아가씨...

셰인
따귀정도면 많이 봐준거죠.
저 밥맛 없는 녀석은 그냥 사막에 묻어버려야 해요.

엑스
그랬다간 죽을거야...

레이나
갑자기 함정을 파두고 덤비다니 한가닥 하는데?
각오해, 지금부터 감사의 인사를 확실하게 해주겠...

알라딘
...아름다워

레이나
응?

알라딘
지금 그 일격...너무 짜릿했슴다!
누님같은 사람 처음 봤어요!
이름! 이름을 알려 주시지 않겠슴까?

레이나
아, 그게, 저기, 레이나인데 왜?

알라딘
레이나씨! 아니다, 레이나 누님! 부탁이 있슴다!
제 주인님이 되어 주세욧!
뭐든지 하겠슴다, 당신의 집사가 되겠습니다요!

알라딘
아, 같이 도시로 가지 않겠어요?
이런 사막 보다는 그 편이 훨씬 좋습죳!
제가 안내하겠슴다! 자, 자자!

레이나
자, 잠깐 기다려...헉?!

셰인
뭡니까, 이 급작스런 전개는...

== 어두운 하늘의 사막

엑스
그럼 알라딘은 그 요술 램프를 획득해서
엄청 부자가 되었다는 거야?

알라딘
정답입니닷!
그런데 황제란 녀석이 내 요술 램프를 뺏는 바람에...
덕분에 빈털털이가 된 채로 사막으로 쫓겨났습니닷!

셰인
그런 무적 아이템을 빼앗겼단 거예요?
잘 한다. 잘 해.

알라딘
어쩔 수 없었슴다!
램프의 요정은 전지전능하지만 욱하는 성질이 있어서
상대의 도발에 말려들고 말았습니다요....

알라딘
아~아~... [운명의 서]대로라면 지금쯤
공주랑 결혼해서 떵떵거리며 잘 살고 있을 텐데.

타오
요술 램프라... 난 흥미 없어.
원하는 게 있으면 스스로 쟁취한다는 타입이라서 말이지.
넌 어때?

엑스
뭐든지 소원을 들어준다라...
난... 흐음...
레이나는 소원 있어?

레이나
글쎄... 난... 뭐든지 다 들어 준다면...
[마법사]를 찾아달라고 하겠어.

엑스
[마법사]?

알라딘
앗! 한 명 알고 있습니다요! 마법사!
황제에게 내 램프를 빼앗아 오라고 한 녀석인데
질이 아주 나쁜 녀석입죠!

레이나
내가 찾는 마법사가 아닐거야.
녀석이 원하는 건 요술 램프가 아니야.

레이나
더 무서운 거야.

엑스
...레이나?

레이나
아, 아무 것도 아냐. 빨리 가자.

***

엑스
에...에... 에에엣취!!
뭐야 이건... 낮이랑 영 다르잖아.

셰인
사막은 저녁이 되면 춥다고 들었습니다.
낮에는 불지옥이고 저녁엔 얼음지옥이지요.
둘 다 지옥이긴 매한가지지만...

알라딘
다들 방한대책 확실히 하십쇼. 진짜 장난 아니니까.
으음? 레이나 누님, 괜찮슴까?

레이나
...응, 괜찮아.

타오
아가씨, 정말 괜찮은거야?
얼굴색이 안 좋은데.

레이나
걱정마... 이 정도로 멈출 순 없지...
서둘러야... 해...

엑스
레이나...?
레이나아! 정신 차려!

*

레이나
하아...하아...

셰인
힘들었나 보네요.
하긴 요즘 쉴 새없이 강행군이었으니.

타오
오늘 밤은 여기서 자야겠다.
저 상태로는 여행 못 해.

레이나
안 돼... 빨리 하아... 빨리 이 상구의
카오스 텔러를 쓰러뜨려야...해.
안 그럼 나는...

엑스
레이나, 잘 들어.
우리들이 쓰러지면 다 소용없어.

알라딘
걱정하지 마십쇼. 그 뭐시기 텔러는 잘 모르지만
우리들이 레이나 누님을 확실히 지켜드릴 테니까!

레이나
아, 알았어. 그럼 좀 쉴게.
아주 잠깐만 좀 자고 일어날게...

레이나
\......

알라딘
저기... 순수한 마음에서 묻는 겁니다만.
레이나 누님은 왜 저렇게 필사적이심까?
그 뭐시기 텔러를 왜 쓰러뜨리려고...?

엑스
그건 카오스 텔러를 그냥 두면 위험하니까.
그래서 레이나는...

타오
그 이유만은 아니야.
아가씨한테는 나름대로 싸우는 이유가 있지.
이쯤 됐으니 얘기해도 되겠지.

타오
아가씨한테 카오스 텔러는 원수야.
자신의 상구가 멸망한 원인이지.

***

엑스
그 날 저녁 타오는 처음부터 끝까지 다 털어놨다.

엑스
왜 레이나가 상구를 여행하게 되었는지.
왜 레이나가 카오스 텔러를 그렇게나 증오하게 되었는지.

== 회상

타오
원래 아가씨는 어떤 상구의 공주였다지 아마.
[공백의 서]의 주인으로 행복하게 살고 있었어.

타오
그런데 어느 날 아가씨가 사는 상구의 스토리 텔러가
카오스 텔러로 변해버렸어.
손 쓸 겨를도 없이 아가씨의 상구는 그냥 폭삭...

== 어두운 하늘의 사막

타오
나도 그 이상은 몰라.
아가씨도 더 이상은 말 안 하더라고.

엑스
그랬구나... 전혀 몰랐네...

셰인
우리들도 그렇게 오래 같이 여행한 게 아니니까요.
누구한테나 속사정은 있는 법이니까.

알라딘
으으... 좋았어, 결정했습니다욧!!
나도 그 뭐시기 텔러라는 녀석을 무찌르는데
한 몫 거들겠슴다!

엑스
알라딘, 네가 거든다고?
카오스 텔러가 뭔지 알고 하는 말이야?

알라딘
아뇨. 그건 잘 모르겠슴다!
하지만 레이나 누님을 아프게 만드는 녀석이라면
절대 용서 못합죳!

셰인
뭐... 의욕 하나는 인정 하겠습니다만.
그렇게 언니를 생각한다면 지금은 간병에 집중해 주세요.

셰인
시끄러운 녀석들이 슬슬 기어나오기 시작했으니.

타오
지금은 회복 담당이 쉬는 중이니까.
다들 안 다치도록 조심해.

엑스
알고 있어!

***
*전투*

엑스
...겨우 끝났네.
타오와 셰인은? 아, 자고 있구나.

알라딘
다들 수고하셨슴다!
과연 레이나 누님의 친구들이심다!
엑스님도 완전 강하신데요!

엑스
난 그저 히어로의 힘을 빌리고 있을 뿐이야.
전혀 내 힘이 아닌걸.

알라딘
그게 무슨 상관임까. 중요한 건
누구의 힘이냐가 아니라 힘을 쓸 수 있을 때,
그 힘을 어떻게 사용하느냐에 달려있슴다.

엑스
힘을 어떻게 사용하느냐?

알라딘
전 요술 램프라는 힘을 제멋대로 마구 쓰다가
요 꼴이 나버렸으니까요.
힘은 올바르게 사용해야 합니다요.

알라딘
사람은 자신의 운명을 거스르면 안됩니다요.
그렇기 때문에 황제가 요술 램프를 가지고 있음 안되죠...
절대로 안됩니닷.

엑스
맞아. 절대로. 꼭 되찾겠어.

*

레이나
...어라?
벌써 아침이야?
분명 나 여기서 쓰러졌다가...

레이나
내가 미쳤나 봐. 이렇게 있으면 안 되는데!
다들 어디에...?

알라딘
쿠울...쿨...

엑스
...쿨...

레이나
...그래. 그렇구나. 날 지켜주고 있었던 거야.
다들 일어나면 출발해야겠어.

레이나
모두들 고마워....

== 사막의 동굴

알라딘
보세요! 오아시스임다!
저 너머의 수원에서 흘러오나 봐욧!
어때요, 제가 말한대로 이 동굴을 지나가길 잘했죠?

레이나
...음. 인정하긴 싫지만 어쩔 수 없네.
여기서 좀 쉬어갈까? 빌런도 없는 것 같고.

엑스
그럼 내가 저쪽가서 물 떠올게.

엑스
으쌰, 이정도면 충분하겠지?
빨리 돌아가야겠다

????
자신이 싸우는 의미가 뭔지 그 답을 찾았나요?
[산초] 씨.

엑스
당신은 돈키호테의 상구에서 만난 그 음유시인...!
어째서, 여기에...?!

????
놀라실 것 없습니다.
당신들도 상구에서 상구로 이동하고 있지 않습니까?
[조율의 무녀]님과 일행분들...

엑스
우리들을 알고 있나요?!
당신, 도대체 정체가 뭐야!

레이나
엑스?
아까부터 누구와 얘기... 어?

????
[공주님] 오랜만에 뵙겠습니다.
아니 지금은 [조율의 무녀]라고 부르는 게 편하시겠죠?

레이나
엑스!
빨리 그 녀석한테서 떨어져!

????
크흣...!

알라딘
왜 그러심까!
무슨 일이... 으왓 괴물들이!

타오
뭐냐, 네놈은...!

셰인
이유는 모르겠지만 위험한 냄새가 가득합니다.

????
크흐흐, 다시 인사드립니다.
나는 로키...
혼돈을 사랑하는 [마법사]입니다!

엑스
[마법사]? 설마 레이나가 말한 녀석이!

레이나
절대로 안 놓칠거야...
저녀석... 저녀석만은...!

***
*전투*

로키
과연 공주님이십니다!
제가 친애하는 카오스 텔러를 쓰러뜨린
[조율의 무녀]와 그 일행답습니다.

엑스
친애하는, 카오스 텔러라고?

레이나
로키는 카오스 텔러를 만들어내는 능력을 가지고 있어.
나는 그걸 직접 본 적이 있어.

엑스
그럼... 레이나의 상구를 멸망시킨 것도...
지금까지의 카오스 텔러도...
전부 저 사람이...?

로키
자 여러분. 더, 더 즐겨봅시다~
제가 사랑하는 이 혼돈과 함께...!

타오
미치겠군... 메가 빌런까지 등장한거냐?
갑자기 왜 이러는 거냐고!

레이나
...로키이!!!

셰인
언니 일단은 진정하시구요.
저 느글느글한 면상,확 엎어버립시다.

***
*전투*

로키
저런... [공주님]은 정말 좋은 친구분들과
인연이 닿으신 것 같습니다.
저 또한 기쁘게 생각하옵니다.

레이나
시끄러워. 네게 들어야 할 것들이 너무 많아.
각오해라!

로키
크흣, 냉정한 척하다가 금방 뜨거워지는 점은
옛날과 똑같으십니다.

로키
그렇게 소중한 것을 놓치는 것까지 그대로군요.

엑스
위험해!

알라딘
헤...헤헤... 아슬아슬 했습니다욧...

엑스
알라딘...! 가슴에서... 피가!

타오
나쁜 자식!

레이나
왜... 왜... 네가...!
마...말하지 마. 내가 마법으로 회복을!

알라딘
하아... 요술 램프 따위 없어도 소원은... 이루어지는 군요...
좋아하는 사람을 지켰어...
추, 충분함다. 이건 제가 선택한 운명...

알라딘
\......

셰인
언니, 안타깝지만 알라딘은...

레이나
마, 말도 안 돼...
그런...!

로키
당신도 알고 있을 겁니다. [조율]로 되돌릴 수 있는 것은
카오스 텔러가 만든 왜곡 뿐이라는 것을.
죽음을 되돌릴 순 없지. 참, 그러고보니...

로키
요술 램프를 사용하면 다시 원점으로 되돌릴 수 있을지도...

엑스
그 입 닥쳐!!!!!!!!!!!!!!!!!!!!!

레이나
...사라졌어?!

로키
도시에서 여러분들을 기다리고 있겠습니다.
[카오스 텔러]가 되신 황제와 함께.
크흐, 크흐흐, 크하하하하하하하!

*

엑스
알라딘은 죽었다.
잠시 우리들은 망연자실한 채
알라딘의 유해를 바라보다가 그를 사막에 묻었다.

엑스
우리들은 아무 말도 하지 않고
다시 도시를 향해 묵묵히 걸어간다.
마음 속에서 로키의 비웃음이 쉼없이 울리고 또 울린다.

== 후회의 사막

레이나
도시까지 얼마나 남았어?

셰인
희미하지만
지평선에 도시 비슷한 게 보이기 시작했습니다.
내일쯤 도착하지 않을까 싶은데요.

타오
아가씨, 긴장 풀어.
또 쓰러질 거야?

레이나
긴장? 긴장 안 하고 있어.
난 그저 [조율의 무녀]로서의 역할에
최선을 다하고 있을 뿐이야. 언제나처럼 말야.

엑스
아, 잠깐, 레이나!

셰인
아까 그 로키라는 사람 말인데요,
안 물어 봐도 됩니까?

타오
지금은 타이밍이 안 좋아.
억지로 들이대서 아가씨의 신뢰를 잃을 순 없지.

타오
지금은 그냥 기다려.
누구에게나 말하고 싶지 않은 과거 정도는 있으니까.

***

레이나
\.....................

엑스
레이나, 잠이 안와?

레이나
아... 좀 생각할 게 있어서.
엑스도?

엑스
나도 그렇지 뭐.

엑스
카오스 텔러의 [조율]에 성공해도
알라딘은 안 돌아온다는 게 진짜야?

레이나
아마도 우리들이 알라딘이라고 부르던 그녀석은 아닐 거야.
알라딘이라는 이름을 가진 누군가가
새로운 [주연]으로 등장하겠지...

엑스
...너무 슬프네. 그럼 우리가 아는 알라딘은
이 상구에서 존재 자체가 완전히 지워져 버리는 거야?!

레이나
그래. 사람의 목숨에 자꾸 연연해하지 마.
상구에서 스토리 텔러는 신같은 존재니까.

레이나
이제 자자.
내일의 결전을 대비해서 말야.

레이나
엑스... 잘 자.

엑스
알라딘. 네 존재가 지워지게 두진 않을 거야.

엑스
요술 램프를 되찾아서 꼭 널 살려 낼 거야.

== 황제의 궁전

타오
소원을 들어준다는 램프의 요정인지 뭔지가
이 궁전에 있다고?

셰인
빨리 해치워버립시다.
저 로키인지 뭔지 하는 놈의 말대로 되도록
둘 순 없으니까요.

로키
크흐흐. 저도 꽤나 미운 털이 박혔나 보군요...

레이나
로키!

로키
결국 당신은 아무 뉘우침도 없이
카오스 텔러의 [조율]을 서슴치 않는 군요.

로키
알고 있습니까?
[조율]을 하면 당신이 만난 알라딘의 존재는
없었던 것이 됩니다.

엑스
없었던 것으로는 안 돼!
우리들이 절대 그렇게 만들지 않아!

레이나
카오스 텔러는 어디지?
요술 램프를 찾아가겠어.

로키
크흐, 진짜 성가신 친구들을 두셨군요.
이번에는 더 이상 어떻게 해 볼 도리가 없을 것 같습니다.

로키
그렇다고 해서 황제를 순순히 내 줄 수는 없으니까요.

타오
잔 말 말고 직접 덤벼라!
비겁하게 빌런들한테 떠 넘기지 말라고!

로키
제가 왜? 저는 이래도 평화주의자입니다.
그리고 남들 노는 거 옆에서 구경하는 게
제 작은 취미랍니다.

레이나
당신, 하나도 안 변했어!
그럼 내가 끌어 내 주지!

***
*전투*

로키
아이고 무서워라. 빌런 정도로는 택도 없겠군요.
그렇다면 본격적으로 시작해야겠지요.

로키
그럼 뒷일을 부탁드립니다.
황제 폐하.

황제
끼히... 끼히히...!

셰인
저게 황제?
같이 있는 저 괴물이 램프의 요정?
생긴 건 전혀 요정이 아닌데...

엑스
그 램프 이제 돌려받아야겠어.
그건 원래 알라딘 거야!

황제
무슨 말을 하느냐! 이 세계에 있는 모든 건 내 것이다!
거렁뱅이 꼬마에게... 순순히 내어 줄 줄 아느냐!

황제
내 실력을 보여주지! 램프의 요정이여!
나를 지키고 녀석들을 없애라!

램프의 요정
명령을 받들겠습니다. 주인님.

로키
여러분, 싸우느라 바쁜데 참 미안하지만
전 일이 있어서요. 먼저 가보겠습니다.
운이 좋으면 또 만나겠죠. 그럼 이만.

엑스
로키! 저 자식... 도망치는 거냐!

레이나
안 쫓아가도 돼!
지금은 여기 카오스 텔러의 [조율]이 먼저야!

레이나
램프의 요정은 황제한테 조종당하고 있을 뿐이니까.
황제 잡기에 집중하자.

타오
그렇다고 해도 저 램프의 요정이란 녀석
보호장벽까지 치고 있는데?
본체를 어떻게 끌어내지?

엑스
괜찮아. 전에 알라딘이 말했잖아.
램프의 요정은 도발에 약하다고!

엑스
다들 공격이닷!

***
*전투*

엑스
좋아! 요술 램프만 있으면 알라딘을 살릴 수 있어!

엑스
헉...!

타오
램프가 산산조각이 났어....

셰인
아마 아까 공격때문에 한계에 달했나 보군요.
복원도 안되고 램프의 요정도 마찬가지고.

엑스
말도 안 돼!
그럼 알라딘은 어떻게 해!

레이나
...『혼돈의 소용돌이에 삼켜진 이야기들이여』

엑스
레이나 멈춰!

레이나
『나의 언명에 따라
여기 조율을 시작하오니......​』

*조율 컷씬*

궁전의 부하
알라딘 전하 납시오~!!

알라딘
핫핫핫,
램프가 있으면 이 알라딘님의 인생에 무서울 것 없지!
이제 내 세상이다!

알라딘
이 알라딘님의 운명을 멋지게 바꿔볼까!

*

엑스
결국 나는 알라딘을 구하지 못했어...

레이나
그것이 알라딘의 운명이었어.
[운명의 서]로부터 자유롭지 않지만
그래도 자신의 운명을 스스로 선택하려고 했지.

레이나
우리들 모두 누군가의 선택에 의해 수동적인 인생을
살고 있어. 원망할 테면 원망해도 좋아.

레이나
이제와서 이 사명을 그만두겠다고해도 맘대로 안 되거든.

엑스
...그렇게 잊혀진다 해도...
나는 절대로 알라딘을 잊지 않을 거야.
절대, 절대로...

*

로키
하하, [조율의 무녀]는 변함 없더군요.
굳이 따진다면 어떤 상구의 소년 하나가 더 추가된 정도군요.

로키
어? 무슨 말씀을! 그냥 평범한 아이입니다.
당신이 직접 만날 일은 없지만.

로키
하긴 그렇죠.
우리들은 우리들끼리 엄숙하게 의식을 거행하도록 합시다.

로키
오래된 [이야기]를 끝내고
새로운 우리들의 [이야기]를 시작하기 위해...