= 8. 잔다르크의 상구 ※잔느의 상구 - Flero
:hardbreaks:

....
과거에 프랑스와 영국은 왕립계승권을 둘러싸고
끝없는 전쟁을 벌이고 있었다.

훗날 백년전쟁이라 불리는 격렬한 전투는
양국의 운명을 크게 바꾸는 계기가 되었다.

세력을 확장한 영국은 오를레앙을 함락시키고
반대 세력인 샤를 7세를 몰아 낼 작전을 펼쳤다.

전략적 요소였던 오를레앙을 포위하는 영국군.
그러나 그곳에 한 소녀가 거느리던
프랑스군이 나타나 영국군을 철퇴시킨다.

소녀의 이름은 잔다르크.
훗날 『오를레앙의 소녀』라 불리는 성녀다.
....

== 전쟁의 성 밑 마을 서쪽

타오
아가씨! 엑스! 셰인!
뛰어, 뛰어, 뛰어어어어어어어어!
화살이 날아온다!!

셰인
시작부터 난장판인 건 익숙하지만,
갑자기 전쟁터에 던져 놓다니...
아무리 그래도 이런 법이 어딨어요! 언니!

레이나
나한테 불평하지 마!
어쩔 수 없잖아. 그런 상구로 들어와 버렸으니까!

엑스
침착하지 않으면 큰일나!
근데 우리 어느 쪽으로 뛰어가야...
...어?

*

????
윽...

엑스
왜 저런 곳에 여자아이가 있는 거야...!

타오
흥. 왜인지는 모르겠지만
쓸데없는 덤도 있는 것 같군!

레이나
역시 나타났구나. 빌런!
모두들 서두르자! 얼른 저 애를 구해야 해!

엑스
알았어!

***
*전투*

레이나
너 괜찮니?
다친 곳은 없어!?

????
...하아, 하아, 당신들은 누구시죠?

엑스
우리는 여행자야.
넌 혼자니? 이 마을 사람이야?

칼리
저는 칼리라고 해요.
조금 전까지 일행과 함께 있었는데...
악마의 습격을 받고... 이 마을이 불바다가 되었어요.

엑스
악마... 저 빌런들을 말하는 건가.
큰일이야. 얼른 일행도 찾아야 될 텐데...

셰인
안 되겠어요. 주변이 온통 불타고 있어요.
사람을 찾을 여유는 없겠네요.
어서 안전한 곳으로 피난 가야 합니다.

칼리
...그럼 성... 오를레앙 성으로 가요.
거기서 잔다르크를 만나면,
악마와 싸울 성녀를 만나면...

타오
잔다르크?
그 성녀라는 사람을 만나면 되는 거지?
지금 어디에 있는데?

칼리
여기보다 북서쪽에 있는 성에...
쿨럭, 쿨럭쿨럭...

엑스
칼리!

칼리
아, 아무래도 마지막 순간이 왔나 봐요...
이제 몸에 힘이... 안 들어가요.
제 영혼도... 곧 신의 곁으로...

레이나
잠깐, 정신 차려!
기다려 봐. 지금 회복 마법을 걸...

수수께끼의 배고픈 소리
쿨~~~~~~~~~
※플레로의 오역: 꼬르륵

레이나
\........

타오
뭐. 일단 큰 지장은 없는 것 같네.

칼리
이럴수가... 아침밥을 못 먹는 바람에...
안 돼... 배가 고파서...
하늘나라로 가버릴 것만 같아요...

셰인
언니. 우선 지금은 위기 상황이니까
태클 거는 건 나중에 하세요.
괜찮아요. 셰인도 같은 마음이니까요.

엑스
아무튼 안전한 곳으로 피난 가자.

레이나
...어쩐지 또 귀찮은 녀석을 구해버린 것 같아.

== 오를레앙의 숲

칼리
하아. 얼마나 자비로운 일인가요.
더없는 혼돈에 빠지게 했던 배고픔이
이렇게 채워지고 진정되다니...아, 기적같은 일이에요.

레이나
이 아이...우리가 갖고 있던 식량을
전부 먹어치웠어. 내가 아껴뒀던 샌드위치까지...

엑스
워워. 레이나...
아마 악마도 이 숲까지는 못 왔나 봐.

칼리
숲? 지금 제가 숲에 있나요?

레이나
무슨 소리야?
그건 보면 알잖...

레이나
...너, 눈이 안 보여?

칼리
네...선천적인 병으로...아, 염려하지 마세요.
이 모든 것도 신의 뜻일테니까요.

타오
그래. 댁도 고생이 많군.
그런데 악마와 전쟁이라니 엄청 뒤숭숭한 상황이잖아.

칼리
원래 프랑스와 영국의 전쟁이었어요.
그런데 어느새 악마가 나타났고...
그 결과 싸움이 심해졌죠.

칼리
지금은 프랑스나 영국과는 상관없이
악마에 홀린 자와 인간의 싸움으로
변해버렸어요...

엑스
그리고 그 악마와 싸우는 인간측 중심인물이
잔다르크.
역시 그 사람이 이 상구의 [주연]일까?

레이나
글쎄 어떨지. 만나보면 알겠지.
조금 더 쉬고 나서 성으로 가자.
쫓아오는 빌런도 다행히 없네.

셰인
아니에요. 언니. 지금까지의 여행을 떠올려 보세요.
빌런이 나타난 건 대체로 그런 말을 한 다음이었어요.

레이나
무슨 소리야. 얘도 참.
이상한 징크스를 붙이고 그래...

칼리
...느껴져요. 눈에 보이지 않는 사악한 기운이...
악마의 기운, 그것도 여럿이에요!

셰인
그러게 뭐랬어요.

레이나
뭐가 그러게야! 내 잘못이 아니잖아!?
불가항력이라고. 방금 그건!
에에잇! 타이밍 나쁜 빌런들!

레이나
다들 칼리를 보호하면서 숲을 빠져 나가야 해!
징크스 따위에 질까 보냐!!

***
*전투*

칼리
후우, 악마의 기운이 사라져 가요...
다들 강하시군요...

엑스
하하. 저런 상대는 익숙하거든.
슬슬 숲을 빠져나갈 때가 됐나...

????
기다리시오. 거기 여행자들이여.

????
방금 악마와 싸우신 듯 한데
당신들은 프랑스와 영국. 어느 쪽 세력입니까?

타오
미안하지만 우리는 둘다 아니야.
오를레앙 성에 가고 싶을 뿐이지.
가는 길을 알고 있다면 좀 가르쳐 주겠어?

????
오를레앙 성으로요? ...마침 잘 됐군요.
저희 부대도 귀환하려던 참이었거든요.

레이나
저희 부대?
설마 당신...

????
아. 소개가 늦었습니다.
저는 프랑스=영국 연합 악마 토벌대를
이끄는 잔다르크라고 합니다.

잔다르크 ※잔느
이런 곳에서 서서 얘기하기도 그렇네요.
우선 함께 성으로 가시죠.
얘기는 그 후에...

== 오를레앙 성 밖의 초원

엑스
악마와 싸우는 성녀 잔다르크.
그녀는 우리에게 이 세계에서 일어나고 있는
일들을 알려 주었다.

엑스
원래 잔다르크는 프랑스 사람이었지만
영국군 앞에 나타난 악마와 싸우기 위해 적군이었던
인간들도 한데 모아 연합군을 조직했다고 한다.

엑스
악마는 인간을 홀린다.
지금 이 전쟁은 [나라와 나라]가 아닌
[인간과 악마]의 전쟁으로 바뀌어버렸다.

엑스
우리는 그런 상황에서도 상냥한 그녀와
친해지게 되었고, 어느새 오를레앙 성에 다다랐다.
그러나 그 곳에서 또 큰 어려움에 맞닥뜨린다.

레이나
악마가 오를레앙 성을 점령했다고?
어떻게 된 거야?

잔다르크
아직 전령을 통해 전해 들은 것 뿐이지만...
아무래도 악마가 침입하는 바람에 다른
악마 무리까지 이끌려 온 것 같습니다.

잔다르크
성 안에 있는 질 드 레 대장과도 연락이 안 되고...
악마들이 성 어디에 숨어 있는지도
모르는 상황입니다.

셰인
주요 전투병은 안에 갇혀 있고...
역시 그러면 섣불리 접근할 수는 없겠군요.

타오
난처한걸... 어디로 숨어서 들어가야...

칼리
그건, 제가 안내할 수 있습니다.

엑스
칼리? 성을 안내한다니...
너도 성에 들어가는 건 처음이잖아?

칼리
네. 하지만 눈이 보이지 않기 때문에
[볼 수 있는] 것도 있는 법이죠.
저 성에 퍼져 있는 악마의 기운을 저는 느낄 수 있습니다.

칼리
그 기운을 느끼면서 움직이면
성을 되찾을 수도 있을 거예요.

잔다르크
좋아요. 급작스레 부탁드려 죄송하지만
여러분의 힘을 저 잔다르크에게 빌려 주십시오.
이 성을 악마에게 넘겨주어서는 안 됩니다.

레이나
물론이야, 당연하지.
빌런들 맘대로 내버려 두지는 않을 거야!

***
*전투*

== 오를레앙 성

엑스
성을 점령한 악마, 즉 빌런들과
싸운 우리는 녀석들을 쫓아내는 데 성공한다.

엑스
잔다르크의 상관인 질 드 레 대장도
감사 인사를 하며 우리를 악마 토벌대의
일원으로 스카우트했다.

엑스
말하자면 즉석에서 뽑힌 용병으로서 우리도
이 전쟁에 참가하게 된 것이다.

질 드 레
이 성에 있는 악마들은 쫓아냈지만 그 악마의
우두머리가 또다시 적국으로 돌아갔다는 정보가
들어왔다. 우리는 악마를 무찔러야 하네.

질 드 레
제군들은 잔다르크가 이끄는 부대에 독립부대로서
참가하여 악마 토벌에 협력해주기를 바라오.
제군들의 활약을 크게 기대하겠네.

잔다르크
여러분의 실력은 저도 잘 알고 있습니다.
함께 싸워 주신다면 이보다 든든한 일도 없을 겁니다.
잘 부탁드립니다.

*

셰인
너무 과대평가 한 것 같은데요.
이렇게 성까지 왔는데 다시 그 전쟁터로
되돌아가야 하나요.

타오
하여튼 어느 상구에 가도 인간은
늘 싸우는 생물이군.

레이나
아무래도 상관 없어. 전쟁터에 가면 아마
그 악마인지 뭔지도 만나겠지. 얘기를 들어보니
카오스텔러와 뭔가 연결고리가 있는 것 같고...

레이나
...어? 그러고 보니 엑스는?

셰인
그 배고픈 아이한테 간다고 했어요.
아무렴 함께 데리고 전쟁터에 나갈 수는 없으니
작별 인사를 하겠다고요.

레이나
칼리한테?
흐음...

타오
응? 뭐야 아가씨?
설마 질투야? 질투하는 거야!?
하하. 아가씨도 귀여운 구석이 있...

레이나
정말 바보야! 그런 거 아니거든!
그냥 좀 신경 쓰였을 뿐이야!

레이나
그래... 좀 신경 쓰인 것 뿐이라고...

셰인
저기. 심각한 분위기로 때우시려는 것 같은데
치명상으로 들어갔어요, 언니.
얼른 타오 오빠한테 회복 마법을 걸어 주세요.

*

엑스
미안. 칼리. 우리는 그 마을에 다시 가봐야 돼.
네 일행에 대해서 단서를 찾으면 꼭 알려줄게.

칼리
마음 쓰지 마세요.
인연이 있으면 또 만날 수 있겠죠...
아, 출발하실거면 이 빵을 하나 가져 가세요.

엑스
고...고마워. 잘 받을게.
그럼 난 간다.
돌아오면 또 이런저런 얘기 나누자.

칼리
정말 상냥한 분이시군요.
신이시여...
엑스 님의 상냥함이 보답 받는 날이 오기를...

== 전쟁의 성 밑 마을 서쪽

빌런
그르... 그르르르...!!

엑스
심각하군...
전에 왔을 때보다 빌런 수가 늘어났어...

레이나
잔다르크, 어떻게 할까?

잔다르크
이 마을은 지금 악마 군이 제압하고 있어요.
이 곳은 국경 부근의 전략적인 거점이라
되찾을 수 있다면 상황이 많이 달라지죠.

잔다르크
악마 무리는 저희가 맡겠습니다.
그 틈에 당신들은 국경을 봉쇄하고 있는 악마들을
습격해 주세요. 괜찮겠습니까?

타오
물론이지!
요컨대 실컷 날뛰라는 거잖아?

셰인
어설프게 연계하자고 하지 않는 만큼
셰인들도 마음 편하고 좋네요.

잔다르크
고마운 말씀입니다. 그럼 시작하죠.
여러분께 신의 가호가 있기를!

빌런
그르...그르아아아아아아아아아...!!

레이나
자, 다들. 간다!

***
*전투*

엑스
우리는 국경 방면의 길을 봉쇄한
빌런들을 습격하는 데 성공했다.

엑스
성 밑 마을을 되찾은 잔다르크 군은
단숨에 사기가 올랐다.
그리고 잔다르크는 병사들을 향해서 연설했다.

잔다르크
오늘 우리는 악마에게서 마을을 되찾는데
성공했습니다! 이는 신이 우리의 정의를
축복한다는 최고의 증거입니다!

잔다르크
자, 신에게 사랑받는 자들이여!
길이 열렸습니다! 지금이 바로 나아갈 때입니다!

병사들
우와아아아아아아아아아아아아!!

*

엑스
굉장해... 그렇게 격렬하게 싸우고도
저렇게 병사들을 격려할 수 있다니...

타오
정말 이정도 병사를 통솔하다니 대단한 대장이야.
뭐, 둘 중에 하나를 고르자면 나는 아가씨처럼
빈틈 투성이인 게 귀염성 있어서 좋다만.

레이나
...그걸 칭찬이라고 하는 거야?

셰인
그런데 이대로 적군 진영까지 가는 건가요?
대규모 행군이 되겠네요.

레이나
불평해봤자 소용 없어.
여기까지 온 이상 카오스텔러가 있는 곳까지
한번에 달려가자고!

엑스
응. 모두 가자.

== 전쟁의 성 밑 마을 동쪽

잔다르크
모두 겁먹지 말고 전진하세요!
당신들에게는 잔다르크가 있습니다!
신의 빛은 우리를 향해 반짝이고 있습니다!

타오
역시 적군 땅이군! 빌런이 우글우글해!
아가씨! 카오스텔러의 기운은 안 느껴져?

레이나
카오스텔러인 지는 모르겠지만, 기분 나쁜 기운은
아까부터 대량으로 느껴져.
뭔가가 가까운 곳에 숨어 있어.

셰인
그 악마인지 뭔지는 어디로든 숨어들 수 있다고 그랬죠.
오를레앙 성에서도 결국 악마는 못 찾았어요.

엑스
조심해서 나쁠 건 없지.
특히 이런 전쟁터에서 조금이라도 틈을 보였다가는
잠시도 못 버틸...

엑스
잔다르크! 위험해!

잔다르크
윽!?

*

엑스
잔다르크, 괜찮아!?

잔다르크
하아... 하아... 죄송해요...
어깨를 조금 다쳤어요...

악마 사제
저주에 걸렸군.
성녀여, 이제 그대는 전쟁터에 설 수 없소.
그대의 운명도 이제 끝이네.

레이나
틀림없어! 찾았다. 악마!
아니, 카오스텔러.
너는 여기서 우리가 막을 거야.

악마 사제
그럴 수는 없지. 나는 아직 할 일이 남아 있거든.
잔다르크의 저주가 침투하면 다시 데리러 오지.
그 때까지 이 녀석과 놀고 있어 주실까?

레이나
메가 빌런을 소환했어...
매번 똑같은 수법을 쓰다니
정말 한결 같은 카오스텔러야...

셰인
사라졌습니다!
저 악마 정말 어디에서든 나타나고 사라지는군요...!

타오
도망쳐 버린 건 어쩔 수 없어!
지금은 저 메가 빌런을 상대하는 게 우선이야!
얼른 해치워버리자!

엑스
그래, 가자!
잔다르크를 지켜야해!

***
*전투*

레이나
...미안해요. 상처는 회복 마법 덕에 아물었지만
당신한테 건 저주까지는...

잔다르크
마음 쓰지 마세요.
오늘 만약 제가 죽는다면 그 또한
신의 뜻일 겁니다...

엑스
두렵지 않아?
지금 이 순간에도 저주가 퍼지고 있는데...

잔다르크
제가 가장 무서운 건 이 목숨이 다하는 것이 아니라
신념이 끊어지는 것입니다.

엑스
신념이...끊어진다고?

잔다르크
조국을 통일하여 모두가 평화롭게 살 수 있는 세계를
실현하기 위해서 제가 태어났으며 또한
제가 살아가는 이유 였습니다...

잔다르크
설령 이 몸이 쓰러진다 하더라도
마음만은 누군가에게 전해져 피와 살이 되어
머지않아 세상을 움직이는 힘이 되겠지요.

잔다르크
그 마음이 누구에게도 전해지지 않게 되는 그 때가
진정한 의미로서 영혼이 사라지는 거랍니다.
잔다르크라는 영혼이 사라지는 거예요...

잔다르크
만약 제게 무슨 일이 일어나거든
뒷 일을 잘 부탁드립니다.

엑스
불길한 소리 하지 마.
어서 오를레앙 성으로 돌아가자.

레이나
약속할게, 잔다르크. 무슨 일이 있어도
우리가 널 죽게 내버려두지 않을 거야.
반드시 너를 지켜 낼 거야.

잔다르크
...후후. 고맙습니다.
당신들을 만난 이 운명에
감사해야겠네요...

엑스
이리하여 우리는 잔다르크를 데리고
오를레앙 성으로 돌아갔다.

엑스
잔다르크는 씩씩하게 웃었지만
그녀의 얼굴에 맺힌 땀은 그 몸에 걸린
저주가 얼마나 강한지 말해주고 있었다.

== 오를레앙 성

엑스
우리는 잔다르크를 데리고 오를레앙 성으로 돌아갔다.
그러나 잔다르크의 저주는 풀리지 않았고
그대로 병상에 눕게 되었다.

엑스
잔다르크가 쓰러지고 온 성에 불안이 퍼져 나가자
질 드 레 대장은 악마가 다시 침입할 것을 염려하여
경비 태세로 돌입했다.

엑스
...모두가 살기를 띠고 있어.
다들 건너편에서 경비를 서는데
여기는 나 혼자 있어도 되는 걸까?

칼리
어머, 엑스 님...

엑스
칼리...? 이런 데서 뭐하고 있어?
혼자 다니면 위험해!

칼리
죄송해요.
좀처럼 잠이 안 와서...
잔다르크 님께서 위험하다는 소식 때문에...

엑스
아. 소문을 들었구나.
괜찮아. 다들 잔다르크를 지키고 있으니까.
자, 칼리는 방으로 돌아...

칼리
지킨...다고요.
무엇으로부터 누구를 지킨다는 거죠?

칼리
어차피 마지막에 잔다르크 님은
화형을 당해 죽을 텐데요.

엑스
뭐?

칼리
그레고리력 1431년 5월 30일.
당시 영국의 점령지였던 루앙에서
진짜 잔다르크는 처형 당했어요.

칼리
이 상구가 잔다르크의 상구인 이상
잔다르크의 운명을 이어 받은 그 사람도 또한
이 결말로부터 도망칠 수 없어요...

엑스
거짓말이야... 그걸 어떻게 믿어.
게다가 어떻게 칼리가 잔다르크의
운명을 알고 있는 거야! 상구에 대해서도...

칼리
저는 보여요. 엑스 님.
이 빛을 비추지 못하는 눈동자로 [운명]의 흐름을
살짝 엿볼 수가 있어요.

칼리
당신은 지금 잔다르크의 운명에 대해 분노를 느끼고 있군요.
이런 불합리한 일을 용서할 수 없다고 생각하죠.
그럼 다시 물을게요.

칼리
엑스 님.
당신은 대체 무엇으로부터 무엇을 지키고 싶은 거죠?
잔다르크 님의 목숨인가요? 아니면 운명인가요?

엑스
그건...나는...!

성의 병사
악마다~~!!
악마가 나타났다~~!!

칼리
...아무래도 대답을 기다릴 시간은 없는 것 같네요.
어서 달려 가세요.
그게 당신이 해야 할 일이라고 믿는다면.

엑스
...위험하니까 그늘진 곳에 숨어 있어.
나중에 데리러 갈 테니까, 알겠지?

칼리
엑스 님. 당신은 너무 상냥해요...
저 칼리는 언제나 당신의 영혼이 평온하기를
기도하겠습니다.

***
*전투*

레이나
잔다르크를 놔줘. 카오스텔러!
이 이상 네 멋대로 하게 내버려 두지 않을 거야!

악마 사제
내 멋대로? 무슨 소리를 하고 있는가?
이건 어디까지나 예정된 [운명]대로
흘러가고 있을 뿐이다.

악마 사제
이 마녀를 처형하는 운명대로.

엑스
...!?

레이나
잔다르크를 처형한다고?
어떻게 된 거야? 잔다르크!

잔다르크
...이 악마 말은 사실입니다.
저는 오를레앙을 해방시킨 후에 적국으로 잡혀가서
처형 당할...그런 운명이에요...

타오
아무래도 이 상구의 스토리텔러는
원래부터 지독한 성격이었나 보군.
또 거지 같은 운명을 정해줬어!

악마 사제
이대로 잔다르크를 데려 가겠네.
어차피 너희는 나를 못 이기...

엑스
...그렇게는 못 해.

엑스
잔다르크한테서 떨어져어어어어어어어어!!

레이나
엑스!

악마 사제
흥!

악마 사제
운명을 받아 들여라.
그것이 신께서...
스토리텔러께서 정해 놓은 규칙이다.

잔다르크
엑스 님...

엑스
아... 부탁이야, 정신 차려!
엑스...
엑스!!

엑스
\......

*

질 드 레
이건 성스러운 전투다!
우리의 사랑스러운 [오를레앙의 처녀]를
악마들로부터 구출해내야 한다!

*

셰인
...괜찮으시겠습니까?
아무리 저주 때문에 신참 씨가 혼수 상태라고는 해도
이대로 두고 싸우러 나간다니...

레이나
여기 있는 게 엑스도 안전할 거야.
카오스텔러를 [조율]하면 저주도 풀 수 있을 테니까...

레이나
가자. 타오, 셰인.
잔다르크와 엑스를
반드시 구해내야 돼...

== 오를레앙의 숲

타오
이 숲을 지나가는 게 벌써 몇 번째인지...

셰인
원래 왔던 길을 따라서 적군 진영에 쳐들어가는
거니까 어쩔 수 없어요.

레이나
\......

셰인
언니, 혹시 신참 씨가 오기를
기대하는 거예요?

레이나
...그런 거 아니야.
서두르자.
지금은 우리 셋이서 이겨내야 해.

== 회상

잔다르크
...제가 가장 두려워하는 것은
이 목숨이 다하는 것이 아니라
신념이 끊어지는 것입니다.

잔다르크
설령 이 몸이 사라진다 하더라도
그 마음은 누군가에게 전해져 피와 살이 되어
머지않아 세상을 움직이는 힘이 되겠지요.

잔다르크
그 마음이 누구에게도 전해지지 않게 되는 그 때가
진정한 의미로서 영혼이 사라지는 거랍니다.
잔다르크라는 영혼이 사라지는 거예요...

== 오를레앙 성

엑스
...응? 내가 대체...
다들...잔다르크는...?

칼리
정신이 드세요?
이제 괜찮을 거예요.
당신한테 걸린 저주는 풀었으니까요.

칼리
다른 분들은... 잔다르크 님을 구하기 위해
악마가 있는 적국으로 가셨어요.
아침에 출발하신 것 같아요.

엑스
잔다르크가...악마가 있는 적국에 있다고?
...이런. 큰일이야!

칼리
뒤쫓아가실 생각인가요?
그렇게 잔다르크 님을 구한다고 해도
뭐가 달라지죠?

칼리
엑스 님의 그 행동이,
반드시 보답 받으리란 법은 없잖아요?

엑스
보답을 받는지 못 받는지가 문제가 아니야.
설령 언젠가 처형 당할 운명이라고 해도
그 결말을 지금 맞이하면 안 돼.

엑스
잔다르크의 마음만큼은 반드시 지켜야 되거든.
왜냐하면 그건 틀림없이 올바른...마음이니까...

엑스
모두를 쫓아갈게. 칼리.
운이 좋으면 다시 만날 거야.
그럼 안녕.

칼리
...결국 당신은 그 [운명]을 선택하는군요.
정말 어리석은 사람이에요...

== 오를레앙의 숲

타오
...그러고 보니 얼마 전까지는
이 패밀리도 3명 밖에 없었구나.

셰인
신참 씨가 온 지 어느 정도 지났죠?
평소에는 존재감이 0인데 없으니까
뭔가 부족한 느낌이 드네요.

레이나
그러게. 어느새 함께 있는 게 당연해졌단 말이야...

타오
...잔다르크의 운명이 아직 신경 쓰여?

레이나
신경 쓰는 거 아니야.
우리가 어떻게 할 수 있는 문제가 아닌 걸.
하지만 엑스는 어떻게 생각하는지 마음 쓰여서...

셰인
쓸데없이 참견하기 좋아하니까요, 신참 씨는.
이번 일도 좀 길어질 것 같아요.
...앞으로도 같이 여행을 떠나 줄까요?

타오
그건 그 녀석이 스스로 결정할 일이야.
그거야말로 우리가 어떻게 할 수 있는 일이 아니...

귀에 익은 목소리
어~이! 레이나, 타오, 셰인!

레이나
엑스!
네가 어떻게 여기에...

엑스
당연히!
잔다르크를 구하러 왔지.

엑스
설령 잔다르크의 운명이 정해져 있다고 해도
잔다르크의 마음을 짓밟아서는 안 돼.
그렇잖아?

타오
하...하하! 그게 네가 내린 답이야?
정말 대단한 인물이다. 넌!

셰인
드디어 늘 그래왔던 것처럼 4명으로
돌아왔네요.

레이나
정말 쓸데없는 걱정 좀 시키지 마!
엑스 주제에!
하아...정말이지 넌...

레이나
어서 와. 기다리다 지쳤어.
엑스.

엑스
응!
다녀왔어. 레이나.

== 전쟁터 변두리의 숲

레이나
정말이야? 질 드레 대장.
잔다르크의 처형을 동쪽에 있는 광장에서
집행한다는 게...

질 드 레
틀림 없을 걸세. 그 곳에는 화형대도 있으니.
민중이 보는 앞에서 성녀를 죽이기에는
안성맞춤인 곳이지.

질 드 레
어떻게든 처형되기 전에 잔다르크를 구해야만 해...

셰인
...역으로 처형이 집행되기 직전에 달려가면 어떨까요?

엑스
무슨 말이야?
그럼 잔다르크가 위험해지잖아...

타오
아니. 이런 큰 일을 벌일 땐 반드시
평소와는 다른 긴장감이라는 게 생기거든.
분명히 빈틈이 생길 거야.

레이나
사전에 정확하게 계획을 짜면
잔다르크를 되찾아 올 뿐만 아니라 그 악마를
쓰러뜨릴 기회도 생길 지 몰라.

질 드 레
그 신출귀몰한 악마를 대체 어떻게 몰아 세워야...

셰인
그 점에 대해서는 셰인한테 한 가지 생각이 있어요.

엑스
셰인의 제안에
질 드 레 대장은 갑자기 흥미를 보인다.

엑스
이리하여 우리는 작전 준비를 마치고
잔다르크가 기다리는, 화형대가 있는 광장으로
서둘러 갔다.

== 회형대가 있는 광장

악마 사제
지금 여기서 우리 동포의 피를 흘리게 한
마녀 잔다르크의 처형을 집행한다!
이의 있는 자가 있는가?!

열광하는 민중
죽여라! 마녀를 죽여라!
불에 타는 고통 속에서 죽게 하라!!

잔다르크
\......

악마 사제
좋다!
그럼 불을 지르겠다! 집행관이여!
횃불을 들고...

엑스
잠깐 기다려!!

엑스
잔다르크의 처형을 멈춰줘야겠어!
카오스텔러!!

잔다르크
.........엑스 님!

악마 사제
어떻게 내 저주에 걸리고도 움직일 수 있는 거지?

엑스
글쎄, 왜일까?
알고 싶으면 우리랑 싸워볼래?

악마 사제
그런 도발에는 안 넘어간다!

레이나
편리하겠군. 옆에 있는 사람을
금방 병정으로 만들어버릴 수 있다니.
하지만 그런 것에 질 우리가 아니지!

타오
좋았어!
빌런 녀석들! 화재랑 싸움은 내 전문이지!
전부 다 한꺼번에 상대해주마!

***
*전투*

악마 사제
이놈들...!
빌런 좀 쓰러뜨렸다고 우쭐거리지 마라...!

레이나
카오스텔러는 대체 어디로 간 거지?

악마 사제
우하하핫! 이렇게 된 이상
이제 너희는 내 모습을 볼 수 없지!
이대로 서서히 괴롭히다가 죽여주마!

악마 사제
하하핫. 죽어라!

악마 사제
뭐야!?

레이나
넌 이동할 때 바닥에 그림자가 생기거든.
지금까지는 밤이라 알아차리기 힘들었지만...

레이나
질 드 레 대장의 병사들이 주위를 둘러싸고
빛을 비춰주고 있거든.
그래서 네 그림자가 아주 잘 보이거든?

셰인
작전을 세운 건 저 셰인입니다.
이제 도망칠 곳은 아무데도 없습니다.

악마 사제
네... 네놈들이...

악마 사제
이런... 망할 것들이이이이이!!
네 녀석들 전부 때려 죽일 거다!!

타오
최후의 발악이라도 해 볼 셈인가?
그럼 마지막을 장식해볼까!

레이나
잘 들어! 녀석이 사용하는 마법 공격은 조심해야 해.
그 저주보다 더 끔찍한 마법을 숨기고 있을
가능성이 있어! 가자!

엑스
좋아! 반드시 잔다르크를 구해내겠어!

***
*전투*

잔다르크
고맙습니다...
여러분이 꼭 와주실 거라 믿고 있었어요.

엑스
잔다르크. 전에 말했지?
마음은 누군가에게 전해져 세상을 움직이는 힘이 될 거라고.
난 아직 그 말이 무슨 뜻인지 반도 이해 못했지만...

엑스
그래도 잔다르크의 마음을 헛되게 하고 싶진 않아.
네가 어떤 운명에 놓여진다 하더라도
네 마음은 분명, 바른 길을 걷고 있을 테니까.

잔다르크
잘 부탁드립니다. 엑스 씨.
제 마음을 부디 당신들의 여행길에도
데려가 주세요.

레이나
이제 됐지?
그럼 시작한다.

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라
여기 조율을 시작하오니....』

*조율 컷씬*

레이나
왜 울상이야? 엑스.
자, 다음 상구로 떠나자.
잔다르크의 마음을 짊어진 만큼 더 열심히 해야지?

엑스
그야 물론이지.
가자, 레이나. 모두.

타오
그건 그렇고 그 칼리라는 아가씨는 누구였을까?
아가씨도 못 푼 저주를 풀어버리다니...

엑스
잔다르크나 상구에 대해서도 잘 아는 것 같던데...
결국 일행도 못 찾아줬네.

셰인
어쩌면 셰인들처럼 상구를 여행하는
[공백의 서]의 소유자일 지도 모르겠네요.
분명 괜찮을 거예요. 의외로 씩씩해 보이던걸요.

레이나
그러게...

엑스
왜 그래? 레이나.

레이나
...음. 나도 잘 설명은 못하겠는데.
어쩐지 그 애랑은 금방 또 만날 것 같아.
그런 느낌이 들어...

*

칼리
재미있는 분들이었어요. [조율의 무녀] 일행은.
서로를 더 이해하면 다가설 수 있을 것 같은데...
그렇죠? 로키.

로키
죄송하옵니다만... 사랑하는 [혼돈의 무녀]님.
앞으로 이렇게 제멋대로 행동하는 건 삼가 주십시오.
아무리 저라고해도 이번만큼은 간담이 서늘했습니다...

칼리
앗, 미안해요. 하지만 역시 직접 만나봐야
알 수 있는 것도 있거든요. 그들은 잘못된 신념에
사로잡혀 있어요. 어서 구원에 나서야만...

로키
...이미 [그 준비]는 갖춰졌습니다.
가시죠. 칼리 님.
우리 교단의 사명을 다하기 위해서.

칼리
네, 로키...
