= 8.1. 성냥 용사의 전설 에피소드0 ※성냥의 용사전설·에피소드0 - Flero
:hardbreaks:

== 성냥 팔이의 거리

성냥팔이 소녀
―저는 몹시 가난한 성냥팔이 소녀예요.
오늘도 아버지 말씀을 따라 이 추운 밤하늘 아래
길가에 서서 성냥을 팔고 있죠.

성냥팔이 소녀
얼어붙을 것 같은 추위 속에서 지나가는 사람들에게
말을 걸고 있지만 성냥은 좀처럼 팔리지 않아요.
하지만 어쩔 수 없어요.

성냥팔이 소녀
왜냐하면 이게 내 운명이니까...
이렇게 아무도 돌아보지 않는 허무한 성냥불처럼
살아가는 게 제 삶의 방식이니까요―

성냥팔이 소녀
성냥... 성냥 사세요...
어떡하지... 전혀 안 팔려... 이대로 가면
아버지가 화내실 텐데... 집으로 돌아갈 수도 없어...

성냥팔이 소녀
하아... 하아... 손이 차가워졌어...
그러면... 한번 더 성냥을 켜볼까...?

성냥팔이 소녀
성냥불을 보고 있으면 굉장히 안심이 되는 걸...
진수성찬이 나오는 꿈... 모험을 하는 꿈...
이번에는 어떤 꿈을 꿀 수 있을까...?

성냥팔이 소녀
...하아. 따뜻하다.
마음이 따끈따끈해졌어...
우~와, 또 뭐가 보이기 시작했어...

성냥팔이 소녀
누구지 이 사람들은...? 왠지 엄청 좋은 냄새가 나...
어쩌면 맛있는 요리를 가져다 주는 천사일 지도―

타오
이 녀석! 꼬맹이가!
이런 밤중에 불장난을 하면 안 되지!

성냥팔이 소녀
네? 어엇... 네에!?

셰인
성급하게 판단하지 마세요. 그야 살다 보면
이런저런 힘든 일이 있다는 건 알지만
방화는 하면 안 되요. 안 되요. 절대로 안 되요.
※플레로의 실수

성냥팔이 소녀
아... 아니에요! 저는 성냥팔이예요!
성냥팔이 소녀라고요. 방화범이 아니에요!
너무 추워서 성냥을 켠 것 뿐......

위장이 울리는 소리
꼬르륵~~~~~

성냥팔이 소녀
으으......

엑스
성냥불을 켜봤자 배가 부르진 않겠지.
빵이 있는데 괜찮으면 먹을래?

성냥팔이 소녀
먹을래요! 먹을게요! 잘 먹겠습니다!

레이나
잠깐. 카오스텔러가 없는 상구에서 쓸데없는
간섭을 하면 안 된다고 늘 말했잖아.
어디서 빌런이 나올지 모른단 말이야...

엑스
알고 있지만 그래도 역시 이대로 내버려 둘 수는...

타오
그래 맞아. 아가씨. 스토리텔러가 직접 나타나는
경우는 상구의 [주인공]과 얽혔을 때잖아?
이런 꼬맹이 좀 도와줬다고...

셰인
아니요. 그렇지도 않은 모양이에요.

***

빌런
크르르! 크르르크르륵!!

성냥팔이 소녀
어... 뭐지 저 검은 건...
설마 성냥이 천사가 된 건가......?

레이나
천사가 아니라 악마겠지!
아~ 정말! 매번...!!
일단 이 곳을 벗어나자!

***

성냥팔이 소녀
더는 안 되겠어요. 못 뛰겠어요...
배가 고파서...

타오
너무 무리하게 만들었나봐.
빌런들은 일단 뿌리쳤고...
이제 어떻게 할 거야? 아가씨.

레이나
굳이 그 타이밍에 빌런이 나타났다는 건
이 상구에서 그 성냥을 파는 여자아이가
굉장히 중요한 존재라는 거겠지.

레이나
예를들면 이 아이를 돕지 않고 내버려 두는 게
원래 그 애의 운명이었을 지도...

엑스
말도 안 돼!
그대로 내버려 두라는 거야!?

레이나
어디까지나 추측일 뿐이야. 우선 그 애한테 사정을
들어보기 전에는 아무것도 알 수 없어.
단지 지금은 그럴 상황이 아닌 것 같네...

성냥팔이 소녀
추워요... 추워...
이럴 땐 성냥을...
나에게 남겨진 마지막 성냥 한 개비를 켜면...

성냥팔이 소녀
하아. 정말 따뜻하다...
어머? 거기 있는 건 천국에 계신 할머니인가요?
왜 그러세요? 제게 무슨 하실 말씀이 있나요?

타오
...저기. 저 꼬맹이가
성냥불에 대고 말을 걸기 시작했는데.
정말 괜찮을까?

엑스
그러게... 좀 말을 걸어보자.
저기. 성냥팔이야.
대체 누구랑 얘기를...

성냥팔이 소녀
...응? 뭐라고요!?
이 세상에 큰 위험이 도사리고 있다고요!?

레이나
잠깐만. 천국에 계신 할머니가
손녀한테 대체 무슨 얘기를 하는 거야?

셰인
잘 모르겠지만 상황이 참 갑작스럽게 전개되네요.

성냥팔이 소녀
그래요... 그렇구나...
머지않아 이 세계에 큰 재앙이 닥치는구나.
그래서 용사가 나서야 하는구나...

성냥팔이 소녀
용사 마리가 이끄는 용기 있는 동료들.
미아의 숲에 있는 용감한 남매와 가시나무 성의
잠자는 공주를 모아서 맞서 싸워라... 알았어요...

성냥팔이 소녀
아앗. 하지만 성냥불이 곧 꺼질 거야...
이 불이 꺼지면 내 생명도 다 타버리겠지...
아직... 이런 곳에서... 잠들 수는...

성냥팔이 소녀
누가... 누가 부디... 제 대신에 동료를...
이 세계를 구할 동료들을... 모아서...
―콜록.

엑스
성냥팔이야!!
일어나! 일어나 봐!

레이나
얼른 의사한테 데려가는 게 좋겠어.
당분간 안정을 취해야만 할 수도 있어...

타오
방금 그 신의 계시 같은 건 어떻게 할 거야?
잠꼬대로 치부할 수도 있지만...
아마 진짜로 한 말이겠지...

셰인
용사 마리와 미아의 숲에 있는 용감한 남매.
그리고 잠자는 숲 속의 공주... 라.
너무 노골적으로 우리한테 맡긴 것 같은데요...

엑스
결국 우리가 직접 할 수 밖에 없는 건가...

***

엑스
―이리하여 성냥팔이 소녀의 계시를 떠맡게 된 우리는
용사 마리와 그 동료들을 찾기 위해 여행을 떠났다.

엑스
과연 용사를 찾아서 무사히 이 상구의 운명을
원래대로 되돌려 놓을 수 있을 것인가.
앞날이 조금 불안합니다...―

== 미아의 숲

그레텔
―나는 그레텔이야. 8살.
오빠랑 같이 숲 속에 버려졌어.

그레텔
숲에서 굉장히 달콤한 향이 나는 과자집을 발견했는데
그 곳에는 무서운 마녀 할머니가 살고 있었어.

그레텔
그 집에서 마녀 할머니한테 잡아먹힐 뻔 했는데
오빠랑 같이 진짜 진짜 열심히 나쁜 마녀 할머니를
무찔렀어!

그레텔
그리고 오빠와 함께 진짜 집으로 돌아갈 예정이었는데―

그레텔
오빠! 오빠!
어, 어디 있어~~!?
어떡해... 길을 잃었나 봐...

그레텔
[운명의 서]에 쓰여진 대로야...
으음... 아마 이 다음에 용사 마리라는 사람을
만나고나서 오빠도 찾는 거였지...?

그레텔
그럼 괜찮...겠지만...
그래도 역시 무서워... 쓸쓸해...
오빠......

엑스
저기, 방금 그 목소리가 너였니?

그레텔
꺅!?
누구? 누구야!?
설마 유괴범인가!?

엑스
아니거든!
음. 좀 묻고 싶은 게 있는데...
혹시 너한테 오빠가 있니?

그레텔
오빠? 응. 있어.
오빠는 헨젤이라고 해.
나는 여동생인 그레텔인데... 아.

그레텔
혹시 용사 마리 일행이에요!?

레이나
우리는 용사 마리가 아니고 대리인이라고나 할까?
혹시 용사 마리를 알고 있니?

그레텔
아... 네. 오빠랑 같이 그 사람의 동료가 될 거라고
[운명의 서]에 쓰여져 있었거든요...

타오
그럼 성냥팔이가 한 말이 진짜였던 건가.
정작 중요한 용사가 안 보이는 게 흠이지만...

셰인
그런데 오빠는 어디에?
아까부터 찾는 것 같던데요.

그레텔
그렇지! 오빠... 오빠가...
조금 전까지 같이 있었는데...
정신을 차리고 보니 아무 데도 없어...

그레텔
나중에 또 만나겠지만...
그래도 역시 불안해... 어디 가서 찾아야 할 지도
모르겠고... 그래서... 그래서... 그래서...

그레텔
으... 으으으... 으아아아아아아아아아앙!!
오빠아아아아! 어디 가버린 거야아아아아!!

엑스
아아... 울지 마. 울지 마.
우리도 같이 찾아줄 테니까. 알겠지?

그레텔
히끅... 으으... 고맙습니다...
잘 부탁드려요... 히끅.

***

레이나
마지막으로 헨젤을 본 게 이 근처였구나.

그레텔
네 맞아요...
같이 집으로 돌아가기 위해 오빠가 떨어뜨려
놓은 자갈을 찾아서 온 건데...

엑스
아. 이 길에 떨어져 있는 자갈 말이구나.
이게 그레텔네 집까지 이어져 있는 건가.
뭔가 다른 단서가 있으면 좋겠는데...

타오
이 숲에서는 쉽게 못 찾을 것 같아.
이걸 봐. 이 주변만 바닥에 개미가 우글거리면서
줄을 만들고 있...

셰인
아니. 잠깐만요.
이 개미들은 먹이를 향해 몰려 있어요.
...이건 쿠키 조각인가요?

그레텔
오빠 거야!
과자집에서 주웠어!
오빠가 계속 나한테 나눠 줬는데...

레이나
응? 이 쿠키 조각들은 아까 자갈과
다른 방향으로 이어져 있는 것 같지 않아?
개미들이 몰려 있어서 알아보기 힘들지만.

엑스
자기가 있는 곳을 알리기 위해서
헨젤이 일부러 남겨 놓은 건가?
만약 그렇다면...

그레텔
오... 오빠가... 뭔가 위험한 일에 빠진거야?
괘... 괜찮은 거지?
오빠랑 또 만날 수 있지?

셰인
우선 이 쿠키 조각을 따라가죠.
울든 걱정하든 나중에 할 일이에요.
동생으로서 오빠를 믿어주세요.

그레텔
훌쩍. 으... 응... 알았어...!

== 가시나무 성

헨젤
―동생과 함께 집으로 돌아가는 중,
갑자기 유괴범이 나를 어디론가 데려와 버렸어.

헨젤
아무래도 그 녀석들은 나를 노예로 팔아 버릴
생각이었던 것 같지만 나는 기회를 봐서 간신히
유괴범들한테서 도망치는 데 성공했어.

헨젤
하지만 유괴범들이 집요하게 쫓아오는 바람에
숨을 수 있는 곳은 이 성 밖에 없었지.
어떤 전설이 남아 있는 이 저주 받은 성 밖에...

헨젤
나중에 그레텔이 올 수 있는 단서를 남겨 놨지만
정말 이런 곳에 동생이 와도 괜찮을까...―

헨젤
[운명의 서]에 따르면 용사 마리가
곧 그레텔을 데리고 여기로 올 텐데...

헨젤
아... 걱정 된다... 걱정 되....
쿠키 말고 다른 단서를 놓고 올 걸 그랬나...
쿠키는 누가 주워먹을 지도 모르잖아...
※플레로의 실수

그레텔
오빠!

헨젤
...그레텔?
이 목소리는 그레텔이니!?

그레텔
다행이야. 오빠...
다시 만났어...

헨젤
자자, 울지 마... 그레텔.
분명히 우리는 다시 만날 수 있다고
[운명의 서]에도 쓰여져 있었잖아?

헨젤
...혹시 여러분이 용사 마리 일행이신가요?

엑스
아니야. 사실 우리도 용사 마리를 찾고 있어.
성냥을 파는 여자아이한테 계시를 부탁 받아서...
네가 헨젤이지?

헨젤
네. 맞아요. 그렇구나. [운명의 서]와 다른 일도
일어나는구나.... 여러분. 동생을 여기까지 데려와
주셔서 감사합니다.

타오
...그건 그렇고 상당히 기분 나쁜 성이네.
여기는 어디지?

헨젤
이 곳은 가시나무 성이에요. 혹시 알고 계신가요?
백 년 동안 잠들게 된 잠자는 숲 속의 공주가
이 성에 있다는 전설이 있어요.

셰인
가시나무... 성이요?
...그런 것 치고는 가시나무 그림자도 형태도
안 보이는데요.

레이나
잠깐만.
가시나무 성이 성냥팔이가 말했던 그 성 아니야?

엑스
가시나무 성의 잠자는 공주... 용기 있는 동료 중
한 명이었지? 그 사람만 찾으면 동료 전원이 모이는군.
여전히 용사 마리의 행방은 알 수 없지만...

타오
그럼 잘 됐군. 어차피 동료는 모아야 하니까.
이 기회에 얼른 잠자는 숲 속의 공주인지 뭔지도
만나 보자고.

헨젤
저... 저기... 저희도 도와 드릴게요!
이건 저희와도 관련된 문제니까요.
그레텔. 괜찮지?

그레텔
응. 오빠랑 같이 있으면
난 괜찮아!

셰인
그럼 만나러 가볼까요?
백 년 동안 잠만 자고 있는 공주님을.

***

레이나
아무래도 잠자는 숲 속의 공주는 이 방에 있는 것 같아.
그런데 백 년이나 잠들어 있는 공주님을 어떻게
깨워야 되는 거야?

헨젤
분명히 전설에서는 공주가 진실한 사랑으로
깨어날 수 있다고 했어요. 공주를 사랑하는 사람이
입을 맞추면 눈을 뜰 거라고...

엑스
공주를 사랑하는 사람이라...
그럼 그 사람을 찾아야 되는구나...
역시 공주님과 어울릴만한 사람이라면 왕자님이려나?

셰인
아니요. 잠깐만요.
백 년을 잠들어 있던 사람이잖아요?
그럼 공주를 아는 사람들은 이미 죽었겠죠?

셰인
얼굴도 성격도 모르는 사람을 어떻게 사랑할 수
있겠어요? 그런데도 사랑을 떠들어대는 녀석이 있다면
그거야말로 수상쩍은데요.

헨젤
그... 그렇지만...
전설에는 그렇게 나와 있는데...

레이나
셰인이 말한 대로야.
내가 공주라면 그런 상대는 절대로 사양하겠어.

타오
에이, 아무려면 어때.
결국은 키스하면 되는 거잖아?
우리 중에서 누군가가 키스하면 되지.

레이나
무슨 소리를 하는 거야!
키스만 하면 뭐든 해결될 거라는 발상 자체가 잘못됐어!
첫 키스를 우습게 생각하지 마!

그레텔
오빠... 저사람들 무슨 얘기 하는 중이야?

헨젤
으음... 글쎄......?

***

엑스
자... 잠깐만. 다들.
어린 아이들이 있는데 그런 얘기는 좀...

셰인
그럼 신참 씨가 키스하세요.

엑스
어째서 나야!?

타오
뭐 어때. 안 일어나면 안 일어나는대로 상대방은
눈치채지도 못할 테고 눈 뜨고 난 후 사과하면
아마 용서해 줄 걸. 안 그래?

레이나
타오! 너 아까부터 말하는 게 저질이야!
그리고 굳이 키스 상대로 엑스를
고를 필요는 없잖아...

????
시끄러워어어어~~!!
사람이 푹 자고 있는데 왜 이렇게 떠들어대!
여기는 내 성이라고!

레이나
당신은... 설마...!

????
그래. 맞아. 내가 잠자는 숲 속의 공주야.
그렇게 안 떠들어도 벌써 옛날에 깨어났거든...

***

잠자는 숲 속의 공주 ※장미 공주
―어떤 저주에 걸려 나는 백 년을 잠들어 있었어.
그리고 백 년째 되는 어느 날 운명의 왕자님이
내게 와서 잠을 깨우는 키스를 했지.

잠자는 숲 속의 공주
그리고 나와 왕자님이 맺어져서 행복하게 살았습니다...
는 커녕 내 운명은 이런 타이밍에서 안 끝나더라고.

잠자는 숲 속의 공주
백 년의 세월이 흐르면서 세상에는 내가 모르는 게
넘쳐났고 내가 이해할 수 없는 신념이 존중받고 있었어.

잠자는 숲 속의 공주
세월은 너무나 잔인했고.
나는 그 흐름을 따라갈 수가 없었지.
그래서 난...―

셰인
이 성에 혼자 틀어박히게 된 거군.
그래서 이 성에 가시나무가 안 보인 거군요.
이미 저주가 풀렸으니까.

잠자는 숲 속의 공주
왕자님은 몇 번이나 나를 사랑한다고 말해줬지...
그 사랑은 진짜일 거라고 생각하지만 세상에는
사랑만으로는 어쩔 수 없는 게 있거든...

그레텔
흐음. 잘 모르겠지만 공주님도 고생이구나.
사탕 줄 테니까 힘 내.

잠자는 숲 속의 공주
...고마워. 잘 먹을게.

헨젤
잠자는 숲 속의 공주님.
당신의 [운명의 서]에도 쓰여져 있을 거예요.
우리와 함께 세계를 구하는 여행을 떠나 주시겠어요?

잠자는 숲 속의 공주
그건 안 돼. 내가 따라가는 건 용사 마리거든.
다른 사람을 따라가라는 얘기는 [운명의 서]에 없었어.

헨젤
그럴 수가...
그야 이 사람들은 용사가 아니지만
그래도 여행을 떠나는 게 우리의 운명이에요...!

잠자는 숲 속의 공주
하암~ 오랜만에 떠들었더니 졸리네.
용사 마리가 오면 다시 깨워 줘. 그럼...

타오
겁낼 필요 없어. 잠자는 숲 속의 공주님.

잠자는 숲 속의 공주
겁낸다고?
내가 뭘 겁낸다는 거야?

타오
당신 마음을 전부 안다고는 못 하겠어.
하지만 백 년이나 지나면 잘 알던 풍경도 변해 버리지.
그걸 두렵다고 생각하는 건 자연스러운 일이야.

타오
그런데 백 년이 지나도 의외로 중요한 건
전혀 안 변하기도 하거든.
어때? 나랑 같이 바깥 세계를 보러 가자고.

잠자는 숲 속의 공주
......당신과 같이?

***

레이나
...저기. 전혀 이해가 안 되는데.
방금 전에는 실컷 저질 발언만 해대던 녀석이
왜 공주님과 그럴듯한 분위기에 빠진 거야?

셰인
신기하네요. 사실 셰인도 지금 똑같은 생각을 했어요.

​ +
둘 다 얼굴이 무서워...
※아마 이름 누락은 공식의 실수: 엑스

***

잠자는 숲 속의 공주
...헨젤과 그레텔... 이었던가.

헨젤
네... 네!

잠자는 숲 속의 공주
너희는 내 방에서 기다려 줄래?
꼭 확인하고 싶은 장소가 있거든.

그레텔
힝... 왜!?
그레텔도 가고 싶어!

헨젤
자... 잠깐... 그레텔...
알겠습니다. 자리를 비우신 동안 저희가 성을 지킬게요.

잠자는 숲 속의 공주
고마워. 착한 아이들이구나...

타오
일부러 남매를 두고 올 만큼 위험한 장소야?

잠자는 숲 속의 공주
여기보다 북쪽에 있는 동굴... 그 곳에 가면 우리가
싸워야 할 상대의 정체를 알 수 있을 지도 몰라.
나랑 같이 가 줄래?

타오
그야 물론이지!

엑스
―잠자는 숲 속의 공주를 설득하는 데 성공한 우리는
헨젤과 그레텔을 성에 남겨 두고 북쪽 동굴로 떠났다.

엑스
그 동굴에 잠들어 있다는
멸망의 용의 존재를 확인하기 위해서...―

== 봉인의 동굴

엑스
―잠자는 숲 속의 공주의 안내를 따라서 우리는
북쪽 동굴 깊은 곳에 다다랐다.

엑스
그 곳에서 본 건 무참하게 부서진
사당의 남은 조각들이었다.―

잠자는 숲 속의 공주
이럴 수가... 어떻게 이런...
용들의 봉인이 깨졌어...!

타오
흐음. 그 용이라는 게 대체 뭐야?
그 녀석이 세계를 습격하는 재앙이야?

잠자는 숲 속의 공주
몇 백 년 전에 세계를 멸망시킬 뻔한 존재야.
선조께서 죽음을 각오하고 이 동굴 사당에 봉인했다고
들었어.

잠자는 숲 속의 공주
용이 봉인된 후에도 용을 따르는 마녀들이
자손인 나한테까지 저주를 걸었어.
그리고 천천히 자신들이 깨어날 준비를 해온 거야.

잠자는 숲 속의 공주
내가 눈을 떴을 때 세계는 아직 평화로웠어.
그래서 아직 용도 봉인되어 있을 거라고 생각했는데...

셰인
그러고 보니 그레텔도 과자집에서
마녀를 만났다고 했어요.
어쩌면 그 마녀가 용의 추종자였을지도 모르겠네요.

셰인
잠자는 숲 속의 공주님이 왜 여기로 데려왔는지
알겠어요. 그건 그렇다 치고 한 가지 물어봐도 될까요?

셰인
타오 오빠랑 너무 붙어 있는 거 아니에요?

잠자는 숲 속의 공주
어... 어머... 그랬나...
미안해. 타오.

타오
하하. 괜찮아.
밖에 나오는 게 오랜만이라 그럴 거야.
나라도 괜찮다면 도와줄게.

잠자는 숲 속의 공주
타오도 참...

셰인
빠직

레이나
진정해. 셰인.
지금은 짜증낼 때가 아니야.

엑스
그래. 세계의 운명이 걸려 있어...
그 용과 어떻게 싸워야 되는 거지...

레이나
아니. 용사 마리 얘기였어. 우리
아직 중요한 용사를 못 찾았잖아.

레이나
용이 날뛰기 전에 어떻게 해서든 용사 마리를
찾아내야 해... 안 그러면 상구의 운명은 이제
돌이킬 수 없을 거야...

헨젤
여러분. 큰일 났어요!

엑스
헨젤. 그레텔! 무슨 일이야?
성에서 기다리고 있는 거 아니었어?

그레텔
그게 문제가 아니야. 큰일났어!
드래곤이... 엄청 큰 드래곤들이
마을에서 날뛰고 있단 말야!

헨젤
이 동굴이 있는 방향에서 날아왔대!
그래서 여러분께 무슨 일이 생긴 건 아닐까
걱정 돼서요...!

잠자는 숲 속의 공주
설마 우리랑 엇갈린 건가...?
이런 곳에 있을 때가 아니야!
얼른 마을로 가야 되!
※플레로의 실수

타오
아가씨!

레이나
할 수 없지...!

== 성냥 팔이의 거리

엑스
―우리가 마을에 도착했을 때
주변은 활활 타오르는 불꽃으로 둘러싸여 있었다.

엑스
미친 듯이 날뛰는 용들.
그리고 영향을 받은 듯 빌런들도 섞여 있었다.

엑스
대체 어디까지 이 상구의 운명대로 흘러갈지
이제 우리는 알 수가 없다.

엑스
분명한 건 지금 여기서 어떻게든 하지 않으면
돌이킬 수 없는 파국으로 치닫게 된다는 것
뿐이었다.―

그레텔
오... 오빠...

헨젤
나한테서 떨어지지 마. 그레텔.
...잠자는 숲 속의 공주님.
우리가 맞서 싸워야 되는 거죠?

잠자는 숲 속의 공주
그래. 용사 마리와 함께.
하지만 용사는 아직 여기 없어...

***

엑스
어떻게 할 거야? 레이나. 우리가 싸우면
저 용들을 쓰러뜨릴 수 있을 지도 모르겠지만...

레이나
안 돼. 저 용들을 쓰러뜨리는 건 용사 마리의
역할이니까. 그걸 우리가 해 버리면
이 뒤틀린 상구는 영원히 돌이킬 수 없을 거야...!

타오
그렇다고 우리가 여기서 잠자코 보고만 있을 수도
없잖아. 우선 이 마을 사람들만이라도 살려야...
응? 왜 그래? 셰인.

셰인
...이 마을은 처음에 성냥팔이를 만났던 곳이죠?
지금도 이 마을 의사 선생님과 함께 있을 거예요.
어서 그 분도 구해야...

????
그럴 필요 없어!

레이나
너 벌써 일어나도 괜찮은 거야?
다행이야. 그럼 얼른 이 마을에서 도망쳐.
벌써 이 마을에는 드래곤과 빌런들이......

성냥팔이 소녀
...나는 몹시 가난한 성냥팔이 소녀.
아무도 돌아보지 않고 허무한 성냥불처럼
살아가는 게 내 운명이었지... 그래. 지금까지는.

성냥팔이 소녀
하지만 성냥팔이 소녀는 오늘 부로 끝났어!
천국에 계신 할머니의 계시를 들은 지금
오늘부터 나는 새로운 운명을 살아갈 거야!

성냥팔이 소녀
성스러운 화염이 깃든 용사 마리로서!

화염의 용사 마리
성스러운 화염이 깃든 용사 마리로서!

일행 전원
\........................

일행 전원
네가 용사였냐!!!!

레이나
...아. 그런데 냉정하게 생각해 보니까
[성냥팔이 소녀]는 이름이 아니잖아.
마리여도 이상할 게 없네...

타오
야, 용사!
네가 용사라면 왜 우리한테 그런 계시를 부탁한 거지?
동료를 모으는 건 네 역할이잖아.

화염의 용사 마리
죄송해요. 다들 좋은 사람이라
그런 식으로 부탁하면 맡아줄 거라고 생각했어요.
저... 감기 때문에 상태도 안 좋았잖아요...

셰인
노림수였군요.
나쁜 사람이네요.
하지만 뭐. 이제...

엑스
응. 간신히 우리도 걱정 없이 싸울 수 있어!

헨젤
드디어 만났네요.
우리는 계속 당신을 만날 날을 꿈꿔 왔어요.

그레텔
나는 용사가 좀더 왕자님 같은 사람일 거라고
생각했는데. 내 또래 여자아이 였구나...
응, 이게 더 좋아!

잠자는 숲 속의 공주
용사 마리...
당신에게 깃든 성스러운 화염으로 우리의 운명에
빛을 비춰주겠어요?

화염의 용사 마리
물론. 그러기 위해서 내가 여기 있는 거니까.
자, 다들! 함께 가자!
지금 이 순간, 전설을 시작하기 위해서!

***
*전투*

== 전설의 초원

엑스
―용을 쓰러뜨린 성냥 용사들.
마리, 그레텔, 헨젤, 잠자는 숲 속의 공주는
세계를 구한 작은 영웅으로서 사람들로부터 칭송받았다.

엑스
그 후에 그들 앞에는 과자집의 마녀가 남긴
괴물 초콜릿 좀비와의 사투나 잠자는 숲 속의 공주를
키워 준 요정들의 나라에서 일어난 음모.

엑스
그 밖에도 셀 수 없을 정도로 많은 모험이 펼쳐진다.
그들의 모험은 아직 끝나지 않는다.―

잠자는 숲 속의 공주
저기. 타오. 정말 가버리는 거야?
나... 당신만 좋다면 언제까지나 당신을 기다릴게...

타오
\............

셰인
자, 자, 그만. 그만 하세요.
타오 오빠에게는 중요한 사명이 있거든요.
그렇죠? 타오 오빠.

타오
그래, 셰인. 나한테는 너무 과분해.
당신은 당신대로 행복해져야 돼. 알겠지?
잠자는 숲 속의 공주님.

잠자는 숲 속의 공주
...그래.
정말 바보같은 사람이야, 알았어.
당신이 말하지 않아도 행복해질 거야... 훌쩍...

***

그레텔
저기... 엑스 오빠들
정말로 벌써 가는 거야...?

헨젤
그래요. 이렇게 신세를 많이 졌는데...
우리는 아직 답례도 전혀 못 했어요...

엑스
이 세계에서 우리 역할은 이제 끝났거든.
괜찮아. 너희들이라면 앞으로 무슨 일이 있어도
이겨낼 수 있어.

레이나
맞아. 이 상구에는 뭐니뭐니해도
의지할 수 있는 용사님도 있잖아.

화염의 용사 마리
...제가 성냥팔이 소녀였던 시절에 곧잘 성냥에
불을 붙이면서 꿈을 꿨어요.

화염의 용사 마리
여러 장소에서 동료들과 모험을 펼치는 제 모습.
예전의 차가운 하늘이 아니라 따뜻한 태양 아래를
걷고 있는 제 모습을요.

화염의 용사 마리
하지만 이제 저는 성냥에 불을 켜고 꿈을
꾸지 않아도 되죠.... 드디어 이 발로
그 시절 꿈꿨던 곳에 한 걸음 내디뎠으니까요.

화염의 용사 마리
저... 열심히 할게요...
앞으로도 용사로서 모두에게 꿈을
전해줄게요!

엑스
그래, 힘내렴.
화염의 용사님.

엑스
―그렇게 우리는 그들의 배웅을 받으며
그들이 있는 상구를 떠났다.

엑스
헨젤, 그레텔, 잠자는 숲 속의 공주.
그리고 성냥팔이 소녀... 아니 화염의 용사 마리.

엑스
작은 용사들의 전설은 이제
막 시작되었다.―