= 8.2. 욕망의 날개·불사조 위전
:hardbreaks:

== 초급 집념 개막 엑스 편
=== 욕망의 거리

엑스
――이 세계에는 『영원한 생명』을 품은 괴물이 있다.
그 괴물에게는 불로불사의 힘이 깃들어 있으며,
괴물을 쓰러뜨린 자에게는 그 힘이 주어진다고 한다.

엑스
도착한 상구에서 우리는 그런 소문을 들었다.
그리고 소문을 쫓아, 그 상구에는 우리 말고도
수많은 『공백의 서』 소유자들이 모여 있었다.

엑스
그들은 불로불사의 힘을 원하며 괴물을 찾아다녔다.
사람들의 욕망은 상구의 운명을 어지럽혔고, 그 결과,
상구에 수많은 빌런을 불러들이고 말았다.

엑스
사태를 수습하려는 우리였지만,
불로불사를 갈구하는 사람들의 욕망은 작열하는 불꽃이 되어
점점 더 타오르며 번져가려 하고 있었다…―――

*

빌런
크르르… 크르르…

엑스
안 돼, 여기도 빌런들이 있어…
이래서는 모두와 만나기로 한 장소에도 도착할 수 없어…!

엑스
이렇게 된 이상, 나 혼자서라도 저 녀석들을 상대해서…!

빌런
크르윽!?
크르르우!!

엑스
뭐지, 저건…
하늘이 타고 있어…?

엑스
…아니야!
저건, 새다!

=== 밤하늘

????
욕심 많은 인간들아,
한정된 운명에 겁에 질린 자들아.
네놈들, 불로불사의 힘을 원하느냐?

????
그렇다면 이 몸과 싸워 그 강함을 증명해 봐라.
강함의 증표인 스코어를 높인 자에게만,
이 몸이 불로불사의 힘을 내려주마.

????
자, 축제를 시작하자고!
욕망의 불꽃을, 생명의 불꽃을 이 땅에 타오르게 해라!

=== 욕망의 거리

엑스
저게 불로불사의 괴물… 『불꽃의 불사조』!
……상상했던 것보다 성격이 거칠어 보이지만.

엑스
빌런도 사라졌어…
이 틈에 모두와 합류하자!

엑스
――그로부터 얼마 지나지 않아, 우리는 합류했다.

엑스
그리고 사람들을 욕망으로 내모는 불사의 괴물,
『불꽃의 불사조』를 뒤쫓기 시작했다…―――

== 초급 집념 개막 레이나 편
=== 욕망의 거리

레이나
――이 세계에는 『영원한 생명』을 품은 괴물이 있어.
그 괴물에게는 불로불사의 힘이 깃들어 있으며,
괴물을 쓰러뜨린 자에게는 그 힘이 주어진다고 해.

레이나
도착한 상구에서 우리는 그런 소문을 들었어.
그리고 소문을 쫓아, 그 상구에는 우리 말고도
수많은 『공백의 서』 소유자들이 모여 있었지.

레이나
그들은 불로불사의 힘을 원하며 괴물을 계속 찾아다녔어.
사람들의 욕망은 상구의 운명을 어지럽혔고, 그 결과,
상구에 수많은 빌런을 불러들이고 말았지.

레이나
어떻게든 사태를 막으려는 우리였지만,
불로불사를 갈구하는 사람들의 욕망은 작열하는 불꽃이 되어
점점 더 타오르며 번져가고 있었어…―――

레이나
…이상하네.
합류 장소는 이 근처일 텐데,
아직 아무도 없다니…

레이나
설마 모두에게 무슨 일이 생긴 걸까…
어떡하면 좋지… 찾아봐야 하나… 여기서 기다려야 하나…
하지만 거리에는 빌런도 있고…

레이나
뭐지, 저 빛은…
하늘이 타고 있어…?

레이나
…그렇구나.
저 녀석이구나. 소문의 괴물이라는 게…!
불사의 괴물, 『불꽃의 불사조』……

=== 밤하늘

????
욕심 많은 인간들아,
한정된 운명에 겁에 질린 자들아.
네놈들, 불로불사의 힘을 원하느냐?

????
그렇다면 이 몸과 싸워 그 강함을 증명해 봐라.
강함의 증표인 스코어를 높인 자에게만,
이 몸이 불로불사의 힘을 내려주마.

????
자, 축제를 시작하자고!
욕망의 불꽃을, 생명의 불꽃을 이 땅에 타오르게 해라!

=== 욕망의 거리

레이나
무슨 생각인 거야, 저 녀석.
일부러 소동을 키우는 짓을 하다니…
이대로라면 점점 더 상구의 혼란이 커질 거야…!

레이나
아무튼 빨리 모두와 합류해야 해…!
그런데 도대체 다들 어디에――― 
………어라?

레이나
장소를 잘못 찾았어!

레이나
――그로부터 잠시 후, 나는 어떻게든
동료들과 합류했다.

레이나
그리고 모든 열쇠를 쥔 괴물, 『불꽃의 불사조』를
쫓아, 우리는 싸움의 소용돌이 속으로
뛰어들었다…―――

== 초급 집념 개막 타오 편
=== 욕망의 거리

타오
――이 세계에는 『영원한 생명』을 품은 괴물이 있다.
그 괴물에게는 불로불사의 힘이 깃들어 있으며,
괴물을 쓰러뜨린 자에게는 그 힘이 주어진다는 모양이다.

타오
도착한 상구에서 우리는 그런 소문을 들었다.
그리고 소문을 쫓아 상구에는 우리 말고도
『공백의 서』 소유자들이 잔뜩 모여 있었지.

타오
놈들은 불로불사의 힘을 원하며 괴물을 계속 찾아다녔다.
그 욕망은 상구의 운명을 어지럽혔고, 그 결과,
상구에 수많은 빌런을 불러들이고 말았지.

타오
사태를 막으려고 버티는 우리였지만,
불로불사를 갈구하는 놈들의 욕망은 작열하는 불꽃이 되어
점점 더 타오르고 있었다…―――

*

빌런
크르르우…!!

타오
어이, 방해된다! 피라미 녀석들!

타오
나 원 참, 거리도 온통 빌런에게 먹혀버렸구먼.
아가씨네는 괜찮으려나? 여기서 한바탕 화끈하게
날뛰어서, 내가 여기 있다는 어필을 좀…

타오
앙? 뭐야, 저 빛은?
하늘이 타고 있는 건가…?

=== 밤하늘

????
욕심 많은 인간들아,
한정된 운명에 겁에 질린 자들아.
네놈들, 불로불사의 힘을 원하느냐?

????
그렇다면 이 몸과 싸워 그 강함을 증명해 봐라.
강함의 증표인 스코어를 높인 자에게만,
이 몸이 불로불사의 힘을 내려주마.

????
자, 축제를 시작하자고!
욕망의 불꽃을, 생명의 불꽃을 이 땅에 타오르게 해라!

=== 욕망의 거리

타오
이봐 이봐, 더 화끈한 녀석이 있잖아.
저게 그 괴물, 『불꽃의 불사조』였나?
어쩐지 시끄러운 새구먼…

타오
앗차, 이러고 있을 때가 아니지.
빌런 녀석들도 퇴각하는 이 틈에,
얼른 아가씨네가 있는 곳으로 가야겠어!

타오
――그로부터 잠시 후, 나는
아가씨, 꼬맹이, 셰인과 합류했다.

타오
그리고 저 괴물, 『불꽃의 불사조』가 시작한
축제 속으로 뛰어들었다―――

타오
자, 어디 한번 즐겁게 해달라고!

== 초급 집념 개막 셰인 편
=== 욕망의 거리

셰인
――이 세계에는 『영원한 생명』을 품은 괴물이 있어요.
그 괴물에게는 불로불사의 힘이 깃들어 있으며,
괴물을 쓰러뜨린 자에게는 그 힘이 주어진다는 모양이에요.

셰인
그런 소문을 들은 건 여행 중인 상구에서였죠.
소문을 쫓아 상구에는 『공백의 서』 소유자들이
잔뜩 모여 있었어요. 다들 한가한가 보죠?

셰인
한가한 사람들은 불로불사의 힘을 원하며 괴물을 계속
찾아다녔죠. 그 욕망은 상구의 운명을 어지럽혔고,
그 결과 빌런까지 불러들이고 만 거예요.

셰인
언제나 그렇듯 휘말리는 셰인 일행.
여러모로 손을 써봤지만, 한가한 분들의
욕망은 점점 더 타오르기만 할 뿐.

셰인
어쩐지 상구 전체를 엄청나게 기분 나쁜 공기가
휘감기 시작한 거예요.
자자, 어떻게 되려나…―――

셰인
그 괴물 씨를 찾으러 온 건 좋은데,
사방이 빌런투성이네요.
이건 좀 힘들지도 모르겠어요.

셰인
적어도 언니나 신참 씨 일행과 합류할 수 있으면,
좋겠는데 말이죠…

셰인
어라? 하늘이 빛나고 있나?
신형 불꽃놀이인가요?

셰인
…아뇨, 아니네요.
어쩐지 좀 더 기분 나쁜 느낌의 무언가네요…

=== 밤하늘

????
욕심 많은 인간들아,
한정된 운명에 겁에 질린 자들아.
네놈들, 불로불사의 힘을 원하느냐?

????
그렇다면 이 몸과 싸워 그 강함을 증명해 봐라.
강함의 증표인 스코어를 높인 자에게만,
이 몸이 불로불사의 힘을 내려주마.

????
자, 축제를 시작하자고!
욕망의 불꽃을, 생명의 불꽃을 이 땅에 타오르게 해라!

=== 욕망의 거리

셰인
과연, 저게 소문의 괴물 씨,
 『불꽃의 불사조』군요. …상상했던 것보다
잔챙이 냄새가 풀풀 풍기네요.

셰인
아무래도 소동은 이제부터가 본방인 모양이에요.
얼른 언니 일행이 있는 곳으로 갈까요.

셰인
――그 후, 언니나 신참 씨, 타오 오빠와도
합류한 셰인 일행은 축제의 불을 끄기
위해 괴물 씨를 뒤쫓기 시작합니다.

셰인
불로불사에는 전혀 관심 없지만,
역시 그냥 내버려 둘 수는 없으니까요―――

== 초급 집념 종막
=== 욕망의 거리

타오
헤, 이걸로 끝이냐?
『불꽃의 불사조』라는 것도 별거 아니구먼.
불사의 괴물이라더니 이름값이 아깝군…

레이나
…!?
잠깐! 불사조의 몸을 봐!
갑자기 타오르더니…!

*

불꽃의 불사조
이 몸의 생명의 불꽃을 껐다고 생각했느냐?
이 불사조, 이 정도로 멸망하지는 않는다.

셰인
새 주제에 나불나불 잘도 떠드네요.
꼬치구이로 만들어서 먹어버릴까요.
아, 이미 구워져 있었던가요.

엑스
모두 조심해.
저 녀석, 분명 또 뭔가를 꾸미고…

불꽃의 불사조
흥, 하나 마나 한 조언이구나.
동료들 사이에서 우등생인 척하고 싶은 거냐?
모브 얼굴 검사.

엑스
엣.

불꽃의 불사조
거기 아가씨도, 「1인칭이 자기 이름」인 캐릭터가
허용되는 건 지금뿐이다. 앞날을 위해서
캐릭터의 방향성을 다시 생각해보는 게 좋을 거다.

불꽃의 불사조
열혈 바보랑 어느 쪽이 더 심한지는 막상막하다만.
분하다면 이번엔 제대로 이 몸을 숨통을 끊어보라고.

셰인
……하아?

타오
……뭐라고?

레이나
모두, 도발에 넘어가면 안 돼!
상대의 의도대로 되는 거야! 유감스럽지만 나한테 그런 수법은
안 통하거든. 내 그릇의 크기를 뼈저리게 느끼게――

불꽃의 불사조
…………

레이나
말 좀 하라고오오오오오오!

레이나
잠깐만. 진짜로 가버렸는데!
나만 무시하는 거야!?

엑스
…자, 얘들아. 이제부터 어떻게 해줄까.

타오
아니 아니, 결정됐잖아, 무개성 검사.
오늘 밤은 기분 좋게 닭고기 전골로 가자고.
재료는 『불꽃의 불사조』가 어때?

셰인
최고네요, 타오 오빠.
불사라는 걸 후회할 때까지,
철저하게 조리해 주죠.

레이나
저 새를 다른 누구에게 넘겨줄 순 없지…
저 녀석만은 반드시 우리가 처리하겠어!!

== 중급 욕망 개막
=== 욕망의 숲

레이나
자, 저 불사조를 쫓아 여기까지 왔는데,
우선 상황을 정리하자.
확인 첫 번째, 우리가 해야 할 일은?

셰인
저 새 자식을 누구보다 빨리 때려눕히는 것.
하지만 상대는 불사의 괴물이니 평범한 방법으로는
쓰러뜨릴 수 없죠. 승패의 열쇠를 쥔 건 스코어, 맞죠?

타오
그래. 녀석과는 몇 번이고 싸우게 될 것 같으니까.
그래서 스코어를 벌기 위해 약점을 찌르거나,
여러 가지 싸우는 법을 시험해 볼 필요가 있어.

타오
여기서 확인 두 번째.
녀석의 근본적인 약점은?

엑스
불타고 있으니까… 역시 얼음 같은 거?

셰인
단순하지만 아마 그렇겠죠.
자, 확인 세 번째입니다.
저 새 자식은 지금 어디에?

레이나
목격 정보에 따르면 이 숲 어딘가에 있어.
하지만 빌런들도 끊임없이 튀어나오니까,
그쪽도 상대해야 해.

엑스
그럼 마지막으로 확인 네 번째.
준비는 다 됐어?

타오
물을 것도 없잖아.
자, 저 새 녀석의 코를 납작하게 해주자고.

== 중급 욕망 종막

*

=== 욕망의 숲

엑스
아무래도 정말 불사신인 모양이네.
쓰러뜨려도, 쓰러뜨려도 몇 번이고 부활해…

타오
저렇게 보니 불로불사라는 것도 편리하구먼.
얼마든지 강한 녀석이랑 싸울 수 있으니까 말이야.

셰인
그렇다면 셰인은 끝없이 무기를 만지작
거리고 싶네요.
여러 가지 커스터마이즈를 시험해 보고 싶어요.

레이나
너희 둘은 좀 더 다른 데
쓸 곳이 없는 거야…

셰인
그러는 언니는 불로불사의 힘을 손에 넣으면
어떻게 할 건가요?

레이나
에? 
으음……
…………세계 평화?

엑스
…우리에게는 딱히 필요 없을 것 같네,
불로불사.

== 상급 업화 개막 엑스 편
=== 욕망의 산

엑스
――― 『불꽃의 불사조』를 뒤쫓는 우리는
어느 산 중턱에 도착한다. 하지만 그곳에는 이미
다른 『공백의 서』 소유자들도 모여 있었다.

엑스
『불꽃의 불사조』를 둘러싸고 다투는 사람들.
욕망의 끝에 상처 입고 쓰러진 사람들의 모습으로
산길은 가득 메워지려 하고 있었다―――

타오
…나 원 참, 바보 같은 녀석들.
알지도 못하는 것 때문에
쓸데없는 피를 흘리지 말라고.

셰인
빌런도 꾸역꾸역 나타나고 있어요…
이건 서두르지 않으면 정말 큰일 나겠는데요…

레이나
엑스…

엑스
막아야 해…
이 다툼의 불꽃을 끌 수 있는 건 우리뿐이야…!

== 상급 업화 개막 레이나 편
=== 욕망의 산

레이나
――― 『불꽃의 불사조』를 뒤쫓는 우리는
어느 산 중턱에 도착했어. 하지만 그곳에는 이미
다른 『공백의 서』 소유자들도 모여 있었지.

레이나
모두 『불꽃의 불사조』를 둘러싸고 서로 다투었어.
욕망의 끝에 상처 입고 쓰러진 사람들의 모습으로
산길은 가득 메워지려 하고 있었어―――

타오
…나 원 참, 바보 같은 녀석들.
알지도 못하는 것 때문에
쓸데없는 피를 흘리지 말라고.

셰인
빌런도 꾸역꾸역 나타나고 있어요…
이건 서두르지 않으면 정말 큰일 나겠는데요…

레이나
엑스…

엑스
막아야 해…
이 다툼의 불꽃을 끌 수 있는 건 우리뿐이야…!

== 상급 업화 개막 타오 편
=== 욕망의 산

타오
――― 『불꽃의 불사조』를 뒤쫓는 우리는
어느 산 중턱에 도착했다. 그곳에는 『불사조』를
찾는 다른 녀석들이 바글바글 모여 있었지.

타오
『불꽃의 불사조』를 둘러싸고 서로 다투는 바보들.
욕망의 끝에 상처 입고 쓰러진 녀석들의 모습으로
산길은 가득 메워지려 하고 있었다―――

타오
…나 원 참, 바보 같은 녀석들.
알지도 못하는 것 때문에
쓸데없는 피를 흘리지 말라고.

셰인
빌런도 꾸역꾸역 나타나고 있어요…
이건 서두르지 않으면 정말 큰일 나겠는데요…

레이나
엑스…

엑스
막아야 해…
이 다툼의 불꽃을 끌 수 있는 건 우리뿐이야…!

== 상급 업화 개막 셰인 편
=== 욕망의 산

셰인
――― 새 자식 씨를 뒤쫓는 셰인 일행은
산 중턱에 도착합니다. 그곳에는 『불꽃의 불사조』를
찾는 한가한 분들이 잔뜩 모여 있었습니다.

셰인
『불꽃의 불사조』를 둘러싸고 서로 다투는 한가한 분들.
욕망의 끝에 모두 쓰러져 가고, 축제는 점점 더
안 좋은 방향으로 타오르며 번져갑니다―――

타오
…나 원 참, 바보 같은 녀석들.
알지도 못하는 것 때문에
쓸데없는 피를 흘리지 말라고.

셰인
빌런도 꾸역꾸역 나타나고 있어요…
이건 서두르지 않으면 정말 큰일 나겠는데요…

레이나
엑스…

엑스
막아야 해…
이 다툼의 불꽃을 끌 수 있는 건 우리뿐이야…!

== 상급 업화 종막
=== 욕망의 산

불꽃의 불사조
정말 바보들뿐이군, 인간들이란.
불로불사라는 감당하지도 못할 힘을
갈구하며 이렇게 서로 상처 입히고 있다니.

불꽃의 불사조
너희도 그렇게 생각하지 않느냐?

엑스
이제 그만해, 불사조.
이런 싸움에 무슨 의미가 있는 거야…

레이나
분히 이 싸움에 도전한 사람들은 어리석을지도
모르지만, 그걸 부추긴 건 당신이야.
이대로라면 점점 돌이킬 수 없는 일이…

불꽃의 불사조
상관없다, 그걸로.
――― 그것이 이 세계의 운명이니까.

엑스
…그게 무슨 소리야?

불꽃의 불사조
말 그대로의 의미다. 이 세계는
불로불사의 상징인 『불꽃의 불사조』를 갈구하며,
다투고 멸망하기를 반복한다. 그것이 이 상구다.

불꽃의 불사조
『불꽃의 불사조』는 결코 사람 앞에 모습을 드러내지 않지.
사람들은 불로불사라는 가짜를 쫓으며,
서로 죽이고 멸망해 간다.

불꽃의 불사조
멸망 뒤에 남는 것은 폐허라는 이름의 재뿐.
그리고 재 위에서 사람들은 다시 일어나 나라를
부흥시키지. 마치 『불꽃의 불사조』처럼 말이야.

타오
말은 잘하는구먼.
그보다 너, 모습을 드러내지 않는다면서 지금 여기
나타나 있지 않느냐.

불꽃의 불사조
케케케, 글쎄다.
멸망을 부추긴다는 의미에선 제대로 역할을
다하고 있으니, 괜찮지 않으냐?

레이나
그래도 정도가 있지. 당신의 부추김 때문에
『공백의 서』 소유자들까지 이 상구에 몰려들고,
빌런까지 발생하고 있잖아.

셰인
말해두겠는데, 이대로 빌런을 내버려 두면
이 상구가 어떻게 될지 모른다고요?
재생할 수 없게 되어도 좋은 건가요?

불꽃의 불사조
상관없다. 그것이야말로 인간들이 스스로 선택한,
운명의 결말이라는 것이니까.

레이나
…그 결말을 바꾸려면 어떻게 해야 하지?

불꽃의 불사조
답은 이미 알고 있지 않느냐?
이 몸을 쓰러뜨려라. 북쪽 거리 광장에서,
거기서 결판을 내도록 하지.

엑스
…그런 결말, 절대로 용납 못 해.
불사조를 이번에야말로 쓰러뜨리겠어…!

== 초급 비상 개막 엑스 편
=== 멸망의 광장

불꽃의 불사조
여기까지 끈질기게 쫓아온 너희의 집념의 불꽃,
정말 대단하구나…. 자, 멸망을 향해
마지막 불꽃을 태워보자고!

엑스
우리가 끝내고 싶은 건 생명도, 세계도 아니야.
이 바보 같은 소동 그 자체다.
각오해라, 불사조!

== 초급 비상 개막 레이나 편
=== 멸망의 광장

불꽃의 불사조
여기까지 끈질기게 쫓아온 너희의 집념의 불꽃,
정말 대단하구나…. 자, 멸망을 향해
마지막 불꽃을 태워보자고!

레이나
당신의 제멋대로인 논리에 다른 사람들을
말려들게 하진 않겠어.
당신의 불꽃, 지금 여기서 꺼뜨려 주지!

== 초급 비상 개막 타오 편
=== 멸망의 광장

불꽃의 불사조
여기까지 끈질기게 쫓아온 너희의 집념의 불꽃,
정말 대단하구나…. 자, 멸망을 향해
마지막 불꽃을 태워보자고!

타오
이봐 이봐, 헛소리하지 마라. 네놈이 지핀
불의 책임 정도는 네놈이 스스로 지라고.

타오
네놈의 불장난도 이제 진절머리 난다.
여기서 결판을 내주마.

== 초급 비상 개막 셰인 편
=== 멸망의 광장

불꽃의 불사조
여기까지 끈질기게 쫓아온 너희의 집념의 불꽃,
정말 대단하구나…. 자, 멸망을 향해
마지막 불꽃을 태워보자고!

셰인
착각하시면 곤란한데, 딱히 당신의
축제 따위엔 관심 없습니다.

셰인
남의 삶을 비웃는 것밖에 할 줄 모르는
새 자식에게 한 방 먹여주는 것. 그뿐입니다.
자, 끝까지 상대해 드리지요.

== 초급 비상 종막 엑스 편
=== 멸망의 광장

불꽃의 불사조
…설마 불사인 이 몸으로
여기까지 몰릴 줄이야…

엑스
…결국 넌 무엇을 하고 싶었던 거야?
사람 앞에 모습을 드러내지 않는 게 본래의 불사조라면,
이런 소동을 일으킨 넌 정체가 뭐야?

불꽃의 불사조
…이봐, 인간들아. 너희는 스토리텔러에게서
 『운명의 서』를 받는 게 인간뿐이라고
생각하고 있지는 않느냐?

불꽃의 불사조
『운명의 서』는 영혼을 가진 모든 자에게 주어진다.
그리고 가끔 그중에는 운명이 텅 빈 자도
태어나지… 이 몸처럼 말이야…

엑스
그 말은 너도 『공백의 서』 소유자라는 거야?
그럼 불로불사의 힘을 준다는 건?

불꽃의 불사조
그런 거, 다 거짓말이다.
인간들을 부추기기 위한 방편이지.

불꽃의 불사조
아니면 선대 불사조라면 그런 것도 가능했을지
모르고, 받은 인간이 있었을지도 모르지.

불꽃의 불사조
하지만 이 몸의 서에는 그런 것조차도
적혀 있지 않았다.

불꽃의 불사조
아무리 상처 입어도 죽는 것조차 할 수 없어.
이런 지옥 같은 세계, 통째로 잿더미로 만들어버려도
상관없지 않느냐.

엑스
그래서 이런 빌런을 발생시키는 소동을
일으켰다는 거야? 자신과 함께 세계를 멸망시키려고…
그런 거, 용납될 리가 없어!

불꽃의 불사조
너희가 뭘 안다고! 불사조로 태어났으면서,
어떻게 살아야 할지도 모른다.
그런 이 몸의 기분을 너희가 알기나 하느냐!

불꽃의 불사조
이 몸은 불사조가 아니야… 불사조의 모습과 힘만
가지고 태어난, 어찌할 도리 없는 가짜다.
이런 지옥에서 어떻게 살아가라는 거냐…

엑스
…어떻게 살아야 할지 같은 건 간단해.
『공백의 서』 소유자니까,
스스로 운명을 선택하면 되는 거야.

엑스
어디까지든 날아갈 수 있는 날개가 있잖아.
상구 밖이라도, 원하는 곳으로 날아가면 돼.

불꽃의 불사조
…그런가. 고작 그것뿐이면 됐던 건가.
아무래도 정말 어리석었던 건
이 몸이었던 모양이군.

엑스
기다려, 어디로 가려는 거야?

불꽃의 불사조
너희의 삶을 흉내 낼 뿐이다.
다툼이 없는 세계로,
이 몸의 불꽃이 빛나는 곳으로 날아오를 뿐…

불꽃의 불사조
…또 어디선가 만나자고. 강한 여행자들이여.
잘 있어라.

*

엑스
――― 그렇게 말하고 불사조였던 존재는
상구를 떠나갔다.

엑스
불사조가 모습을 감추자 『공백의 서』
소유자들도 상구를 떠났고, 안정을 되찾은 상구에서
빌런의 모습도 사라져 갔다.

엑스
그래도 지금도 상구 사람들은 결코 모습을 드러내지 않는
『불꽃의 불사조』를 쫓으며 다툼을 반복하고 있다.

엑스
그리고 상구를 떠난 불사조가
그 후 어디로 사라졌는지.
그것을 아는 사람은 아무도 없다―――

== 초급 비상 종막 레이나 편
=== 멸망의 광장

불꽃의 불사조
…설마 불사인 이 몸으로
여기까지 몰릴 줄이야…

레이나
당신, 그랬었지.
『불꽃의 불사조』는 본래 사람 앞에 모습을 드러내지 않는다고.

레이나
그런데 당신은 반대로 사람들 앞에 나타나서
욕망을 계속 부추겼어. 도대체 왜?

불꽃의 불사조
…이봐, 인간들아. 너희는 스토리텔러에게서
 『운명의 서』를 받는 게 인간뿐이라고
생각하고 있지는 않느냐?

불꽃의 불사조
『운명의 서』는 영혼을 가진 모든 자에게 주어진다.
그리고 가끔 그중에는 운명이 텅 빈 자도
태어나지… 이 몸처럼 말이야…

레이나
그렇다면 당신도
『공백의 서』 소유자라는 거야?
그럼 불로불사 이야기는…

불꽃의 불사조
그런 거, 다 거짓말이다.
인간들을 부추기기 위한 방편이지.

불꽃의 불사조
아니면 선대 불사조라면 그런 것도 가능했을지
모르고, 받은 인간이 있었을지도 모르지.

불꽃의 불사조
하지만 이 몸의 서에는 그런 것조차도
적혀 있지 않았다.

불꽃의 불사조
아무리 상처 입어도 죽는 것조차 할 수 없어.
이런 지옥 같은 세계, 통째로 잿더미로 만들어버려도
상관없지 않느냐.

레이나
과연. 그래서 사람 앞에 나타나 『공백의 서』
여행자들까지 부추겨서 상구를 엉망으로 만들려고
한 거구나. 세계와 함께 자신을 멸망시키기 위해…

레이나
바보 같긴.
그래 봤자 아무것도 안 되는데…

불꽃의 불사조
너희가 뭘 안다고! 불사조로 태어났으면서,
어떻게 살아야 할지도 모른다.
그런 이 몸의 기분을 너희가 알기나 하느냐!

불꽃의 불사조
이 몸은 불사조가 아니야… 불사조의 모습과 힘만
가지고 태어난, 어찌할 도리 없는 가짜다.
이 지옥에서 어떻게 살아가라는 거냐…

레이나
그렇다면 이 상구를 뛰쳐나가면 돼.
『공백의 서』 소유자는 원하는 세계, 원하는 운명을
스스로 선택해서 살아갈 수 있으니까.

레이나
적어도 우리는
그렇게 살아가고 있다고 생각해.

불꽃의 불사조
…그런가. 고작 그것뿐이면 됐던 건가.
아무래도 정말 어리석었던 건
이 몸이었던 모양이군.

불꽃의 불사조
그렇다면 이 날개로 날아오르도록 하지.
다툼이 없는 세계로,
이 몸의 불꽃이 빛나는 쪽을 향해서…

불꽃의 불사조
…또 어디선가 만나자고. 강한 여행자들이여.
잘 있어라.

*

레이나
――― 그렇게 말하고 불사조였던 존재는
상구를 떠나갔어.

레이나
불사조가 모습을 감추자 『공백의 서』
소유자들도 상구를 떠났고, 안정을 되찾은 상구에서
빌런의 모습도 사라져 갔지.

레이나
하지만 지금도 상구 사람들은 모습을 드러내지 않는 불새를
쫓으며 다툼을 반복하고 있어.

레이나
그리고 상구를 떠난 불사조가
그 후 어디로 사라졌는지.
행방을 아는 사람은 아무도 없어―――

== 초급 비상 종막 타오 편
=== 멸망의 광장

불꽃의 불사조
…설마 불사인 이 몸으로
여기까지 몰릴 줄이야…

타오
이봐, 너 결국 뭘 하고 싶었던 거냐?
이런 소동까지 일으키고 말이야. 애초에 너,
진짜로 『불꽃의 불사조』였긴 한 거냐?

불꽃의 불사조
…이봐, 인간들아. 너희는 스토리텔러에게서
 『운명의 서』를 받는 게 인간뿐이라고
생각하고 있지는 않느냐?

불꽃의 불사조
『운명의 서』는 영혼을 가진 모든 자에게 주어진다.
그리고 가끔 그중에는 운명이 텅 빈 자도
태어나지… 이 몸처럼 말이야…

타오
아― 그렇구먼…. 즉 너도 우리와
똑같은 『공백의 서』 소유자라는 거군.
그럼 그 불로불사를 준다는 건?

불꽃의 불사조
그런 거, 다 거짓말이다.
인간들을 부추기기 위한 방편이지.

불꽃의 불사조
아니면 선대 불사조라면 그런 것도 가능했을지
모르고, 받은 인간이 있었을지도 모르지.

불꽃의 불사조
하지만 이 몸의 서에는 그런 것조차도
적혀 있지 않았다.

불꽃의 불사조
아무리 상처 입어도 죽는 것조차 할 수 없어.
이런 지옥 같은 세계, 통째로 잿더미로 만들어버려도
상관없지 않느냐.

타오
그래서 바보들을 부추겨서 이 상구를 엉망으로
만들고 상구랑 같이 동반자살이라도 하려 했던 거냐.
너도 어지간히 큰 바보구먼.

불꽃의 불사조
너희가 뭘 안다고! 불사조로 태어났으면서,
어떻게 살아야 할지도 모른다.
그런 이 몸의 기분을 너희가 알기나 하느냐!

불꽃의 불사조
이 몸은 불사조가 아니야… 불사조의 모습과 힘만
가지고 태어난, 어찌할 도리 없는 가짜다.
이 지옥에서 어떻게 살아가라는 거냐…

타오
그러니까 네가 바보라는 거야. 이 세계가
마음에 안 들면 얼른 밖으로 뛰쳐나가면 되잖아.
굳이 이런 축제 같은 걸 벌이지 않아도 말이야.

타오
적어도 그쪽이
훨씬 마음은 가벼워질 거다?

불꽃의 불사조
…그런가. 고작 그것뿐이면 됐던 건가.
아무래도 정말 어리석었던 건
이 몸이었던 모양이군.

불꽃의 불사조
그렇다면 이 날개로 날아오르도록 하지.
다툼이 없는 세계로,
이 몸의 불꽃이 빛나는 쪽을 향해서…

불꽃의 불사조
…또 어디선가 만나자고. 강한 여행자들이여.
잘 있어라.

*

타오
――― 그렇게 말하고 불사조라고 자칭하던
대바보는 어디론가 날아가 버렸다.

타오
불사조가 모습을 감추자 떠들썩하던 바보들도
상구를 떠났고, 안정을 되찾은 상구에서는
빌런 녀석들의 모습도 사라져 갔다.

타오
하지만 지금도 상구에 사는 녀석들은
결코 사람 앞에 나타나지 않는 『불꽃의 불사조』를 두고
다툼을 반복하고 있다.

타오
그리고 상구를 떠난 저 녀석이
그 후 어디로 사라졌는지.
행방을 아는 녀석은 아무도 없다―――

== 초급 비상 종막 셰인 편
=== 멸망의 광장

불꽃의 불사조
…설마 불사인 이 몸으로
여기까지 몰릴 줄이야…

셰인
계속 의문이었는데, 당신 정말로
 『불꽃의 불사조』 씨 맞나요?

셰인
당신의 행동은 본래 불사조의 운명에서
한참 벗어나 있어요. 도대체 당신은
정말 누구인가요?

불꽃의 불사조
…이봐, 인간들아. 너희는 스토리텔러에게서
 『운명의 서』를 받는 게 인간뿐이라고
생각하고 있지는 않느냐?

불꽃의 불사조
『운명의 서』는 영혼을 가진 모든 자에게 주어진다.
그리고 가끔 그중에는 운명이 텅 빈 자도
태어나지… 이 몸처럼 말이야…

셰인
과연, 그런 거였나요. 셰인 일행과
똑같은 『공백의 서』 소유자 씨였군요.
그럼 저 불로불사를 준다는 건요?

불꽃의 불사조
그런 거, 다 거짓말이다.
인간들을 부추기기 위한 방편이지.

불꽃의 불사조
아니면 선대 불사조라면 그런 것도 가능했을지
모르고, 받은 인간이 있었을지도 모르지.

불꽃의 불사조
하지만 이 몸의 서에는 그런 것조차도
적혀 있지 않았다.

불꽃의 불사조
아무리 상처 입어도 죽는 것조차 할 수 없어.
이런 지옥 같은 세계, 통째로 잿더미로 만들어버려도
상관없지 않느냐.

셰인
그런 이기적인 화풀이에 남을 말려들게 하지
말아주세요, 라고 하고 싶지만 셰인도 예전에
그렇게 생각했던 시기가 있었으니까요…

셰인
동정을 바라는 건 아니겠지만,
뭐, 기분은 이해해요.

불꽃의 불사조
너희가 뭘 안다고! 불사조로 태어났으면서,
어떻게 살아야 할지도 모른다.
그런 이 몸의 기분을 너희가 알기나 하느냐!

불꽃의 불사조
이 몸은 불사조가 아니야… 불사조의 모습과 힘만
가지고 태어난, 어찌할 도리 없는 가짜다.
이 지옥에서 어떻게 살아가라는 거냐…

셰인
그렇다면 얼른 밖으로 날아가 버리면 어때요?
물론 밖에 나가면 여러 가지 고생은 하겠지만요.
모르겠지만요.

셰인
어쩌면 동료라는 걸
만날 수 있을지도 모르잖아요?
운이 좋다면 말이죠.

불꽃의 불사조
…그런가. 고작 그것뿐이면 됐던 건가.
아무래도 정말 어리석었던 건
이 몸이었던 모양이군.

셰인
가시는 건가요?

불꽃의 불사조
…이 세계에서 이 몸의 역할은 이제 끝이다.
다툼이 없는 세계로,
이 몸의 불꽃이 빛나는 쪽으로 날아가겠어…

불꽃의 불사조
…또 어디선가 만나자고. 강한 여행자들이여.
잘 있어라.

*

셰인
――― 그렇게 말하고 불사조라고 자칭하던
누군가는 어디론가 날아갔습니다.

셰인
불사조가 사라지고, 떠들썩하던 한가한 분들도
상구를 떠났고, 안정을 되찾은 상구에서는
빌런들의 모습도 사라져 갔습니다.

셰인
하지만 지금도 상구에 사시는 분들은
결코 사람 앞에 나타나지 않는 『불꽃의 불사조』를 두고
질리지도 않고 다툼을 반복하고 있다고 하네요.

셰인
그리고 상구를 떠난 저 새 자식 씨가
그 후 어디로 가버렸는지.
행방을 아는 사람은 아무도 없답니다―――