= 8.2. 욕망의 날개·불사조 위전 (欲望の翼・不死鳥偽伝)
:hardbreaks:

link:8.2..욕망의_날개·불사조_위전-Gemini.adoc[Gemini 번역]

== 初級　執念　開幕　エクス編
=== 欲望の街

エクス
ーーこの世界には『永遠の命』を宿した怪物がいる。
その怪物には不老不死の力が宿っており、
怪物を倒した者にはその力が授けられるという。

エクス
たどり着いた先の想区で僕らはそんな噂を耳にした。
そして噂をめぐり、その想区には、僕たち以外にも
大勢の『空白の書』の持ち主たちが集っていた。

エクス
彼らは不老不死の力を求め、怪物を探した。
人々の欲望は想区の運命をかき乱し、その結果、
想区にたくさんのヴィランを呼び寄せてしまった。

エクス
事態を収束しようとする僕たちだけど、
不老不死を求める人々の欲望は灼熱の炎となって
ますます燃え広がろうとしていた…ーーー

*

ヴィラン
クルル…クルル…

エクス
だめだ、ここもヴィランたちがいる…
これじゃあみんなとの合流場所にも辿り着けない…！

エクス
こうなったら、僕ひとりであいつらを相手して…！

ヴィラン
クルッ！？
クルルウ！！

エクス
なんだ、あれ…
空が、燃えている…？

エクス
…違う！
あれは、鳥だ！

=== 夜空

？？？？
欲深き人間ども、
限られた運命に怯える者どもよ。
てめーら、不老不死の力が欲しいのか？

？？？？
だったら、オレ様と戦い、その強さを示してみろ。
強さの証であるスコアを高めた者にだけ、
オレ様が不老不死の力を授けてやるよ。

？？？？
さぁ、祭りを始めようぜ！
欲望の炎を、命の炎をこの地に燃え上がらせろ！

=== 欲望の街

エクス
あれが不老不死の怪物…『炎の不死鳥』！
……想像していたのより、ガラが悪いけど。

エクス
ヴィランもいなくなった…
いまのうちにみんなと合流しよう！

エクス
ーーそれからほどなくして、僕たちは合流した。

エクス
そして人々を欲望に走らせる不死の怪物、
『炎の不死鳥』を追いかけ始めたんだ…ーーー

== 初級　執念　開幕　レイナ編
=== 欲望の街

レイナ
ーーこの世界には『永遠の命』を宿した怪物がいる。
その怪物には不老不死の力が宿っており、
怪物を倒した者にはその力が授けられるという。

レイナ
たどり着いた想区で私たちはそんな噂を耳にしたの。
そして噂をめぐり、その想区には、私たち以外にも
大勢の『空白の書』の持ち主たちが集っていた。

レイナ
彼らは不老不死の力を求め、怪物を探し続けた。
人々の欲望は想区の運命をかき乱し、その結果、
想区にたくさんのヴィランを呼び寄せてしまったの。

レイナ
なんとか事態を止めようとする私たちだけど、
不老不死を求める人々の欲望は灼熱の炎となって
ますます燃え広がっていたの…ーーー

レイナ
…おかしいわね。
合流場所はこのあたりのはずなのに、
まだ誰もいないなんて…

レイナ
まさかみんなの身になにかあったのかしら…
どうすればいいの…探すべきか…ここで待つべきか…
でも街にはヴィランもいるし…

レイナ
なにかしら、あの明かり…
空が、燃えている…？

レイナ
…そうか。
あいつなのね。噂の怪物っていうのは…！
不死の怪物、『炎の不死鳥』……

=== 夜空

？？？？
欲深き人間ども、
限られた運命に怯える者どもよ。
てめーら、不老不死の力が欲しいのか？

？？？？
だったら、オレ様と戦い、その強さを示してみろ。
強さの証であるスコアを高めた者にだけ、
オレ様が不老不死の力を授けてやるよ。

？？？？
さぁ、祭りを始めようぜ！
欲望の炎を、命の炎をこの地に燃え上がらせろ！

=== 欲望の街

レイナ
どういうつもりなのよ、あいつ。
わざわざ騒ぎを広げるような真似をして…
このままじゃますます想区の混乱は広がるわ…！

レイナ
とにかく早く、みんなと合流しないと…！
でもいったい、みんなはどこにーーー 
………あれ？

レイナ
場所、間違えた！

レイナ
ーーそれからしばらくして、私はどうにか
仲間たちと合流した。

レイナ
そしてすべての鍵を握る怪物、『炎の不死鳥』を
追って、私たちは戦いの渦中に
飛び込んでいった…ーーー

== 初級　執念　開幕　タオ編
=== 欲望の街

タオ
ーーこの世界には『永遠の命』を宿した怪物がいる。
その怪物には不老不死の力が宿っており、
怪物を倒した者にはその力が授けられるらしい。

タオ
たどり着いた想区でオレたちはそんな噂を耳にした。
そして噂をめぐって想区には、オレたち以外にも
『空白の書』の持ち主たちが大勢集っていやがった。

タオ
連中は不老不死の力を求め、怪物を探し続けた。
その欲望は想区の運命をかき乱し、その結果、
想区にたくさんのヴィランを呼び寄せちまった。

タオ
事態を止めようと踏ん張るオレたちだったけど、
不老不死を求める連中の欲望は灼熱の炎となって
ますます燃え広がっていた…ーーー

*

ヴィラン
クルルウ…！！

タオ
おら、邪魔だ！雑魚どもが！

タオ
ったく、すっかり街もヴィランに飲まれてやがる。
お嬢たち、大丈夫だろうな？ここはいっちょ、派手に
暴れて、オレがここにいるアピールを…

タオ
あん？なんだぁ、あの光？
空が、燃えてやがるのか…？

=== 夜空

？？？？
欲深き人間ども、
限られた運命に怯える者どもよ。
てめーら、不老不死の力が欲しいのか？

？？？？
だったら、オレ様と戦い、その強さを示してみろ。
強さの証であるスコアを高めた者にだけ、
オレ様が不老不死の力を授けてやるよ。

？？？？
さぁ、祭りを始めようぜ！
欲望の炎を、命の炎をこの地に燃え上がらせろ！

=== 欲望の街

タオ
おいおい、もっと派手なのがいるじゃねーか。
あれが例の怪物、『炎の不死鳥』だったか？
なんだか、騒がしい鳥だな…

タオ
おっと、こうしちゃいられねー。
ヴィランどもも退散しているこの隙に、
さっさとお嬢たちのもとへ行かねーと！

タオ
ーーそれからしばらくして、オレは
お嬢、坊主、シェインと合流をはたした。

タオ
そしてあの怪物、『炎の不死鳥』がおっぱじめた
祭りに飛び込んでいったーーー

タオ
さて、楽しませてもらおうじゃねーか！

== 初級　執念　開幕　シェイン編
=== 欲望の街

シェイン
ーーこの世界には『永遠の命』を宿した怪物がいる。
その怪物には不老不死の力が宿っており、
怪物を倒した者にはその力が授けられるらしい。

シェイン
そんな噂を耳にしたのは、旅先の想区でのことです。
噂をめぐって想区には『空白の書』の持ち主たちが
大勢集まっていました。みんなヒマなんですかね？

シェイン
ヒマ人たちは不老不死の力を求め、怪物を探し
続けます。その欲望は想区の運命をかき乱し、
その結果、ヴィランまで呼び寄せてしまったのです。

シェイン
いつものごとく巻き込まれるシェインたち。
いろいろ手は尽くしたのですが、ヒマ人さんたちの
欲望はますます燃え広がるばかり。

シェイン
なんだか想区じゅうを、ものすごくいやーな空気が
包み込んでいったのです。
さてさて、どうなることやら…ーーー

シェイン
例の怪物さんを探しに来たのはいいですが、
そこらじゅうヴィランだらけですね。
ちょっとこれはしんどいかもです。

シェイン
せめて姉御や新入りさんたちと合流できれば、
いいんですけど…

シェイン
おや？空が光ってる？
新手の花火ですかね？

シェイン
…いや、違いますね。
なんだかもっと、いやーな感じのものですね…

=== 夜空

？？？？
欲深き人間ども、
限られた運命に怯える者どもよ。
てめーら、不老不死の力が欲しいのか？

？？？？
だったら、オレ様と戦い、その強さを示してみろ。
強さの証であるスコアを高めた者にだけ、
オレ様が不老不死の力を授けてやるよ。

？？？？
さぁ、祭りを始めようぜ！
欲望の炎を、命の炎をこの地に燃え上がらせろ！

=== 欲望の街

シェイン
なるほど、あれが噂の怪物さん、
『炎の不死鳥』ですか。…想像していたより、
三下臭がすごいですね。

シェイン
どうやら騒ぎはここからが本番っぽいです。
早く、姉御たちのところに行きますか。

シェイン
ーーその後、姉御や新入りさん、タオ兄とも
合流を果たしたシェインたちは、祭りの火消しの
ために怪物さんを追いかけ始めます。

シェイン
不老不死にはまったく興味ありませんが、
さすがに放ってはおけないですからねーーー

== 初級　執念　終幕
=== 欲望の街

タオ
へ、これで終わりか？
『炎の不死鳥』とやらも大したことねーな。
不死の怪物が聞いてあきれるぜ…

レイナ
…！？
待って！不死鳥の体を見て！
急に燃え上がって…！

*

炎の不死鳥
オレ様の命の炎を消したつもりかぁ？
この不死鳥、これしきで滅びはしねーよ。

シェイン
鳥のくせにぺらぺらとよくしゃべりますね。
串焼きにして食べてやりましょうか。
って、もう焼けてたんでしたっけ。

エクス
みんな、気をつけよう。
あいつ、きっとまたなにかを仕掛けて…

炎の不死鳥
ハン、当たり障りのない助言だなぁ。
仲間内の優等生を気取っているつもりか？
モブ顔剣士。

エクス
えっ。

炎の不死鳥
そこの娘も、「一人称自分の名前」キャラが
許されるのはいまのうちだけだ。今後のために
キャラの方向性を考え直したほうがいいぞ。

炎の不死鳥
熱血バカとどっちがアレかはいい勝負だがな。
悔しければ、今度はちゃんとオレ様を仕留めてみな。

シェイン
……はっ？

タオ
……んだと？

レイナ
みんな、挑発に乗ったらダメ！
相手の思うツボになるわ！残念だけど、私にその手は
通じないわよ。私の器の大きさを思い知らせてーー

炎の不死鳥
…………

レイナ
なんか言いなさいよおおおおおおおおお！

レイナ
ちょっと待って。ほんとに行っちゃったんだけど！
私だけスルーなの！？

エクス
…さて、みんな。これからどうしてやろうか。

タオ
いやいや、決まってるだろ、無個性剣士。
今夜は景気良く、トリ鍋といこうぜ。
具材は『炎の不死鳥』なんてどうよ？

シェイン
最高ですね、タオ兄。
不死であることを後悔するまで、
とことん調理してやりましょう。

レイナ
あの鳥をほかの誰かになんて渡さない…
あいつだけは絶対に私たちが仕留めるわよ！！

== 中級　欲望　開幕
=== 欲望の森

レイナ
さて、あの不死鳥を追ってここまで来たけど、
まずは状況を整理しましょう。
確認その１、私たちがやるべきことは？

シェイン
あの鳥ヤローを誰よりも早くぶっ倒すこと。
でも相手は不死の怪物なので、普通のやり方では
倒せない。勝敗のカギを握るのはスコア、ですね?

タオ
ああ。奴とは何度も戦うことになりそうだしな。
それで、スコアを稼ぐために、弱点をついたり、
いろいろと戦い方を試す必要がある。

タオ
そこで確認その２。
やつのそもそもの弱点は？

エクス
燃えているから…やっぱり氷とか？

シェイン
単純だけど、たぶんそんなところですね。
さて、確認その３です。
あの鳥ヤローはいまどこに？

レイナ
目撃情報によれば、この森のどこかにいる。
けれどヴィランたちも湧いて出てくるから、
そっちも相手しないといけない。

エクス
じゃあ最後に、確認その４。
もう準備はできた？

タオ
聞くまでもねーだろ。
さぁ、あの鳥にひと泡吹かせてやろうぜ。

== 中級　欲望　終幕

*

=== 欲望の森

エクス
どうやら、本当に不死身みたいだね。
倒しても、倒しても、何度も復活してくる…

タオ
ああしてみると不老不死ってのも便利なもんだな。
いくらでも強いやつと喧嘩できるしよぉ。

シェイン
だったら、シェインは延々武器をいじり
続けていたいですね。
いろんなカスタマイズを試してみたいです。

レイナ
あんたたち、二人はもっとほかに
使い道がないわけ…

シェイン
そういう姉御は不老不死の力を手にしたら、
どうするんですか？

レイナ
え？
うーんと……
…………世界平和？

エクス
…僕たちにはあんまし必要がなさそうだね
不老不死。

== 上級　業火　開幕　エクス編
=== 欲望の山

エクス
ーーー『炎の不死鳥』を追いかける僕たちは、
ある山腹にたどり着く。しかし、そこにはすでに
ほかの『空白の書』の持ち主たちも集まっていた。

エクス
『炎の不死鳥』をめぐり、争う人々。
欲望の果てに傷つき倒れた人々の姿で
山道は埋め尽くされようとしていたーーー

タオ
…ったく、馬鹿どもが。
わけのわからねーもんのために、
無駄な血を流してんじゃねーよ。

シェイン
ヴィランもぞろぞろ現れてきてます…
これは急がないとほんとにマズそうです…

レイナ
エクス…

エクス
止めなくちゃ…
この争いの炎を消せるのは、僕たちしかいない…！

== 上級　業火　開幕　レイナ編
=== 欲望の山

レイナ
ーーー『炎の不死鳥』を追いかける私たちは、
ある山腹にたどり着いた。でも、そこにはすでに
ほかの『空白の書』の持ち主たちも集まっていたの。

レイナ
みんな、『炎の不死鳥』をめぐり、争いあった。
欲望の果てに傷つき倒れた人々の姿で
山道は埋め尽くされようとしていたのーーー

タオ
…ったく、馬鹿どもが。
わけのわからねーもんのために、
無駄な血を流してんじゃねーよ。

シェイン
ヴィランもぞろぞろ現れてきてます…
これは急がないとほんとにマズそうです…

レイナ
エクス…

エクス
止めなくちゃ…
この争いの炎を消せるのは、僕たちしかいない…！

== 上級　業火　開幕　タオ編
=== 欲望の山

タオ
ーーー『炎の不死鳥』を追いかけるオレたちは、
ある山腹にたどり着いた。そこには『不死鳥』を
探すほかの連中がわんさか集まっていやがった。

タオ
『炎の不死鳥』をめぐり、争いあう馬鹿ども。
欲望の果てに傷つき倒れちまった連中の姿で
山道は埋め尽くされようとしていたーーー

タオ
…ったく、馬鹿どもが。
わけのわからねーもんのために、
無駄な血を流してんじゃねーよ。

シェイン
ヴィランもぞろぞろ現れてきてます…
これは急がないとほんとにマズそうです…

レイナ
エクス…

エクス
止めなくちゃ…
この争いの炎を消せるのは、僕たちしかいない…！

== 上級　業火　開幕　シェイン編
=== 欲望の山

シェイン
ーーー鳥ヤローさんを追いかけるシェインたちは、
山腹にたどり着きます。そこには『炎の不死鳥』を
探すヒマ人さんたちが大勢集まっていました。

シェイン
『炎の不死鳥』をめぐり、争いあうヒマ人さんたち。
欲望の果てにみんな倒れていき、祭りはますます
いやな方向へ燃え広がっていきますーーー

タオ
…ったく、馬鹿どもが。
わけのわからねーもんのために、
無駄な血を流してんじゃねーよ。

シェイン
ヴィランもぞろぞろ現れてきてます…
これは急がないとほんとにマズそうです…

レイナ
エクス…

エクス
止めなくちゃ…
この争いの炎を消せるのは、僕たちしかいない…！

== 上級　業火　終幕
=== 欲望の山

炎の不死鳥
本当バカばかりだな、人間どもは。
不老不死などという、己の手にあまる力を
求めて、こうして傷つけ合っている。

炎の不死鳥
お前たちもそうは思わねーか？

エクス
もう止めるんだ、不死鳥。
こんな戦いになんの意味があるんだ…

レイナ
たしかにこの戦いに挑んだ人々は愚かかも
しれないけど、それを煽ったのはあなたよ。
このままだとどんどん取り返しがつかないことに…

炎の不死鳥
いいんだよ、それで。
ーーーそれがこの世界の運命なんだから。

エクス
…どういうこと？

炎の不死鳥
文字通りの意味だよ。この世界は
不老不死の象徴たる『炎の不死鳥』を求め、
争い、滅びを繰り返す。それがこの想区だ。

炎の不死鳥
『炎の不死鳥』は決して人の前に姿を現さない。
人々は不老不死などというまやかしを追い求め、
殺し合い、そして滅びゆく。

炎の不死鳥
滅びのあとに残るのは廃墟という名の灰ばかり。
そして灰のあとから、人々は立ち上がり、国を
復興させる。『炎の不死鳥』のようにな。

タオ
うまいこと言ってるつもりか？
だいたいお前、姿を現さねーって、いまここに
現れているじゃねーか。

炎の不死鳥
ケケケ、さぁな。
滅びを煽るって意味じゃ、きっちり役目を
全うしているし、いいんじゃねーの？

レイナ
それでも限度があるわよ。あなたの煽りのせいで
『空白の書』の持ち主たちまでこの想区に押し寄せ、
ヴィランまで発生させちゃってるじゃない。

シェイン
言っときますけど、このままヴィランを放っておくと
この想区がどうなるかわかりませんよ？
再生できなくなってもいいんですか？

炎の不死鳥
構わねーさ。それこそ、人間たちが自ら選んだ、
運命の結末、ってことだからよ。

レイナ
…その結末を変えるには、どうしたらいいのかしら？

炎の不死鳥
答えはもうわかってんだろ？
オレ様を倒せ。北の街の広場で、
そこで決着をつけようじゃないか。

エクス
…そんな結末、絶対にさせない。
不死鳥を、今度こそ倒すんだ…！

== 超級　飛翔　開幕　エクス編
=== 滅びの広場

炎の不死鳥
ここまで追いすがるお前らの執念の炎、
恐れ入ったぜ…。さぁ、滅びに向けて
最後の炎を燃やそうじゃねーか！

エクス
僕たちが終わらせたいのは命でも、世界でもない。
この馬鹿騒ぎそのものだ。
覚悟しろ、不死鳥！

== 超級　飛翔　開幕　レイナ編
=== 滅びの広場

炎の不死鳥
ここまで追いすがるお前らの執念の炎、
恐れ入ったぜ…。さぁ、滅びに向けて
最後の炎を燃やそうじゃねーか！

レイナ
あなたの勝手な理屈に、ほかの人々を
巻き込ませなんて絶対にしない。
あなたの炎、いまここで消してあげるわよ！

== 超級　飛翔　開幕　タオ編
=== 滅びの広場

炎の不死鳥
ここまで追いすがるお前らの執念の炎、
恐れ入ったぜ…。さぁ、滅びに向けて
最後の炎を燃やそうじゃねーか！

タオ
おいおい、馬鹿言うなよ、てめーで焚きつけた
火の責任くらい、てめーで始末をつけな。

タオ
てめーの火遊びにももうウンザリだ。
ここでケリ、つけさせてもらうぜ？

== 超級　飛翔　開幕　シェイン編
=== 滅びの広場

炎の不死鳥
ここまで追いすがるお前らの執念の炎、
恐れ入ったぜ…。さぁ、滅びに向けて
最後の炎を燃やそうじゃねーか！

シェイン
勘違いしてもらっては困りますが、別にあなたの
祭りになんて興味はありません。

シェイン
人の生き方をバカにするしか能がない
鳥ヤローに一矢報いる。それだけです。
さぁ、とことん付き合ってもらいますよ。

== 超級　飛翔　終幕　エクス編
=== 滅びの広場

炎の不死鳥
…まさか不死であるこの身で
ここまで追いつめられるとはな…

エクス
…結局、君はなにがしたかったんだ？
人前に姿を現さないのが本来の不死鳥なら、
こんな騒ぎを起こした君は何者なんだ？

炎の不死鳥
…なぁ、人間ども。お前たちはストーリーテラーから
『運命の書』を与えられるのが人間だけだと
思ってはいないか？

炎の不死鳥
『運命の書』は魂を持った者すべてに与えられる。
そして、時折その中には運命がまっさらな者だって
生まれてくる…オレ様みたいにな…

エクス
つまり君も『空白の書』の持ち主ってこと？
それじゃあ、不老不死の力を授けるっていうのは？

炎の不死鳥
あんなもん、嘘っぱちさ。
人間どもを煽るための方便だよ。

炎の不死鳥
あるいは先代の不死鳥ならそんなこともできたかも
しれねーし、授けられた人間もいたのかもしれない。

炎の不死鳥
けど、オレ様の書にはそんなことすらも、
書かれてはいなかった。

炎の不死鳥
どんなに傷つけられても死ぬことすらできない。
こんな地獄みたいな世界、まるごと灰にしたって
いいじゃないかよ。

エクス
だから、こんなヴィランを発生させるような騒ぎを
起こしたっていうの？自分ごと世界を滅ぼすために…
そんなの、許されるはずがない！

炎の不死鳥
お前らになにがわかる！不死鳥として生まれながら、
どんなふうに生きればいいかもわからない。
そんなオレ様の気持ちがお前らにわかるのか！

炎の不死鳥
オレ様は不死鳥じゃない…不死鳥の姿と力だけを
持って生まれた、どうしようもないニセモノだ。
こんな地獄で、どうやって生きればいいんだよ…

エクス
…どう生きればいいかなんて、簡単だ。
『空白の書』の持ち主なんだから、
自分で運命を選べばいいんだよ。

エクス
どこまでも飛んでゆける翼があるんだから。
想区の外へだって、望むところに飛べばいいんだよ。

炎の不死鳥
…そうか。たった、それだけでよかったのか。
どうやら本当に愚かだったのは
オレ様のほうだったようだな。

エクス
待って、どこへ行くつもりなの？

炎の不死鳥
お前らの生き方を真似するだけさ。
争いのない世界へ、
オレ様の炎が輝くほうへ飛び立つだけ…

炎の不死鳥
…またどこかで会おうぜ。強き旅人たち。
じゃあな。

*

エクス
ーーーそう言って、不死鳥だった存在は
想区を旅立っていった。

エクス
不死鳥が姿を消したことで、『空白の書』の
持ち主たちも想区を去り、安定を取り戻した想区から
ヴィランの姿も消えていった。

エクス
それでもいまも想区の人々は決して姿を見せない
『炎の不死鳥』を追いかけ、争いを繰り返している。

エクス
そして想区を飛び立った不死鳥が、
その後、どこへ消えたのか。
それを知る人は誰もいないーーー

== 超級　飛翔　終幕　レイナ編
=== 滅びの広場

炎の不死鳥
…まさか不死であるこの身で
ここまで追いつめられるとはな…

レイナ
あなた、言ってたわよね。
『炎の不死鳥』は本来、人の前に姿を現さないって。

レイナ
それなのにあなたは逆に人前に姿を現して、
欲望を煽り続けていた。いったいなぜ？

炎の不死鳥
…なぁ、人間ども。お前たちはストーリーテラーから
『運命の書』を与えられるのが人間だけだと
思ってはいないか？

炎の不死鳥
『運命の書』は魂を持った者すべてに与えられる。
そして、時折その中には運命がまっさらな者だって
生まれてくる…オレ様みたいにな…

レイナ
それじゃあ、あなたも、
『空白の書』の持ち主だってこと？
だったら、不老不死の話っていうのは…

炎の不死鳥
あんなもん、嘘っぱちさ。
人間どもを煽るための方便だよ。

炎の不死鳥
あるいは先代の不死鳥ならそんなこともできたかも
しれねーし、授けられた人間もいたのかもしれない。

炎の不死鳥
けど、オレ様の書にはそんなことすらも、
書かれてはいなかった。

炎の不死鳥
どんなに傷つけられても死ぬことすらできない。
こんな地獄みたいな世界、まるごと灰にしたって
いいじゃないかよ。

レイナ
なるほど。だから人の前に姿を現し、『空白の書』の
旅人まで煽って、想区をむちゃくちゃにしようと
したのね。世界ごと、自分を滅ぼすために…

レイナ
バカね。
そんなことしたって、なんにもならないのに…

炎の不死鳥
お前らになにがわかる！不死鳥として生まれながら、
どんなふうに生きればいいかもわからない。
そんなオレ様の気持ちがお前らにわかるのか！

炎の不死鳥
オレ様は不死鳥じゃない…不死鳥の姿と力だけを
持って生まれた、どうしようもないニセモノだ。
こんな地獄で、どうやって生きればいいんだよ…

レイナ
だったら、この想区を飛び出せばいい。
『空白の書』の持ち主は好きな世界、好きな運命を
自ら選択して生きることができるのだから。

レイナ
少なくとも私たちは、
そうやって生きているつもりよ。

炎の不死鳥
…そうか。たった、それだけでよかったのか。
どうやら本当に愚かだったのは
オレ様のほうだったようだな。

炎の不死鳥
ならばこの翼で羽ばたくとしよう。
争いのない世界へ、
オレ様の炎が輝くほうに向かって…

炎の不死鳥
…またどこかで会おうぜ。強き旅人たち。
じゃあな。

*

レイナ
ーーーそう言って、不死鳥だった存在は
想区を旅立っていったわ。

レイナ
不死鳥が姿を消したことで、『空白の書』の
持ち主たちも想区を去り、安定を取り戻した想区から
ヴィランの姿も消えていったの。

レイナ
けれど、いまも想区の人々は姿を見せない火の鳥を
追いかけ、争いを繰り返している。

レイナ
そして想区を飛び立った不死鳥が、
その後、どこへ消えたのか。
行方を知る者は誰もいないーーー

== 超級　飛翔　終幕　タオ編
=== 滅びの広場

炎の不死鳥
…まさか不死であるこの身で
ここまで追いつめられるとはな…

タオ
なぁ、お前、結局なにがしたかったんだ？
こんな騒ぎまで起こしてよぉ。そもそもお前、
本当に『炎の不死鳥』だったのか？

炎の不死鳥
…なぁ、人間ども。お前たちはストーリーテラーから
『運命の書』を与えられるのが人間だけだと
思ってはいないか？

炎の不死鳥
『運命の書』は魂を持った者すべてに与えられる。
そして、時折その中には運命がまっさらな者だって
生まれてくる…オレ様みたいにな…

タオ
あー、なるほどね…。つまりお前も、オレたちと
おなじ、『空白の書』の持ち主ってわけか。
じゃあ、あの不老不死を授けるってのは？

炎の不死鳥
あんなもん、嘘っぱちさ。
人間どもを煽るための方便だよ。

炎の不死鳥
あるいは先代の不死鳥ならそんなこともできたかも
しれねーし、授けられた人間もいたのかもしれない。

炎の不死鳥
けど、オレ様の書にはそんなことすらも、
書かれてはいなかった。

炎の不死鳥
どんなに傷つけられても死ぬことすらできない。
こんな地獄みたいな世界、まるごと灰にしたって
いいじゃないかよ。

タオ
だからバカどもを煽って、この想区をめちゃくちゃに
して、想区ごと心中を図ろうとしたのか。
お前も相当の大バカだな。

炎の不死鳥
お前らになにがわかる！不死鳥として生まれながら、
どんなふうに生きればいいかもわからない。
そんなオレ様の気持ちがお前らにわかるのか！

炎の不死鳥
オレ様は不死鳥じゃない…不死鳥の姿と力だけを
持って生まれた、どうしようもないニセモノだ。
こんな地獄で、どうやって生きればいいんだよ…

タオ
だから、お前はバカなんだよ。この世界が
気にくわねーなら、さっさと外に飛び出せばいい。
わざわざこんな祭り、けしかけなくてもな。

タオ
少なくともそっちのほうが、
なんぼか心は軽くなると思うぜ？

炎の不死鳥
…そうか。たった、それだけでよかったのか。
どうやら本当に愚かだったのは
オレ様のほうだったようだな。

炎の不死鳥
ならばこの翼で羽ばたくとしよう。
争いのない世界へ、
オレ様の炎が輝くほうに向かって…

炎の不死鳥
…またどこかで会おうぜ。強き旅人たち。
じゃあな。

*

タオ
ーーーそう言って、不死鳥を名乗っていた
大馬鹿はどこかへ飛び立っちまった。

タオ
不死鳥が姿を消したことで、騒いでいた馬鹿どもも
想区を去り、安定を取り戻した想区からは
ヴィランどもの姿も消えていった。

タオ
けど、いまも想区に住む連中は
決して人前に姿を現さない『炎の不死鳥』を巡り、
争いを繰り返している。

タオ
そして想区を飛び立ったアイツが、
その後、どこへ消えたのか。
行方を知ってるやつは誰もいないーーー

== 超級　飛翔　終幕　シェイン編
=== 滅びの広場

炎の不死鳥
…まさか不死であるこの身で
ここまで追いつめられるとはな…

シェイン
ずっと疑問だったのですが、あなた、本当に
『炎の不死鳥』さんなんですか？

シェイン
あなたの行動は本来の不死鳥の運命から
外れまくっています。いったい、あなたは
本当は何者なのですか？

炎の不死鳥
…なぁ、人間ども。お前たちはストーリーテラーから
『運命の書』を与えられるのが人間だけだと
思ってはいないか？

炎の不死鳥
『運命の書』は魂を持った者すべてに与えられる。
そして、時折その中には運命がまっさらな者だって
生まれてくる…オレ様みたいにな…

シェイン
なるほど、そういうことですか。シェインたちと
おなじ、『空白の書』の持ち主さんだったのですね。
じゃあ、あの不老不死を授けるってのは？

炎の不死鳥
あんなもん、嘘っぱちさ。
人間どもを煽るための方便だよ。

炎の不死鳥
あるいは先代の不死鳥ならそんなこともできたかも
しれねーし、授けられた人間もいたのかもしれない。

炎の不死鳥
けど、オレ様の書にはそんなことすらも、
書かれてはいなかった。

炎の不死鳥
どんなに傷つけられても死ぬことすらできない。
こんな地獄みたいな世界、まるごと灰にしたって
いいじゃないかよ。

シェイン
そんな自分勝手な八つ当たりに人を巻き込まないで
ください。と言いいたいところですが、シェインも昔
そういうふうに思っていた時期がありましたしね…

シェイン
同情は求めてないのでしょうけど、
ま、気持ちはわかりますよ。

炎の不死鳥
お前らになにがわかる！不死鳥として生まれながら、
どんなふうに生きればいいかもわからない。
そんなオレ様の気持ちがお前らにわかるのか！

炎の不死鳥
オレ様は不死鳥じゃない…不死鳥の姿と力だけを
持って生まれた、どうしようもないニセモノだ。
こんな地獄で、どうやって生きればいいんだよ…

シェイン
ならば、さっさと外へ飛び立てばどうですか？
そりゃ外に出れば、いろいろと苦労はするかも
しれませんが。

シェイン
ひょっとすると、仲間ってやつに
出会えるのかもしれませんよ？
運が良ければ、ですけど。

炎の不死鳥
…そうか。たった、それだけでよかったのか。
どうやら本当に愚かだったのは
オレ様のほうだったようだな。

シェイン
行くんですか？

炎の不死鳥
…この世界でのオレ様の役目はもう終わりだ。
争いのない世界へ、
オレ様の炎が輝くほうへ飛び立つよ…

炎の不死鳥
…またどこかで会おうぜ。強き旅人たち。
じゃあな。

*

シェイン
ーーーそう言って、不死鳥を名乗っていた
誰かさんはどこかへ飛び立っていきました。

シェイン
不死鳥がいなくなり、騒いでいたヒマ人さんたちも
想区を去り、安定を取り戻した想区からは
ヴィランたちの姿も消えていきました。

シェイン
けど、いまも想区に住む方々は
決して人前に姿を現さない『炎の不死鳥』を巡って、
懲りずに争いを繰り返しているそうです。

シェイン
そして想区を飛び立ったあの鳥ヤローさんが、
その後、どこへ行ってしまったのか。
行方を知ってる人は誰もいませんーーー
