= 8.3. 운명에 거역하는 하얀방패 - Flero
:hardbreaks:

== 빨간 망토의 숲

엑스
[공백의 서]의 소유자는 자신의 의지로 자신의 운명을
적어 나간다. 자신의 소망을 이루기 위해 그들은
수많은 이야기로 넘쳐나는 이 세계를 여행한다.

엑스
우리는 카오스텔러를 조율하기 위해 여행을 계속하고
있지만, 이 세계에는 우리 외에도 자신의 의지로
운명을 개척해 나가는 여행자들이 있다.

엑스
예를 들자면 운명의 장난감이 된 생명을 지키기 위해
하얀 방패가 되려 했던, 그 여기사처럼...

하얀 기사
...아무도 없군.
빨간 망토야, 뛸 수 있겠어?

빨간 망토
 네, 넵. 저는 괜찮은데...
하얀 기사 언니가...

하얀 기사
문제 없어.
이 정도는 부상이라고 할 수도 없으니까.

하얀 기사
녀석들이 오기 전에 서두르자...

하얀 기사
...앗.

빌런
크르르! 크르르르~!!

빨간 망토
하얀 기사 언니...!

하얀 기사
걱정하지마.
내 하얀 방패는 그 어떤 사악함도 막아낼 수 있어.

하얀 기사
만약 그것이 스토리텔러가 정한 운명이라 하더라도,
내 방패는 절대 부서지지 않아!

*

엑스
그 무렵, 우리들은 어떤 상구에 도착했다.
그곳은 빨간 망토를 [주연]으로 한 세계.

엑스
그리고 우리들은 숲속에서, 빨간 망토의 행방을 찾는
한 사냥꾼을 만났다...

사냥꾼
그렇군. 너희들도 그 아이의 행방을 모르는구나...

엑스
네. 저희들도 이제 막 이 숲에 도착한 참이거든요...

셰인
전에도 이번이랑 아주 비슷한 경우가 있었죠.
빨간 망토의 상구, 제 2탄이네요...

레이나
전에 갔던 곳은 다른 상구였지만 말이야.

레이나
하지만, 빨간 망토를 찾으려면 할머니의 집으로
향하면 되는 거 아니었어?

사냥꾼
너희들, 그 아이의 운명을 알고 있나?

사냥꾼
그럼 얘기가 빠르겠군.
실은 약간 일이 묘하게 돌아가서 말이지...

사냥꾼
빨간 망토를 잡아먹어야 할 늑대가 누군가에게 당한거야.

레이나
늑대가 당했다구요?
잠깐, 빨간 망토에 나오는 늑대는 분명
당신이 쓰러뜨리게 되어 있는 것 아니었나요...?

사냥꾼
그렇지, 그러니까 이상하다는 거지.

사냥꾼
늑대가 쓰러진 현장에 남아 있던 발자국을 보면,
아무래도 빨간 망토는 늑대를 쓰러뜨린 사람과
함께 있는 것 같아...

엑스
아무래도 그 사람이 빨간 망토를 늑대로부터
구해준 것 같군요...

타오
...흠, 셰인? 너도 눈치챘어?

셰인
네. 공기가 굉장히 술렁거리고 있어요.
틀림없어요.
이 상구에 빌런이 있군요.

엑스
어떻게 된 거야?
이 상구에는 분명 카오스텔러가 없는 것 아니었어?

엑스
그러고보니 빌런이 나타난다는 뜻은...
카오스텔러가 쳐들어 왔거나,
누군가가 상구의 운명에 간섭했을 때...

레이나
그래, 맞아.
그리고 우리들은 막 이 상구에 도착했을 뿐이고
아무것도 하지 않았어. 그렇다면...

레이나
사냥꾼 아저씨.
빨간 망토를 찾는 일, 우리들도 돕게 해 주세요.

레이나
더 늦기 전에 어떻게든 하지 않으면 안 될 것 같군요...

사냥꾼
더 늦기 전에?
무슨 얘긴지는 모르겠지만, 알겠어.
도와준다면 고맙지.

사냥꾼
그럼 따라들 오라구...

== 늑대의 숲

엑스
―숲속 안으로 들아간 우리들은 일단,
두 조로 나뉘어 빨간 망토를 찾기로 했다.

엑스
사실 우리들의 진짜 목적은 따로 있기는 했지만―

엑스
레이나는 늑대를 쓰러뜨린 사람이
[공백의 서]의 소유자라고 생각하는 거지?

레이나
이 상구에 빌런이 나타난 것도 그렇고,
그렇게 생각하는게 자연스럽지 않을까?

레이나
어째서 빨간 망토를 데리고 있는지는 모르겠지만,
빨리 그 사람을 설득해 상구에서 데리고 나가지 않으면
빌런은 계속해서 나타날 거야.

엑스
...우리 설득을 들어줄까?
나쁜 사람은 아닐 것 같지만.

레이나
그건 상대가 어떻게 나오느냐에 달렸...

레이나
...!
쉿.
저쪽에 누군가가 있어.

*

빨간 망토
저기, 하얀 기사 언니.
이제 그만... 이제 도망치는 건 그만두자...
이런 건 내 [운명의 서]에도 적혀있지 않으니...

하얀 기사
걱정하지마.
내 방패는 운명에 구속 당하지 않는 무적의 방패니까.

하얀 기사
그러니까 빨간 망토야.
너를 끝까지 지키기 위해, 나는 싸움을 멈출 수 없...

레이나
당신이 늑대를 쓰러뜨린 사람?
역시 [공백의 서]를 갖고 있었어.
게다가 아주 끼어들기 좋아하는 성격이군.

하얀 기사
...누구냐, 네놈들은?

엑스
당신과 같은 [공백의 서]의 소유자랍니다.
나는 엑스, 이쪽은 레이나.

엑스
당신의 이름... 하얀 기사님은 아니겠지요?
진짜 이름은 뭔가요?

하얀 기사
이름같은 건 없다. 나는 그냥 하얀 기사일 뿐.
이 아이를 지키는 하얀 방패다.
내 사명을 방해한다면, 용서하지 않겠다.

레이나
기다려요.
당신, 자신이 무슨 짓을 하고 있는지 알고 있는 거야!?

레이나
어째서 빌런이 나타나는지,
이대로 계속 운명에 개입한다면 어떻게 될지.
모를 리가 없잖아!

타오
이봐, 아가씨!
그쪽에 누가 있는 거야!?

하얀 기사
...한패가 더 있었군.
빨간 망토야, 가자.

빨간 망토
자, 잠깐, 하얀 기사 언니!

엑스
잠깐! 기다려, 하얀 기사!

레이나
엑스! 어서 쫓아가야 해!

***

셰인
하얀 기사님이라.
도대체 무슨 목적으로 빨간 망토를 데리고 다니는
걸까요?

엑스
아마도 빨간 망토를 지키려는 걸 거야.
자신의 방패로 끝까지 지켜낸다고 했으니까...

타오
하지만, 분명 빨간 망토는 어차피 마지막에 가면
구원을 받는 결말 아니었어?
어째서 녀석이 지킬 필요가 있는 거지?

셰인
그렇네요.
뭐, 간단히 얘기해서 생각 없이 주변에 민폐를 끼치는 타입일 것 같습니다만.

셰인
어쨌든 사냥꾼 아저씨가 돌아오길 기다리자.
그렇게 멀리까지 도망치지는 못했을 테니까.

레이나
\......

엑스
왜 그래, 레이나?

레이나
...음, 조금 신경쓰이는 게 있어서.
이 상구에 대해서 말인데...

사냥꾼
너희들, 어서 와봐!
빨간 망토와 하얀 기사를 찾았다!

레이나
...윽!
아무래도 이야기는 나중에 하는 게 좋겠어!

*

빨간 망토
하얀 기사 언니!
나는 어떻게 되든 상관없으니까 빨리 도망가...!
이대로라면, 언니가 죽을거야...!

하얀 기사
...이 정도 부상은 침 바르면 괜찮아.
걱정하지마.

빨간 망토
...하얀 기사 언니, 하얀 기사 언니.
어째서 그토록 나를 지키려 하는 거야?
그렇게 해봐야, 아무 의미도 없는데...

하얀 기사
...그게 내 사명이니까.
스토리텔러가 강제로 시키는 게 아니야.
나 자신이 선택한 사명이란다.

하얀 기사
조금만 더 쉬고 출발하자.
또 그 녀석들이 쫓아오기 전에...

타오
뭐야? 이미 너덜너덜하군.
이래서야 싸울 수도 없겠는걸.

하얀 기사
너희들!
빨간 망토를 건드리게 놔두지 않을... 으윽.

엑스
괜찮아. 당신이 억지로 무리하지 않아도,
빨간 망토는 마지막에 구원받게 되어 있어.
그런 운명으로 정해져 있다구.

엑스
그러니까 우리와 함께 이 상구를 나가자.
자.

하얀 기사
빨간 망토가 구원을 받는다고?

하얀 기사
바보 같은 소리 마!
너희들은 아무것도 몰라!

하얀 기사
이 아이는 죽게 된다고!
늑대에게 잡아먹혀, 살아나지 못해.
이 상구에서는 그게 빨간 망토 이야기의 줄거리다!

엑스
...자, 잠깐만. 그럴 리가 없어!
그러니까, 빨간 망토는 마지막에 사냥꾼 아저씨가
구하게 되는...

사냥꾼
그 하얀 기사의 말은 사실이야.

사냥꾼
늑대는 빨간 망토를 속여 잡아먹고,
나는 그 늑대를 쏘아 죽이지.
그것이 이 세계에서 반복되어 온 운명.

사냥꾼
그 비극은 마을의 소중한 교훈으로서 후세에 전해지지.
그러다가 교훈이 잊혀질 즈음,
또 같은 운명이 반복되는 거야.

레이나
...그렇게 된 거로군.
좀 더 빨리 깨달았어야 했는데.

레이나
스토리텔러가 다르면,
비록 [주연]은 같아도 적힌 운명은 달라진다.
알고 있었으면서...!

사냥꾼
스토리텔러님이 정한 운명은 절대적.
이 아이는 늑대에게 잡아먹혀야만 한다.
방해는 용서치 않아.

레이나
잠깐...!
당신, 나이프 들고 뭐하는 거야!?
하얀 기사를 죽일 셈이야!?

사냥꾼
그 검은 괴물이 나타나는 건,
이 하얀 기사가 원인이잖아?
그렇다면 망설일 필요가 없지.

사냥꾼
우리 세계의 운명을 지키기 위해서다.
나쁘게 생각하지 말아줘...

사냥꾼
...각오해라!

하얀 기사
...큭!

*

빨간 망토
안돼에에에에에에에에!!

***

사냥꾼
...각오해라!

하얀 기사
...큭!

엑스
역시 안돼겠어, 사냥꾼 아저씨!
※플레로의 실수

사냥꾼
뭐, 뭐하는 거야!? 놔라!
[운명의 서]에 적힌 이야기는 절대적이다...!
이 아이의 죽음을 방해해서는 안돼!

엑스
알고 있지만...!
하지만, 역시 이건 잘못된 것 같아!

타오
꼬마 말대로다.
그러니까, 잠시 잠들어 있으라구!

사냥꾼
크윽...

하얀 기사
...너희들, 어쩔 셈이야?

엑스
구할려는 셈...일거야. 아마도.

셰인
아~아, 저질러 버렸군요.
이걸로 우리도 공범이네요.
어떻게 할까요? 두목 언니.

레이나
어떻게 할까요는 내가 할 소리야!
이제 이 일을 어떻게 수습해야 할지...

타오
뭐, 너무 그러지 말라구.
적어도 이 상구의 [주연]의 소망 하나는
이루어지게 했으니까 말이야.

빨간 망토
하얀 기사 언니...
다행이야... 살아있어서...
정말 다행이야...

하얀 기사
...미안하구나, 빨간 망토야.
걱정하게 만들었군...

셰인
이런.
아무래도 감동의 여운에 빠져 있을 여유는
없을 것 같군요.

*

빌런
크르르! 크르르!

*

레이나
빌런 녀석들.
완전히 우리들을 노리고 있어...
아아, 정말. 할 수 없군!

레이나
우선 이쪽으로 도망치자!
빨간 망토도 같이 따라 와!
타오는 하얀 기사를 부축해!

타오
알았어!

하얀 기사
...신세를 지는군.
너희들까지 휘말리게 하다니...

타오
신경 쓰지 마.
우리들, 트러블에 휘말리는 데는 익숙하니까.
자, 다들 서둘러!

엑스
알았어!

엑스
아, 그런데 사냥꾼 아저씨는 어떻...

레이나&타오&셰인
사냥꾼은 두고 가!

== 안식의 동굴

엑스
―빌런으로부터 도망친 우리는,
빨간 망토와 부상을 입은 하얀 기사를 데리고
동굴에 몸을 숨기기로 했다.

엑스
그리고 그곳에서, 왜 그녀가 여행을 하고 있는지,
하얀 기사에게 이야기를 듣기로 했다...―

== 회상

하얀 기사
우리 가문은 대대로 왕가의 호위를 맡은 기사
일족이었어. 아버님도 오라버니도, 모두 자신의
운명과 사명에 강한 긍지를 갖고 있었지.

하얀 기사
[공백의 서]를 갖고 태어난 나는, 그런 아버님의
모습을 동경했어. 그리고 나는 주위의 반대를 물리치고,
싸우는 기술을 익혀, 기사가 되려 노력했지.

하얀 기사
고통스러운 훈련을 몇달이고 거듭해...
얼마 후 진짜 호위 기사로 임명된 나는,
하나의 사명을 부여받았다.

하얀 기사
백년 동안 잠에 빠지는 저주에 걸린 왕국의 공주.
그 공주의 호위가, 내가 부여받은 사명이었어.

하얀 기사
공주는 마지막에 잠에서 깨어나, 왕자와 맺어지는
결말을 맞이하게 되어 있었지. 하지만 그녀에게는
한가지, 정말 골칫거리인 운명이 있었어.

하얀 기사
공주가 잠에 빠져있는 동안 소중히 여기고 있던
[보물]을 나쁜 녀석들에게 빼앗기게 되어 있던 거야.
그건 잃어버리면 결코 되찾을 수 없는 [보물]이었지...

하얀 기사
공주는 자신의 운명을 슬퍼하며 탄식했지...
그래서 나는 공주를 지키기 위해 모든 수단을 사용하여
멋지게 공주의 운명을 바꿔버린 거야.

== 안식의 동굴

하얀 기사
그때 나는 깨달았지.
운명으로부터 고통받는 약자를 지키는 것.
그것이 나에게 주어진 진정한 사명이자, 운명이라고.

하얀 기사
내 [운명의 서]가 공백인 것은 그 때문...
그렇기에 그 사명을 다하기 위해,
고향인 상구를 뛰쳐나와 여행을 이어가고 있었어.

타오
...당신 기분은 알겠는데 말이야, 하얀 기사.
정해진 운명을 거역해서 큰 일을 저지르려 하면
틀림없이 보복이 돌아온다구.

타오
더군다나 스토리텔러는 외부에서 온 녀석들을
무지하게 싫어한다고 하니 말이야.
고향에서처럼 쉽지는 않을 거라구.

하얀 기사
알고 있어... 알고 있다구...!
하지만, 어쩔 수 없어!
그냥 내버려 둘 수는 없단 말이야!

하얀 기사
아무리 무모하다 하더라도...
나는 절대 이 사명을 포기하고 싶지 않아!
그러니까...!

레이나
맞아. 당신의 사명은 무모해 하얀 기사.
아니면 오만하다고 해도 좋겠지.

레이나
...하지만, 맞아.
운명 그 자체를 바꿀 수는 없더라도,
마지막까지 저항할 수는 있을지도 몰라.

레이나
무엇보다도 그걸 정하는 건 우리들이 아니라,
[주연]에게 물어봐야 하겠지만 말이야.

빨간 망토
나... 늑대에게 잡아먹히는 거,
무섭다고 생각해 본 적 없어...
그게 당연하다고 생각했으니까...

빨간 망토
하지만, 하얀 기사 언니가 구해주었을 때...
필사적인 언니의 모습을 보고있자니,
좀 더 살고 싶어라는 생각이 들었어...

빨간 망토
이런 말 하면 나쁜 아이일지도 모르지만...
그래도 나는... 운명에 거역하더라도, 살고 싶어!

하얀 기사
빨간 망토... 알았어...

셰인
그런데 두목 언니.
뭔가 작전은 있는 건가요?

레이나
작전이라고 할 수 있는 건지 모르겠는데...
거의 성공 확률이 없는 도박이지만....
그래도 해 보겠어?

엑스
여기까지 왔잖아.
끝까지 한번 해보자구.

***

엑스
―레이나가 생각한 작전.
그것은 빨간 망토가 늑대에게 잡아먹혔다는
헛소문을 퍼뜨려 그녀의 죽음을 위장하는 작전이었다.

== 회상

레이나
이 상구에서의 빨간 망토의 역할은,
[늑대에게 잡아먹혔다는 비극을 마을에 알리는 것].

레이나
그렇기에 그 역할만 다하면,
빨간 망토는 그 운명에서 해방된다고 생각해.

레이나
운명의 앞뒤 계산만 맞는다면,
스토리텔러도 그 이상은 관여하지 않을 거야.

레이나
분명 이 상구에는 빨간 망토가 사는 마을 외에도
도시가 있다고 들었어.

레이나
빨간 망토를 죽은 것으로 하고 그녀를 아는 사람이
아무도 없는 도시로 데려간다면 빨간 망토의 운명을
바꿀 수 있을 지도 몰라.

레이나
...어쩌면, 이지만.

== 회상 끝

엑스
그래도 할 수 밖에 없어.
빨간 망토를 구하기 위해,
그녀의 운명을 바꾸기 위해서는...

== 늑대의 숲

셰인
다녀왔습니다, 두목 언니.
예의 그 소문은 널리 퍼뜨려 놓았어요.

셰인
빨간 망토님의 가짜 유품을 준비하거나,
늑대님의 소행으로 보이게 꾸미거나 해서
손을 써놓기는 했지만, 과연 어찌 될지...

레이나
고마워.
이젠 운명이 잘 수습해 주기만을
믿고 기다리는 수 밖에 없어...

엑스
빨간 망토야.
도시는 이 숲을 동쪽으로 벗어나면 있는 거지?

빨간 망토
응. 엄마가 옛날에 살던 도시래.
마을 사람들은 거의 도시쪽으로는 가지 않으니까,
들키는 일도 없을 거야.

빨간 망토
하지만 정말 괜찮을까...?
잘 되면 좋겠지만...

하얀 기사
말했잖아.
나는 널 지키는 하얀 방패라고.
그리고 저들이 있다면, 아무것도 무서울 게 없어.

타오
당연하지. 이 타오 패밀리를 우습게 보지 말라고.
...하지만, 각오는 해 두도록 해.
꽤나 힘든 싸움이 될 테니 말이야...

*

빨간 망토
하얀 기사 언니...!

하얀 기사
괜찮으니 물러나 있어.

하얀 기사
...어떻게 할 거야?
사태가 수습될 때까지 참고 버텨야 할까?

엑스
으음, 도시까지 뚫고 나가는 수 밖에 없다고 생각해.
이대로 멈춰 있어봐야, 녀석들에게 포위될 뿐이야...!

레이나
엑스 말대로야...!
모두, 싸워서 돌파한다!
운명이 뒤바뀌는 그 순간까지!

***
*전투*

나레이션
일행이 빨간 망토를 데리고 빌런들과 싸우고 있을 무렵.
조금 떨어진 숲속에서는...

사냥꾼
...하, 하하, 하하하.
드디어 끝내버렸군, 늑대 녀석!
그 아이를 잡아먹은 벌이다!

사냥꾼
그 소문대로였어...
여행자 녀석들, 그 아이를 지키는 데 실패한 거야...
하하, 맞아. 잘 될 리가 없지...

사냥꾼
이것으로 운명은 지켜졌다...
그 아이의 죽음은 교훈으로서 후세에 전해지겠지...
그러니까... 이걸로... 잘 된거야...

사냥꾼
으, 으으... 제길... 제길...
어째서 그런 착한 아이가 죽지 않으면 안되는 거야...
그런 운명... 너무 하잖아...

사냥꾼
으으... 으아아아아아아아......!

== 희망의 도시

빨간 망토
고마워, 하얀 기사 언니와 모두들...
여기까지 날 데려와 줘서...

하얀 기사
빌런들의 추격도 멈췄다.
아마도 운명의 계산인지가 맞았나 보군.
더 이상 널 구속할 운명은 없어졌어.

빨간 망토
...왠지 무서워. 하얀 기사 언니.
지금까지 당연히 존재하던 길이 없어지고,
정말 미아가 된 것 같아.

하얀 기사
...그렇다면, 내가 곁에 있을까?
나는 네 운명을 바꿔버렸어.
그 책임을 지는 것도, 기사의 의무다.

빨간 망토
...으음, 괜찮아.
나도 하얀 기사 언니들처럼,
자신의 힘으로 이 길을 나아갈 거야.

빨간 망토
그러니까 하얀 기사 언니는 자신의 길을 가도록 해.
나 같은 아이를, 앞으로도 많이,
많이 구해주었으면 해.

하얀 기사
그래, 알겠어...
약속하마...
작별이다. 빨간 망토.

빨간 망토
바이바이, 하얀 기사 언니...
이제 난 [빨간 망토]가 아니야...

하얀 기사
―그 말을 남긴 [빨간 망토]였던 소녀는,
쓰고 있던 빨간 모자를 벗어버리고는,
도시 안을 향해 뛰며 사라져갔다.

하얀 기사
이렇게 해서 [빨간 망토]라 불리던 소녀는 죽었다.
운명으로부터 해방된 이름없는 소녀를 떠나 보내고는,
나는 새로운 사명을 위해 다시 출발하게 된 것이다...―

*

셰인
왠지 이번엔 다른 때보다 더 힘들었네요...
카오스텔러와 싸우는 편이 차라리 낫겠어요...

타오
정말 그렇다니까.
그래서 말인데 하얀 기사.
당신, 앞으로도 혼자서 싸울 생각이야?

하얀 기사
그 아이와도 약속했으니까.
앞으로 어떤 시련이 기다리고 있을 지는 모르지만,
그래도 나는 이 사명을 가슴에 품고 살아갈 거야.

하얀 기사
그게 내가 선택한 나 자신의 운명이니까...

하얀 기사
너희들에게도 신세를 졌군.
운이 좋다면 다시 만나겠지.
그럼...

레이나
잠깐.
괜찮다면 이걸 가져가도록 해.

하얀 기사
이건 분명 너희들이 갖고 있던 책갈피...

레이나
[안내의 책갈피]라고 해.
옛 영웅들의 영혼과 당신을 연결하기 위한 책갈피야.
당신의 운명을 인도해 주는 힘이 될 거라고 생각해.
※인도의 책갈피

엑스
우리들은 떨어져 있어도 서로 연결되어 있어.
하얀 기사, 당신은 결코 혼자가 아니야.
그것만은 잊지 말아줘.

하얀 기사
...하얀 기사가 아니야.

하얀 기사
전 위세 왕국의 호위기사, 에이다.
그게 내 이름이다.

에이다
약속하지.
너희들에게 무슨 일이 생기면,
나는 언제라도 달려 올거야.

에이다
함께 이 세계에서 싸워 나가자.
...같은 공백의 운명을 살아가는 벗들이여.

엑스
...응, 에이다!