= 8.5. 장화신은고양이 VS 오페라의유령 ※장화신은 고양이VS팬텀 - Flero
:hardbreaks:

== 오페라 극장의 도시

엑스
오페라라고 알아?
무대 위의 남녀 배우들이 부르는 음악으로
이야기가 진행되는 무대극을 오페라라고 한다는군.

엑스
우리가 도착한 곳은, 그런 오페라가 열리는
오페라 극장이 있는 도시였다.

엑스
도시 사람들 모두가 오페라를 좋아하며,
특히 사람들의 관심을 모으고 있던 것이
절대적인 인기를 자랑하는 여가수 크리스틴.

엑스
그리고 오페라 극장에 숨어있는
의문의 유령 팬텀에 관한 소문이었다.

타오
오페라 극장을 뒤에서 지배하는 의문의 유령 팬텀...
신출귀몰하여 누구도 그 모습을 본 자가 없고,
때때로 마음에 드는 여가수를 데려가 버린다라...

타오
이거 마음에 드는데?
왠지 모험심을 자극한단 말이지.
너도 그렇게 생각하지? 그렇지?

엑스
관심을 보이면 안돼, 타오.
그러다 또 사건에 휘말리게 될 거야.

엑스
자자, 장보기도 끝났으니,
빨리 레이나 일행이 있는 곳으로 돌아가자.
레이나와 셰인이 기다리고 있을...

레이나
적당히 좀 해!
우린 갈길이 바쁘다고 얘기했잖아!

엑스
방금 그 목소리는, 레이나...?

타오
...큰일이군.
이거, 트러블의 예감이 강하게 드는 걸.

== 오페라 극장 근처의 초원

????
자자, 그러지 말고 잠깐이라도 좋으니
얘기를 좀 들어봐!
들어서 손해는 안볼거야.

레이나
그~러~니~까~!
그쪽도 내 얘기를 좀 들으라구~!

엑스
저기, 우리 동료한테 무슨 볼일이라도...?
헉, 고양이?!

????
어라, 일행인가?
흐~음, 과여~언.
...이 형님들도 힘 좀 쓰게 생겼는 걸.

????
이런, 인사가 늦었군.
저는 이런 일을 합니다.
여기 명함을 받아주십시오.

엑스
아, 뭘 이렇게까지...
[프리 상담사 장화 신은 고양이]?
저기, 상담사가 뭔가요?

장화 신은 고양이
간단히 얘기하자면 사람들의 상담을 듣고,
그 사람이 원하는 재능을 발휘하게 해주는 직업이지.
제대로 된 실적도 갖고 있다구?

장화 신은 고양이
예전에 방앗간집 보잘것없는 셋째 아들을
후작으로 출세시킨 적도 있거든.
내 주인인 카라바 후작 얘기지만.

셰인
이 고양이 아저씨, 아까부터 귀찮게 해요.
우리한테 부탁하고 싶은 일이 있다면서.

타오
부탁하고 싶은 일?
그게 뭔데?

장화 신은 고양이
헤헤, 그게 말이지...
...이런, 방해물이 나타났군.

*

빌런
크르르... 크르르르...!

레이나
빌런들이다...!
아아, 짜증나! 항상 이런 패턴이라니까!
이번엔 피해갈 수 있을 줄 알았는데!

장화 신은 고양이
으음, 당신들 혹시 [팬텀의 사자]들에 대해
뭔가 알고 있나?

엑스
[팬텀의 사자]?
도대체 무슨 얘기야?

장화 신은 고양이
흐음, 그렇군...
일단 이녀석들을 처리하고 나서 내 성으로 와 줘.
거기서 자세히 얘기하자구.

***
*전투*

== 카라바 후작의 성

엑스
빌런을 물리친 우리들은 장화 신은 고양이를 따라,
고양이의 주인인 카라바 후작의 성에 도착했다.

엑스
그곳에서 우리들은 그 빌런들이
[팬텀의 사자]라 불린다는 것을 알게 되었다.

장화 신은 고양이
녀석들이 나타나기 시작한 건 한달쯤 전부터였지.
갑자기 여기저기에서 나타나지 않겠어?

레이나
한달전이라...
우리가 이 상구에 오기 전이야...

엑스
어떻게 된 거야?
이 상구에는 분명 카오스텔러가 없는 것 아니었어?

레이나
응, 그건 틀림없어.
그 빌런은 우리들의 존재에 반응한 것 같았지만...
빌런 발생의 원인은 따로 있어.

레이나
저기, 어째서 그 빌런들은
[팬텀의 사자]라 불리는 거야?
아까 우리한테 부탁하려던 일하고 무슨 관계라도?

장화 신은 고양이
아주 좋은 질문이군!
실은 여러분들에게, 내가 상담을 맡고 있는
여가수의 경호를 부탁하고 싶단 말이지.

장화 신은 고양이
지금 크리스틴과 함께 인기의 쌍벽을 이루고 있는
신인 오페라 가수, 라푼젤의 경호를 말이야.

== 회상

장화 신은 고양이
내가 상담을 맡고 있는 아이... 이름이 라푼젤이라고
하는데 말이야, 지금 그 녀석이 다음 공연의
주인공으로 뽑히기 직전이거든.

장화 신은 고양이
그런데 그 라푼젤에게 최근 협박장이 도착한거야.
무대에서 내려가지 않으면 그 생명을 빼앗겠다,
라고 말이지.

장화 신은 고양이
협박장을 보낸 이는 자신을 [오페라의 유령],
팬텀이라고 칭하더군. 오페라 극장에 전해 내려오는
괴담에 자신을 비유한 거지.

== 카라바 후작의 성

장화 신은 고양이
팬텀이 실제 존재하는지는 몰라.
오페라 극장을 뒤에서 지배한다느니, 지하에서
산다느니, 여러 소문이 떠도는 것 같은데...

장화 신은 고양이
그 괴물들이 나타난 것도,
라푼젤이 협박을 받은 것도 비슷한 시기.
현시점에서 아직 큰 피해가 생긴 건 아니지만...

타오
그렇다고 잘 알지도 못하는 우리들한테,
왜 그런 일을 맡기려는 거야?

장화 신은 고양이
직업상 사람을 보는 눈에는 자신이 있거든.
지금까지 수많은 싸움을 헤쳐온 것 같은데 맞지?
아까전의 싸움을 봐도 알 수 있지.

장화 신은 고양이
부탁이야.
나도 여러가지로 바빠서 손을 쓸 여유가 없다구.
이 고양이를 좀 도와줘~.

레이나
한가지 확인해 둘 것이 있어.
당신의 그 행동은 어디까지가
[운명의 서]에 적혀있는 대로인 거지?

장화 신은 고양이
하하하, 무슨 소릴 하는거야?
물론 전부 예정대로지.
그런건 당연하잖아.

레이나
......그래, 알겠어.

레이나
이 상구에서 무슨 일이 일어나고 있어...
조사할 필요가 있을 것 같아.
이 얘기, 받아들이겠어.

장화 신은 고양이
정말이야!?
헤헤, 고마워. 여러분들.
신세를 지는군...

== 오페라 극장의 도시

크리스틴
♪하늘에 계신 빛나는 천사들이여~~
부디 제 영혼을 저 머나먼 하늘까지 데려가 주소서~~

????
훌륭하다, 크리스틴.
이 얼마나 멋진 소프라노 음성인가...
얼마전의 콘서트보다도 한층 발전했구나...

크리스틴
이 목소리는... [음악의 천사]님...
감사합니다... 이 모든 건 당신이...
저를 여기까지 인도해 주신 덕분이예요...

????
다음 공연의 주인공은 너의 것이다.
너의 [운명의 서]에 적혀있는 대로 만들어 주마.

????
오늘은 이만 쉬거라, 크리스틴...
아무 걱정하지 말고. 너는 그저 최고의 목소리로
노래하는 것만을 생각하면 된다...

*

크리스틴
아아, 또... 또 다시 그 목소리에 지배당해서...
그 사람을 멈추게 할 수가 없었어...

크리스틴
[음악의 천사]님...
당신 덕분에 저는 이렇게 멋지게
노래할 수 있게 되었어요...

크리스틴
그러니... 이제 더 이상 그만해요...
저는 더 이상은 원하지 않아요...

크리스틴
부탁이예요... 에릭...

*

팬텀
내가 길러낸 최고의 가수, 크리스틴...
그녀를 인도하는 것이야말로 나의 운명...
그것을 위해서라면 나는 아무리 더럽혀져도 상관없다...

팬텀
라푼젤, 그리고 내 사도라 불리는 괴물들...
그 어느쪽도 [운명의 서]에 적혀있지 않지만...
아무런들 어떠하리...

팬텀
크리스틴을 방해하는 자는
모두 어둠에 묻어 버리리라...

장화 신은 고양이
팬텀이라... 뭘 바라는지는 모르겠지만...
이쪽도 이쪽 나름의 사정이라는 게 있다는거야.
라푼젤을 방해하게 놔두진 않겠어.

팬텀
나를...

장화 신은 고양이
나를...

장화 신은 고양이&팬텀
방해하는 녀석은 용서하지 않겠다.

== 오페라 극장의 도시

편지
[친애하는 라푼젤에게.
내가 수차례에 걸쳐 경고했음에도 불구하고,
그대는 그것을 무시하고 무대에 서려 한다.

편지
나는 그대의 그 무모함에 찬사를 보낸다.
오늘 밤, 오페라 극장의 2층 5번 박스석으로 오도록.
부디 나에게 그대의 각오를 보여주길 바란다.

편지
만약 오지 않는다면,
죽음보다도 두려운 운명이 그대를 찾아 갈 것이다.
오페라의 유령으로부터]

장화 신은 고양이
이게 팬텀이 보내온 편지야.
죽음보다도 두려운 운명이 뭔지는 모르겠지만...
뭐, 별것 아니겠지.

엑스
그래도 라푼젤은 가겠다고 하는 거로군...
아무 일도 일어나지 않도록, 우리 힘으로 지켜야 해.

레이나
얘기는 알겠는데...
우리 지금, 라푼젤이 기다리는 오페라 극장에
가고 있는 거 맞아?

레이나
어째서 오페라 극장 뒤쪽으로 가는 거야?
입구는 반대쪽이잖아?

장화 신은 고양이
오페라 극장은 애완동물 금지다.
정면으로 들어가면 내가 극장 관리인에게
쫓겨날 거 아냐.

셰인
아, 장화 신은 고양이님은 애완동물에 속하는 거였군요.
그랬구나, 그랬구나.
그렇다면 뒷문으로 몰래 들어가는 건가요?

장화 신은 고양이
보면 알거야.
아, 들려오는군...

장화 신은 고양이
아무래도 우리 노래하는 작은 새는,
오늘 밤도 [왕자님] 노래에 푹 빠진 것 같군.

== 오페라 극장 2층 통로

라푼젤
♪예전의 나는 새장 안의 새였어...
높은 탑 위에서 지저귀기만 하는 작은 새
그런데 어느 날, 당신이 나타났지...

라푼젤
♪이름도 모르는 그 사람
내 노래를 사랑해 준 그 사람...
그 사람이야말로 내가 기다리고 기다리던 왕자님!

라푼젤
♪하지만 그 사람은 떠나가 버렸어...
이루어야만 할 운명이 있다는 말을 남기고는...
그리고, 나에게 이렇게 약속했어...

라푼젤
너의 노래가 [최고의 음악]에 이르렀을 때,
다시 한번 나는 너를 찾으러 가겠어.
반드시, 반드시...

라푼젤
♪그래서 나는 이 무대의 새가 된거야...
오페라에서 갈채를 받으며 드높이 노래하는 새가 되어
그 사람이 사랑한 노래가 끝없이 울려퍼지게 할 거야...

라푼젤
♪그러니 운명의 왕자님,
부디 다시 나를 찾아 주세요...

장화 신은 고양이
라푼젤~, 라푼젤~,
슬슬 노래는 그만하고 머리카락을 늘어뜨려 주겠니?

라푼젤
이 목소리는... 고양이 아저씨!?
네네, 알았어요. 지금 갈께요!

*

타오
설마 머리카락을 타고 올라갈 줄이야...
무지막지하게 긴 머리카락이군.
그렇게 타고 올라가도 괜찮은 거야?

라푼젤
후훗, 익숙하니까 괜찮아요.
처음 뵙겠습니다, 라푼젤이라고 해요.
아저씨한테 얘기는 들었어요.

장화 신은 고양이
라푼젤의 머리카락은 특별하지.
금을 자아낸 듯한 광채를 발하는 긴 머리카락...
이렇게 눈에 띄기 쉬운 인재는 또 없을 거야!

장화 신은 고양이
덧붙이자면 여기 라푼젤은 말이지,
원래 숲속에 있는 탑에 살고 있었지만...

셰인
아, 조금 전의 노래로 대략의 프로필은
파악했으니까 설명 안하셔도 괜찮아요.

레이나
예전에 만났던 왕자님을 찾기 위해
오페라 가수로 데뷔했다는 얘기였지?
그리고 지금 팬텀에게 쫓기고 있고.

엑스
무섭지는 않아?
예고장에 써 있는 곳에
어떤 함정이 기다리고 있을지 모르잖아?

라푼젤
솔직히 무섭답니다.
하지만, 이대로 협박에 굴복해서
그 분을 만나지 못하게 되는 게 더 무서워요...

라푼젤
저는 더 이상 탑에 갇힌 작은 새가 아니니까...
그리고, 여러분과 고양이 아저씨도
함께 가주실 거잖아요?

장화 신은 고양이
물론이고말고.
자, 그럼 서두르자. 이 멤버라면,
제 아무리 팬텀이라도 고양이 앞의 쥐나 마찬가지!

엑스
뭐지, 갑자기 빛이...

????
 +
어리석은 자들이여...이 [오페라의 유령]으로부터
도망칠 수 있으리라 생각했는가...

라푼젤
이 목소리...
혹시 팬텀!?

레이나
어떻게 된 거야...?
박스석에서 기다리고 있는 거 아니었어...!?

장화 신은 고양이
...거기 너희들. 미안하지만 이 아이를 데리고,
먼저 박스석으로 가도록 해.

타오
잠깐 기다려.
고양이 아저씨, 당신은 어쩌려구?

장화 신은 고양이
나는 나대로 할 일이 있지.
라푼젤을 부탁할게.

셰인
술렁거리는 기운이 느껴져요.
아무래도 빌런이 있는 것 같군요.
머리 긴 아가씨, 안내 부탁해요.

라푼젤
...네!
여러분, 이쪽으로!

***

팬텀
사랑스럽고 사랑스러운 라푼젤...
너는 대체 어디에 숨어있느냐?

팬텀
너의 아름다운 머리카락을 싹 잘라 줄까?
너의 가련한 노랫소리를 바짝 말라붙게 해 줄까?
너는 영원히 내 그림자로부터 도망갈 수 없다...

????
♪예전의 나는 새장 안의 새였어...

팬텀
불쌍하군...
공포에 질린 나머지 노래에 의지하는 건가...
역시 너는 크리스틴에게는 한참 미치지 못한다...

????
♪높은 탑 위에서 지저귀기만 하는 작은 새...

팬텀
그 정도의 재능과 각오로...
그녀를 방해하지 마라!!

팬텀
아니...
이건... 라푼젤이 아니었어...??

장화 신은 고양이
그건 축음기라고 하는,
이제 막 세상에 나온 발명품이지.
목소리까지 기록할 수 있거든, 대단하지?

*

팬텀
주위에 연기가...!?
그리고... 이 냄새는... 윽...!?

장화 신은 고양이
점점 몸이 마비되는 것 같지?
인간 전용의 마취가스에, 축음기.
여기저기 연출을 동원해서 손에 넣은 보람이 있군.

장화 신은 고양이
네가 라푼젤을 노렸을 때부터
여러모로 준비하고 있었다구.
제대로 걸려들어서 다행이야.

팬텀
...그래, 너였군.
라푼젤을 인도한 자가...

장화 신은 고양이
그런 너는 어지간히 크리스틴에게
집착하는 것 같은데. 그렇군.
모든 것은 크리스틴을 위해서라는 건가.

장화 신은 고양이
협박장에는 박스석에서 기다린다고
써놓고는 갑자기 우리 라푼젤에게 덤벼들다니,
배짱 한번 좋은 걸?

팬텀
박스석? 협박장?
무슨 얘기냐?
그런 걸 보낸 기억은 없다.

장화 신은 고양이
뭐라고?

팬텀
나는 네놈들이 온 것을 보고
움직였을 뿐.

팬텀
응?
뭐야, 너는...!?

장화 신은 고양이
앗!?
어떻게 된 거야, 팬텀!?

*

장화 신은 고양이
사라졌어!?
제길, 그 몸으로 움직일 수 있을리가 없는데...

엑스
장화 신은 고양이! 괜찮아!?

장화 신은 고양이
아, 너희들인가... 나는 괜찮아.
그렇지만, 팬텀을 놓쳐버렸군...
라푼젤은 어때?

타오
아가씨와 셰인이 같이 있으니까 괜찮아.
하지만, 박스석에는 아무도 없었다구.

엑스
팬텀은 어디로 간 걸까?

장화 신은 고양이
모르지...
그러나, 왠지 묘한 일이 일어날 것 같군...
팬텀도 모르는 뭔가가...

== 오페라 극장의 지하

????
멋지군...!
오페라 극장의 지하에 이런 동굴이 있었을 줄이야...!

????
그 협박장을 이용해서 너와 고양이를 맞부딪치게
하길 잘했군. 덕분에 꼬리가 잡히지 않던 너를
이렇게 붙잡을 수 있었지.

팬텀
네놈은 누구냐...

????
후후후. 나는 너다, 팬텀.
이제부터 네 운명을 넘겨받을 자.
조금전의 마취 때문에 너는 한동안 움직일 수 없다...

????
크리스틴에 매달리고 있는 한,
최고의 음악에는 도달할 수 없다...
그러므로, 오늘부터 내가 새로운 팬텀이 된다...!

팬텀
그만둬... 무슨 짓을 하는 거냐...
내 가면을 벗기지 마... 안돼...

팬텀
그만해애애애애애애애애!!

***

장화 신은 고양이
크리스틴에 대해 조사했는데,
여러모로 재미있는 사실을 알게 되었지.

장화 신은 고양이
크리스틴이 그 재능을 활짝 피우게 된 건
반년 전부터. 이전까지 완전한 무명이었던
그녀는 단숨에 정상의 계단을 올라갔지.

장화 신은 고양이
그런데 그 이유가...
아무래도 본인 말로는 [음악의 천사]가
자신에게 왔기 때문이라고 한다더군.

장화 신은 고양이
[음악의 천사]와 팬텀...
어디까지 관련이 있는지는 모르겠지만
그녀를 좀 감시해 주었으면 해.

== 오페라 극장의 도시

셰인
그런 식으로 장화 신은 고양이님에게 은근슬쩍
귀찮은 일을 떠넘겨 받게 된 겁니다만...
아무리 바쁘다 하더라도 왜 우리가...

셰인
하아, 밤거리는 추워요...
따끈따끈한 침대에서 한숨 자고 싶어요...

레이나
참아, 셰인.
그때 이후 팬텀은 움직이지 않고 있어...
실마리는 이제 크리스틴밖에 없단 말이야...

타오
그런데 크리스틴은 오페라 극장 최고의 가수라고 했지?
오늘 연습하는 걸 들었는데 라푼젤이 더 잘하는 것
같지 않아?

엑스
응. 크리스틴 쪽은 기운이 없다고 해야하나,
마음이 다른 곳에 가 있는 듯한 느낌이었어.
노래에 대해서는 잘 모르지만...

레이나
그녀에게도 무슨 일이 있었을까...?
사정을 들을 수 있다면 좋겠지만...

레이나
앗, 잠깐. 다들 숨어!

크리스틴

엑스
이런 야밤에 어딜 가는 걸까?

레이나
따라 가자!

== 오페라 극장의 지하

크리스틴
이 오페라 극장의 지하에 오는 것도 두번째야.
그 사람이 만든, 어둠의 고향...

크리스틴
에릭, 당신은 아직 여기에 있나요?
당신은 지금 어떤 운명을 걸어나가려 하는 건가요?

크리스틴
에릭...
나를 인도한, 무서운 천사...

레이나
에릭, 그게 유령 팬텀의 이름이었군.

크리스틴
당신들은...!?
나를 미행한 건가요!?

타오
미안해. 라푼젤의 경호를 지시 받았거든.
팬텀한테 볼일이 좀 있어서 말이야.

셰인
그나저나 오페라 극장의 지하에
이런 동굴이 있었다니 놀랐어요...
쓸데없이 넓다고 할 수도 있겠지만.

엑스
가르쳐 주세요.
오페라의 유령 팬텀에 대해서.
우린 지금 무슨 일이 벌어지고 있는지 알고 싶어요.

크리스틴
그렇군요, 라푼젤 님의...
...알겠어요.
그럼 저를 따라 오세요.

크리스틴
저와 함께 에릭을...
팬텀의 폭주를 막아 주었으면 해요...!

***

크리스틴
옛날, 아버지께서 얘기해 주었어요...
순수한 마음을 잃지 않는 사람에게는
[음악의 천사]님이 찾아와 빛나는 재능을 내려준다고...

크리스틴
그래서 반년 전 그 [목소리]가 들렸을 때,
[음악의 천사]님이 찾아와 준 거라고 생각했어요...
옛날 이야기 속의 작은 로테처럼...

엑스
하지만, 그건 천사가 아니라...
오페라의 유령(팬텀)이었던 거죠?

크리스틴
네, 맞아요.
그의 본명은 에릭. 끔찍한 얼굴을 가면 속에 감추고,
이 오페라 극장의 지하에서 고독하게 살고 있던 남자...

크리스틴
에릭은 모든 예술에 정통했고,
재능을 꿰뚫어보는 눈도 갖고 있었어요...

크리스틴
그리고 그의 눈에 들었던 나는 에릭의 음악을
실체화하는 악기로서 그에게 다듬어져 왔지요...
모두 [운명의 서]에 적혀진 그대로...

크리스틴
하지만 라푼젤, 그녀의 존재는
내 [운명의 서]에는 적혀 있지 않았어요...
팬텀도 그녀의 존재를 신경쓰고 있는 것 같았죠...

크리스틴
그가 어떻게 행동할지, 나는 알 수 없어요.
그러니까, 나는...

레이나
...그렇군. 라푼젤은 원래,
오페라 가수가 될 운명이 아니었던 거야.
대강 줄거리가 잡히는군...

엑스
레이나, 뭔가 알겠어?

레이나
응. 이 상구에서 빌런이 발생하고 있는 이유,
그건...

????
이런 곳에 뭘 하러 온 거냐, 크리스틴.

셰인
호오오~, 여기 또 무섭게 생긴 가면 남자 등장이네요.
저게 소문으로 듣던 팬텀님인가요?

타오
그렇겠지.
여기서 만났으니 너도 이제 끝장이다.
그 보기싫은 가면 채로 두들겨 주...

크리스틴
아니야!

크리스틴
저 사람... 에릭의 목소리가 아니야...
당신은 도대체 누구죠!?

????
후후후. 과연 [음악의 천사]에게 사랑받던 크리스틴.
거의 진짜에 가깝다고 생각했는데...
금방 들켜버렸군.

엑스
어떻게 된거야?!
저 사람은 팬텀이 아닌거야?

가짜 팬텀
아~니, 나는 팬텀. [오페라의 유령]이다.
이 오페라 극장의 전설이자 그림자.
이 세상에 최고의 음악을 가져올 존재다.

엑스
최고의 음악...
어라? 그건 라푼젤의 노래에 있던...

== 회상

왕자님
너의 노래가 [최고의 음악]에 이르렀을 때,
다시 한번 나는 너를 찾으러 가겠어.
반드시, 반드시...

== 오페라 극장의 지하

레이나
그랬었군...
당신이 모든 왜곡의 원인이었던 거야.

레이나
저 팬텀은 이 상구의 팬텀이 아니야.
라푼젤이 얘기한 [왕자님], 그리고...

레이나
우리와 같은 외부의 세계에서 온
[공백의 서]의 소유자야.

***

엑스
저 사람이 우리와 같은...
[공백의 서]의 소유자라고?

가짜 팬텀
오호? 너희들도 나와 같이 외부에서 온 자들이었군.
혹시 이 상구의 운명을 다시 쓰러 온 것인가?

레이나
그럴 리가 없잖아...!
당신 때문에 우리가 난처한 상황이거든?

레이나
라푼젤을 꼬드기고,
이런 식으로 팬텀의 가면까지 빼앗아서는...
이 상구를 엉망으로 만들 셈이야!?

타오
애당초 댁의 목적은 뭐지?
라푼젤과 다시 만나기로 약속하지 않았어?
왜 후다닥 만나러 가지 않는거지?

가짜 팬텀
그녀가 [최고의 음악]을 실현하면...
나는 그렇게 말했다.

가짜 팬텀
이 상구에는 훌륭한 여가수가 두 명 있지.
크리스틴, 그리고 라푼젤.
이 둘이 같은 세계에 있다는 건 그야말로 기적이다.

가짜 팬텀
두 개의 다른 재능을 제대로 이끈다면,
둘은 서로에게 영향을 끼치며, 서로 부딪치며,
이윽고 [최고의 음악]으로 승화하게 되겠지.

가짜 팬텀
하지만, 이 상구의 스토리텔러는...
크리스틴에게만 가수로서의 운명을 부여했다...
그래서 내가 운명에 개입한 거다.

셰인
당신의 시시한 이상은 어찌 되든 상관없지만,
여기 있어봐야 계속 빌런에게 쫓겨다닐 뿐이예요.
알고 있긴 한가요?

가짜 팬텀
상구를 통치하는 규칙이자 모든 것을 초월한 존재인
스토리텔러는 상구의 주민을 개인이 아닌,
그 상구에 할당된 각자의 역할로 인식한다고 하지.

가짜 팬텀
그러니 [오페라의 유령]이라는 역할이 유지된다면
내가 빌런에게 위협당하는 일 없이 존재할 수 있다.
그렇게는 생각하지 않나?

엑스
그래서 팬텀의 가면을...
그런게 가능한 거야?

레이나
모르겠어...
그렇게 말대로 쉽게 될 것 같다는 생각은 안드는데...

크리스틴
...당신이 무슨 소릴 하는 건지,
나는 전혀 모르겠어요.
그런 건 아무래도 상관 없어요.

크리스틴
에릭은...?
그 사람은 어떻게 된 건가요...?
그 사람, 지금 어디에 있나요?!

가짜 팬텀
아직 살아있지...
그도 또한 훌륭한 음악적 재능의 소유자거든.
이 지하에서 작곡이라도 하게 할 거야.

가짜 팬텀
이제 너는 운명에서 해방되었다.
내 방식은 훨씬 부드럽지. 너를 위해서라며
뭐든지 파괴하는 그 괴물과는 달라.

가짜 팬텀
너는 이제부터, 녀석이 저지르는 죄 때문에
괴로워 할 필요없다...
좀 더 기쁜 얼굴을 하는 게 어때?

엑스
저녀석...!

장화 신은 고양이
이런 이런, 흥분하지 말라구.
그렇게 화를 내봤자 상대의 페이스에 말려들 뿐이야.

레이나
장화 신은 고양이!
당신, 어느 틈에 여기에!?

장화 신은 고양이
지금 막 왔지.
고양이의 탐지능력을 우습게 보면 곤란하다구.

장화 신은 고양이
내 수염이 알려주고 있어.
저 건너편에서 누군가가 울고 있다고.
그걸 구할 수 있는 건 당신뿐이야.

크리스틴
...에릭이 저 건너편에!?
알았어요, 고마워요!

가짜 팬텀
...이해할 수 없군.
이래서 [운명의 서]에 얽매인 놈들은...

장화 신은 고양이
다른 사람의 운명을 빼앗으려 하는 녀석보다는
훨씬 낫다고 생각하는데? 각오하라구, 가짜 팬텀.
형씨들도 함께 해 줄거지?

엑스
물론!
가짜 팬텀, 너의 가면을 지금 벗겨주마!

***
*전투*

가짜 팬텀
어째서 나를 방해하는 거냐...

가짜 팬텀
나는 그저... [최고의 음악]을 실현하기 위해
조금 운명을 바꾸려 했을 뿐인데...

빌런
크르르... 크르르르...!

가짜 팬텀
머, 멈춰... 오지 마...
지금의 나는 팬텀이다...
이 상구의 주민... 이라고...!

빌런
크르르르르르!!

*

가짜 팬텀
으아아아아아아아아아아아아아!

== 오페라 극장의 지하

엑스
가면과 옷만 남았어...
그 사람은 대체 어디에?

레이나
...지워져 버린거야.
그 남자는 이 상구의 스토리텔러에게 벌을 받은 거야.

장화 신은 고양이
허어, 제 멋대로 설치다가
자신이 뿌린 씨앗 때문에 저 세상으로 가버리다니
웃기지도 않는군...

타오
어, 어어! 고양이 아저씨, 괜찮아?
땀 범벅이잖아!?

장화 신은 고양이
그래... 늙은이가 너무 무리했어...
아이고, 허리가...
나는 괜찮으니 저걸 좀 가져다 주지 않겠어?

엑스
저거라니, 가면이랑 옷 얘기하는 거야?

장화 신은 고양이
그걸 누구보다도 필요로 하는 녀석이
저 건너편에 있지...
그 녀석에게 돌려 줘야해...

*

크리스틴
에릭!
어디 있나요? 에릭~!

에릭의 목소리
...크리스틴?

크리스틴
그 목소리...
에릭, 무사했군요...!

에릭의 목소리
돌아가. 여긴 너같은 사람이 올 곳이 아니야.
나는 가면을 잃었다...
이제 난 팬텀이 아니야...

에릭의 목소리
너도 알고 있을 거야...
내 역겨운 원래의 얼굴을...
내가 앞으로 널 위해 저지를 수많은 죄악을...

에릭의 목소리
어떤 결말을 맞이할지 알면서도...
나는 너를 계속 원하겠지... 그렇기에 이대로...
사라지는 것 또한 그 대가를 치르는 거야...

크리스틴
...알고 있어요, 에릭.
당신이 앞으로 저지를 죄악으로 나 또한
사라지지 않는 고통을 짊어지게 된다는 걸...

크리스틴
하지만 당신 덕분에 나는 멋진 광경을 볼 수 있었어요.
저 무대에서의 흥분이 사라지는 일은 결코 없을
거예요...

크리스틴
그러니 나는 앞으로도 계속 저 무대에 설 거랍니다...
당신이... [음악의 천사]가 이끌어 준
가수 크리스틴으로서―

엑스
여기, 당신의 가면과 옷이예요...
그 가짜는 이제 없어졌어요.
운명은 이제 원래대로 돌아갈 거예요.

에릭의 목소리
...후, 어리석군. 기껏 이 괴물을
사라지게 할 기회가 왔는데도...
참으로, 참으로 어리석군...

== 오페라 극장의 도시

셰인
이것으로 사건 해결인듯 하군요.
이젠 라푼젤씨가
오페라 가수를 포기해 준다면 좋겠는데 말이죠...

타오
하지만, 영~ 찜찜하군.
라푼젤은 계속 속아왔던 거잖아?
그 가짜 팬텀도 사라져 버렸고...

레이나
그건 그렇네...
도대체 뭐라고 얘기하면 좋을지...

장화 신은 고양이
아~, 라푼젤을
다음 공연까지 은퇴시킬 생각은 없다구.

엑스
응? 무슨 소리를 하는 거야?
그런 짓을 하면, 빌런은
앞으로도 계속 나타날 거야!?

장화 신은 고양이
괜찮아.
이건 운명을 원래대로 돌리기 위한 커다란 연극이니까.

장화 신은 고양이
자아, 여러분들.
마지막으로 큰 부탁 좀 할게.
내 연극을 같이 좀 도와줘.

== 오페라 극장 통로

라푼젤
드디어, 내 무대가 시작이야...
지금의 내가 [최고의 음악]을 노래하는 것이 가능할까?

라푼젤
부디 절 지켜 주세요,
왕자님...

크리스틴
라푼젤, 드디어 시작이군요...

라푼젤
크리스틴님!
저, 저기, 저는...

크리스틴
그렇게 긴장하지 말고...
크리스틴이라고 불러도 괜찮아요.

크리스틴
...오디션에서 부른 당신 노래 정말 훌륭했어요.
라푼젤, 당신은 나와는 다른 당신만의 광채를
갖고 있어요.

크리스틴
당신과 같이 공연하게 된 걸 자랑스럽게 생각해요.
자, 함께 가요.
우리들의 무대로.

라푼젤
...네, 크리스틴!

장화 신은 고양이
사실은 말이지,
원래 라푼젤과 맺어질 운명이었던 건
내 주인인 카라바 후작이었어.

== 오페라 극장의 도시

장화 신은 고양이
탑에 갖혀있던 라푼젤의 노래에
이끌린 내 주인이, 그녀에게 첫눈에 반해버려
맺어지게 된다. 그런 줄거리였는데 말이야...

장화 신은 고양이
...어디서 뭐가 잘못된 건지, 라푼젤이
이 도시에서 오페라 가수가 되겠다고 와 있던 거야.

장화 신은 고양이
우연히 그녀를 발견했을 때에는 정말 심장이
튀어 나올 정도로 놀랐다구. 덕분에 상담사라는
어울리지도 않는 일을 시작하게 되어 버렸지.

엑스
그런거였구나...
하지만 그렇다면 오히려 라푼젤이나 후작에게
직접 알려주었으면 좋았잖아?

장화 신은 고양이
사랑은 눈을 멀게 만들지.
가짜 왕자에게 마음을 빼앗긴 그 아이에게,
진실을 얘기해줘 봐야 소용없어.

장화 신은 고양이
내 주인도 계속 시찰 때문에 바빠서,
성을 비우는 일이 많았고 말이야.

장화 신은 고양이
그래서 억지로 [운명의 서]의 줄거리대로
끌어오려 했던 거야.

장화 신은 고양이
그거 알아?
이번 연주 목록에 높은 탑에서 프리마돈나가
혼자 노래하는 장면이 있거든.

장화 신은 고양이
이 공연에는 내 주인도 보러 와 있지.
원래 [운명의 서]에 적혀있는 것과 비슷한
상황을 준비해 두면, 아마도...

레이나
아하~ 그러니까 이번 공연만 잘 넘기면
이 상구의 운명은 무사히 원래대로 돌아올 가능성이
높다는 얘기네.

셰인
바깥 상황을 보고 왔어요.
역시나 빌런들이 여기저기서 모이고 있군요.
모두 오페라 극장쪽을 향하고 있어요.

타오
드디어 결판을 낼 때가 온 거야.

장화 신은 고양이
...그렇다면 슬슬 마지막 임무를 끝내야겠군.
아아, 제길... 몸이 또 아파오는군...

타오
이런, 무리하지 마.
나머진 우리들한테 맡기라구.

장화 신은 고양이
늙은이 취급하지 마!
그 빌런이라는 괴물들, 한두 마리가 아니지?
그럼 조금이라도 머릿수가 많은 편이...

????
쥐 한마리 제대로 못잡을 고양이 손까지
빌려야 할 필요가 있을까?

엑스
팬텀...
뭐하러 온 거야?

팬텀
그렇게 냉정한 소리 하지 마.
나는 누구보다도 오페라 극장의 음악을 사랑한다.

팬텀
크리스틴이 주연이 아니라는 점은 부아가 치미지만
내 무대가 남에게 더럽혀지는 건
더더욱 불쾌해서 견딜 수가 없어. 같이 싸우겠다.

장화 신은 고양이
...헤, 헤헤.
여어, 팬텀.
꽤나 극적인 등장이구먼.

팬텀
과장된 연기는 네놈쪽이지.
네놈의 어설픈 연기 덕에,
내 운명도 어지간히 엉망이 되어버렸다.

팬텀
네놈은 조용히 무대나 감상하고 있어.
2층 5번 박스석, 나의 특등석을 준비해 놓았다.
고맙게 생각하도록.

장화 신은 고양이
쳇, 너한테 시달리는 극장 지배인이 불쌍하군.
알~았다구. 뒷일은 부탁하지.

레이나
맡겨둬, 장화 신은 고양이!
공연은 무슨 일이 있어도 꼭 지켜내겠어!
팬텀도 알겠지!?

팬텀
그래, [오페라의 유령]의 무서움을
뼛속 깊이 느끼게 해주지.

***
*전투*

== 오페라 극장 회장

라푼젤
끝났어... 내 무대가...
내가 할 수 있는 건... 전부 보여줬어...

크리스틴
축하해요, 라푼젤!
최고의 노래였어요!

라푼젤
크리스틴... 고마워요... 고마워요...
왠지 지금, 가슴이 너무 뜨거워져서...

크리스틴
무대에서 모든 걸 다 보여주면 그런 기분이 되는 거에요.
그 느낌을 잊지 않기 위해 우리들은 계속 무대에
오르는 거죠.

라푼젤
그래, 그랬군요...
내가 찾고 있던 건 왕자님이 아니었어요...

라푼젤
그 탑에서 보였던 밖의 광경...
끝없이 펼쳐지는 저 밖의 세계로 뛰어들고
싶었던 거에요...

라푼젤
난 이 노래로 밖을 향해 날아올랐어...
정말 원했던 건...
이미 내 안에 있었던 거야...

크리스틴
어머나? 라푼젤,
당신에게 손을 흔들고 있는 손님이 있어요.
카라바 후작 같은데요?

라푼젤
...카라바 후작?

라푼젤
...어째서일까, 저 분과는 처음 만난 느낌이 아니야.
아주 이전부터, 알고 있던 것 같은...

크리스틴
어서 가 봐요!
저 사람, 당신에게 관심있는 것 같아요.

라푼젤
저, 저기...
카라바 후작님, 안녕하세요...

크리스틴
에릭, 오늘 내 노래는 어땠나요?

크리스틴
언젠가 당신의 고독과 슬픔이 치유되는 그날까지,
나는 계속 이곳에서 노래할 거예요...
그러니까 부디 지켜봐 줘요. [음악의 천사]님...

== 오페라 극장 2층 통로

장화 신은 고양이
이런 이런...
이걸로 겨우 제자리로 돌아가기는 했지만...
고양이를 이렇게 혹사시키다니.

장화 신은 고양이
자, 드디어 이걸로 나도 편안한 노후를 보내게 되었군.
돈 많은 후작님과 아름다운 부인에게 보살핌을 받는
꿈 같은 화려한 생활. 으음, 두근두근 하는 걸.

장화 신은 고양이
너희들에게도 뭔가 인사를 해둬야 겠지.
헤헤, 정말 잘 해줬어.

팬텀
녀석들이라면 이미 출발했다.
더 이상 이 상구의 운명에 간섭할 수는 없다면서 말이야.

장화 신은 고양이
...팬텀이냐.
갑자기 말 걸지 마. 놀라잖아.
모습을 드러내는 게 어때?

팬텀
[오페라의 유령]은 망령 같은 존재...
간단히 모습을 드러내거나 하진 않는다...
그런 존재다...

장화 신은 고양이
아~ 예예. 그렇군요.
하지만... 그랬군. 다들 가버렸군.
적어도 우리 라푼젤의 노래를 들려주고 싶었는데...

팬텀
흥, 라푼젤 따위...
크리스틴의 발끝에도 못 미치지...
짐승은 진정한 예술을 이해하지 못한다.

장화 신은 고양이
허이구, 잘도 그런 소릴. 가면 쓴 스토커 주제.
안심하라구. 이제 곧 라푼젤은 은퇴다.
그 다음은 당신이 좋을대로 하면 돼.

팬텀
그렇군.
너의 얼굴을 안 봐도 된다고 생각하니,
시원하군.

장화 신은 고양이
그건 내가 할 소리.
오페라 극장의 일은 이제 지긋지긋하다구.

장화 신은 고양이
하지만 말이야 난 짐승이지만,
당신이 준비한 그 박스 자리는 최고였어.
그럼 잘 있으라구, 팬텀.

팬텀
그래, 작별이다...
나의 숙적 장화 신은 고양이여...