= 9. 이상한 나라의 상구 - Flero
:hardbreaks:

....
어떤 곳에 앨리스라는 소녀가 살았습니다.
공상을 좋아하는 앨리스에게 언니가 읽는
그림이나 대화가 없는 책은 따분함 그 자체.

그날도 앨리스는 강가에서 언니 옆에 앉아
공상에 잠겼는데 어디선가
이런 목소리가 들려왔습니다.

「이런, 큰일이다! 지각이다, 지각!」
하고 허둥대며 시계를 가진 토끼가
눈앞을 지나갔습니다.
놀란 앨리스는 시계 토끼의 뒤를 쫓아갔습니다.

바쁘게 뛰어다니는 시계 토끼는 마침내
커다란 토끼 굴로 뛰어듭니다.
호기심을 참지 못한 앨리스도
또 뒤를 따라 굴로 뛰어들었습니다.

굴 안으로 떨어진 앨리스는
어쩐지 아주 천천히 떨어진 듯한 느낌을 받았고
길고 긴 시간을 지나 앨리스는 어떤 장소에
도달합니다.

그곳은 기묘한 주민들이 사는 『이상한 나라』.
앨리스는 혼자 이 『이상한 나라』에서
길을 잃고 말았습니다.
....

== 다과회의 초원

???? ※모자장수 해터
헤이~ 아가씨. 우리랑 차 한잔 어때?
이 모자장수 해터와 3월 토끼의 티 파티에서
하얗게 불태워 보지 않을래?

???? ※삼월토끼
그래~ 당신처럼 귀여운 아이라면
우리 [매드 티 클럽] 파티는 대환영이야!

레이나
어...저기 잠깐만!
티... 티 파티라니?

*

엑스
도착하자마자 레이나가 모르는 사람들한테 붙잡혔어!!

셰인
셰인은 뭔지 알아요. 저거 헌팅이라는 거죠?
대단해요, 언니. 엄청난 인기네요.
저게 전설의 [저랑 커피 한 잔 하실래요]구나...

타오
아가씨한테 저런 패거리가 잘 달라붙는 것 같아.
의외로 세상 물정을 잘 모르다 보니
이상한 사람들이 다가가기 쉬운가 봐...

레이나
이봐! 보고만 있지 말고 좀 도와 줘!
아니... 그러니까 파티에는 안 간다구.
으아앙... 도와 줘!! 헬프 미!!

엑스
어휴... 보고있자니 불쌍하네...
내가 다녀올게...

*

???? ※앨리스
삐삑!!
이봐! 거기 두 사람!!
풍기문란 죄로 체포하겠다!!

모자장수 해터
큰일이야!
[정숙한 숙녀를 위한 풍기 단속 부대]다!
앨리스가 왔다구! 도망가자! 3월 토끼!

3월 토끼
알았어! 모자장수 해터!
우리 매드 티 클럽은 화려하게 도망갈지어다!

????
어휴, 매드 티 클럽!
오늘은 꼭 이 앨리스가 체포해 주겠어!
기다려~~~!!

레이나
저 아이... 앨리스라니 설마...

셰인
어?
언니, 왜 그러세요?

레이나
다들 얼른 저 아이를 쫓아가!

엑스
어? 자... 잠깐... 레이나!

***

모자장수 해터
쳇! 앞질러 오다니!

앨리스
후후후. 이제 단념해!
풍기를 문란하게 하는 자는
이 앨리스가 용서하지 않을 거니까!

레이나
자... 잠깐만!
앨리스! 앨리스!!

앨리스
당신은 조금 전에 본...?
뭐죠? 지금은 임무중인데...

엑스
하아, 하아... 드디어 따라잡았다...
레이나는 대체 어쩔 셈이지...?
혹시 벌써 카오스 텔러의 단서를 잡은 건가...

레이나
저기... 나, 나는...

레이나
당신의 엄청난 팬이야!

레이나 이외 전원
뭐?

레이나
어릴 때부터 [이상한 나라의 앨리스]를
엄청 좋아했어!! 여기가 앨리스의 상구지?
체셔 고양이는? 시계 토끼도 있어!?

엑스
레이나... 왜 저러는 거야?

셰인
모르겠어요.
잘 모르겠지만 평소보다 더 상태가 안 좋은 건
분명하네요.

앨리스
[이상한 나라]? 아냐, 그렇지 않아!
그건 옛날 얘기야!
모든 [이상한] 것들을 내가 단속하고 있거든!

레이나
어? [이상한] 것들을 단속한다고?

앨리스
이 세상에서 멋대로 설치는 이상한 것들과 부조리,
불건전한 것을 단속하는 게 우리의 역할이지.
이름하여 [정숙한 숙녀를 위한 풍기 단속 부대] 이야!

앨리스
이상한 말을 하는 걸 보니
아무래도 당신도 체포하는 게 좋겠어!
트럼프 병사! 잡아!

레이나
체... 체포!?
자, 잠깐만. 어떻게 된 거야? 앨리스!

3월 토끼
이봐. 당신들!
이 녀석들과 얘기해봤자 말이 안 통한다고!
우리랑 같이 도망가지 않을래? 도망 치자!?

엑스
그게 좋겠어...
도망가자. 레이나!

레이나
앨리스... 어째서...

앨리스
이봐! 기다려!!

== 숙녀의 초원

엑스
―앨리스 일행의 추적을 피한 우리는
아무것도 없는 초원에 도착했다.

엑스
그 곳에서 매드 티 클럽의
모자장수 해터와 3월 토끼가
이 상구의 사정을 말해 주었다.―

모자장수 해터
옛날엔 다들 좀 더 자유로웠어.
떠드는 것도 자유, 큰소리로 외치는 것도 자유.
규칙은 단 하나! [모든 일에 의미를 부여하지 말라]!

3월 토끼
하지만 [정숙한 숙녀를 위한 풍기 단속 부대]가
나타난 뒤로는 모든 게 변해버렸어. 이상한 사람은
인정하지 않겠다며 모두 데려가 버렸지...

엑스
그 대장이 아까 본 앨리스라는 여자아이구나...

모자장수 해터
요샌 이것도 안 되고 저것도 안 되고, 다 안 된대.
모조리, 전부 없애 버렸어...
지금의 앨리스는 정상이 아니야.

레이나
정상이 아니...

3월 토끼
그건 제쳐두고!
우리 다같이 티 파티 하지 않을래?
쭉쭉 마시고, 단숨에 해치워 버리자고!

셰인
아뇨. 사양하겠습니다.
...어쩐지 위험한 냄새만 나니까요.

3월 토끼
그으래?
그럼 마음 내킬 때 언제든지 와!
우리는 늘 웰컴이니까!

모자장수 해터
진정한 자유는 우리 매드 티 클럽에 있으리!
자, 3월 토끼여.
지금 이 순간! 무사히 도망친 기념으로 차를 마시자꾸나!

3월 토끼
오오! 좋지, 좋아!

타오
허어... 가버렸네.
대체 누가 정상인지 모를 상구군.
자, 이제부터 어떻게 할까?

엑스
저기 레이나.
아까 [이상한 나라의 앨리스]가 어쩌고 했잖아.
레이나는 이 상구에 대해 뭔가 알고 있어?

레이나
이 상구의 모델이 된 얘기를 알고 있어.
[이상한 나라]를 헤매는 한 여자아이 이야기를
어릴 때 들은 적이 있거든....

레이나
그래. 걸어 가면서 설명할게...

***

셰인
흠. 그러니까 이 상구는 그 [이상한 나라의 앨리스]
얘기가 모델이라는 거군요.

타오
하지만 얘기를 들어보니까 뭐랄까... 원래는 상당히
엉망진창인 세계였던 것 같은데. 그런데 그 이야기에
[건강한 청년을 위한 불량배]는 안나온다는 거지?

셰인
타오 오빠,
[정숙한 숙녀를 위한 풍기 단속 부대] 예요.
그런데 이름이 너무 길군요. 정숙대로 줄일까요?

레이나
어디까지나 상구는 그 얘기를 모델로 만든 것 뿐이라
세세한 부분은 다를지도 모르지만... 적어도
저런 부대 얘기가 나오는 에피소드는 없었어.

레이나
하물며 [주연]인 앨리스가 [이상한 나라]를
단속하다니...

엑스
그럼 다시 한번 앨리스를 만나러 가자.

레이나
하지만 우리는 앨리스의 눈 밖에 났잖아.
얘기를 안 들어줄 지도 몰라.

엑스
그래도 만나보기 전에는 아무것도 알 수 없잖아.
그리고 이제와서 눈 밖에 나는 것 정도는
전혀 무섭지 않아.

셰인
말 한 번 잘 했습니다. 신참 씨.
사실 그 말 그대로 입니다.

타오
좋~았어. 그럼 다시 청축대를 찾으러 가 볼까!

셰인
타오 오빠.
그 정도로 틀려버리면 그냥 바보일 뿐이에요.

레이나
그것도 그렇네. 다들 고마워.
그럼 다시 앨리스를 찾으러 가 보자.

== 불건전한 마을

무서워하는 마을 사람
어, 어떻게 그런...! 부디 자비를! 자비를!
작업 중 피곤해서 잠깐 멍하니 있던 것 뿐이에요!
결코 게으름 피우던 게 아니라구요!

앨리스
안돼.
집중력이 흐트러진다는 건 풍기가 문란하다는 거야!
작은 혼란이 질서를 어지럽히지! 그렇지, 부대장?

시계 토끼
네... 넵! 새... 새 법안에도 나와 있네요.
[노동 중에는 작업과 관계 없는 생각을 금지한다]
다, 당신은 그걸 위반했어요.

앨리스
트럼프 병사. 이 사람을 데려가!
풍기를 어지럽히는 나쁜 아이는 재판을 받아야지!

무서워하는 마을 사람
아악! 싫어! 재판은 싫어!

레이나
그만둬! 앨리스!

시계 토끼
헉!? 뭐... 뭐죠!?
사람이 엄청 많이 왔는데요!?

앨리스
또 당신이야? 대체 뭐야...
내 임무를 방해하지 마!
나는 모두를 위해서 일하고 있거든?!

레이나
아니야. 지금 넌 원래의 네가 아니야.
카오스 텔러의 영향인 걸까?
대체 누가 너를 그렇게 바꿔놓은 거지?

앨리스
카오스 텔러...? 원래의 나...?
무슨 말인지 전혀 모르겠어.

앨리스
에잇. 더 이상 일을 방해하면 모두 체포할 거야!
트럼프 병사! 저 사람들을 잡아!

타오
질서니 뭐니 하면서 결국은 난폭한 걸 좋아하는가 보군!

엑스
그건 그렇고 머릿수로는 못 당할 것 같은데?

셰인
어떻게 할까요? 언니.
이대로 철수할까요? 아니면 맞서 싸울까요?

레이나
물러설 생각은 없어.
앨리스를 설득할 때까지 이대로 밀고 나갈 거야!

***
*전투*

시계 토끼
대... 대장님~!
트럼프 병사가 전부 당해버렸어요~!

앨리스
다, 당황하지 마. 우리는 하트의 여왕님께
선택 받은 최고의 숙녀야! 공상과 불가사의를 동경하는
어린 아이가 아닌 성숙한 레이디 말이야!

엑스
안 되겠어... 얘기가 전혀 안통해...
레이나, 어떻게 설득할 거야?

레이나
성숙한 레이디라...
성숙한 레이디는 이상한 케이크를 집어먹고
몸이 커지지는 않을 걸.

앨리스
흠칫!

레이나
언니 말을 무시하고 토끼를 쫓다가 굴에 빠지고,
키우던 고양이를 인사시키려 하고,
그런 엄청난 말괄량이가 성숙한 레이디(웃음) 라니.

앨리스
어, 어떻게 당신이 그걸 알고 있지?
숨기고 싶은 과거를... 내 흑역사를!

레이나
후후후. 너에 대해서는 전부 알고 있어.
원한다면 여기 있는 모두에게 얘기할 수도 있는데?
그 흑역사인지 뭔지를.

앨리스
그~~ 만~~ 해~~!

셰인
어라? 설득이란 게 뭐였죠?
셰인 눈에는 협박으로 보이는데요.

타오
그래도 저쪽에 먹히고 있어...
이거 이대로 밀고 나가면 될 거 같은데?

모자장수 해터
이~~~얏호!!
만반의 준비를 갖추고 등장하였도다. 매드 티 클럽!!

3월 토끼
앨리스 대장!
우리 파티에 강제로 초대하겠어!
이~~~얏호!!

앨리스
잠깐, 좀, 그만해...
꺄아아아아아아아아아아아아악!!

시계 토끼
대, 대장님!!
어떡하지, 어떡해!
대장님이, 대장님이 납치됐어~~!!

레이나
당황하고 있을 때가 아니잖아!
정말이지 저 두 사람은 이 타이밍에 쓸데없는 짓을!
어서 쫓아가자!

엑스
이 상구는 정말 정신이 없네!

== 문제의 숲

엑스
―우리들은 모자장수 일행을 쫓아 숲에 도착했다.
하지만 매드 티 클럽의 모습은 어디에도 보이지 않았다.

엑스
앨리스의 이름을 몇 번이나 불러봤지만
돌아오는 대답은 없었다―

타오
쳇. 그 녀석들 어디로 가버린 거야...
설마 납치하려고 계속 기회를 노리고 있었던 건가?

셰인
으음~ 그냥 충동적으로 행동하는 것 같은데요...
그래서 오히려 행동을 예측하기 어려워서 성가시네요.

레이나
앨리스...

엑스
정말 좋아했나 보구나.
[이상한 나라의 앨리스] 얘기를...

레이나
내가 지내던 성에 이야기를 종종 들려주던
할아버지가 있었어. 그 분 이야기를 정말 좋아했어.
그 중에서도 앨리스가 특히 마음에 들었지.

레이나
이상한 나라의 모험을 동경해서...
굉장히 두근거렸거든...
뭐 그래서 생각이 많은 건지도 모르겠지만...

엑스
그렇구나...
그럼 더더욱 카오스 텔러 마음대로 바꾸게 둘 수는 없지.

모자장수 해터
으아악!
사... 사사사사살려줘어어어어어어어!!

타오
방금 그 소리...
그 모자장수 목소리 아니야!?

***

모자장수 해터
지... 지지지지진정하게!
우선 허브티를 마시면서 진정하자고!
그러니까 그 커다란 괴물은 도로 집어넣고...!

시계 토끼
정, [정숙한 숙녀를 위한 풍기 단속 부대]를...
야, 얕보지 마세요...!
커다란 괴물이 아니라, 에이스 씨라구요!

시계 토끼
어서 대답하세요...
대장님을... 앨리스 대장님을 어디로 데리고 간 거죠?

엑스
시계 토끼와 모자장수!
그리고 시계 토끼 옆에 있는 건...
메가 빌런인가...!

레이나
저 시계 토끼...
허둥대기만 하는 줄 알았더니 성가신 걸 불러 왔잖아!

레이나
정숙대가 마음대로 하게 내버려 두지는 않을 거야!
쓰러뜨리자!

시계 토끼
머, 멋대로 이상하게 부르지 마세요~!

***
*전투*

시계 토끼
어, 어어어떻게...
[정숙한 숙녀를 위한 풍기 단속 부대]의 에이스 씨가!

레이나
이제 어떻게 할 거지? 시계 토끼.
또 뭘 부를 거면 상대해줄게.

시계 토끼
여, 여여왕님께... 보고해야 돼요오오!
[정숙한 숙녀를 위한 풍기 단속 부대]는
절대로 지지 않을 겁니다아아아아아!

엑스
그 긴 이름을 더듬지도 않고 잘도 말하네.
안 쫓아가도 돼?

레이나
토끼보다 지금은 앨리스의 행방을 찾아야 돼.
우선 저쪽 사정부터 들어봐야지.

모자장수 해터
이봐! 그만둬! 힘으로 누르지 마!
매드 티 클럽은 폭력에 굴하지 않는다구!
초대 손님의 프라이버시는 함부로 공개하지 않아!

타오
초대 손님이라니 너희가 앨리스를 납치해 갔잖아!
구해줬는데 그렇게 나오겠다...? 아. 그래.
그쪽이 그럴 생각이라면... 해치워. 셰인.

셰인
알겠습니다.

모자장수 해터
흥... 뭐야뭐야. 힘으로 해결하려고 해봤자
아무 의미 없을 거... 응? 왜 어깨에 손을 올리지?
엄지 손가락을 왜 꽉 누르는...

셰인
갑니다... 비장의 기술 오니가시마류 쾌감 지압술!

모자장수 해터
끼... 꺄아아아아아아아아아아악!!
안돼애애애애애애애애애애애애애애애애!!

엑스
뭐야 저건...
모자장수가 어린 아이한테는 보여 줄 수도 없는
얼굴을 하고 있어... 대체 셰인이 뭘 한 거야?

타오
후후... 이건 궁극의 오니가시마류 쾌감 지압술!
몸의 혈자리를 정확하게 자극하고 궁극의 쾌락을
느끼게 하여 상대방의 적대심을 없애는 기술이지.

레이나
아니, 뭐야 그 쓸데없이 대단한 특기는.

타오
궁극의 쾌락은 궁극의 고통과도 같지...
어때? 입을 열 마음이 생겼어?

모자장수 해터
큭... 죽일 거라면 죽여라...
매드 티 클럽은 결코 지지 않...

셰인
이얍

모자장수 해터
꺄아아아아아아아아아아아아아아악!
굉장해애애애애애애애애애애애애애애애!!

엑스
―지압공격으로 이성도 광기도 날아가 버리는
쾌락을 느낀 모자장수는 마침내 곧 숨이
끊어질 듯한 상태로 앨리스가 있는 곳을 불었다.

엑스
그리하여 우리는 모자장수의 안내로
매드 티 클럽의 은신처에 가게 되었다―

== 해터의 아지트

모자장수 해터
도착했다! 여기가 우리 은신처라네!
앨리스도 지금 여기서 3월 토끼와 함께
차를 마시고 있을 시간...

3월 토끼
으아~~앙!!
모자장수!!

모자장수 해터
무, 무무슨 일이야. 3월 토끼!
응? 앨리스가 안 보이는데...

3월 토끼
앨리스가... 앨리스가... 없어졌어~~!!

레이나
어떻게 된 거야!?
또 누가 데려간 거야!?

3월 토끼
있잖아. 조금 전까지 나랑
엄청 즐겁게 다과회 하는 중이었거든.

3월 토끼
그런데 앨리스가 차 매너가 엉망이라고 화를 내서...

3월 토끼
어떻게든 달래보려고 했는데...
이제 이런 차는 못 마시겠다면서
점점 동굴 깊숙한 곳으로 가버렸어~~!

타오
아... 뭐... 너희랑 안 맞을 것 같긴 하지...
그 아가씨.

셰인
이 동굴... 제법 안쪽까지 이어져 있는 것 같아요...
어서 찾으러 가지 않으면 미아가 될 수도...
그런데 무엇 때문에 그렇게까지 화를...

셰인
저기 하나 물어봐도 돼요?
차라는 게 이렇게 선명한 청록색이었던가요?

3월 토끼
그건 저번에 쐐기벌레 씨한테
받았는데 완전 최첨단 찻잎이야!
매우 건강해지는 케미컬 드링크? 라길래...

레이나
매너 문제가 아니잖아!
왜 그런 걸 내어준 거야!!

3월 토끼
왜냐니 그건 우리가...

모자장수&3월 토끼
매드 티 클럽이니까!!

엑스
레이나, 서두르자.
이 사람들이 카오스 텔러보다 질이 안 좋아.

레이나
그래 맞아.

***

앨리스
으으... 정말 싫어... 뭐야 그 사람.
그렇게 이상한 걸 먹이려고 하다니...
역시 체포해야 돼. 저런 사람들은...

앨리스
나는 저런 사람들이랑은 달라...
현실을 잘 아는 성숙한 레이디야.
더이상 꿈꾸는 여자아이가 아니라고.

레이나
아니. 넌 꿈꾸는 여자아이야.
그것도 아주 멋있는.

앨리스
당신은... 왜 또...

레이나
당신이 아니라 나는 레이나야.
이 사람들은 동료인 엑스, 타오, 셰인이야.

엑스
우리는 너를 구하러 왔어.
이 곳은 위험하니까 함께 돌아가자.
저 두 사람한테는 우리가 말할게.

셰인
뭐. 여차하면 오니가시마류 쾌감 지압술로
입 다물게 할 수도 있어요.

타오
맞아 맞아. 우리는 네 편이야.
그러니까 너무 미워하지 마. 얘기를 나누는 것 쯤은
이상하지도 않고 부조리하지도 않잖아?

앨리스
레이나... 씨?
당신은 나에 대해서 잘 알고 있는 것 같은데...
어째서? 왜 나를 구하려는 거야?

레이나
너는 무슨 말인지 모르겠지만
내가 어릴 때 네 도움을 받은 적이 있거든.
네 [이야기] 덕분에.

앨리스
내 [이야기]...?

레이나
저기, 앨리스.
지금 네가 하고 있는 단속이
정말 네가 하고 싶은 일이야?

레이나
너는 스토리 텔러로부터
더 두근거리는 모험을 할 [운명]을
받은 것 아니었어?

앨리스
모험 같은 건 시시해.
이제 난 그런 거 졸업했어.
성숙한 레이디가 할 일이 아니야.

레이나
뭐 어때? 무리해서 어른이 되지 않아도 괜찮아.
있는 그대로의 너도 충분히 멋진 걸.

레이나
너와 하고 싶은 얘기가 아주 많아.
그러니까 과자 먹으면서 얘기하지 않을래?
걱정마. 꼭 제대로 된 과자를 준비할게.

앨리스
\......

앨리스
난 먹을 거라면 쿠키가 좋아.
정말 정말 맛있는 쿠키를 준비해 줄 수 있어?

레이나
그래 물론이지!

***

앨리스
호박 마차를 만드는 마법사?
바깥에는 그런 세계도 있어?

레이나
그렇다니까. 호박 마차 뿐만이 아니야.
무서운 늑대와 보물섬의 해적, 풍차 거인까지
여러 상대와 싸웠는 걸.

레이나
뭐, 전부 내 지혜와 용기로 헤쳐 오긴 했지!

앨리스
대단하다... 그 밖에는?
그 밖에 레이나와 친구들은 어떤 모험을 했어?

*

엑스
둘 다 많이 친해진 것 같네.

셰인
그렇네요.
약간 언니 이야기가 본인한테 유리하게
포장된 것이 맘에 안들긴 하지만요.

타오
뭐... 너무 그러지 마. 이제 앨리스와 친해져서
카오스 텔러에 대해 알아내면...

3월 토끼
큰일났어! 모자장수가! 해터가!
모자장수모자장수모자장수모자장모
자장자장자장자장잘도잔다...!

엑스
자장가 부를 때가 아니야!
...가 아니고, 무슨 일이야?
모자장수한테 무슨 일 생겼어!?

*

시계 토끼
드, 드디어 찾았군요! 불건전한 무리들!!
더 이상 도망 못 갑니다!

모자장수 해터
끄응...
잡혀 버렸군...

앨리스
시계 토끼... 너...!

시계 토끼
대장님! 여기 계셨군요!
자, 어서 이 사람들을 모두 잡아서 돌아갑시다!
일망타진하면 큰 공을 세울 수 있어요!

앨리스
\...

시계 토끼
어... 왜 그러세요? 앨리스 대장님.
그 반응은... 설마... 대장님도
저 사람들한테 물들었나요...?

앨리스
저기, 잘 들어. 시계 토끼. 이 사람들은
그렇게 나쁜 사람들이 아니야. 얘기를 잘 들어보면
이해할 수 있을 거야. 그러니까...!

시계 토끼
아, 됐어요. 이제 됐어요.
당신은 [정숙한 숙녀를 위한 풍기 단속 부대] 대장이
아니에요. 이젠 단속 대상이죠.

앨리스
시계 토끼!

레이나
물러나 있어. 앨리스!
너는 우리가 지킬 거야!
가자 얘들아!

***
*전투*

시계 토끼
흐... 흥! 애써 저항하려나 본데
이 녀석만 잡으면 우리 승리는 확정이에요!
저 먼저 철수할게요!

모자장수 해터
꺄아아!! 재판은 싫어!!
살려 줘!!

3월 토끼
안돼...!
모자장수가... 해터가...!!

엑스
큰일났어...! 빨리 쫓아가야 해!

엑스
이런...! 또 나타났어...!

레이나
얼른 이 녀석들을 쓰러뜨리자, 엑스!
이러다가는 시계 토끼를 놓쳐버리겠어!

엑스
알고 있어!
우오오오오오오오오오!!

***
*전투*

엑스
틀렸어. 시계 토끼를 완전히 놓쳤어.

레이나
모자장수가 재판이 어쩌고 하던데...
잡히면 어떻게 되는 거야?

앨리스
재판할 때는 하트의 여왕님이 직접 죄인을 심판해.
판결은 예외 없이 다 처형이지만.

타오
처음부터 결과가 정해진 재판인 거네.
그런 녀석이라고해도 역시 내버려 둘 수는 없으니...

셰인
직접 쳐들어가서 구하는 수밖에 없겠네요.
그 재판은 어디서 열리죠?

3월 토끼
하트의 여왕 성인데... 안 될 거야...
성에는 특별한 길이 있고
선택 받은 사람이 아니면 들어갈 수 없어.

3월 토끼
우리들은 성까지 갈 수도 없...

앨리스
내가 안내할게.

레이나
앨리스...!

앨리스
나는 하트의 여왕 직속 부대인
[정숙한 숙녀를 위한 풍기 단속 부대] 대장을
지낸 사람이야.

앨리스
하트의 여왕 성으로 가는 길도 알아.
재판장까지 데려다 줄게.

3월 토끼
으아~~앙! 앨리스으으으!
고마워! 정말 고마워!

앨리스
인사는 레이나와 친구들한테 해.
나는 그냥 맛있는 쿠키에 대한 답례를 하는 것 뿐이니까.

레이나
응, 앨리스. 고마워...

== 여왕의 재판소

레이나
앨리스, 이 문 너머에서 재판이 열리는 거야?

앨리스
응, 아마 지금쯤 법정이 열렸을 거야.

엑스
저기, 역시 하트의 여왕이 카오스 텔러일까?

타오
어느 쪽이든 상관 없어.
이 재판에 이의가 있다는 건 변함 없으니까.

셰인
맞아요. 얼른 쳐들어갑시다.
하나 둘...

*

엑스
어? 아무도 없는데?
재판이 안 열렸어...

레이나
어떻게 된 거야? 앨리스.

앨리스
즉, 이렇게 된 거지.

타오
이봐 이봐.
재판 치고는 엄청난 병사가 무더기로 모여 있는데?

셰인
그렇군요.
아무래도 이건 화약을 들고 불 속으로
뛰어드는 상황이네요.

시계 토끼
대장님, 고생하셨습니다!

시계 토끼
작전 대성공이네요! 일부러 모자장수한테 잡혀서
그 소굴이 있는 곳도 알아내고 틈새를 노려
방해하는 이 사람들까지 감쪽같이 속이다니...

시계 토끼
대장님을 의심하는 연기를 했을 때는 내심
흠칫 했는데... 작전은 대성공이에요! 역시 대장님!
이 냉철한 모습이야말로 성숙한 레이디죠!

앨리스
이제 알겠지? 레이나.
당신이 들려준 모험담은 재미있었지만
그런 건 아무 쓸모도 없어.

앨리스
꿈, 공상, 이야기. 그런 데 얽매여 있는 한
성숙한 레이디는 될 수 없다고.
당신은 언제까지나 보잘것없는 어린아이일 뿐이야

엑스
그렇지 않아, 앨리스. 만약 진심으로 그렇게
말하는 거라면 아직 네가 우리를 얕보고
있는 거야. [이야기]의 힘을 너무 우습게 봤어.

레이나
앨리스, 너에게 가르쳐 줄게.
내가 너한테 이야기한 모험담이 거짓이 아니란 걸...

레이나
우리에게 깃든 히어로의 영혼은
이런 역경 따위에 지지 않아!

***
*전투*

레이나
하아... 하아...
어때? 이래도 아직 우리를 체포할 생각이야?

시계 토끼
말도 안돼... 트럼프 병사가 전멸하다니...

앨리스
어째서... 어째서?
나는 이제 옛날처럼 공상으로 도망치는
약한 여자아이가 아닌데...

앨리스
현실에 맞서 싸워 이기는 강한 힘을 가진
여자아이란 말이야!

레이나
공상으로 도망치면 어때?
나는 정말로 네 [이야기]를 좋아했어.

레이나
잘난 체하는 교훈과는 다른
앨리스의 이상한 나라의 모험을 듣고 자랐지.
그래서 지금 내가 여기 있는 거야.

앨리스
내 모험...
이상한 나라의 모험...

앨리스
어? 왜 내가...
단속을 하고 있는 거지...?

????
흔들리지 마! 앨리스!
이 세계에서 이상한 것이나 공상 따위는
필요하지 않아!!

*

엑스
저 사람이 하트의 여왕...!?
하지만 저 모습은...

셰인
맞아요. 이 정도면 이제 뻔한 패턴이죠...
카오스 텔러가 등장했어요...!

타오
나 참. 어이가 없네.
혼돈을 퍼뜨리는 카오스 텔러가 부조리를 단속하다니.

하트의 여왕
혼돈? 바보같은 소리하지 마!
나는 모든 걸 제자리에 반듯하게 놓고 싶을 뿐이야!
한 치의 오차도 없이 꼭 맞게!

레이나
그럴 권리가 너한테 있을까?
이미 이상해진 존재가 뭘 꼭 맞게 해놓겠다는 거야?

하트의 여왕
내가 바로 이 세계의 규칙이다!
세계를 심판할 권리는 바로 나에게 있다!
따라서 너희들도 전원 처형하겠다!!

앨리스
나는...
나는...

레이나
앨리스. 네 눈으로 직접 확인해야 해...
어른이든 어린 아이든 [불합리]한 일에는
지지 않는다는 것을!

***
*전투*

시계 토끼
여... 여왕님이 졌다아아아아아아아아!
큰일이야... 큰일났네... 큰일이다아아아아아아아아아!

앨리스
내가 틀렸던 걸까. 빨리...나는 빨리 어른이 되고
싶었어. 그래서 여왕님 말대로 [정숙한 숙녀를 위한
풍기 단속 부대] 대장이 된 건데...

앨리스
사실은 무엇과 싸워야 되는 건지
나는 아무것도 몰랐던 거야...

레이나
네 모험은 여기서 끝이야. 앨리스.
너는 [이상한 나라]에서 모험을 마치고
현실에 있는 집으로 돌아가거든.

레이나
네가 우리와 만난 건 꿈속에서 일어난 일 같겠지...
하지만 나는 너와 만난 걸
절대로 잊지 않을 거야... 절대로... 안녕. 앨리스...

앨리스
안녕이라니... 잠깐 기다려... 레이나!
아직 당신과 하고 싶은 얘기가 많은데...

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라
여기 조율을 시작하오니...』

엑스
―레이나의 몸에서 조율의 빛이 흘러나온다.
이리하여 앨리스의 상구는 원래의 모습을 되찾았고
우리와 앨리스의 만남은 꿈속의 일이 되었다.

엑스
그럴 예정이었다...―

앨리스
여왕님이 사라졌어!?
뭐야? 방금 그거! 레이나가 한 거야!?

레이나
앨리스!
너... 어떻게 나를 기억하는 거야!?

모자장수 해터
수고했다. [조율의 무녀] 일행.
덕분에 걸림돌인 하트의 여왕을 처리할 수 있었네.

엑스
모자장수...!?
뭔가 상태가 이상해...!

셰인
아니에요.
이 사람은 모자장수가 아니에요...
아니... 처음부터 속았던 건가...!?

모자장수 해터
자, 이상한 나라 이야기는 이것으로 끝.
새로운 이야기를 시작해 볼까?

*

???? ※재버워크
이제부터는 거울 나라 시간이야.

*

앨리스
뭐... 뭐야!? 검은 게 내 몸을 기어오르고 있어!
도와줘... 레이나! 도와줘어어어!!

*

레이나
앨리스... 앨리스으으으으!!

*

타오
얼른 도망가!
바닥을... 재판장을...
이 세계를 전부 삼키고 있어!!

셰인
안돼요! 이제 시간이 없어요!!

*

엑스
―어둠이 세계를 삼킨다. 앨리스의 절규도,
레이나의 슬픔도, 타오의 분노도,
셰인의 놀라움도, 모든 것을 삼킨다.

엑스
그렇게 우리의 의식은 끊기고
새로운 세계로 강제로 끌려 들어갔다...―