= 9.2. 유리구두의 검은여제 - Flero
:hardbreaks:

????
[심볼].
그것은 시련을 극복한 영웅들의 궤적을 상징하는 아이템.

????
사람들은 형태가 있는 [심볼]을 동경하고,
거기에서 영웅들의 이야기를 찾습니다.

????
[심볼]과 영웅들의 이야기는 표리일체.
어느 한쪽에 일그러짐이 발생하면,
다른 한쪽도 일그러진 모습으로 변해 버리죠...

????
그렇기 때문에 일그러진 [심볼]은
올바른 형태로 되돌리지 않으면 안됩니다.

????
그것이 바로 저, [정화의 여신]에게
주어진 임무이니까요...

== 맑은 샘의 초원

빌런
크르르르!
크르르! 크르아!

타오
망할 빌런 녀석들!
끊임없이 나타나다니!

셰인
상구에 도착하자마자 성대한 환영식이 열렸네요...
대체 뭡니까?
다들 의욕이 너무 넘치네요!

엑스
레이나, 이래서는 끝이 없겠어!
일단 물러나는 게 좋지 않을까?!

레이나
그렇긴 하지만...
어디로 빠져나가야 할 지...!

????
당신은 용감한 여행자가 되고 싶은가요?
아니면 무모한 여행자가 되고 싶은가요?

엑스
뭐지...?
지금 뭔가 들리지 않았어?

레이나
들렸어, 여자 목소리 같은데...

셰인
어쩐지 이상한 기분이 드네요.
머리에서 직접 울리는 것 같아서 기분 나빠요.

타오
지금 한창 바빠 죽겠는데...
뭐야 대체!

????
다시 한번 묻겠습니다.
― 당신은 용감한 여행자가 되고 싶은가요?
― 아니면 무모한 여행자가 되고 싶은가요?

엑스
용감한 여행자!
우리는 용감하고자 하는 여행자다!

레이나
잠깐, 마음대로 대답하지 마!
나도 같은 대답을 하려고 하긴 했지만...

????
그 대답은 틀림 없겠지요?
그렇다면 초원 건너편에 있는 사원으로 와 주십시오.

????
당신들이 진짜 용감한 여행자라면
분명 도착할 수 있을 겁니다.
당신들이 찾고 있는 것도 그곳에 있습니다...

셰인
...어라, 끝이에요?
우리를 도와주려던 게 아니었어요?
자기 할 말만 다 하고는 끝인 겁니까?

타오
어쩌지, 아가씨!
이대로 계속 갈 거야!?
아니면 물러날 거야!?

레이나
당연하잖아, 계속 가야지!
누군지는 모르겠지만 거짓말쟁이라고 오해받는 건 싫어!

== 맑은 샘

엑스
여기가 그 사람이 말한 사원인가.
굉장해... 사원 안에 이런 샘이 있다니...

셰인
흐음...
개인적으로는 빌런들이 떨어뜨리고 간
이게 더 신경쓰이네요.

셰인
이건 뭘까요?
이렇게 유리 구두가 많으니 보기엔 예뻐 보이지만...
왠지 이상한 기분이 드는데요.

타오
그러게. 가지고 있어도 쓸모 없을 거 같은데.
그자리에 그대로 내버려두자...

????
맑은 샘까지 잘 오셨습니다.

타오
우왓, 깜짝이야!!

엑스
샘에서 사람이 나왔어...

????
저는 큐벨리에.
상구의 균형을 담당하는 [정화의 여신]입니다.

레이나
[정화의 여신]...?
그건 뭐야?

큐벨리에
[정화의 여신]이란 [심볼]을 관리하고
이 상구의 질서를 지키는 존재입니다.
스토리텔러로부터 독립한 존재...

큐벨리에
이 샘은 빌런에 의해 봉인되어 있었지만...
여러분께서 빌런을 물리친 덕분에 봉인이 풀렸습니다.

큐벨리에
아아, 이렇게 누군가와 이야기하는 것이
몇백 년 만인지...
나무꾼이 도끼를 빠트린 이후 처음인 것 같군요.

레이나
저기 그러니까, 미안해요.
무슨 말인지 전혀 모르겠어요...
어째서 우리를 이곳에 부른 거죠?

큐벨리에
어머, 나도 참.
깜빡 잊고 있었네요.
실은 여러분들에게 부탁이 있어요.

큐벨리에
이 상구를 구하기 위해...
카오스텔러의 [심볼]의 정화를 도와주시지 않겠습니까?

== 회상

큐벨리에
우선 [심볼]이란 상구의 [주연]을 이끌어 온,
이 상구의 운명을 지배하는 상징...

큐벨리에
원래대로라면 대대로 [주연]에게 계승되어
그들을 인도하는 것이 [심볼]의 역할입니다만...

큐벨리에
이 [심볼]이 저주에 걸려 버려서...
[심볼]을 몸에 지니고 있던 [주연]은
카오스텔러로 바뀌어 버렸답니다.

큐벨리에
이 유리구두는 진짜 [심볼]에서 태어난
복제품 [부정의 심볼].

*

큐벨리에
이 [부정의 심볼]은 상구 여기저기에 흩뿌려져,
상구에 사는 사람들을 점점 빌런으로 변하게
만들고 있습니다.

큐벨리에
상구의 카오스텔러를 [주연]으로 되돌리는 방법은
단 하나... 저주받은 [심볼]을 성스러운 샘의 힘으로
정화하는 것입니다.

큐벨리에
빌런에 의해 봉인된 샘은 두 곳이 더 있습니다.

*

큐벨리에
우선 동쪽에 있는 달의 숲에 봉인된 [달의 샘].

*

큐벨리에
그리고 또 한 곳은
왕국의 성에 봉인된 [태양의 샘]입니다.

== 맑은 샘

큐벨리에
[정화의 여신]의 힘은 샘에서 나옵니다.
세 곳의 모든 샘이 열리지 않으면 저는 그 힘을
제대로 쓸 수 없습니다.

큐벨리에
봉인된 샘을 다시 열 수 있는 것은 진정으로 올바른
마음을 가진 사람뿐. 그리고 여러분은
[용감한 여행자]임을 완벽하게 증명해 주었습니다.

큐벨리에
부탁 드립니다.
여러분만이 희망입니다.
부디 저에게 힘을 빌려주세요...

타오
그렇구만.
말하자면 여느 때처럼 빌런 녀석들을
날려버리면 되는 거지?

레이나
바보.
빌런 녀석들을 날려버리면서
남은 두 샘의 봉인을 풀어야 한다는 뜻이야.

셰인
하지만 갑자기 [용감한 여행자]라고 하셔도...
어쩐지 수상쩍다고나 할까요...

큐벨리에
아, 중요한 사실을 빠뜨렸네요.
아까 발견한 [부정의 심볼]도 잊지 말고 회수해 주세요.

큐벨리에
그 [부정의 심볼]도 샘의 힘으로 정화해야만 한답니다.
정화하면 다양한 아이템으로 바꿀 수 있습니다.

큐벨리에
무엇으로 바뀔지는 운에 달렸지만,
운이 좋다면 엄청나게 희귀하고
엄청나게 강한 무기가 나올 가능성도...

셰인
갑시다, 해 봅시다! 모아 봅시다!
[부정의 심볼]을 많이 모아서
새로운 무기를 듬뿍 손에 넣는 거에요.

레이나
기다려, 두 번째 바보.
목적이 바뀌었다고!

타오
뭐, 상관 없잖아?
의욕이 생겼으니 말이야.

큐벨리에
후훗, 의욕이 생긴 듯하니 다행입니다.

큐벨리에
희귀한 아이템을 획득할 수 있는 확률은
[달의 샘], [태양의 샘] 순서대로 높아진답니다.
그 점을 기억해 두세요.

큐벨리에
그럼, 잘 부탁드리겠습니다.
부디 여러분들에게 찬란한 운명이 찾아오기를...

== 맑은 샘의 초원

레이나
[심볼] 정화라...
[조율]의 힘을 쓸 수 없다는 말인가?
아직 알 수 없는 것 투성이지만...

타오
어쨌든 목적지는 정해졌어.
어서 출발하자고!
뭐든 해보지 않으면 아무것도 알 수 없으니까.

엑스
우선 [달의 샘]으로 가자.
분명 동쪽 숲에 있다고 여신님이 말했었지?

셰인
가는 길에 [부정의 심볼] 회수도
잊지 말라는 당부가 있었죠.

레이나
응, 그럼, 출발하자.

== 서쪽 고갯길

큐벨리에
이 상구의 [주연]은 신데렐라.
그녀는 유리 구두로 왕자님의 눈에 띄고
그와 맺어졌습니다.

큐벨리에
유리 구두는 이 상구 사람에게 있어
기적과 행복의 상징이며 신데렐라의 운명을
나타내는 [심볼]인 것이죠.

큐벨리에
과연 [조율의 무녀] 일행의 모험 끝에
기다리는 것은 무엇일까요...
그건 아무도 알 수 없...

레이나
음, 해설하기 전에 잠시 기다려 주시겠어요?

큐벨리에
어머나, 무슨 일이죠?

레이나
무슨 일이죠?는 제가 할 말이에요!

레이나
여신님.
어째서 우리와 함께 있는 거죠?

큐벨리에
무슨 말씀입니까?
샘에서 출발했을 때부터 계~~속 함께 있지 않았습니까.

타오
그러니까, 마치 당연하다는 듯 말하는데...
우리가 싸울 때 여신님 모습은 안 보였던 것 같은데...

큐벨리에
원래 내 역할은 [심볼] 관리...
빌런과 싸울 힘은 가지고 있지 않습니다.
하지만 [심볼]을 느낄 수는 있지요.

큐벨리에
저도 함께 있는 게 분명 당신들에게도
힘이 될 거라 생각하는데...

큐벨리에
혹시, 함께 가면 안 되는 겁니까?

레이나
딱히 안 되는 건 아니지만...

큐벨리에
감사합니다!
다행이에요...
저 혼자 샘에 남아 있는 것도 외롭던 참이라...!

큐벨리에
그럼 저를 여신님이라 하지 말고
마음 편히 큐벨리에라고 불러 주세요!
존댓말도 금지입니다!

큐벨리에
이건, 여신과의 약속입니다!?

셰인
어쩌면 이 여신님은
생각보다 재미있는 분일지도?

타오
재미있다기 보다
단순히 외로움을 잘 타는 거 아니야?

엑스
저기, 여신님...
이 아니라, 큐벨리에.

엑스
이 상구의 [주연]은 카오스텔러가 되어 있는 거지?
그 말은 즉...

큐벨리에
네, 그렇습니다.
카오스텔러로 변한 건 이 상구의 [주연],
신데렐라입니다.

큐벨리에
지금 이 상구는 신데렐라가 품고 있는 감정에
사로잡혀 있어요.
마치 검은 구름으로 휩싸인 것처럼...

레이나
큐벨리에...
대체 신데렐라에게 무슨 일이 있었던 거야?

큐벨리에
잠시 걸으면서 이야기해 볼까요?
어째서 운명을 거머쥔 그녀가
카오스텔러가 되어 버렸는지...

***

큐벨리에
유리 구두가 이끄는 대로
신데렐라는 왕자님과 맺어졌지요.

큐벨리에
하지만 신분을 초월한 결혼으로
그녀는 각종 질투를 받을 수 밖에
없게 되었습니다.

큐벨리에
건강했던 그녀는 그래도 행복을 이어가려고
했었는데...

큐벨리에
머지않아 신데렐라는 카오스텔러로 변해
세상에 대한 복수를 시작한 것입니다...

엑스
\............

큐벨리에
저기, 엑스 님 무슨 일이죠?
굉장히 우울한 모습인데...

셰인
아아, 신참 씨는 다른 상구에서
신데렐라 님과 친구로 지냈어요.
생각이 많아진 것 아닐까요.

타오
어디까지나 다른 상구였으니까 이곳의 신데렐라는
그녀석이 알고 있는 신데렐라와는 다른 사람이야.
신경 쓸 필요 없어.

타오
하긴, 이런 말을 한다고 금방 이해할 정도라면
고생하지 않겠지.

레이나
엑스...

엑스
...내가 알고 있는 신데렐라는
유리 구두를 신을 날을 기대하고 있었어.
분명 이 상구의 신데렐라도 같은 생각을 할 거야.

엑스
이렇게 어두운 세상은 신데렐라와 어울리지 않아.
그렇지?

레이나
그럼, 물론이지.

큐벨리에
아무래도 저는 정말 좋은 여행자를 만난 것 같군요.

큐벨리에
두 번째 샘, [달의 샘] 사원은 여기에서
동쪽에 있는 숲 안에 있어요...

큐벨리에
우선 [달의 샘]의 봉인을 해제합시다.
모든 것은 그 다음에 해결될 거에요.
반드시 신데렐라를 구해 주자고요.

== 신데렐라의 무도회장

????
맑은 샘의 봉인이 풀렸나...
[정화의 여신]이 움직이기 시작한 것 같군...

????
그 여신을 돕고 있는 사람이 있다니...
뭐 상관 없어... 내가 직접 상대해 주지...
방해하는 녀석은 모두 잿더미로 만들어줄게...

== 재를 뒤집어 쓴 소녀의 초원

큐벨리에
헉.

큐벨리에
동쪽에서 뭔가 다가오고 있어요.
이건... [심볼]의 기운!

레이나
[심볼]이 다가오고 있어?
그 말은 즉...

셰인
[심볼]을 가진 사람...
카오스텔러가 된 신데렐라가
이곳으로 오고 있다는 뜻 입니까?

큐벨리에
지금 이 상태로는 [심볼]의 정화가
쉽지 않을 거에요!
어딘가 몸을 숨기는 편이 좋을 거 같은데...

타오
무슨 소릴 하는 거야. 상대방이 직접 오고 있어.
찾는 수고를 덜 수 있다고.
너도 각오는 되어 있겠지?

엑스
응... 이 상구의 신데렐라가
어떤 사람인지 만나서 확인해야겠어...!

***

빌런
크르르... 크르르르...!

셰인
끝이 없어, 이 빌런들.
유리 구두만 계속 떨어뜨리고 있어요...

레이나
그보다 카오스텔러는...?
어디까지 왔어?

큐벨리에
이 근처까지 와 있어요!
이제 곧 우리 앞에...

????
어머나?
여신님 주변에 사람이 꽤나 많네요.

엑스
... 신데렐라, 너 맞니?

카오스 신데렐라
처음 뵙겠습니다, [정화의 여신님]과 그 동료님들.
저는 신데렐라.
혼돈을 만들어내고 운명에 복수하는 여왕...

카오스 신데렐라
너희들 그러면 안되지?
여신님을 제대로 환영해 드리라고 그렇게 말했거늘.

빌런
크르르~!
크르르~!

카오스 신데렐라
큭... 큭큭큭...
이런이런~ 유리 구두 맛은 어때?
밟아 줬으면 하는 곳이 여긴가? 아님 여긴가?

큐벨리에
시, 신데렐라 그만두세요!
신성한 [심볼]로 그런 경망한 행동을 하다니...

카오스 신데렐라
유리 구두는 내 것이야...
내 것을 어떻게 쓰든, 내 마음이지.
거기 있는 당신들도 밟아드릴까?

남자 두 명
\......

엑스
웃기지마!
그런 거 관심 없어!

타오
하, 우리를 우습게 보지 말라고!

셰인
두 분 다 어째서 대답하는데 잠깐 주저하셨죠?

카오스 신데렐라
큭큭... 재미있는 분들이군요.
그럼 모처럼의 기회이니 왈츠 상대가 되어 주시겠어요?

엑스
기다려 신데렐라! 우선 이야기를...!

레이나
소용없어요!
카오스텔러를 막을 수 있는 건
싸움밖에 없다는 걸 알잖아!
※플레로의 실수

큐벨리에
신데렐라의 약점은 빛속성과 불속성입니다.
완전히 쓰러뜨릴 순 없어요.
우선 여기선 버티는 것만 생각해 주세요...!

***
*전투*

카오스 신데렐라
하아... 하아...

레이나
궁지에 몰렸군, 카오스텔러...
모든 샘의 봉인을 풀지 않으면
여기에서 당신을 [조율]하겠어!

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라,
여기 조율을 시작하오니....』

레이나
\.................................

레이나
말도 안 돼...
[조율]의 힘이 먹히지 않다니...!?

카오스 신데렐라
......큭, 큭큭,
큭큭큭큭...
뭐~야, 지금 그게 마법의 주문인가요?

카오스 신데렐라
저를 어떻게 해보려고 하셨나요?

큐벨리에
그것이 [심볼]의 힘입니다...!
레이나 님의 [조율]이 [심볼]에 의해
방해 받고 있는 것이죠.

큐벨리에
신데렐라가 신고 있는 유리 구두를 정화하지 않는 한,
그녀는 결코 쓰러지지 않을 겁니다...

카오스 신데렐라
[부정의 심볼]을 쓰는데도 빌런으로 바뀌지 않는다니...
대체 당신들은 뭔가요...?

카오스 신데렐라
원래 이 세계의 [주연]...
세상의 운명을 지배하는 내게...
저항하겠다는 건가요...?

엑스
아니야!
당신은 운명을 지배할 수 있는 사람이 아니야!

엑스
신데렐라, 이런 짓을 하려고 가족들의
온갖 모욕을 참아온 게 아니잖아!

카오스 신데렐라
당신, 시끄럽군요...

카오스 신데렐라
감히 누구 앞에서 하는 말이죠?
영원히 말을 할 수 없도록 만들어 드릴까요?

레이나
엑스!

큐벨리에
그만두세요, 신데렐라!

엑스
\.....................

카오스 신데렐라
.........후훗, 오늘은 봐 드리죠.
당신, 멋진 표정을 짓고 있군요.
당신이 굴복한 표정을 보고 싶어졌어요...

카오스 신데렐라
다음 번에는 함께 왈츠를 추도록 해요.
절망과 슬픔으로 가득 찬 얼굴로 춤을 추는 모습,
정말 기대되는 군요...

타오
어이, 엑스!
괜찮아!?

엑스
아, 아아. 응...
아무렇지도 않아...

셰인
신데렐라가 사라졌습니다...
하지만 정말 위험하군요.
언니의 [조율]이 통하지 않는 카오스텔러라니...

레이나
응. 정말 이런 건 처음이야.
이것이 [심볼]의 힘이란 거군...

레이나
나머지 두 샘의 봉인 해제...
서둘러야겠어.

엑스
응, 그래.
더 이상 그녀를 이대로 둘 순 없어...!

== 호박의 초원

엑스
\......

큐벨리에
잠이 안 오나요?

엑스
큐벨리에...
미안, 내가 깨운 거야?

큐벨리에
아니요, 신경 쓰지 마세요.
여신은 잠드는 일이 없으니까요.

큐벨리에
... 신데렐라가 신경 쓰이나요?

엑스
... 신데렐라가 세상을 매우 증오하는 것 같았어.

엑스
그녀는 계속 행복한 미래를 꿈꿔왔지...
실제로도 그렇게 될 운명이었어...
그런데, 어째서 그렇게 된 걸까...?

엑스
대체 신데렐라에게 무슨 일이 있었던 거야...?

큐벨리에
... 저는 지금 그 질문에 대답해드릴 수 없습니다.
하지만 확인할 수는 있지요.

엑스
그건 우리가 주운 유리 구두...?

큐벨리에
잘 보세요.

== 회상

​ +
―왕자님과 맺어져, 왕족이 된 신데렐라.
하지만 왕실 사람들은 평민 출신인 그녀를
차가운 태도로 대했습니다.

​ +
왕자님은 공무를 위해 궁전을 비우는 일이 많았기 때문에
신데렐라는 항상 궁전에서 외롭게 지냈지요.

​ +
하지만 신데렐라는 웃음을 잃지 않았어요.
신데렐라는 사람들에게 꿈의 상징이었기 때문이지요.

​ +
사람들은 신데렐라가 영원히 유리 구두처럼
반짝이길 바랐습니다.

​ +
그래서 신데렐라는 외로운 왕실에서
언제나 웃고, 웃고, 웃고, 웃고,
또 웃었던 것입니다. 그리고...

신데렐라
웃어야 해... 언제나 즐거운 듯...
누구나 나를 보고 행복하다고 느낄 수 있을 만큼...

신데렐라
나는 세상에서 가장 행복한 여자...
그것이 이 세상에서 주어진 내 역할이니까...

== 호박의 초원

엑스
지금 그건... 신데렐라의 기억...?

큐벨리에
[심볼]은 사람들의 동경을 모으는 도구.
거기에는 많은 사람들의 마음,
특히 [주연]의 마음이 강하게 담겨 있어요.

큐벨리에
[심볼]의 복제품인 [부정의 심볼]에도
그 조각이 남아있을 거에요...

엑스
그렇구나...
그럼 신데렐라는 왕자님과 맺어진 후에도
계속 싸워왔던 거구나...

엑스
가족들에게서는 노예 취급을 받고...
그래도 매일 웃는 얼굴로 열심히 일하고...
이제 겨우 그 보상을 받는가 싶었더니...

큐벨리에
\...............

엑스
큐벨리에...?

큐벨리에
저는 지금껏 상구의 운명에 간섭하지 않고
[심볼]과 [주연]의 이야기를,
그리고 역대 신데렐라들의 모습을 지켜봤어요...

큐벨리에
그러니까 저는 그녀들이 지닌
착한 심성과 기품을 잘 알고 있어요.

큐벨리에
[심볼]이 정화되면 분명 그녀는 다시 행복해질 수
있는 운명을 되찾을 수 있을 거에요.

큐벨리에
그러니 함께 힘내도록 해요!
저도 뒤에서 여러분을 응원하겠습니다...
이건 여신과의 약속입니다!

엑스
큐벨리에... 고마워...

== 달의 숲

엑스
―우리는 고개를 넘어서
[달의 샘] 사원이 있는 숲속으로 들어갔다.

엑스
숲 안쪽 사원으로 이어지는 그 길을 방해라도 하려는 듯
우리 앞에는 수많은 빌런들이 도사리고 있었다.

셰인
알고는 있었지만...
쉽게 통과시켜 줄 것 같은 패턴은 아니네요...

타오
헤헤, 상관 없잖아.
이 녀석들 모조리 날려버리면 되는 거지?
그 정도는 알고 있다고.

큐벨리에
여러분, 이곳을 돌파하면
[달의 샘] 사원에 도착할 수 있어요.

큐벨리에
하지만 지금 이 앞에서 [심볼]의 반응이...!

엑스
신데렐라가 여기에 있어!?

레이나
이곳이 상대방에게는 꼭 지키고 싶은 장소일 테니까...
아무튼 지금 여기서 물러날 수는 없어.

레이나
올바른 마음을 가진 용감한 여행자로서
이곳을 반드시 통과할 거야...!

***
*전투*

레이나
빌런 숫자도 많이 줄었어...!
이제 곧 [달의 샘] 사원에 도착할 수 있어...!
그러니까 지금쯤 분명...

큐벨리에
... 여러분, 도착했어요.

타오
이런이런, 적군 대장님이 행차하셨습니까.

카오스 신데렐라
당신들 정말 굉장하네요...
내가 만들어 놓은 꿈속에서 아직도 놀고 계시나요...?

카오스 신데렐라
어차피 내가 만든 운명을 뒤집을 수 없는 법...
대체 무엇을 바라고 있으신지요...?

엑스
네가 행복해지는 미래를 바라고 있어, 신데렐라.

엑스
예전에 네가 운명에 맞서 행복을 찾으려고 한 것처럼,
이번에는 우리가 너의 어긋난 운명에 맞설 차례야!

카오스 신데렐라
무슨 소리를 하는 거야?
시시해... 시시해...
아아, 시시하기 짝이 없어!

카오스 신데렐라
좋아, 덤벼 보세요.
두 번 다시 그런 마음을 갖지 않도록
가르치고 굴복시켜 줄 테니까...

셰인
어쩐지 상대방의 약점을 찌른 것 같아요.
엄청 화가 났네요.

큐벨리에
[심볼]의 힘이 강해졌어요.
아까보다 더 강력해졌을 거에요.
여러분, 부디 조심하세요...!

***
*전투*

카오스 신데렐라
이 빛은... 설마...!

큐벨리에
신데렐라...
[달의 샘]은 봉인이 풀렸어요.

큐벨리에
이제 이곳은 어떠한 혼돈도 들어올 수 없는
성지입니다...
어서 이곳에서 사라져 주세요...

카오스 신데렐라
천하의 내가...
두 번이나 지다니...
이런... 어째서...

엑스
신데렐라...

카오스 신데렐라
...쳐다보지 마.
왕족인 나를... 그런 눈으로 쳐다보지 마!

카오스 신데렐라
이제 나는 그 누구의 명령도 따르지 않아!
새어머니와 언니들에게 구박 받던 옛날의 내가 아니야!

카오스 신데렐라
지배하는 쪽은 나야...!
시시한 왕실도, 나를 보려 하지 않는 백성도
그리고 너희들도...

카오스 신데렐라
모조리 유리 구두의 힘으로
무릎 꿇게 해 주겠어...!

셰인
가버렸네요...
엄청나게 원한을 산 것 같지만...

레이나
지금은 어쩔 수 없어...
아무튼 이제 [달의 샘]의 봉인은 풀렸어!

큐벨리에
여러분, 고맙습니다...
이제 저도 능력의 일부를 되찾았습니다.
여기로 와 주세요...

== 달의 샘

레이나
이곳이 [달의 샘]...
처음에 본 샘하고는 또 분위기가 다른 걸.

큐벨리에
기본적으로는 [맑은 샘]과
다를 바 없지만, 정화의 힘은 훨씬 강하지요.

큐벨리에
[달의 샘]에 [부정의 심볼]을 던져 넣으면
희귀한 아이템을 보다 쉽게 손에 넣을 수 있을지도
모릅니다.

셰인
그렇다면 당분간 [심볼] 회수에
집중하고 이곳에서 아이템을 획득하는 것도...

레이나
세~이~인~?
너, 목적을 잊은 건 아니겠지?

셰인
윽...

타오
셰인 말대로 여기서 무기를 획득하는 것도
괜찮은 방법일지도 몰라.
적은 앞으로도 더 강해질 테니까.

엑스
[부정의 심볼]이 많이 모이면
이곳으로 돌아오는 게 좋을 것 같아.

큐벨리에
어떤 전략을 세우든 편하신대로 해주십시오.
여러분의 여행길에 꼭 도움이 됐으면 좋겠습니다.

== 달의 숲

레이나
... 마지막으로 하나 더, [태양의 샘]은
신데렐라의 성에 봉인돼 있다고 했지?
분명 신데렐라도 그곳에...

엑스
신데렐라가 기다리고 있을 거야...
다들, 가자!

== 신데렐라의 무도회장

나레이션
―엑스 일행이 카오스 신데렐라에게
가고 있을 즈음.

카오스 신데렐라
\......

== 회상

엑스
네가 행복해지는 미래를 바라고 있어, 신데렐라.

엑스
예전에 네가 운명에 맞서 행복을 찾으려고 한 것처럼,
이번에는 우리가 너의 어긋난 운명에 맞설 차례야!

== 신데렐라의 무도회장

카오스 신데렐라
...흥, 예전의 나?

카오스 신데렐라
굴욕적인 나날을 견뎌 냈더니
그 다음에는 위선적인 웃음을 짓게 하고...
그런 [나]는 이제 필요 없어.

카오스 신데렐라
지금의 나는 이미 그 시절의 내가 아니야...
이 유리 구두를 신고 진정한 내 모습을 되찾았어...

카오스 신데렐라
그 아이에게도 가르쳐 줘야겠군...
지금의 내가 얼마나 훌륭한 존재인지를...
큭... 큭큭... 큭큭큭...

== 성 밑 마을 근처의 고갯길

엑스
Zzz... Zz... z...
응? 거기 누구야...?

카오스 신데렐라
어머, 이제 일어났어?

엑스
엇!?
신데렐라...!?

카오스 신데렐라
쉿, 조용히.
다른 사람들이 깨겠어.
모처럼 당신과 이야기를 하려고 왔는데...

엑스
나와 이야기를?

카오스 신데렐라
응, 당신이 나를 오해하고 있는 것 같아서.

카오스 신데렐라
지금 내가 얼마나 행복한지 알아 줬으면 해...
지금 내가 얼마나 최고인지 알아 줬으면 해...
지금 나는 마음속 깊이 웃을 수 있으니까.

카오스 신데렐라
자아, 느껴봐...
나의 마음을...

*

누군가의 목소리
신데렐라, 신데렐라, 신데렐라...

신데렐라
그만해... 나는 이제 웃을 수 없어...

신데렐라
이렇게 되려고 유리 구두를 신은 게 아니야...

누군가의 목소리
신데렐라, 신데렐라, 신데렐라...

신데렐라
더 이상 나를... 신데렐라라고 부르지 마!

*

엑스
큭... 우윽...!

카오스 신데렐라
그치? 이제 잘 알겠지?
그 때 내가 느낀 절망을...
그 때 내가 느낀 고통을...

카오스 신데렐라
그 때보다 지금이 훨씬 행복해...
나는 지금 마음속 깊이 웃고 있어...
예전의 내가 바라던 내가 됐으니까....

카오스 신데렐라
당신 나를 좋아하지?
그렇다면 내 곁으로 와.
호박 마차 시중꾼을 시켜주겠어.

엑스
그렇지...않아...!
진정한 너는... 그런 생각을 할 리가...!

카오스 신데렐라
...진정한 나?
...아직도 모르겠어?
여기에 있는 사람이 진정한 나야!

카오스 신데렐라
...아아, 이제 됐어.
그렇게 나에 대해 환상을 품은 채 죽어버려!

레이나
그만뒤!
신데렐라, 아니, 카오스텔러!

카오스 신데렐라
!!

== 성 밑 마을 근처의 고갯길

카오스 신데렐라
...어머나, 꽤나 대단한 걸? 여신님.
겨우 [심볼]의 기운을 차단해서 접근했는데...

큐벨리에
그 정도로 [심볼]의 힘을 제어할 수 있게 되었군요...
하지만 이제 더이상 지켜볼 수만은 없어요.
엑스 님, 괜찮으십니까?

엑스
응, 고마워... 나는 괜찮아...

카오스 신데렐라
정말 한없이 거슬리는 녀석들이군...
흥, 상관 없어.
지금 당장 전부 잿더미로 만들어 주겠어!!

***
*전투*

카오스 신데렐라
...이제 이해했어.
당신들이 결코 나의 운명에 굴복하지 않을 거라는 걸.

카오스 신데렐라
그렇다면 나도 그에 어울리는 장소를 준비해야겠지?

레이나
어울리는 장소?
그게 무슨...

카오스 신데렐라
내 성 안에 있는 무도회장...
그곳에서 당신들을 위한 무도회를 열어 주겠어.

카오스 신데렐라
당신들과 나만의 무도회...
그곳에서 어느 쪽이 지칠 때까지 춤을 추는 거야...
두근두근하지?

타오
우리가 왜 굳이 네가 있는 곳까지 가야만 하는 거지?
그쪽도 이제 더 이상 싸울 힘이 없는 거 아니었어?

타오
그럴바엔 여기서 당장 쓰러뜨리는게 좋지 않겠...

큐벨리에
아닙니다, 지금은 신데렐라의 요청을 들어줍시다.

타오
큐벨리에, 무슨 말이야!?

큐벨리에
여기서 싸우더라도 정화가 이루어지지 않는 이상
결론이 나지 않을 거에요.
거기다 무도회장에는 우리의 목표도 있어요.

레이나
마지막 샘... [태양의 샘] 말이군.

카오스 신데렐라
기다리고 있겠어...
즐겁고도 즐거운 무도회로 만들어 줄 테니...

셰인
가버렸네요.
하지만 어째서 신데렐라 님이 신참 씨를
맘에 들어 하는 걸까요?

엑스
자신이 무엇 때문에 힘들었는지에 대해 알아주길
바란게 아니었을까...
그래서 나에게 접근해서 그런 말을...

엑스
지금이 훨씬 행복하다고 했지만...
그건 거짓말일 거야... 정말로 행복하다면...
그렇게 고통스러워할 리 없어...!

큐벨리에
아마 신데렐라 자신의 마음속으로는
멈춰주길 바라고 있을 거에요.

큐벨리에
카오스텔러의 힘이 그 아이의 고통을 증폭시키고
결국 왜곡되고 말았어요.
어떻게 해서든 그녀를 구해줘야만 합니다...!

레이나
모두들, 서두르자.
신데렐라가 성에서 기다리고 있어.
그곳에서 결판을 내자고!

== 신데렐라의 성

타오
신데렐라의 성이라...
엑스 와 처음 만난 날이 생각나는 군.

셰인
그 뒤로 세월이 얼마나 지났는지...
생각해보면 우리도 꽤 멀리까지 온 것 같아요...

레이나
아니야, 아직 그렇게 많이 지나지 않았다고.
게다가 지금은 감상에 젖어 있을 때도 아니야.

엑스
큐벨리에, 신데렐라는 이 성 안에 있는 거야?

큐벨리에
네. [심볼]의 기운이 통로 안쪽에서 느껴지고 있어요.
그리고 [태양의 샘] 사원도.

레이나
성 안에 사원이 있다니 이상하지 않아...?

큐벨리에
[태양의 샘]은 [주연]과 가장 인연이 깊은 장소에
나타나는 법이니까요....
문제는 신데렐라가 쉽게 통과시켜 줄까인데...

셰인
앗, 아무래도 그럴 마음은 없어 보이네요.

*

타오
하아, 뭐 이렇게 될 줄 알았어...
할 수 없지~ 무도회 전에 준비운동이라도 해둘까!

엑스
기다려 신데렐라...
지금 그쪽으로 갈 테니까!

***
*전투*

== 신데렐라의 무도회장

카오스 신데렐라
어서오세요, 여러분.
제가 준비한 환영식이 마음에 드셨는지 모르겠네요.

레이나
환영?
글쎄, 무슨 말인지 모르겠는걸.

카오스 신데렐라
후훗, 허세 부릴 필요 없어요.
서로 이렇게 대화를 나누는 것도 이게 마지막일테니까요.

카오스 신데렐라
마지막으로 남기고 싶은 말은 없나요?
죽고나서 후회해봐야 소용없으니까.

엑스
우리가 말하고 싶은 건 단 하나.
너를 반드시 악몽에서 꺼내 주겠어.
그뿐이야.

큐벨리에
당신의 그 유리 구두를 원래 모습으로 돌려 놓겠어요.
신데렐라, 당신이 걸어 가야 할 운명을 위해.

카오스 신데렐라
...하고 싶은 말은 다 하셨나요?

카오스 신데렐라
그렇다면 좋습니다.
자, 시작해볼까요?

카오스 신데렐라
죽음의 종이 울릴 때까지 끝나지 않는
절명과 혼돈의 무도회를!

***
*전투*

카오스 신데렐라
여기서 내가 쓰러지다니...
싫어... 싫다고...
절대로 그 날로 돌아가고 싶지 않아...

카오스 신데렐라
나는 단지... 행복하게 웃고 싶을 뿐이었어...
희망의 상징이 아닌 한 명의 사람이길 바랐는데...

엑스
걱정하지 마.
너의 고통을 알고 있는 사람이 여기 있으니까.

카오스 신데렐라
...당신이 뭘 안다고 그래?

엑스
내가 아니야.
이 세계에서 언제나 당신을 지켜봐 온 사람이야.
...그렇지 큐벨리에?

큐벨리에
신데렐라.
혹시 힘들어지면 사원의 샘으로 와 주세요.

큐벨리에
당신 앞에 모습을 드러낼 수 있을지는 모르겠지만...
나는 언제나 당신을 지켜보고 있을 테니까요...

카오스 신데렐라
...후후, 정말 이상한 여신님이군.

큐벨리에
레이나 님.
제가 [심볼]을 정화할테니 레이나 님도 [조율]을...

레이나
응, 알겠어...

큐벨리에
『저주받은 부정의 상징이여
 나의 빛 아래에서
 여기 정화를 시작하노라...』

레이나
『혼돈의 소용돌이에 삼켜진 이야기들이여』

레이나
『나의 언명에 따라,
여기 조율을 시작하오니....』

*조율 컷씬*

== 태양의 샘

큐벨리에
이것으로 [심볼]의 정화가 끝났습니다.
뒤틀려 있던 이 상구의 운명도
언젠가는 원래대로 돌아가겠지요.

타오
언젠가?
[조율]은 끝난 거 아니야?

큐벨리에
사실은 아직 [부정의 심볼]을 가진
빌런들이 상구를 배회하고 있어요.

큐벨리에
[심볼]은 스토리텔러라도 간섭할 수 없습니다.
그리고 그 복제품인 [부정의 심볼]도
완전히 소멸될 때까지 시간이 걸린답니다.

셰인
그 말인 즉슨,
아직 좀 더 [심볼]을 회수해야 한다는 거군요.
거리낌없이 보물을 획득할 수 있겠어요!

레이나
셰인, 발상이 정말 독특하구나...
그 점 하나는 존경할만 해.

큐벨리에
[부정의 심볼]에는 또 하나,
더욱 강력한 힘이 깃들어 있는
[혼돈의 심볼]이라 부르는 것이 있어요.

큐벨리에
[맑은 샘]과 [달의 샘]으로는 정화할 수 없는
[혼돈의 심볼]은 이 [태양의 샘]으로 정화할 수 있어요.

타오
할 수 없지. 어차피 벌어진 일이니.
부정이든 혼돈이든 나머지 [심볼]도 회수하러 가볼까.
그렇지 아가씨?

레이나
응. 여신님께 여러모로 도움 받았으니까
마지막까지 돕도록 하자.

엑스
고마워 큐벨리에.
처음 목소리를 들었을 때 당신을 믿고 행동해서
다행이야.

큐벨리에
감사 인사를 드려야 할 건 저입니다.
여러분 덕분에 이 상구의 균형을 지킬 수 있게 됐어요

큐벨리에
또 언젠가 [정화의 여신]이 있는 상구를
방문할 기회가 있다면 그 세상에 있는
[저]도 꼭 만나 주세요.

큐벨리에
어느 상구에서든 [저]는 분명 당신들을 환영할 테니까요.

큐벨리에
이건 여신과의 약속이라구요?

엑스
응, 알겠어. 큐벨리에...