= 9.4. 얼음과 불꽃의 판타지아 - Gemini
:hardbreaks:

link:9.4..氷と炎のファンタジア.adoc[원문]

== 얼음과 불꽃의 국경

나레이션
―――정령들이 거주하는, 어느 섬이 있었다.
그 섬은 예전에 하나의 왕국이 통치하고 있었으나,
왕국 내에서는 항상 내란의 폭풍이 휘몰아쳤다.

나레이션
이윽고 왕국은 3개의 영토로 분단되었고,
정령들 또한 각각의 나라로 나뉘어 갔다.

나레이션
얼어붙는 눈을 가져오는 설정에게 사랑받은, 「얼음의 나라」.
홍련의 업화를 불태우는 염정에게 사랑받은, 「불의 나라」.
격렬한 번개를 울려 퍼뜨리는 뇌정에게 사랑받은, 「번개의 나라」.

나레이션
3국 간의 다툼이 시작된 지 200여 년.
왜 자신들이 싸우는지 그 이유도 모른 채,
지금도 여전히 다툼은 끊임없이 반복되고 있었다…―――

*

죽어가는 호위병
공주님, 어서 피하십시오…
저는 이제 틀렸습니다…
끝까지 지켜드리지 못한 것, 용서해 주십시오…

글레시아
무슨 소리를 하는 건가요!
곧 알버스 일행도 와줄 거예요…
도움은 반드시 옵니다, 그러니까…!

죽어가는 병사의 목소리
자애로우신 공주님…
당신의 앞날에
설정의 축복이 함께하기를…――――――

글레시아 ※그레시아
…어째서, 이 땅은 피로 더러워져야만 하는 걸까.
…어째서, 이 사람은 목숨을 잃어야만 하는 걸까.

글레시아
내 심장에 깃든 설정이여, 가르쳐 주세요.
왜 우리는 다투어야만 하는 것인가요…

*

빌런
크르르… 크르르아!!

*

글레시아
이름도 모르는 괴물들…
아직도 우리에게 이빨을 드러내는 건가요…

글레시아
너희를 보낸 것은 누구지?
「불의 나라」? 아니면 「번개의 나라」…?
아니, 누구든 상관없어.

글레시아
이 「얼음의 나라」 제1왕녀, 글레시아의 목을
너희 같은 괴물에게 내주지는…!

*

????
핫!

*

????
괜찮나?

글레시아
당신은, 「불의 나라」 사람…?
어째서 「불의 나라」 병사가,
적인 나를 구하는 거지!?

????
이번 「불의 나라」와 「얼음의 나라」의 전쟁은,
저 괴물들 때문에 무승부로 결판났다.
더 이상의 다툼은 무용지물이다.

이그니스
…인사가 늦었군. 난 이그니스.
「불의 나라」의 이프리트 부대 대장, 이그니스다.

글레시아
이그니스…
설마, "홍련의 이그니스"…!?

이그니스
…그 반응을 보니, 아무래도 당신의 『운명의 서』에도
똑같은 내용이 적혀 있는 모양이군요.
정말 아이러니한 일입니다…

글레시아
…나는 그런 운명, 믿지 않아.

글레시아
나는 「얼음의 나라」의 공주야.
아무리 서에 기술되어 있다고는 해도,
그런 운명, 믿을 수 있을 리가…

이그니스
우리 운명의 향방에 대한
논의는 나중에 하도록 하죠.
지금은 이곳을 빠져나가는 것이 선결 과제입니다.

????
이그니스, 여기 있었구나!

글레시아
……이분들은?

이그니스
방금 알게 된 여행자들입니다.
저 괴물들에게 대항할 수 있는 힘을 가지고 있죠.
그들과 함께라면, 이곳도 빠져나갈 수 있을 겁니다.

엑스
글레시아 공주님, 당신을 안전한 곳까지
모셔다드리겠습니다. 저희를 따라오세요.

이그니스
자, 글레시아 공주님.
우리와 함께 가시죠.

글레시아
으, 응…

***

글레시아
고마워요… 이그니스.
여기까지 왔으면, 나머지는 혼자서 돌아갈 수 있으니까요…
분명 종자인 알버스도 마중 나와 줄 거예요…

글레시아
설마 「불의 나라」 백성인 당신에게
도움을 받을 줄이야…

이그니스
…믿는 정령은 다를지라도,
우리는 이 섬에 살아가는 똑같은 생명.
구할 수 있다면, 그것보다 좋은 일은 없습니다.

이그니스
당신이 무사해서 다행입니다.
그 마음에는 거짓이 없습니다.

글레시아
…고마워요, 당신은 다정한 사람이군요.
하지만 이제 만나는 건 이번 한 번으로 끝내는 게 좋겠어요…

글레시아
『운명의 서』의 기술이 사실이라면,
우리의 앞날에 기다리고 있는 것은,
너무나 슬픈 일들뿐이니까요…

이그니스
그렇군요…
그편이 서로를 위하는 길이겠지요…

이그니스
잘 가십시오, 글레시아 공주님.
부디 평안하시길…

*

이그니스
…엑스 일행에게는 신세를 졌군.
너희가 없었다면,
그 상황을 헤쳐 나올 수 있었을지 어떨지…

엑스
이그니스… 왜 그런 위험을 무릅쓰면서까지,
적국의 공주님을 지키려 한 거야?

엑스
「불의 나라」와 「얼음의 나라」는 대립하고 있잖아?
그런데도, 왜…

이그니스
…그러고 보니 너희는 카오스텔러라는 적을
쫓고 있다고 했었지.
그게 이 섬 어딘가에 숨어 있다고 하던가…

이그니스
그 괴물들… 빌런이라고 했던가…
과연, 확실히 그런 괴물에 대해서는
『운명의 서』에 적혀 있지 않았지…

이그니스
…좋다, 너희에게는 이야기해 두도록 할까.

== 회상

이그니스
「불의 나라」의 검사인 나 이그니스와,
「얼음의 나라」의 왕녀인 글레시아 공주…

이그니스
적대 관계인 우리들은,
서로 사랑하게 될 운명인 모양이다…

*

이그니스
우리는 자신의 마음을 관철하기 위해
나라를 떠나, 도피 행각을 이어가지만…

*

이그니스
이윽고 삼국 간에 대규모 전쟁이 시작되고,
그 전쟁 도중에 나는 전사하게 되어 있다.

이그니스
홀로 남겨진 그녀가 어떻게 되었는지는 모른다…

이그니스
결국, 우리는 소중한 것을 잃고,
결코 맺어질 수 없다.
그것이 우리들의 서에 기술된 운명이다…

== 얼음과 불꽃의 국경

타오
…참으로 기분 더러운 운명이구만.
당신은 자신에게 주어진 그 운명을,
바꿔버릴 생각은 없는 거야?

이그니스
…바꾼다, 바꾸지 않는다를 따지기 이전에,
나는 이 운명을 믿지도 않았어.
내가 「얼음의 나라」의 공주와 사랑에 빠지다니…

이그니스
그러고 보니, 글레시아 공주도
똑같은 말을 했었지…
생각하는 건 둘 다 똑같은가…

셰인
그 얼음 공주님도 마음이 복잡하시겠네요.
운명으로 강요받는 사랑이라니.
셰인으로서는 상상도 안 가지만요…

엑스
…이그니스는 글레시아 공주를 만나고,
어떤 생각이 들었어?

이그니스
아무렇지도 않아.
이제 우리는 만날 일도 없어.
만날 이유도 없지.

이그니스
그보다 그 빌런들이
누구의 소행인지 밝혀내야만 한다.

이그니스
너희의 힘을 빌리고 싶군.
함께 「불의 나라」로 와주었으면 하는데.

레이나
물론이지!
우리가 할 수 있는 일이라면,
얼마든지 도와줄게!

이그니스
고맙군, 잘 부탁한다.

== 얼음의 나라의 본영

글레시아
………

알버스
공주 전하, 무슨 일이십니까?

글레시아
알버스…
아니, 아무것도 아니야.
잠시 생각에 잠겼을 뿐이야…

글레시아
앞으로의 일을,
생각하고 있었을 뿐…

알버스
그렇습니까.
너무 무리는 하지 마십시오.
공주 전하께서도 오늘 밤은 피곤하실 테니까요…

알버스
무슨 불안한 점이라도 있다면 무엇이든 말씀해 주십시오.
이 알버스는 어린 시절부터 당신의 종복.
사양하지 마십시오.

글레시아
응, 고마워, 알버스…

글레시아
(…이그니스.
계속 내 마음속에 남아있던, 그 이름…)

글레시아
(나는 내 운명을 믿지 않았어.
그 마음은 이그니스를 만난 지금도 변함없어…
나는 그 사람을 지금도 앞으로도 사랑하지 않을 거야…)

글레시아
(그런데… 어째서일까…?
어째서 내 심장은, 그 사람을 떠올릴 때마다
계속 고동치고 있는 걸까…)

글레시아
(부탁이야… 이 차가운 「얼음의 심장」이여…
더 이상, 내 가슴을 아프게 하지 마…)

== 불의 나라의 수도

엑스
「번개의 나라」에 대한 초계 임무, 말인가요?

이그니스
그래. 지난번 전투에서, 빌런들은
우리와 「얼음의 나라」, 양쪽 진영을 습격했다.

이그니스
우리가 쓰러져서 득을 보는 건 「번개의 나라」…
가능성으로 따지면, 이 「번개의 나라」에 너희가 말하는
카오스텔러가 잠복해 있을 확률이 높겠지.

레이나
과연… 하지만 그렇다면, 똑같은 추측을
「얼음의 나라」 측에서도 하고 있겠네요.
어쩌면 벌써 움직이고 있을지도 몰라요.

셰인
전쟁을 일으키기에는 서투른 방식입니다.
양쪽에 싸움을 걸었다간,
단번에 반격당할 뿐이니까요.

타오
차라리, 「얼음의 나라」와 동맹을 맺어버리면
어떻겠어? 같은 원수가 있다면,
그편이 움직이기 편하잖아.

이그니스
이 초계 임무는 그것까지 내다본 일이다.
카오스텔러에 관한 단서를 잡을 수 있다면,
그 정보를 바탕으로 「얼음의 나라」와 동맹을 맺을 수 있지.

이그니스
이것은 비공식적인 임무다.
대장인 나는 대놓고 움직일 수 없으니,
대신 신뢰할 수 있는 부하를 동행시키지.

레기아
이그니스 대장의 부하, 레기아다.
대장님께 신세를 졌다고 들었다.
가는 길에 잘 부탁하지.

타오
우리야말로 잘 부탁해.
우리는 이 섬의 지리에
어두우니까 큰 도움이 될 거야.

셰인
설령 이 섬의 지리에 밝았다고 한들,
언니의 길치 능력 앞에서는 무용지물이겠지만요…

레이나
그런 능력 없어!
요즘은 그렇게까지 길을 잃지는 않는다고!?

엑스
반드시, 단서를 찾아내고 말겠어요.

이그니스
그래, 부탁한다.
너희에게 염정의 가호가 함께하기를.

== 불의 나라의 성

이그니스
(그 전투로부터 며칠…
나는 이렇게 「불의 나라」로 돌아왔고,
그녀 또한 「얼음의 나라」로 돌아갔다…)

이그니스
(글레시아 공주…
태어날 때부터 내 『운명의 서』에 기록된,
내 미래를 좀먹어가는 저주의 이름…)

이그니스
(적국의 공주를 사랑하다니 있을 수 없는 일이다.
그 괴물의 습격 때, 그녀를 찾은 것은
그 사실을 확인하기 위해서였다…)

이그니스
(하지만, 처음으로 눈에 담은 나의 저주는,
너무나 아름다운 모습을 하고 있었다……
손을 뻗어, 만지고 싶어질 정도로…)

이그니스
(나는 이제, 그녀를 만나서는 안 된다…
비극의 노예가 될 생각은 없어…
분명 그녀도, 그것을 바라고 있을 터다…)

== 번개의 나라의 국경

엑스
여기가 「번개의 나라」와 「불의 나라」의 국경인가…

레기아
그래, 저 고개를 넘으면,
「번개의 나라」에 도착한다.

레기아
위조 통행증은 가지고 있나?
그걸 써서, 섬 밖에서 온 상인이라고
말해두면, 국경 문도 통과할 수 있을 거다.

레기아
이 주변은 통행인이 적지만,
눈에 띄는 것은 피하고 싶군.
가급적 누군가의 눈에 띄지 않도록 주의해서,

셰인
앗.

레이나
자, 잠깐, 셰인!
뭐 하는 거야!

셰인
조용히 하세요, 저쪽에 누군가 있어요.

레기아
뭐라고?

*

레기아
저건…"얼음매" 알버스!?
「얼음의 나라」 최강의 궁수가,
왜 「번개의 나라」 국경에!?

타오
함께 있는 사람도, 「얼음의 나라」 녀석인가?

레기아
…아니, 저 복장은 「번개의 나라」 병사군.
왜 저놈들이 함께 있는 거지…
무언가 의논하고 있는 모양인데…

레기아
음, 아무래도 이야기가 끝난 모양이군.
알버스는 「얼음의 나라」로 귀환할 셈인가…?

*

셰인
대립하고 있을 터인 「얼음의 나라」와 「번개의 나라」
사람들이 몰래 밀회라니…
그냥 평범한 대화라고는 생각되지 않네요.

레기아
…아무래도 정찰을 하고 있을 때가 아니군.
지체 없이 대장님들께 보고해야겠어…!

레이나
기다려, 그렇다면 우리는
알버스 쪽을 쫓아갈게.
정보는 조금이라도 더 얻어두는 게 좋잖아?

레기아
그, 그렇군. 부탁한다!
나는 즉시 대장님과 장군님께 보고하겠다!
내일 일몰 전까지 「불의 나라」로 돌아와 줘!

*

엑스
레이나, 왜 알버스 쪽을 쫓는 거야?
우리가 부탁받은 건 「번개의 나라」 정찰이잖아?

레이나
글레시아 공주가 말했던 종자의 이름도,
분명 알버스였지…

레이나
그 공주님이 「불의 나라」를 속이고,
「번개의 나라」와 동맹을 맺을 것 같지는 않아.
아마 이 사실은 글레시아 공주도 모르고 있는 게 아닐까…

타오
아무것도 모르는 것뿐이라면 다행이겠지.
왕 몰래 가신이 은밀하게 움직이는 이유…
가장 먼저 생각할 수 있는 건…

셰인
…뭐, 왕에 대한 반역 준비겠죠.

엑스
…즉 글레시아 공주에게 위험이 닥치고 있다는 거야?

레이나
나라를 끌어들이는 이그니스와 글레시아 공주의 사랑…
만약 두 사람이 이 상구의 『주역』이라면,
카오스텔러에게 노려진다고 해도 이상할 게 없어…!

레이나
알버스를 쫓아가자.
글레시아 공주를 지켜야 해…!

== 불의 나라의 성

이그니스
알버스가 「번개의 나라」 사람과 밀회를…?

레기아
옛, 지금은 엑스 일행이 알버스를
추적하고 있습니다. 밀회 이유 등은
아직 알 수 없습니다만…

이그니스
(…글레시아 공주가 우리를 속이고,
그 악명 높은 「번개의 나라」와 손을 잡을 리가 없다.
그렇다면, 이건 알버스의 독단인가?)

이그니스
(설마, 전장에서 그녀가 괴물들에게 습격당한 것도…)

레기아
이그니스 대장님?

이그니스
…「얼음의 나라」까지 가서 엑스 일행과 합류하겠다.
레기아는 여기서 대기해라.

레기아
대장님께서 직접 가시지 않아도, 제가…!
아, 잠시만요, 대장님!?

*

이그니스
(…아무 일도 없어야 할 텐데.
부탁이다, 부디 무사해 다오…!)

== 얼음의 나라의 성

글레시아
(그날 이후 며칠이나 지났는데…
그 사람을 잊을 수가 없어…
마치 낙인처럼 마음에 새겨져서…)

글레시아
(…안 돼. 그 사람과는 이제 만나지 않기로 맹세했잖아.
나는 「얼음의 나라」의 공주야…
그 사람에게 끌리다니, 그런 건…―――)

????
크르르… 크르르아!!

글레시아
에…?

글레시아
어째서…
왜, 괴물들이 이 성에…!?

글레시아
누구… 누구 없어요!
어마마마… 어마마마는 어디 계신 거죠…!

글레시아
세상에…
어째서 아무도 나와주지 않는 거야…!?

빌런
크르르… 크르르아!!

글레시아
큭…!!

== 얼음의 나라의 성하 마을

글레시아
어째서…?
괴물이 이렇게나 돌아다니고 있는데…
거리는 죽은 듯이 고요해…

글레시아
「얼음의 나라」에 지금, 무슨 일이 일어나고 있는 거야…?
부탁이야… 누가 좀 와줘…
어마마마… 알버스…

*

*

글레시아
―――윽!?

== 얼음의 나라의 성하 마을

글레시아
어째서… 왜… 그 사람의 얼굴을…
왜, 이런 때에 떠올리는 거야…!

글레시아
아니야… 아니라고…!
나는 그 사람을 생각하거나 하지…
사랑하고 있을 리가 없는데…!

엑스
글레시아 공주님!

글레시아
당신들은… 이그니스와 함께 있던 분들…!
어째서 여기에!?

레이나
조금 사정이 있어서요.
저기, 알버스와는 만났나요?

글레시아
알버스…?
아니요, 아직 돌아오지 않았을 거예요.

셰인
이곳으로 돌아온 건 틀림없을 텐데요.
그런데도 얼음 공주님은 만나지 못했다.
그렇다는 건…

타오
이 빌런들…
그 활잡이 녀석이 뒤에서 조종하고 있는 건가…

글레시아
에… 무슨 소리를 하는 거죠…?
알버스가, 이 괴물들을…?
그럴 리가 없는데…!

레이나
진정하고 들어요, 글레시아.
알버스는 「번개의 나라」 사람과 접촉하고 있었어요.
당신은 이 사실을 알고 있었나요?

글레시아
알버스가, 「번개의 나라」와…?
어떻게 된 거지…?
저기… 이게 알버스가 한 짓인가요…!?

엑스
…우선 이곳을 떠납시다.
저 눈길을 넘어가면,
안전한 곳이 나올 테니까요.

글레시아
…응, 알겠어.

== 얼음의 나라 근처의 설산

엑스
…글레시아 공주님, 계속 풀이 죽어 계시네.

타오
어쩔 수 없잖아.
돌아갈 곳도 없어지고, 믿었던 사람에게도
배신당했으니까.

레이나
무슨 도움이라도 되어주면 좋으련만…

셰인
지금은 가만히 놔둡시다.
셰인네는 결국, 이방인이니까요.

셰인
…응?

엑스
왜 그래, 셰인…
어, 저건――!

*

글레시아
(알버스가 배신했어…
이제 돌아갈 곳도 없어…
어마마마는 정말 무사하신 걸까…?)

글레시아
(나는… 대체 앞으로,
어떻게 해야 하는 걸까…)

글레시아
(도와줘…
이그니스…)

이그니스
글레시아 공주님…

글레시아
에…

이그니스
…엑스 일행에게 이야기는 들었습니다.
당신이 무사해서 다행,

글레시아
어째서…

글레시아
어째서… 당신은…
이런 때에 와버리는 건가요…
이런… 내가 당신을 생각한 바로 그때에…

이그니스
…글레시아 공주님.

글레시아
적인 당신을 좋아해서는 안 돼…
적인 당신을 좋아하게 될 리가 없어…
나도, 계속 그렇게 생각했어…

글레시아
하지만… 저 괴물에게 쫓기고 있었을 때…
머릿속에 떠오른 건 당신의 얼굴이었고…
당신의 얼굴을 보니까… 눈물이 멈추지 않아서…

글레시아
미안해요…
이런 말을 해도… 분명 당신을 곤란하게 만들 뿐…
당신을 괴롭게 할 뿐인데…

이그니스
…제 『운명의 서』에 적혀 있었습니다.
당신의 심장에 대해서…

이그니스
설정을 품은 얼음의 심장…
염정의 가호를 받은 「불의 나라」 사람이 만지면,
당신의 몸은 눈처럼 녹아버리고 말죠…

이그니스
…저는, 당신에게 아무것도 해줄 수 없습니다.
염정의 가호를 받은 이 몸은,
당신의 마음과, 몸을 상처 입힐 뿐입니다.

이그니스
그러니 적어도, 당신을 괴롭히는 불꽃을
이 검으로 털어내 보이겠습니다.
당신의 다정함이 녹아버리지 않도록…

글레시아
고마워요… 이그니스.

*

엑스
저기, 이걸로 괜찮은 걸까…
저 두 사람이 맺어지더라도,
그 앞에 기다리고 있는 것은…

타오
그런 건, 본인들이 가장 잘 알고 있겠지.
그래도 멈출 수 없는 거겠지.
사람의 마음이라는 건 말이야.

셰인
좋아하게 됐기 때문에, 그 운명에 이르는 것일까.
그 운명을 부여받았기 때문에, 좋아하게 된 것일까.
대체 어느 쪽일까요.

레이나
사람의 마음에 옳고 그름은 없어.
그저 돌진할 뿐이야.
캄캄한 미래를 향해서 말이지.

== 번개와 얼음의 국경

에메랄다
드디어 시작이야, 샤를로트.
임무 내용, 제대로 알고 있지?

샤를로트
바보 취급 하지 마.
우리의 목적은 글레시아 공주를 붙잡아,
그녀를 뇌제님 앞으로 모셔가는 것.

샤를로트
「얼음의 나라」는 이미 함락됐어.
그 공주님에게 돌아갈 곳은 없어.
붙잡히는 것도 시간문제야.

샤를로트
…하지만, 알버스의 말로는 그 공주님 곁에는
"홍련의 이그니스"가 붙어있다고 했잖아.
그 녀석은 만만치 않아, 어떻게 따돌릴 거야?

에메랄다
…걱정하지 마, 이미 손은 써뒀으니까.

에메랄다
글레시아 공주도…"홍련의 이그니스"도…
그들의 편이 되어줄 사람은 아무도 없게 될 거야.

== 얼음의 나라 근처의 초원

레이나
그럼, 일단 「불의 나라」로 돌아가는 걸로
하면 되는 거지?

이그니스
그래, 그녀를 망명자로서 데려가겠다.
사정을 이야기하면, 함부로 대우받지는
않을 터다.

이그니스
글레시아 공주님도, 괜찮으시겠습니까?

글레시아
…응, 물론이지.

엑스
글레시아 공주님, 안색이 좋아지셨네.

레이나
그러게, 어찌 됐든 건강한 게 제일이야.

글레시아
분명, 모두 덕분이야.
당신들과 함께 있으면,
왠지 무척 안심이 돼.

글레시아
…이런 시간이 계속 이어졌으면 좋겠네.

이그니스
걱정하지 마십시오, 이어지게 만들겠습니다.
자, 갑시다.
당신을 「불의 나라」로 모시겠습니다.

== 얼음과 불꽃의 국경

글레시아
여기를 넘어가면,
이그니스의 고향이 있는 거네.

이그니스
예. 설정의 힘을 특히 강하게 품은 당신에게는
불편한 점이 있을지도 모르겠습니다만,
부디 혜량해 주신다면…

글레시아
그렇게 남 대하듯 하는 말투는 그만둬.
나는 당신에게 몇 번이나 도움을 받았어…

글레시아
운명이나 입장이 어떻든,
적어도 지금의 우리는 가까운 사이일 터야.
그렇지, 이그니스 벨플레임.

이그니스
알겠습니… 알겠어.
최대한 노력해 보지, 글레시아.

글레시아
…응. 부탁해, 이그니스.

레이나
조―아, 그럼 빨리 「불의 나라」로 돌아가서,
휴식이나 취하―――

*

레기아
―――이그니스 대장님.

이그니스
레기아…?
이런 곳에서 무슨 일이지?

레기아
대장님… 그쪽에 계신 분은,
「얼음의 나라」의 제1왕녀, 글레시아 공주님이군요?

이그니스
그래…. 「얼음의 나라」의 정보가 벌써 전해진 건가?
그렇다면 이야기가 빠르겠군.

이그니스
그녀는 그 괴물들에게 쫓기고 있었고,
「불의 나라」로의 망명을 희망하고 있다.
장군님과도 이야기하고 싶으니, 다리를 좀 놓아주…

레기아
방금, 「얼음의 나라」에서 사자가 찾아와,
이런 요구를 했다고 합니다.

레기아
글레시아 공주가 「불의 나라」 병사에게 납치되었다.
그녀를 「얼음의 나라」로 돌려보내지 않으면, 「얼음의 나라」와
「번개의 나라」 연합군이 습격을 감행하겠다고 말입니다.

엑스
그건 엉터리예요!
「얼음의 나라」는 빌런에게 습격당했을 텐데!

레기아
진실인지 아닌지는 상관없다!
연합군이 우리에게 칼끝을 겨누고 있다는 게
문제인 거다! 우리 전력으로는 도저히 상대가 안 돼!

레기아
…「얼음의 나라」 사자는 알버스입니다.
그놈에게 당했습니다.
이그니스 대장님을 유괴범이라고도 말하고 있더군요…

글레시아
세상에… 알버스가…

레기아
대장님, 글레시아 공주의 신병을 이쪽으로 넘겨주십시오.
공주만 확보하면 피를 흘리지 않아도 됩니다.
우리 나라를 지키기 위해, 부디…

이그니스
…………

***

레기아
자, 대답을 들려주십시오.
이그니스 대장님…

글레시아
이그니스, 이제 됐어.
여기까지 온 것만으로도 충분해.

글레시아
당신은 목숨을 걸고 나를 지켜주었어.
그 행위가 가져온 결과라면,
어떤 결과든 받아들일 수 있어.

글레시아
당신은 누구보다 강하고, 다정한 불꽃…
부디 당신의 불꽃으로, 이 혼란스러운 세상을
계속 비춰줘…

레기아
각오는 선 모양이군…

*

레기아
…이게 어찌 된 일입니까?

레기아
그 사람은 적이라니까요…
당신은 적을 지키기 위해,
나라를 위험에 빠뜨릴 셈입니까!

이그니스
레기아, 네가 말하는 적이란 뭐지?
우리는 왜 서로 증오하고, 칼을 겨누고 있는 거지?

이그니스
나는 검을 휘두르며 항상 의문이었어…
어째서 우리 모두 평화를 원하고 있는데,
피를 흘려야만 하는 것인지…

이그니스
가호를 받은 정령은 다르지만,
이 사람은 똑같은 마음을 품고 있다.
똑같은 세상을 바라고 있어.

이그니스
그런데 왜, 똑같은 소망을 가진 이 사람을
「적」이라 불러야만 하는 거냐!

글레시아
이그니스…

레기아
…결국, 당신은 그 여자를 선택하는 겁니까.
나라보다도, 동료보다도,
적국의 공주를 선택하겠다는 거냐고!!

레기아
그렇다면 각오해라, 이그니스 대장, 아니,
반역자 이그니스 벨플레임!
네놈을 여기서 베어버리겠다!

타오
아무래도 말이 통할 기색은 없어 보이네…

레이나
이그니스, 글레시아 공주님!
레기아는 우리가 막을게.
당신은 그녀를 데리고 도망쳐!

이그니스
너희들…!

엑스
우리는 무엇이 옳은지 모르겠지만…
그래도 이그니스 일행의 편이 되어주고 싶어!
그러니까, 여기는 우리에게 맡겨줘!

글레시아
엑스… 모두… 고마워요…

이그니스
고맙군… 가자, 글레시아!

레기아
네놈들… 배신자의 편을 들다니…
그렇다면 용서하지 않겠다…

셰인
병사들도 달려오고 있네요.
본의 아니지만, 할 수밖에 없겠군요…

타오
좋아. 남의 연애를 방해하는 녀석은,
이 타오 패밀리가 가만두지 않지!

***
*전투*

레기아
큭…

엑스
미안해, 레기아.
하지만, 저 두 사람을 내버려 둘 순 없어…

레기아
도망칠 수 있을 것 같나…
이 섬에서… 이 운명에서…
대장님, 글레시아 공주님, 그리고 나도…

== 정령의 섬·항구

글레시아
…결국, 우리, 『운명의 서』대로
움직이고 말았네.
그렇게나 피하려고 했었는데…

이그니스
…저기, 하나만 가르쳐주지 않겠나.

이그니스
내 『운명의 서』에는 홀로 남겨진 당신이 어떻게 되는지,
기록되어 있지 않았어.

이그니스
내가 죽은 뒤,
당신에게 어떤 운명이 기다리고 있는지,
가르쳐주지 않겠나?

글레시아
………………

*

이그니스
세상에… 아아, 이럴 수가…

글레시아
슬퍼하지 마, 이그니스…
나는 계속 자신에게 닥칠 운명을 두려워하며
살아왔어. 내 운명을 저주하기도 했지.

글레시아
하지만, 신기하네…
지금은 내 운명이 그렇게까지 두렵지 않아…

글레시아
…내 『운명의 서』에 기록된 이름이,
당신이라서 다행이야.

이그니스
…글레시아.
아아, 나도―――

*

*

이그니스
―――윽!?

*

글레시아
이그니스…!?
이그니스, 정신 차려요…!

글레시아
앗…

샤를로트
저기, 에메랄다.
적이라곤 해도, 여자애한테 거칠게 굴면
안 된다고…

에메랄다
그저 기절시킨 것뿐이니 문제없다.
나머지는 "얼음매"에게 맡기면 돼.
뇌제님께 어서 그녀를 헌상해야 한다…

이그니스
기다려…
그녀를… 어디로 데려가는 거냐…

이그니스
윽…
젠장… 이 화살은, 알버스의…

이그니스
글레시아아아아아…!

이그니스
빌어먹을…

*

알버스
그녀의 이름을 함부로 부르지 마라, 홍련.

알버스
너를 놓아주지는 않겠다.
그녀의 운명을 망가뜨린 네 죄를
뼈저리게 느끼게 해주지…

== 정령의 섬·항구

레이나
…큰일이야, 상처가 너무 깊어!
기다려, 지금 회복 마법을―――

이그니스
가까이 오지 마!

이그니스
…글레시아가 「번개의 나라」 녀석들에게 끌려갔다.
나는 지금 알버스에게 노려지고 있어.
녀석은 나를 여기서 보낼 생각이 없는 모양이야…

이그니스
부탁이다, 나 대신 그녀를…
「번개의 나라」로 향할 수 있는 건 너희뿐이다…

엑스
그럴 수가, 이그니스를 여기 남겨두고 가라니…

이그니스
달리 그녀를 지킬 방법이 없다.
이런 일, 너희에게밖에 부탁할 수 없어.
들어주겠나?

타오
…아무래도 그 방법밖에 없을 것 같구만.

셰인
「번개의 나라」…
거기에 역시 이 상구의 카오스텔러가?

레이나
그럴 가능성이 높아…
어느 쪽이든, 「번개의 나라」로 쳐들어가지 않으면
아무것도 알 수 없겠지만.

이그니스
――윽!?

엑스
이그니스!?

이그니스
녀석의 목표는 나다.
여기는 내가 막아내지.
너희는, 어서 그녀를…!

엑스
…알았어, 반드시 글레시아는
우리가 구해낼게!

***

이그니스
………

알버스
잘 버텨냈군.
몇 발이나 쐈더라?
도중에 화살을 검으로 쳐냈을 때는 놀랐지만 말이야.

알버스
유언이 있다면 들어주지, 홍련.
아, 공주 전하라면 안심해.
그녀의 안전은 이 내가 보장할 테니까.

이그니스
………

알버스
이제 대답할 기운도 없나.
그럼 어쩔 수 없지. 여기서 숨통을 끊어주―――

레기아
멈춰라!

레기아
그자의 신병은 「불의 나라」에서 맡겠다.
이쯤에서 물러나 주실까.

알버스
꽤나 만신창이가 된 모양인데 미안하지만,
「얼음의 나라」 공주님을 납치한 남자를
그쪽에게 순순히 넘겨줄 수 있을 것 같아?

알버스
이 남자에게는 죽음의 대가를 치르게 해야 한다.
공주를 빼앗긴 측으로서,
그 정도의 보복은 허용되지 않겠어?

레기아
…글레시아 공주가 없다는 것은
이미 공주님이 그쪽으로 돌아갔다는 뜻.

레기아
그렇다면, 당신도 당초의 목적은 달성했을 터.
반역자라곤 하나 이 남자는 우리 나라 사람,
정당한 재판을 받을 권리가 있다.

알버스
정당한 재판이라…
그렇게 동료를 감싸겠다는 속셈인가?

레기아
감싸다니?
왜 배신자를 감쌀 필요가 있지.

레기아
우리 나라의 법은, 염정의 맹세를 저버린 자를
결코 용서하지 않는다.
반드시 합당한 형벌을 내릴 것이다.

알버스
……그 말에 거짓은 없겠지?

알버스
이 남자의 처분은 너희에게 맡기마.
「불의 나라」의 올바른 처단을 바라지.

== 번개의 나라의 성·대청

글레시아
으으음…
여기는…?

????
여기는 「번개의 나라」…
짐의 궁전이다, 글레시아 공주…

글레시아
당신은…
뇌제 볼텀…!

뇌제 볼텀
귀공녀를 만나게 되어 기쁘군.
글레시아 공주, 설정을 품고 「얼음의 심장」을 가진 자여.

글레시아
…당신이 그 괴물들을 부추긴 건가요?
「얼음의 나라」가 괴멸한 것도, 알버스가 배신한 것도
전부 당신이…!

뇌제 볼텀
그 젊은이는 배신한 것이 아니다.
단지 운명이 아니라, 자신의 신조에 따랐을 뿐.
운명에 스러져가는, 귀공녀를 구하기 위해.

글레시아
나를 구해?
그런 헛소리를…!

뇌제 볼텀
―――"천정".
그 이름에, 짐작 가는 곳은 없나?

글레시아
―――윽!?
어째서, 당신이 그 이름을…!?

뇌제 볼텀
뇌정, 설정, 염정.
셋으로 나뉘어 있는 이 정령들은 원래,
천정이라 불리는, 하나의 거대한 정령이었다.

뇌제 볼텀
그 천정이 강림할 때,
이 땅은 다시 하나로 통일되어,
평온으로 가득 찰 것이다, 그렇게 전해지고 있지.

뇌제 볼텀
…분명, 귀공녀의 『운명의 서』에는,
이런 내용이 적혀 있었을 터다.

뇌제 볼텀
귀공녀는 「불의 나라」 전사와 사랑에 빠진다.
하지만, 이윽고 남자는 귀공녀에게 마음을 전하지 못한 채,
전장에서 목숨을 잃고, 귀공녀는 그 사실에 절망한다…

뇌제 볼텀
그리고 귀공녀는 이 섬의 전쟁을 끝내기 위해,
이 천정을 소환하게 되지.

뇌제 볼텀
―――자신의 목숨과 맞바꿔서 말이다.

== 회상

글레시아
―――내 『운명의 서』에 따르면,
나는 전장에서 만난 이그니스를 잊지 못해,
성을 빠져나가, 그를 만나러 간다고 되어 있어.

*

글레시아
그리고 이그니스와 재회하여 도피 행각을 이어가지만,
때를 같이하여 삼국 간의 대립은 가열되고,
이윽고 최종 전쟁이 발발하고 말아.

글레시아
나와 이그니스는 이 섬에서 도망칠 예정이었어.
하지만 섬을 떠나는 배에 올라타기로 한 날 아침,
그는 나에게 아무 말도 남기지 않고 전장으로 향했지.

글레시아
그리고 격렬한 전화 속에서, 그는 목숨을 잃었어…―――

== 번개의 나라의 성·대청

뇌제 볼텀
사랑하는 자의 죽음과 귀공녀의 희생에 의해,
길고 길었던 전쟁이 종결된다.

뇌제 볼텀
귀공녀들의 운명은, 이 세상 모든 운명과
강하게 얽혀 있다.
그래서 어떻게 해서든 귀공녀를 억제할 필요가 있었다.

글레시아
어째서 당신이 내 운명을 알고 있는 거지…?

뇌제 볼텀
믿지 못하겠다면 그래도 상관없다.
짐은 귀공녀의 의사를 존중하고 싶을 뿐이다.
그러니 글레시아 공주. 이건 제안이다만…

뇌제 볼텀
귀공녀의 심장에 깃든 설정을,
짐에게 내놓지 않겠나?

글레시아
에…?

뇌제 볼텀
짐 또한 이 땅의 평온을 바라는 자…
귀공녀 대신 짐이 천정을 소환하여,
이 전쟁을 종결시키도록 하마.

뇌제 볼텀
심장에 깃든 설정은 귀공녀에게 있어 저주…
그것을 제거하면, 귀공녀의 심장은,
「얼음의 심장」이라는 저주에서 해방될 것이다.

뇌제 볼텀
…그리고, 사랑하는 남자와 여생을 함께할
미래를 얻을 수 있겠지.

글레시아
……무슨 소리를 하는 거야.
적의 왕인 당신의 말을
어떻게 믿으라는 거지!

뇌제 볼텀
믿지 못하겠다면 그래도 상관없다.
「얼음의 나라」 백성들도 원래 모습으로 돌려보내 주지.
짐은 귀공녀의 의사를 존중하고 싶을 뿐이다.

뇌제 볼텀
하지만 짐 또한 평온을 바라고 있다
거친 짓은 하고 싶지 않―――음?

뇌제 볼텀
…아무래도 쥐새끼가 섞여 들어온 모양이군.

에메랄다
"홍련의 이그니스"입니까?

뇌제 볼텀
아니, 정해진 운명을 갖지 않은 쥐새끼들이다.
이리저리 돌아다니는 건 골치 아프군…

뇌제 볼텀
샤를로트, 너는 쥐새끼들을 요격하러 가라.
에메랄다는 글레시아 공주를 성 최상층에 있는
방으로 모셔라.

샤를로트 & 에메랄다
옛.

글레시아
(설마 엑스 일행이 여기에?
이그니스도, 모두도,
나를 위해 움직여주고 있어…)

글레시아
(이런 남자의 말을 믿어서는 안 돼…
하지만, 만약 정말로 운명을 바꿀 수 있다면…)

글레시아
(나는 대체 어떻게 해야…)

== 번개의 나라의 수도

엑스
마을에 발을 들이자마자, 빌런이 나타났어…
역시 이 상구의 카오스텔러는 「번개의 나라」에…

레이나
그러게…
하지만, 「번개의 나라」 어디에 있는지는 아직…

샤를로트
침입자들!
이 「번개의 나라」에 쳐들어오다니
배짱도 좋구나!

셰인
오호라, 왠지 소란스러운 분이 오셨네요.

타오
어―이, 거기 당신.
그쪽에 있다는 건 빌런의 동료인 거야?

샤를로트
그거에 대답할 의무는 없어.
내 사명은 하나,
너희를 뇌제님 앞으로 통과시키지 않는 거야.

엑스
…뇌제라면, 이 나라의 왕인가?
설마 그 사람이 이 상구의 카오스텔러인 거야?

레이나
아무래도 그런 것 같네.
왕이라면, 있는 곳은 성…
혹시 글레시아 공주도 그곳에…

셰인
아, 머리 위에 느낌표가 떴어요.
이건 정답이네요.

타오
생각하는 게 얼굴에 다 드러나는 타입인가 보구만.
감정이 앞서는 건,
상대에게 파고들 틈을 주는 거라고?

샤를로트
닥쳐, 침입자!
이 샤를로트 바르헤트가,
반드시 너희를 날려버릴 거니까!

샤를로트
각오해!

== 불의 나라의 수도

나레이션
―――엑스 일행이 「번개의 나라」에서
샤를로트과 전투를 벌이고 있었을 무렵.

나레이션
레기아는 이그니스를 「불의 나라」로
연행했다―――

이그니스
……여기는, 「불의 나라」인가?

레기아
정신이 들었나, 이그니스.
그래, 여기는 「불의 나라」의 수도다…

레기아
네가 앞으로 어떻게 될지,
설명할 필요도 없겠지?

이그니스
…후회는 하지 않는다.
나는 해야 할 일을 했을 뿐이다.

레기아
닥쳐라!
배신자 주제에, 잘도 그렇게
당당할 수 있군.

레기아
어째서냐…
모든 것을 잃는 것이 두렵지는 않은 거냐?

이그니스
내가 정말로 두려운 건,
지키고 싶은 것을 지키지 못했을 때다.
그것을 위한 목숨, 아깝지 않다.

레기아
…너는 아무것도 모르고 있어.
네 행동으로 무언가를 지킬 수 있다고…?
아니, 아무것도 지킬 수 없어!

레기아
왜냐하면 너는…

이그니스
…기다려.
수도 쪽이 소란스럽지 않나…?

레기아
저건…?

*

빌런
크르르… 크르르아!!

레기아
저 괴물들…!
왜 「불의 나라」에…!?

이그니스
!?
아직 시민들이 남아있어…!
이 혼란으로 통제가 되지 않는 건가…!

레기아
이그니스!
너, 무슨 짓을 할 셈이냐!

이그니스
시민들을 안전한 곳까지 피난시키겠다.
멈춰 서 있을 틈이 없어.
단 한 명의 희생자도 낼 수는 없다…!

레기아
그렇게,
혼란을 틈타 도망칠 셈이냐?

이그니스
…의심스럽다면, 당장 죽여라.
하지만, 너라면 알고 있을 거다.
내가 지금 이 상황에서 도움이 될 남자라는 것을.

이그니스
어떻게 할 거냐, 레기아.
나라에 따라 나를 구속할 것인가.
자신의 마음에 따라 나를 풀어줄 것인가.

레기아
…………

레기아
…나는 즉시 성으로 돌아가 부대를 움직이겠다.
그때까지, 이 구역의 구조를, 부디…

이그니스
그래!

== 번개의 나라의 성·통로

글레시아
뇌제는, 정말로 이 땅의 평화를 바라고 있는 거야?

에메랄다
물론.
뇌제님의 말씀에 거짓은 없다.
그분은 항상 앞을 내다보고 계신다.

에메랄다
오히려, 왜 당신이
뇌제님의 권유에 응하지 않는지 이해할 수 없군.

글레시아
…나는 그저, 그 사람과 마찬가지로
다툼이 없는 세상을 바랄 뿐이야.
그 광경을, 그 사람과 함께 보고 싶어.

에메랄다
…그렇다면, 우리와 마찬가지군.

글레시아
엣…

에메랄다
나도, 그리고 샤를로트도,
원래는 전쟁 고아였다.
그것을 뇌제 폐하께서 거두어주셔서 기사가 되었지.

에메랄다
모두 소망은 같다.
그러니 글레시아 공주가 두려워할 것은 아무것도 없을 터.

글레시아
…하지만.

에메랄다
――윽!

에메랄다
윽!?

글레시아
얼음 화살… 설마 이건…!

알버스
공주 전하, 모시러 왔습니다.

글레시아
알버스… 당신, 어째서…!?

알버스
책망은 나중에 달게 받겠습니다.
지금은 이곳을 떠나야만 합니다…

알버스
뇌제의 힘을 얕보고 있었습니다…
녀석은 자신의 힘을 제어하지 못하고 있습니다…
녀석은, 당신을 구할 수 없습니다…

글레시아
…무슨 뜻이야?

에메랄다
이놈, 알버스…
우리를, 배신…하다니…

빌런
크르르으!

글레시아
에메랄다가 괴물로…
세상에…!

알버스
어서요!
여기는 위험합니다!

글레시아
아… 알버스…!

== 불의 나라의 수도

레기아
그 괴물들은 철수했습니다만,
이쪽의 피해가 막심합니다…
병사의 태반이 당했습니다…

이그니스
…그런가.

이그니스
그보다, 괜찮은 건가?
말투가 돌아왔다고.

레기아
엣?
아…

레기아
…이 괴물들,
역시 「번개의 나라」가 보낸 걸까요?

이그니스
…그럴지도 모르지.
글레시아… 엑스 일행…
부디 무사해 다오…

레기아
……………

레기아
……가십시오, 대장님.

이그니스
…무슨 소리냐.
나는 사로잡힌 몸일 텐데?

레기아
어차피 제가 말려도 당신은 갈 거잖아요?

레기아
이 전화에 휘말려 행방불명되었다고
말한다면, 변명은 가능하니까요.

이그니스
…고맙다, 레기아.
네게 염정의 가호가 함께하기를…

레기아
…당신이 가버릴 거라는 건 알고 있었어요.
내 서에는 대장님에 관한 일도 적혀 있었으니까.
내 이 마음이 닿지 않을 거라는 것도…

레기아
나도 참 무르네…
운명의 흐름이 꽤 바뀌었는데도,
결국, 서에 적힌 대로 보내주고 말았어…

레기아
정말로 이 세상은…
누구도, 행복해질 수 없어…

== 번개의 나라의 성·대청

뇌제 볼텀
힘이…
억눌러지지 않아…

뇌제 볼텀
아아, 어서 이 대지에 평화를…
다툼이 없는 세상을…

뇌제 볼텀
피가 흐르지 않도록…
모두, 빌런으로 바꿔서…
크… 큭큭큭… 큭하하하…!

== 번개의 나라의 수도

샤를로트
윽… 윽…

빌런
크르르르르으…!

엑스
샤를로트!

타오
제길, 빌런이 되어버렸잖아!
동료까지 안중에도 없는 거냐!

레이나
…뇌제의 카오스텔러로서의 힘이
폭주하기 시작한 걸지도 몰라.

레이나
빨리 『조율』을 하지 않으면,
이 상구는 빌런들에게 집어삼켜지고 말 거야!

엑스
빨리 글레시아 공주님을 구해야 해…
이그니스에게 부탁받았는데…

셰인
…하지만, 두 분을 구해도,
카오스텔러를 『조율』해도, 두 분을
기다리고 있는 결말을 바꿀 수는 없어요.

셰인
그래도 가고 싶으신가요?
신참 씨.

엑스
나도, 구할 수만 있다면 구하고 싶어…
두 사람의 운명을 바꿔주고 싶어…
하지만, 그걸 저 두 사람은 바라지 않아…

엑스
…이그니스 일행은 말했어.
자신의 마음 끝에, 소망하던 평화가 있다고.

엑스
그 두 사람의 소망을 카오스텔러가
짓밟게 내버려 둬선 안 돼.
그러기 위해서 우리는 싸우고 있는 거니까.

타오
잘 말했다, 꼬맹아.
좋은 각오야.

레이나
나아가자.
이그니스 일행의 마음을, 지키기 위해서…!

***
*전투*

== 번개의 나라의 성·통로

알버스
………

글레시아
…알버스, 손을 놔줘.

알버스
………

글레시아
…부탁이니까, 놔줘.

알버스
저도 참 많이 미움받게 되었군요…

글레시아
…미워하지 않아.
당신은 내 목숨을 구하기 위해,
「번개의 나라」와 동맹을 맺은 거잖아, 그렇지?

글레시아
하지만, 어째서.
왜 당신이, 내 운명을 알고 있었던 거야?

알버스
…그야, 알 수밖에요.
제 운명은 항상 당신 곁에 있었습니다.
태어날 때부터, 죽을 때까지 계속…

알버스
당신 운명의 결말도,
당연히 제 서에는 기록되어 있었으니까요…

알버스
저 뇌제의 힘이 있다면,
공주 전하의 운명을 바꿀 수 있을 거라 생각했습니다…
하지만 그것은 착각이었던 모양이군요…

글레시아
알버스, 나는…

알버스
더 이상은 말씀하지 않으셔도 됩니다.
더 이상의 말은 필요 없습니다…

알버스
당신의 운명에도, 마음에도,
저는 없었습니다.
그저, 그뿐인 이야기입니다.

빌런
크르르… 크르르아!!

알버스
…가십시오.
여기는 제가 맡겠습니다.

글레시아
알버스…
이것만은 알아줬으면 해.

글레시아
나는… 나의 이 마음과 행동에, 후회 따윈 없어.
설령 아무리 잔혹한 운명이라 해도,
나는 그 사람을 만날 수 있었던 이 운명을 자랑스럽게 생각해.

알버스
…분하군.
공주 전하께 그런 말을 하게 만드는
홍련의 남자가, 부럽고… 질투 나…

알버스
자, 가십시오.
가란 말이다, 글레시아!
뇌제 따위에게 네 운명을 꺾게 하지 마!

알버스
자, 와라, 괴물 놈들아.
"얼음매"라며 두려움 샀던 내 화살을 맛보아라!

== 번개의 나라의 콜로세움

엑스
…여기는 투기장인가?

타오
또 악취미적인 곳에 들어와 버렸구만…
얼른 나가자. 빨리 공주님을 찾아야 해…

셰인
기다려 주세요.
저쪽 입구에서 누군가 달려오고 있어요…

글레시아
…엑스?
모두들…?

엑스
글레시아 공주님…!
다행이다, 무사하셨군요…!

레이나
카오스텔러는?
뇌제는 어디에 있어?

글레시아
모르겠어…
나, 필사적으로 도망쳐 나왔으니까…

엑스
…알았어.
우선 이곳을 벗어나자.
글레시아 공주님을 안전한 곳으로――

*

뇌제 볼텀
호오, 어디로 데려가려 하는 것이냐?

글레시아
뇌제 볼텀…

레이나
당신이… 이 상구의 카오스텔러…!

뇌제 볼텀
글레시아 공주.
어느 길을 택할지, 마음은 정했나?
설정을 내놓을 결심은 섰는가?

글레시아
뇌제…
나는 설정을 내놓을 생각이 없어…

글레시아
지금의 당신은 평온에서 가장 먼 곳에 있어…
그런 사람에게 설정의 힘을 넘겨줄 수는 없어…

글레시아
이제, 나는 내 운명을 두려워하지 않아.
우리의 일시적인 꿈을 위해,
이 섬의 희망을 꺾어버릴 수는 없어!

뇌제 볼텀
그런가…
기어코 「얼음의 심장」인 채로 있기를 바라는가…
그렇다면, 귀공녀의 서를 힘으로라도 고쳐 쓸 뿐이다.

뇌제 볼텀
짐은 귀공녀의 의사를 존중하고 싶었다만…
안타깝군… 아아, 참으로 안타까워…

타오
어이, 손대게 놔두지 않을 거라고.

셰인
셰인네를 우습게 보지 마세요.

엑스
우리는 글레시아 공주님을 지키겠다고,
이그니스와 약속했어.
네놈 마음대로 하게 두지 않아!

글레시아
미안해… 이그니스…
운명을 바꿀 기회가 주어졌는데도…
하지만 나, 이 선택에 후회는 없어.

글레시아
우리의 운명은…
우리가 바라는 세상을 향한 희망은,
절대로 지켜내 보이겠어…!

뇌제 볼텀
…좋다, 어리석은 자들이여.

뇌제 볼텀
그렇다면 네놈들 전원,
이 자리에서 숙청해주마!

***
*전투*

뇌제 볼텀
어리석은 공주로다…
귀공녀를 사랑한 남자의 죽음이라는 결말을 바라다니…
그 남자도, 참으로 가련하군…

글레시아
……………

????
그렇지도 않아.

글레시아
―――윽!?

엑스
이그니스…
무사했구나…

이그니스
엑스, 모두,
고맙다, 약속을 지켜줘서…

이그니스
글레시아의 선택은 틀리지 않았어.
우리들의 운명은 우리들의 것.
누군가의 손에 맡기거나 하지 않아.

뇌제 볼텀
짐은… 진정으로 평화를 바랐던 것이다…
누구의 피도 흘리지 않고… 모두가 행복해지는 운명을…

이그니스
…그 말이 진심이었다 해도,
지금의 당신에게 그것을 맡길 수는 없다.
왜곡된 운명, 원래대로 돌려놓도록 하지.

레이나
…정말로 괜찮은 거지?

이그니스
그래, 해줘.

글레시아
여러분, 부디 저희를 잊지 말아 주세요…
저희는 온 힘을 다해 이 운명을 살았어요…
저희는 누구보다도, 행복했어요…

엑스
응, 잊지 않을게…
절대로, 잊지 않을 거야!

레이나
잘 가요, 이그니스, 글레시아 공주님…

레이나
『혼돈의 소용돌이에 삼켜진 이야기꾼이여』

레이나
『나의 언명 따라,
여기 조율을 시작하오니…』

== 『조율의 빛』 속

글레시아
…있지, 이그니스.
원래 운명으로 돌아가기 전에 부탁이 있어.

글레시아
나를, 안아줄래…?

이그니스
…그래, 알았어, 글레시아.

글레시아
느껴져… 당신의 고결하고, 다정한 불꽃이…
아플 정도로, 강하게, 느껴져…

이그니스
…왜 『운명의 서』 속에서,
나는 당신 앞에서 떠나갔던 것일까.
지금이라면 알 것 같아…

이그니스
당신의 몸에 닿을 수 없다는 절망을,
나는 견딜 수 없었던 거군…

이그니스
미안해, 글레시아…
이렇게 당신을 상처 입히고 있는데도,
나는 지금, 너무나 행복해…

글레시아
나도 그래요, 이그니스…

이그니스
…사랑해, 글레시아.

== 정령의 섬·항구

엑스
―――『조율』된 상구의
그 뒤의 이야기를 하자.

엑스
이그니스가 말했듯이 전쟁이 일어났고,
그곳에서 이그니스는 목숨을 잃었다.

엑스
그리고 절망한 글레시아 공주는 자신의 몸을 바쳐,
천정을 소환하고 이 땅에 평화를 가져왔다.

엑스
이그니스와 글레시아 공주의 마음이 자아낸,
평화의 광경.
하지만, 그곳에 두 사람의 모습은 없었다…―――

타오
…저 두 사람, 정말로 행복했을까.

셰인
타인의 행복을 가늠하는 건, 제삼자는 할 수 없어요.
뭐―, 그저 행복했기를 빌어줄 뿐이죠.

레이나
그렇네.
저 두 사람은 자신의 운명을 관철했어…
거기에 만족했을 거라고 생각해… 분명히 말이야…

엑스
…그래도, 이 광경을
두 사람에게도 보여주고 싶었어.

섬을 떠나는 선원
배가 떠난다――!
더 탈 녀석은 없나―!

붉은 머리의 남성 승객
아, 기다려 줘.
지금 우리도 탈게!
자, 이쪽이야…

푸른 머리의 여성 승객
응, 고마워…

엑스
(어라…?
　방금 그 손님들은…)

엑스
(…그럴 리 없겠지.
　하지만, 그랬으면 좋겠네…)

레이나
배가 출발하네.
슬슬 우리도 가자, 엑스.

엑스
응, 알았어.
